### ISSUE TITLE
PHP errors e.g. T_ENCAPSED_AND_WHITESPACE

### ISSUE THREAD

**Issue by ashgibson** [laravel/homestead#1008]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.2
  - Provider: Parallels 14.1.0
  - Homestead: 2.2.2

## Host operating system
MacOS Mojave 10.14.2

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: parallels

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects
      to: /home/vagrant/projects

sites:
    - map: myproject.test
      to: /home/vagrant/projects/myproject/public

databases:
    - homestead
```

## Actual behavior
When making changes in my php files on host machine in either PHPStorm or TextMate it appears that strange characters are being inserted during the sync to the homestead server.

I have tried updating the parallel tools as per http://parallels.github.io/vagrant-parallels/docs/configuration.html but still the same issue.

**Comment by svpernova09** [comment]
Edit your `Homestead.yaml` to this:

```

folders:
    - map: ~/Projects
      to: /home/vagrant/projects/myproject

sites:
    - map: myproject.test
      to: /home/vagrant/myproject/public
```
