### ISSUE TITLE
No input file specified

### ISSUE THREAD

**Issue by Paviluf** [laravel/homestead#1011]
Well I had this error "No input file specified" when I tried to go to my site. I reported it back but I didn't followed the bug report template. So I had make the steps again to provide the logs and the error is gone ! I don't think I have changed anything. I will still open the issue because there is still some error in the log like that, that may be related since it seem to be a ngnix error whereas I use apache :
```
homestead-7: Job for nginx.service failed because the control process exited with error code.
homestead-7: See "systemctl status nginx.service" and "journalctl -xe" for details.
```

## Versions
  - Vagrant: 2.2.2
  - Provider: Virtualbox
  - Homestead: master // Box 6.4.0

## Host operating system
Fedora 28

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 1024
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /media/Data/Development/Code
      to: /home/vagrant/Code
      type: "nfs"

sites:
    - map: td.test
      to: /home/vagrant/Code/td
      type: "apache"
      php: "7.0"
    - map: lrdt.test
      to: /home/vagrant/Code/lrdt
      type: "apache"
      php: "7.0"
    - map: ft.test
      to: /home/vagrant/Code/ft
      type: "apache"
      php: "7.0"
    - map: phpmyadmin.test
      to: /usr/share/phpmyadmin
      type: "apache"
      php: "7.0"

databases:
    - td
    - lrdt
    - ft

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.
```

## Vagrant destroy & up output
vagrant up fail due to https://github.com/laravel/homestead/issues/1009
https://gist.github.com/Paviluf/198637cd22c26bc2c2a290e5b7d6f965
after removing the blackfire repo, vagrant halt and vagrant up
https://gist.github.com/Paviluf/a5a323270a8c49799f95d7ea9b4401ec

## Expected behavior
Sites should be working

## Actual behavior
There is this error when you try to go to the site with your browser: No input file specified
Work well on v7.19.2

## Steps to reproduce
1. vagrant up
2. go to your site with your browser
