### ISSUE TITLE
Nginx: "No such file or directory" even though file exists

### ISSUE THREAD

**Issue by Luc45** [laravel/homestead#1014]
I wrote my own "serve" script for WordPress Multisite, available [here](https://gist.github.com/Luc45/b8ca3620f302f1731331c2f3d865c415).

I will describe the problem in steps:

1. Run `vagrant up`
2. Run `vagrant ssh`
3. Nginx should be running, but is not. I have to run `sudo service nginx start` for it to start, and it does.
4. If I run `sudo service nginx status` instead, I see this:

```
vagrant@homestead:~$ sudo service nginx status
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-12-22 15:28:56 UTC; 53s ago
     Docs: man:nginx(8)
  Process: 1111 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Dec 22 15:28:54 homestead systemd[1]: Starting A high performance web server and a reverse proxy server...
Dec 22 15:28:56 homestead nginx[1111]: nginx: [emerg] open() "/home/vagrant/dev/code/roles/wp-content/uploads/nginx-helper/map.conf" failed (2: No such file or directory) in /etc/nginx/sites-enabled/roles.localhost:12
Dec 22 15:28:56 homestead nginx[1111]: nginx: configuration file /etc/nginx/nginx.conf test failed
Dec 22 15:28:56 homestead systemd[1]: nginx.service: Control process exited, code=exited status=1
Dec 22 15:28:56 homestead systemd[1]: nginx.service: Failed with result 'exit-code'.
Dec 22 15:28:56 homestead systemd[1]: Failed to start A high performance web server and a reverse proxy server.
```

It is telling me that the file `/home/vagrant/dev/code/roles/wp-content/uploads/nginx-helper/map.conf` does not exist. If I try to run `vi /home/vagrant/dev/code/roles/wp-content/uploads/nginx-helper/map.conf`, it opens the file, so **it does exist.**

The directive from the `serve-wordpress-multisite.sh` script that includes that file is this one:
```
map \$blogname \$blogid {
    default -999;
    include $2/wp-content/uploads/nginx-helper/map.conf;
}
```

## Debug I did so far:
1. Changed map.conf to chmod 777 (just to test)
2. Verified that map.conf owner is vagrant, same user that runs Nginx service

# My question is:
Why do Nginx can't find the file during `vagrant up`, but it can when I run `sudo service nginx start`? How can I debug/fix this?

Further debug info bellow:

## Versions
  - Vagrant: 2.2.0
  - Provider: Virtualbox 5.2.22
  - Homestead: I don't have "homestead" command installed

## Host operating system
Windows 10 Pro 64 bits

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:/Vagrant/dev
      to: /home/vagrant/dev
      type: "nfs"

sites:
    - map: homestead.localhost
      to: /home/vagrant/dev
    - map: album.localhost
      to: /home/vagrant/dev/code/album
    - map: wpbrowser.localhost
      to: /home/vagrant/dev/code/tmp/wordpress
    - map: tina.localhost
      to: /home/vagrant/dev/code/tmp/tina
    - map: roles.localhost
      to: /home/vagrant/dev/code/roles
      type: wordpress-multisite

databases:
    - homestead

ports:
    - send: 80
      to: 80
    - send: 3306
      to: 3306
    - send: 443
      to: 443
    - send: 21
      to: 21
    - send: 22
      to: 22

blackfire:
    - id: ***
      token: ***
      client-id: ***
      client-token: ***

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.
```

## Vagrant destroy & up output
I'm afraid to run `vagrant destroy`

**Comment by svpernova09** [comment]
So the TL;DR I believe to be: You're requiring nginx to pull a file from a mapped folder *before* folders have been mapped. When the VM boots the services all fire normally and if nginx starts up before the folders are finished being mapped (Almost a 100% chance this will always happen) the file won't exist yet, throwing the error. 


Longer answer:

**Don't rely on folder shares for provisioning**. You should rely on `/vagrant` path being mapped to current directory you're running `vagrant` commands from. (I don't remember if this is mapped first, but it is a special mapped folder that will always be mapped unless you specifically map `.`, which you should probably never do)

**WP Multisite**: What makes your serve script great? Would it make sense to incorporate into Homestead? Lets have that discussion in another thread.

**Don't Map standard ports** in `Homestead.yaml` We already map most of those ports to localhost for you albeit to alternate ports but mapping the standard ports to localhost is asking for networking confusion.

**Don't map directories** to **projects**, map a **project**

Instead of:

```
folders:
    - map: C:/Vagrant/dev
      to: /home/vagrant/dev
      type: "nfs"
```

Do this:

```
folders:
  - map: C:/Vagrant/dev/code/album
    to: /home/vagrant/album
    type: "nfs"
  - map: C:/Vagrant/dev/code/tmp/wordpress
    to: /home/vagrant/wordpress
    type: "nfs"
  - map: C:/Vagrant/dev/code/tmp/tina
    to: /home/vagrant/tina
    type: "nfs"
  - map: C:/Vagrant/dev/roles
    to: /home/vagrant/roles
    type: "nfs"

sites:
  - map: album.localhost
    to: /home/vagrant/album
  - map: wpbrowser.localhost
    to: /home/vagrant/wordpress
  - map: tina.localhost
    to: /home/vagrant/tina
  - map: roles.localhost
    to: /home/vagrant/roles
    type: wordpress-multisite
```

```
I'm afraid to run vagrant destroy
```

I bet! This is also a huge red flag that you're fighting against the tools instead of using them. Anything that should be *in* the VM before you start working on it should be set up and configured in `after.sh`. I don't know if that's how I'd handle the WP multi site or not.
