### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by Simoneu01** [laravel/homestead#1016]
## Versions
  - Vagrant: v2.2.2
  - Provider: Virtualbox v6.0.0 r127566 (Qt5.6.2)
  - Homestead: v2.2.2
  - Nodejs: v11.6.0
  - npm: v6.5.0

## Host operating system
Windows 10 1809

## Homestead.yaml
```yaml
# ---
ip: "192.168.10.10"
memory: 10240
cpus: 4
provider: virtualbox

authorize: C:/Users/famig/.ssh/id_rsa.pub

keys:
    - C:/Users/famig/.ssh/id_rsa

folders:
    - map: E:/Progetto/code
      to: /home/vagrant/code
      type: "smb"
      mount_options: ["mfsymlinks,dir_mode=0775,file_mode=0664"]

sites:
    - map: homestead.test
      to: /home/vagrant/code/laravel/public
    - map: bulma.test
      to: /home/vagrant/code/bulma/public
    - map: phpmyadmin.test
      to: /home/vagrant/code/phpMyAdmin

databases:
    - homestead
    - bulma
    - phpmyadmin

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.

```

## Actual behavior
I can't run `npm run dev`

## Steps to reproduce
1. install vagrant
2. install homestead
3. run `npm install`
4. run `npm run dev`

## Debug LOG
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.5.0
3 info using node@v11.6.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/vagrant/code/bulma/node_modules/.bin:/home/vagrant/.composer/vendor/bin:/usr/local/go/bin:/home/vagrant/.rbenv/plugins/ruby-build/bin:/home/vagrant/.rbenv/shims:/home/vagrant/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vagrant/.dotnet/tools
9 verbose lifecycle @~dev: CWD: /home/vagrant/code/bulma
10 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
11 silly lifecycle @~dev: Returned: code: 126  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run development`
13 verbose stack Exit status 126
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid @
15 verbose cwd /home/vagrant/code/bulma
16 verbose Linux 4.15.0-43-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v11.6.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 126
22 error @ dev: `npm run development`
22 error Exit status 126
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 126, true ]

**Comment by Simoneu01** [comment]
### Update
I have change file_mode in Homestead.yaml:
before:
```
folders:
    - map: E:/Progetto/code
      to: /home/vagrant/code
      type: "smb"
      mount_options: ["mfsymlinks,dir_mode=0775,file_mode=0664"]
```

after:
```
folders:
    - map: E:/Progetto/code
      to: /home/vagrant/code
      type: "smb"
      mount_options: ["mfsymlinks,dir_mode=0775,file_mode=0755"]
```
And now I can run `npm run dev` but i have another error.

### Debug LOG:
[debug.log](https://github.com/laravel/homestead/files/2717326/debug.log)

### CLI LOG:
[debug.log](https://github.com/laravel/homestead/files/2717327/debug.log)
