### ISSUE TITLE
homestead setup code file can't be found 

### ISSUE THREAD

**Issue by heba222** [laravel/homestead#1020]
i'm trying to setup laravel /Homestead 

i'm new to laravel trying to learn it but during the last three days  I could not pass the setup process 

I tried to setup laravel/homestead globally based on Edwin tutorial 
https://www.udemy.com/laravel-homestead/learn/v4/content

and did try to set it up per project based on this tutorial 
https://www.youtube.com/watch?v=rs2Hzx4qBm8

I did every step they did got the same result as they did exactly but still cant open my project 
in both cases the only error happen when i try to reach code file through 

vagrant@testperproject:~$ cd Code/
i get this : 
-bash: cd: Code/: No such file or directory

what should i do ? I really want to pass this to move on to work why is it so hard ?! 

## Host operating system
win 10 

below will see .yaml after setting up homestead per project 

## Homestead.yaml
```ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: 'H:\laravel-apps\testperproject'
        to: /home/vagrant/code
sites:
    -
        map: homestead.test
        to: /home/vagrant/code/public
databases:
    - homestead
name: testperproject
hostname: testperproject
```

## Versions
  - Vagrant: Vagrant 2.2.2
  - Provider:  VirtualBox-6.0.0-
  - Homestead: laravel/homestead (virtualbox, 6.4.0)

## Expected behavior
code file supposed to be reachable 
i'm confused if every thing is correct how can I check ? 

I hope someone can help me

**Comment by svpernova09** [comment]
Please follow the instructions in the issue template. We need all of that info to help you. My guess is your folder paths are incorrect.

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by svpernova09** [comment]
Change your `Homestead.yaml` to this:

```
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: 'H:\laravel-apps\testperproject'
        to: /home/vagrant/testperproject
sites:
    -
        map: homestead.test
        to: /home/vagrant/testperproject/public
        
databases:
    - homestead
name: testperproject
hostname: testperproject
```
