### ISSUE TITLE
error on vagrant up

### ISSUE THREAD

**Issue by Tenfleques** [laravel/homestead#1023]
Vagrantfile confDir not set correctly at least for my case.

## Versions
  - Vagrant: 2.2.2
  - Provider: Virtualbox 6.0

## Host operating system
This is the operating system that you run locally.
MacOS High Sierra 

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/dev/www/homestead/sites
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead
```

## Expected behavior
upon `vagrant up` the vagrant is supposed to download the box and setup.

## Actual behavior
error fires `Homestead settings file not found in`

## Steps to reproduce
1. git clone <this repo>&& cd  <repo dir>
2. `vagrant up` 
3. error! 
However resolved the error by editing the vagrant file 
instead of:
`confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))`
I put:
`confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))+"/resources"`

and all worked just fine.
