### ISSUE TITLE
Laravel Executable Requires sudo

### ISSUE THREAD

**Issue by nomanurrehman** [laravel/homestead#1028]
Inside the homestead box, I have to "sudo laravel new ..." as "laravel new ..." halts with permission errors. This is a bit confusing since immediately after executing the command, composer says:

```bash
Do not run Composer as root/super user! See https://getcomposer.org/root for details
```

What is even more confusing is the file permissions are all correct.

## Versions
  - Vagrant: 2.2.3
  - Provider: Virtualbox
  - Homestead: 7.20.0

## Host operating system
Red Hat Enterprise Linux 7

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 3072
cpus: 2
provider: virtualbox
mariadb: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /home/noman/Development/PHP/voyager
      to: /home/vagrant/projects/voyager

sites:
    - map: voyager.dev
      to: /home/vagrant/projects/voyager/public
      php: "7.3"

databases:
    - voyager
```

## Expected behavior
Is this how it is supposed to work and there is nothing to be alarmed about?

## Actual behavior
I think only doing "laravel new ..." should work.

## Steps to reproduce
Simply provision a homestead box and try creating a new project inside "home/vagrant/code" using "laravel new".
