### ISSUE TITLE
stalls after php7.1-cli setup is called

### ISSUE THREAD

**Issue by Artistan** [laravel/homestead#1029]
## Versions
  - Vagrant: 2.23
  - Provider: Virtualbox 6.0.0 r127566
  - Homestead: v7.20.0

## Host operating system
macOS Mojave 10.14.2

## Homestead.yaml
```yaml
---
name: "me-Apache"
hostname: "me-apache"
ip: "192.168.10.11"
memory: 1028
cpus: 1
provider: virtualbox

variables:
    - key: APP_ENV
      value: local
    - key: PHP_IDE_CONFIG
      value: "serverName=me-apache"

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code
      type: "nfs"

sites:
    - map: binadminlocal.meeee.net
      to: /home/vagrant/code/internal-admin
      schedule: true
      type: "apache"

databases:
    - homestead

blackfire:
    - id: xxxx
      token: xxx
      client-id: xxx
      client-token: xxx
```

## Vagrant destroy & up output
Apache stalls on vagrant up....
https://gist.github.com/Artistan/274e3c79d43765eced237e3c6d5cfe29

## Expected behavior
finish install

## Actual behavior
stalls after php7.1-cli setup is called

```
    Chuck-Apache: Setting up php7.1-cli (7.1.26-1+ubuntu18.04.1+deb.sury.org+1) ...
    Chuck-Apache:
````

## Steps to reproduce
1. use my homestead config and vagrant up.
