### ISSUE TITLE
php7.3-fpm resulting in bad gateway

### ISSUE THREAD

**Issue by martijn94** [laravel/homestead#1031]
In the newest version of homestead (8.0.0) the default PHP version is 7.3. However there seems to be a problem on a freshly provisioned install. NGINX returns a 502 bad gateway when provisioned for php-7.3.

When switching `fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;` to `fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;` the site loads fine again.

Error in NGINX log:
```
2019/01/15 09:15:59 [error] 539#539: *15 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.10.1, server: com.nbs.test, request: "GET /wp-admin/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "com.nbs.test"
```

Error in PHP-FPM log:
```
[15-Jan-2019 09:32:14] WARNING: [pool www] child 904 exited on signal 11 (SIGSEGV - core dumped) after 1006.631644 seconds from start
[15-Jan-2019 09:32:14] NOTICE: [pool www] child 988 started
```

Error in /var/log/syslog
```
Jan 15 09:32:14 vagrant kernel: [ 1538.380198] php-fpm7.3[904]: segfault at 7ffdc3952ff8 ip 000055e499dad9e0 sp 00007ffdc3953000 error 6 in php-fpm7.3[55e499b2b000+3e6000]
```

My debugging skills didn't go any further unfortunately.

## Versions
  - Vagrant: 2.2.2
  - Provider: Virtualbox
  - Homestead: 8.0.0
  - Homestead box: 7.0.0 (same issue on 6.4.0)

## Host operating system
MacOS 10.14.2

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
name: "Vagrant V2"
hostname: martijn.local
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Sites
      to: /home/vagrant/sites
      type: nfs

sites:
    - map: sandbox.test
      to: /home/vagrant/sites/sandbox
    - map: com.nbs.test
      to: /home/vagrant/sites/nbs
```

## Vagrant destroy & up output
https://gist.github.com/martijn94/8bbd717d0c9b29f49068641589eb1d37

## Expected behavior
Site loads for a added site

## Actual behavior
Nginx returns 502 bad gateway

## Steps to reproduce
Provision fresh box with the latest versions of homestead.
