### ISSUE TITLE
Wrong provider in latest box update

### ISSUE THREAD

**Issue by guictx** [laravel/homestead#1033]
While trying to update Homestead to latest version, vagrant fails updating the box to version 7.0.0.

After further inspection it looks like the file parallels.box at the Vagrant cloud is a copy of virtualbox.box as they have the same hash.

## Versions
  - Vagrant: Vagrant 2.2.3
  - Provider: Parallels 13.3.2
  - Homestead: 7.20.0

## Host operating system
macOS 10.14.2

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: parallels
update_parallels_tools: false
mariadb: true
# backup: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /localboq/project1
      to: /home/vagrant/code/project1

    - map: /localboq/project2
      to: /home/vagrant/code/project2

    - map: /localboq/project3
      to: /home/vagrant/code/project3

sites:
    - map: www. project1.test
      to: /home/vagrant/code/project1/htdocs
      type: "apache"
      php: "7.0"

    - map: project2.test
      to: /home/vagrant/code/project2/htdocs
      type: "apache"
      php: "7.2"

    - map: www.project3.test
      to: /home/vagrant/code/project3/htdocs
      type: "apache"
      php: "7.0"

databases:
    - project1
    - project2
    - project3
```

## Expected behavior
`vagrant box update` should update my box to version 7.0.0

## Actual behavior
`vagrant box update` fails with the following error:

```
The box you attempted to add doesn't match the provider you specified.

Provider expected: parallels
Provider of box: virtualbox
```

## Steps to reproduce
1. Install Homestead 7.20.0 with parallels box 6.4.0
2. run `vagrant box update`

## Additional info
- Downloaded parallels.box from https://vagrantcloud.com/laravel/boxes/homestead/versions/7.0.0/providers/parallels.box and tried to add it to vagrant with `vagrant box add parallels.box --name homestead`:  it is recognised as being a virtualbox one.
- Downloaded virtualbox.box from https://vagrantcloud.com/laravel/boxes/homestead/versions/7.0.0/providers/virtualbox.box and compared its hash to parallels.box. The files are identical:
 ```
$ shasum parallels.box
e21ea8d61b75e38a1857bd0353259af730439b05  parallels.box

$ shasum virtualbox.box
e21ea8d61b75e38a1857bd0353259af730439b05  virtualbox.box
```
