### ISSUE TITLE
Issue creating new VM after adding database backup flag in homestead.yaml

### ISSUE THREAD

**Issue by mikeybinns** [laravel/homestead#1034]
I have an issue with the the new database backup feature.
When enabled in homestead.yaml with the backup: true flag, vagrant hits this error:

```
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: C
Line number: 528
Message: undefined method `each'
```
I realise the path isn't helpful, but I believe I have narrowed it down to this part of the homestead.rb file:
```
if settings.has_key?('backup') && settings['backup'] && (Vagrant::VERSION >= '2.1.0' || Vagrant.has_plugin?('vagrant-triggers'))
      dir_prefix = '/vagrant/'
      settings['databases'].each do |database|
        Homestead.backup_mysql(database, "#{dir_prefix}/mysql_backup", config)
        Homestead.backup_postgres(database, "#{dir_prefix}/postgres_backup", config)
      end
    end
```
the `settings['databases'].each do |database|` line is line 528 in my file. (this is due to added code above so it will not be the same in yours)

## Versions
  - Vagrant: 2.2.3
  - Provider: Virtualbox - Version 5.2.22 r126460
  - Homestead: 7.0

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.20"
memory: 4096
cpus: 4
provider: virtualbox
backup: true

networks:
    - type: "private_network"
      ip: "192.168.10.20"

authorize: C:/WebServer/.ssh/id_rsa.pub

keys:
    - C:/WebServer/.ssh/id_rsa

folders:
    - map: C:/WebServer/Websites/homestead
      to: /home/vagrant/websites/homestead

sites:
    - map: homestead.local
      to: /home/vagrant/websites/homestead
      hosts: 192.168.10.20
      type: "apache"

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.

hosts_file_additions: true

```

## Vagrant destroy & up output
No existing vm exists, only vagrant up output which is above.

## Expected behavior
Vagrant should load as normal

## Actual behavior
Run into vagrant error on vagrant up

## Steps to reproduce
1. set backup:true in homestead.yaml
2. run vagrant up
