### ISSUE TITLE
issue with elasticsearch installation on vagrant up

### ISSUE THREAD

**Issue by dbatten5** [laravel/homestead#1035]
## Versions
  - Vagrant: 2.2.3
  - Provider: Virtualbox
  - Homestead: 7.20.0

## Host operating system
MacOS High Sierra v10.13.2

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
elasticsearch: 6

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Sites/builder
      to: /home/vagrant/code/builder

sites:
    - map: local.builder
      to: /home/vagrant/code/builder/public

databases:
    - local

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

blackfire:
    - id: xxx
      token: xxx
      client-id: xxx
      client-token: xxx

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.

```

## Vagrant destroy & up output
https://gist.github.com/dbatten5/2ff7c4fbe79dd94aef4326dd05afc3bc

## Expected behavior
vagrant up works as expected and elasticsearch is enabled

## Actual behavior
errors occur at various stages of the installation

## Steps to reproduce
run vagrant up

i've tried removing `elasticsearch: 6` from the Homestead.yaml file and vagrant up works as expected. tried several times doing combinations of `vagrant box update` with `vagrant destroy && rm -rf .vagrant` to no avail. please excuse my terminology, i'm quite new to vagrant and homestead
