### ISSUE TITLE
Apache and php5.6 on box 7.0.0 and homestead 8.0.0. ERROR: Conf php5.6-fpm does not exist.

### ISSUE THREAD

**Issue by kolexndr** [laravel/homestead#1038]
## Versions
  - Vagrant: 2.2.3;
  - Box version: 7.0.0
  - Provider: Virtualbox 6.0.2.
  - Homestead: master, 8.0.0, 7.20.0.

## Host operating system
Win10 x64 

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: d:/fixthephoto
      to: /home/vagrant/code/public/fixthephoto
    - map: d:/fixthephoto_test
      to: /home/vagrant/code/public/fixthephoto_test

sites:
    - map: fixthephoto.vagrant
      to: /home/vagrant/code/public/fixthephoto
      type: "apache"
      php: "5.6"
    - map: fixthephoto-test.vagrant
      to: /home/vagrant/code/public/fixthephoto_test
      type: "apache"
      php: "5.6"

databases:
    - fixthephoto
```

## Vagrant destroy & up output
Vagrant destroy && rm -rf .vagrant && vagrant up
and
journalctl -xe (from inside of guest os)

https://gist.github.com/kolexndr/9a37e67743d263504b79dedd179c2ded

## Actual behavior
php5.6 doesnt work with Apache
