### ISSUE TITLE
Hosts are not reachable from host machine when VPN connection is disabled

### ISSUE THREAD

**Issue by wukis** [laravel/homestead#1039]
## Versions
  - Vagrant: 2.2.3.
  - Provider: Virtualbox 6.0.0
  - Homestead: homestead 7, latest cloned master
  - Vagrant hosts updater plugin (latest)

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 4
provider: virtualbox
#ssl: true
#natdnshostresolver: off

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: forum.test
      to: /home/vagrant/code/forum/public
      php: "7.2"
    - map: academy.test
      to: /home/vagrant/code/academy/public
      php: "7.2"

databases:
    - forum
    - academy

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.


```

## Vagrant destroy & up output
[GitHub Gist](https://gist.github.com/wukis/a19a1577b26d3ec6bfe0b1f1ad16bb14)

## Expected behavior
- If I launch my computer without automatic VPN connection and run homestead - I should be able to access hosts from guest machine.
- If I launch my computer with automatic VPN connection and run homestead, and then I turn off VPN - I should still be able to access hosts from the guest machine

## Actual behavior
Hello, I have issues with my homestead hosts. If I fully restart my computer, let VPN to connect, then start my homestead machine - everything works. Now if I decide to turn of VPN connection - I cannot reach any hosts that are active from homestead (homstead is still running, when I click disconnect from NordVPN). Furthermore, if I try to run "vagrant up" without enabled VPN connection (even after fresh computer restart) - homestead runs, I can ssh into it, but I cannot reach any hosts. If I publish site through ngrok - public url, the site is reachable, everything inside the machine works perfectly. I'm not sure, but this is related to my VPN. I'm using NordVPN. Is there any settings I can try that would help me with this? Also I believe this has nothing to do with vagrant/homestead/virtualbox versions as I've been having this issue for a while, even thou I've update everything when there is updates available.

Additionally, sometimes when I work on a project, without touching my VPN or anything else I lose ability to access guest machine hosts. I have to try re-provision homestead and try again - sometimes it helps, sometimes I have to do full restart to get homestead hosts working again.

Also I always re-check my hosts file if the entries from Homestead.yaml are properly set in my hosts file - they are, so I'm sure that it has nothing to do with vagrant plugin.

## Steps to reproduce
1. Launch computer from fresh restart
2. Let NordVPN connect
3. Launch homestead
4. Access a host from the guest machine on browser
5. Turn of VPN connection
6. Refresh previously accessed host on browser and get that the host is not found
7. Re-enable VPN connection
8. Re-run and re-provision guest machine
9. Refresh previously accessed host and be able to see it in browser

## References
None
