### ISSUE TITLE
Newly installed Homestead v8.0.0 report 502 Bad Gateway

### ISSUE THREAD

**Issue by Jonathan0wh** [laravel/homestead#1045]
I encountered constant 502 Bad Gateway error after a fresh installation of Homestead v8.0.0. After searching, I found that it was related to php 7.3 mod xdebug. I tried

 ```
sudo phpdismod xdebug
sudo service php7.3-fpm reload
```

 and it successfully resolved the problem (as what is in the two links in the Reference part).

But I'm helping out some other students to start on Homestead as well, and it may not be good if I have to disable xdebug after installation every time, let alone xdebug may be used in the future.

Anyway, is there any better solution for it (Maybe xdebug team is trying to solve the compatibility issue with php 7.3? But before that, maybe it would be better to disable mod xdebug by default in Homestead v8.x and add some explanation about this in the documentation, such that at least people would not see 502 after initial installation)?

## Versions
  - Vagrant: Vagrant 2.2.3
  - Provider: Virtualbox 6.0.2r128162
  - Homestead: homestead v8.0.0

## Host operating system
macOS Mojave Version 10.14.2

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/homestead/public

databases:
    - homestead

backup: true

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.
```

## Expected behavior
Test site loaded.

## Actual behavior
502 Bad Gateway displayed. Tried refreshing many times, and for few times the page could be displayed, but for most times it was 502 error.

## Steps to reproduce
1. Install Homestead following the official documentation https://laravel.com/docs/5.7/homestead
2. Open Chrome and visit an example site (homestead.test in my Homestead.yaml)
3. 502 Bad Gateway displayed. Tried refreshing many times, and for few times the page could be displayed, but for most times it was 502 error.

## References
- #1031 
- https://stackoverflow.com/questions/54335705/new-laravel-homestead-installation-502-bad-gateway-refresh-the-website

**Comment by dudedigital** [comment]
I had the same problem. Random 502 errors between page loads.

**Comment by svpernova09** [comment]
from inside the VM run `sudo phpdismod xdebug`. if the issue continues then it's likely still issues upstream with PHP 7.3 You can override and go back to 7.2 by adding `php: '7.2'` to your `Homestead.yaml`

**Comment by mdgrech** [comment]
Reverting to PHP v7.2 in `Homestead.yaml` fix it.

```yaml
sites:
    - map: example.test
      to: /home/vagrant/code/public
      php: "7.2"
```

**Comment by yabasha** [comment]
Is it possible to enable `xdebug` for some sites and disable it for the others?

I disable `xdebug` by running `sudo phpdismod xdebug` and everything went fine, but I need it now for a new project.

**Comment by fraserredmond** [comment]
As of xdebug v2.7.0RC2 (and therefore v2.7.0 onwards) it looks like this is fixed.

**Comment by svpernova09** [comment]
> Is it possible to enable xdebug for some sites and disable it for the others?

Only per PHP version

**Comment by francoislevesque** [comment]
Fixed in Homestead 8.4.0

**Comment by gustaveco** [comment]
Hi i have similar problem on Homestead 10.8 on Windows 10. I configured it with the following yaml:

```
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: D:\Gustavo\gdrive\www\learn
      to: /home/vagrant/learn

sites:
    - map: homestead.test
      to: /home/vagrant/learn/public

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

**Comment by gustaveco** [comment]
Changed to Apache and worked fine.
```
sites:
    - map: homestead.test
      to: /home/vagrant/learn/public
      type: "apache"
```
Also, ngnix was giving long response times with `ping` and also some packages missing.
