### ISSUE TITLE
Port Collisions after update and some other stuff, vmware fusion

### ISSUE THREAD

**Issue by tobiasvielmetter** [laravel/homestead#1046]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: v8.0.1
  - Provider: VMWare, latest version of plugin 2.0.3 as well as vmware fusion 11.0.2
  - Homestead: Vagrant 2.2.3

## Host operating system
macOSX Mojave 10.14.2

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: vmware_fusion
# backup: true
authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code
      type: nfs

sites:
    - map: someapp-app.test
      to: /home/vagrant/Code/someapp-app/public
      type: someapp
    - map: someapp-ta.test
      to: /home/vagrant/Code/someapp-ta/public
    - map: someapp-whitecube.test
      to: /home/vagrant/Code/someapp-whitecube/public
    - map: someapp-img.test
      to: /home/vagrant/Code/someapp-img/public
      type: someappimg
    - map: someapp-website.test
      to: /home/vagrant/Code/someapp-website/public
    - map: website-vielmetter.test
      to: /home/vagrant/Code/vielmetter.com/public
    - map: ephemera-scan.test
      to: /home/vagrant/Code/ephemera-scan/public
    - map: someapp-promo.test
      to: /home/vagrant/Code/someapp-promo/public

variables:
    - key: APP_ENV
      value: local

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.
```

## Vagrant destroy & up output
https://gist.github.com/tobiasvielmetter/4bd386e2cfa9290d5b1ad370d2080d2c

## Expected behavior
Normal start of VM was expected

## Actual behavior
Since updating I have port collisions that cancel homestead boot midway.

## Steps to reproduce
vagrant up on most recent versions

## References
Could not find relevant references to this issue yet.
