### ISSUE TITLE
vagrant up: [ErrorException] my-project: rename(/home/vagrant/.composer/cache/composer-temp.phar,/usr/local/bin/composer): Permission denied

### ISSUE THREAD

**Issue by rvzug** [laravel/homestead#1051]
## Versions
  - Vagrant: 2.2.3
  - Provider: Virtualbox (5.2.26)
  - Homestead: 8.0.1 | Box version: v7.0.0

## Host operating system
Windows 10 64-bits

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: 'D:\Projects\my-prject'
        to: /home/vagrant/code
sites:
    -
        map: my-project.test
        to: /home/vagrant/code/public
databases:
    - homestead
name: my-project
hostname: my-project
```

## Vagrant destroy & up output
[GitHub Gist](https://gist.github.com/rvzug/a1981911b6aef70fbac6b616c355db51) 

## Expected behavior
Update composer trough self-update and continue until ``vagrant up`` completes

## Actual behavior
[ErrorException] my-project: rename(/home/vagrant/.composer/cache/composer-temp.phar,/usr/local/bin/composer): Permission denied

## Steps to reproduce
1. Vanilla installation of Homestead 
2. ``vagrant up``

## References
#1049
