### ISSUE TITLE
macOS - mount.nfs: access denied by server while mounting

### ISSUE THREAD

**Issue by timo002** [laravel/homestead#1053]
I'm trying to get my homestead up and running. Homestead is running fine when I'm not using NFS, only then it is extremely slow. So I'm enabling NFS, but that throws me an error while starting the vagrant.

I created a disk image of the type Mac OS extended (journaled) and that disk I'm trying to mount.

## Versions
  - Vagrant: 2.2.3
  - Provider: Virtualbox 6.0.4
  - Homestead: 8.0.1 ? 7.0.0

## Vagrant plugins:
  - vagrant-bindfs (1.1.0, global)
  - vagrant-vbguest (0.17.2, global)

## Host operating system
macOS Mojave (10.14.2)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /Volumes/codedisk/blog
      to: /home/vagrant/code/blog
      type: "nfs"

sites:
    - map: blog.symfony.test
      to: /home/vagrant/code/blog/public
      type: "symfony4"

databases:
    - homestead
```

## Vagrant destroy & up output
[GitHub Gist](https://gist.github.com/timo002/e5f646f8f89d4012c176faf96411ea16)

## Expected behavior
NFS should be mounted

## Actual behavior
NFS cannot be mounted, virtual machine (homestead) is running and I can acces it with vagrant ssh

## Steps to reproduce
1. vagrant up
