### ISSUE TITLE
"vagrant up" fails if "apt-get update" is called

### ISSUE THREAD

**Issue by philbates35** [laravel/homestead#1055]
## Versions
  - Vagrant: 2.1.2
  - Provider: Virtualbox 5.2.24
  - Homestead: Homestead git repository v8.0.2, box version 7.0.0.

## Host operating system
Fedora 29

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code
      type: "nfs"

sites:
    - map: natours.test
      to: /home/vagrant/Code/natours

databases:
    - homestead

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.
```

## Vagrant destroy & up output
https://gist.github.com/philbates35/7d843776f81520b0ad3984b575fdd803

## Expected behavior
`apt-get update` (triggered by the `vagrant-bindfs` plugin) should have completed successfully, bindfs installed, and vagrant up completed successfully.

## Actual behavior
The bind fs plugin results in a call to `apt-get update` during `vagrant up`, but the `apt-get update` fails with the error:
```
E: Repository 'http://ppa.launchpad.net/nginx/development/ubuntu bionic InRelease' changed its 'Label' value from 'NGINX Mainline' to 'NGINX Mainline (1.15.x)'
```
before it gets to installing `bindfs`.

So although the error happens as a result of the `vagrant-bindfs` plugin being installed, it is the general `apt-get update` command that is failing, which makes believe this is a Homestead isssue, not a bindfs issue.

## Steps to reproduce
1. `vagrant plugin install vagrant-bindfs`
2. `vagrant destroy`
3. `vagrant up`

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
I searched and couldn't find anything.
