### ISSUE TITLE
Z-Ray bar disappeared when I updated to 8.0.1

### ISSUE THREAD

**Issue by ryanrapini** [laravel/homestead#1059]
Hey guys, Looks like when I updated my box today the Zray bar vanished. It was working before the update. 

## Versions
  - Vagrant: 2.2.3
  - Provider: Virtualbox 6.0.4 r128413 
  - Homestead: v8.0.1

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4098
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:\Users\user\Projects\
      to: /home/vagrant/code

sites:
    - map: upload.test
      to: /home/vagrant/code/<redacted>/public/
      zray: "true"

databases:
    - homestead

```

## Vagrant destroy & up output
https://gist.github.com/ryanrapini/40d7369efe95d7e9bdb08755d51916e0

## Expected behavior
Zray bar should appear at the bottom of the page, as it did before I updated my box (laravel/virtualbox) and homestead.

## Actual behavior
There is no Zray Bar

## Steps to reproduce
- Have working Zray bar
- update vagrant box and update homestead

**Comment by svpernova09** [comment]
Z-Ray will only work with PHP 7.2.

Change

```
sites:
    - map: upload.test
      to: /home/vagrant/code/<redacted>/public/
      zray: "true"
```

to 
```
sites:
    - map: upload.test
      to: /home/vagrant/code/<redacted>/public/
      php: "7.2"
      zray: "true"
```
