### ISSUE TITLE
How to get rid of the message "The guest additions on this VM do not match the installed version of VirtualBox" ?

### ISSUE THREAD

**Issue by Paviluf** [laravel/homestead#1060]
## Versions
  - Vagrant: 2.2.3
  - Provider: Virtualbox
  - Homestead: 7.20.0 / box 6.4.0 (need php 5.6 and 7.0)

## Host operating system
Fedora 29

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 1024
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /media/Data/Development/Code
      to: /home/vagrant/Code
      type: "nfs"

sites:
    - map: td.test
      to: /home/vagrant/Code/td
      type: "apache"
      php: "5.6"
    - map: lrdt.test
      to: /home/vagrant/Code/lrdt
      type: "apache"
      php: "7.0"
    - map: ft.test
      to: /home/vagrant/Code/ft
      type: "apache"
      php: "7.0"
    - map: phpmyadmin.test
      to: /usr/share/phpmyadmin
      type: "apache"
      php: "7.0"

databases:
    - td
    - lrdt
    - ft

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.
```

## Vagrant destroy & up output
==> homestead-7: Checking for guest additions in VM...
    homestead-7: The guest additions on this VM do not match the installed version of
    homestead-7: VirtualBox! In most cases this is fine, but in rare cases it can
    homestead-7: prevent things such as shared folders from working properly. If you see
    homestead-7: shared folder errors, please make sure the guest additions within the
    homestead-7: virtual machine match the version of VirtualBox you have installed on
    homestead-7: your host and reload your VM.
    homestead-7: 
    homestead-7: Guest Additions Version: 5.2.20
    homestead-7: VirtualBox Version: 6.0

## Expected behavior
I updated Virtualbox guest addition in Homestead to make it match the version I have on Fedora (6.0.4) and to make the message "The guest additions on this VM do not match the installed version of VirtualBox" disappear.

## Actual behavior
I updated Virtualbox guest addition in Homestead (with the commands below) to make it match the version I have on Fedora (6.0.4) but Homestead (vagrant up / vagrant reload --provision) keep saying "The guest additions on this VM do not match the installed version of VirtualBox".
```
$ vagrant up
$ vagrant ssh
$ sudo apt install linux-headers-$(uname -r) build-essential dkms
$ wget https://download.virtualbox.org/virtualbox/6.0.4/VBoxGuestAdditions_6.0.4.iso
$ sudo mount VBoxGuestAdditions_6.0.4.iso -o loop /mnt
$ cd /mnt
$ sudo sh VBoxLinuxAdditions.run
$ cd
$ sudo umount /mnt
$ rm VBoxGuestAdditions_6.0.4.iso
$ exit
$ vagrant reload --provision
```
I modified the GuestProperty in "~/.vagrant.d/boxes/laravel-VAGRANTSLASH-homestead/6.4.0/virtualbox/box.ovf" to update the guest addition version but that doesn't change anything.
```
$ vim ~/.vagrant.d/boxes/laravel-VAGRANTSLASH-homestead/6.4.0/virtualbox/box.ovf
    <GuestProperty name="/VirtualBox/GuestAdd/Version" value="6.0.4" timestamp="1541805204799979000" flags=""/>
    <GuestProperty name="/VirtualBox/GuestAdd/VersionExt" value="6.0.4" timestamp="1541805204800044000" flags=""/>
```
## Steps to reproduce
See Actual behavior
