### ISSUE TITLE
Homestead

### ISSUE THREAD

**Issue by nicobrinkkemper** [laravel/homestead#1061]
## Versions
  - Vagrant: 2.2.3
  - Provider: 10.0.17134.1 (Microsoft Windows 10 Update/Server 1803 8.3     True)
  - Homestead: 8.1.0

## Host operating system
This is the operating system that you run locally.

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
name: "Codeception Laravel 5 Sample"
provider: hyperv

folders:
    - map: "."
      to: "/home/vagrant/code"

sites:
    - map: homestead.app
      to: "/home/vagrant/code/public"

databases:
    - homestead

```

## Vagrant destroy & up output
https://gist.github.com/nicobrinkkemper/f1ee6386b6847e32731d4163bdb20813

## Expected behavior
Succesful vagrant up

## Actual behavior
Hyperv error for unsupported version

## Steps to reproduce
1.  install vagrant
2.  Clone circleci-demo-php-laravel repo recursive
3.  vagrant up

## References
- https://github.com/hashicorp/vagrant/issues/10384
