### ISSUE TITLE
mysql8: true does not install mysql8

### ISSUE THREAD

**Issue by ndberg** [laravel/homestead#1068]
Tried to install mysql 8 with the new Option in Homestead.yaml "mysql8: true" as seen in your streaming. Unfortunately it does not work. 

Thanks for your help && for this great dev environment.

## Versions
  - Vagrant: Vagrant 2.2.3
  - Provider: Virtualbox 6.0.4
  - Homestead: 7.1.0

## Host operating system
macOS Mojave 10.14.1

## Homestead.yaml
```yaml
ip: 192.168.10.14
memory: 2048
cpus: 1
provider: virtualbox
mysql8: true
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /Users/Andi/Code/fotogecko
        to: /home/vagrant/code
        type: nfs
sites:
    -
        map: fotogecko.test
        to: /home/vagrant/code/public
        schedule: true
        backup: false
databases:
    - fgapp
    - fguserlog
    - fotogecko_old
name: fotogecko
hostname: fotogecko

```

## Vagrant destroy & up output
https://gist.github.com/ndberg/75883b63543f60f0b315bd1cfe1a0276

## Expected behavior
It should have installed mysql 8.

## Actual behavior
It has installed mysql 5.7.
```
vagrant@fotogecko:~$ mysql -V
mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper
```
