### ISSUE TITLE
How to identify the different sites form inside vagrant ?

### ISSUE THREAD

**Issue by ImadSalimi** [laravel/homestead#1078]
Hi, so this here really isn't an issue with the functionality itself, but rather a question that comes from lack of documentation or lack of knowledge from my part.

So I have the setup below with multiple sites running in the same vagrant box, and from my host machine I can use `/etc/hosts` to give them names that will identify them which works with the Homestead.yaml settings and that is cool. But let's say I have some logic in the `resal-api` app which has to communicate with `resal-admin` by making a POST request, but if I use the same host name that I set outside vagrant it won't be recognized inside it, it's as if I'm hitting a URL that doesn't exist at all.

My question is: how can I identify the different sites from WITHIN vagrant? Does Homestead attribute different ports to them or has a mechanism for that? and if so what would be the URL given to each site as per my configuration?

Thank you in advance 

## Versions
  - Vagrant: Vagrant 2.2.4
  - Provider: Virtualbox Version 6.0.4 r128413
  - Homestead: Vagrant 2.2.4

## Host operating system
MacOS High Sierra

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects/Ekliel/backend
      to: /home/vagrant/ekliel
    - map: ~/Projects/Resal/backend
      to: /home/vagrant/resal-api
    - map: ~/Projects/Resal/admin
      to: /home/vagrant/resal-admin

sites:
    - map: ekliel-api.com
      to: /home/vagrant/ekliel/public
      php: "7.2"
    - map: resal-api.com
      to: /home/vagrant/resal-api/public
      php: "7.2"
    - map: resal-admin.com
      to: /home/vagrant/resal-admin/public
      php: "7.2"

databases:
    - homestead
    - resaldb
```
