### ISSUE TITLE
oracle-java8-installer fails to install, due to missing files

### ISSUE THREAD

**Issue by dz46** [laravel/homestead#1087]
## Versions
  - Vagrant: 2.2.3
  - Provider: Virtualbox
  - Homestead: 8.2.0

## Host operating system
Windows 10

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 4096
cpus: 2
provider: virtualbox
elasticsearch: 6
folders:
    -
        map: .
        to: /home/vagrant/code
        type: "nfs"
sites:
    -
        map: jp.test
        to: /home/vagrant/code/public
        type: symfony4
databases:
    - homestead
    - jp_test
name: job-publisher
hostname: jp
variables:
    - key: HOMESTEAD
      value: 1
```

## Expected behavior
When using vagrant prosion the box fails to be initialized completely, because of missing Oracle Java 8 package

```
Setting up oracle-java8-installer (8u201-1~webupd8~1) ...
Using wget settings from /var/cache/oracle-jdk8-installer/wgetrc
Downloading Oracle Java 8...
201-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 104.74.78.99
Connecting to edelivery.oracle.com (edelivery.oracle.com)|104.74.78.99|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz?AuthParam=1555588425_ad58d9735d1986d9897686b31142e5d9 [following]
--2019-04-18 11:51:45--  http://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz?AuthParam=1555588425_ad58d9735d1986d9897686b31142e5d9
Connecting to download.oracle.com (download.oracle.com)|104.101.102.23|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz?AuthParam=1555588425_ad58d9735d1986d9897686b31142e5d9 [following]
--2019-04-18 11:51:45--  https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz?AuthParam=1555588425_ad58d9735d1986d9897686b31142e5d9
Connecting to download.oracle.com (download.oracle.com)|104.101.102.23|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-18 11:51:45 ERROR 404: Not Found.

download failed
Oracle JDK 8 is NOT installed.
```

## Actual behavior
This could be fixed by switching from `oracle-java8-installer`  to `openjdk-11-jre`. After installing manually, everything works as expected.

## Steps to reproduce
1. Create a new vargrant box with homestead
2. Activate elastic search
3. Provision it
