### ISSUE TITLE
MacOS - Connection Timeout After Starting VM

### ISSUE THREAD

**Issue by pseudoramble** [laravel/homestead#1092]
First, thanks for the neat project and all the help! I'm new to Laravel & Homestead, but it's made life a lot easier so far.

Initially when I set up Homestead it seemed to work without issue. However after my initial setup I have issues and pretty consistently receive connection timeout issues when attempting to navigate to the app via browser. This started after switching networks with the host machine (I was at one office and then went to another office). I was able to get it to work by repeatedly reprovisioning/changing IP addresses/hostnames the other day, but it does not appear to be working again.

Right now I'm able to SSH into the vagrant box, and I can see that ngnix is started when I do something like `service nginx status`. I have not seen any specific logs that indicate something is wrong with the VM itself, but I'm not sure where I should be looking.

Some things I have tried include:

* Bringing the VM down & back up
* Destroying the VM & reprovisioning the app
* Setting different IP addresses (192.168.99.99, 192.168.111.111)
* Setting different hostnames
* Hitting the app through the IP address of the machine instead of the hostname (still getting a connection timeout).

## Versions
  - Vagrant: Vagrant 2.2.4
  - Provider: laravel/homestead (virtualbox, 7.1.0)
  - Homestead: 8.2.0
  - VirtualBox 5.2.x

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
OS X Mojave

## Homestead.yaml
```yaml
---
ip: "192.168.99.99"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code/laravel/
      to: /home/vagrant/code

sites:
    - map: app.test
      to: /home/vagrant/code/app/public

databases:
    - homestead
```

## Vagrant destroy & up output
[Gist](https://gist.github.com/pseudoramble/9a8170981da1409026c4a51eb17e1688).

## Expected behavior
Should be able to start vagrant and be able to load the application at the URL `app.test`.

## Actual behavior
Most of the time I receive at Connection Timeout when attempting to load the application. Once in a rare while after `vagrant up --provision` it will work.

## Steps to reproduce
1. Install latest vagrant box for Homestead. 
2. Clone Homestead & check out 8.2.0
3. Configure Homestead.yaml as described above
4. Start the machine and attempt to browse to `app.test`. 

## References
- https://github.com/laravel/homestead/issues/954
