### ISSUE TITLE
Make command produces invalid .yml when multiple folders exist in .example file

### ISSUE THREAD

**Issue by pusherman** [laravel/homestead#1093]
When working with a project that includes a Homestead.yml.example file, running `php vendor/bin/homestead make` will produce an invalid Homestead.yml file.

## Versions
  - Homestead: 8.3.1

## Host operating system
OS X

## Homestead.yml.example
```
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    - map: ~/project1
      to: /home/vagrant/project1

    - map: ~/project2
      to: /home/vagrant/project2
sites:
    - map: project1.test
      to: /home/vagrant/project1/public

    - map: project2.test
      to: /home/vagrant/project2/public
databases:
    - project1
    - project2

name: project1
hostname: project1
```

## Expected behavior
After running the make command, the Homestead.yml produced should be valid and include all the mapped folders from the example file.

```
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /Users/foo/project1
        to: /home/vagrant/project1
    -
        map: /Users/foo/project2
        to: /home/vagrant/project2
sites:
    -
        map: project1.test
        to: /home/vagrant/project1/public
    -
        map: project2.test
        to: /home/vagrant/project2/public
databases:
    - project1
    - project2
name: project1
hostname: project1
```

## Actual behavior
The `Homestead.yml` file produced is invalid yml and produces the following error when running `vagrant up`:

`homestead.rb:170:in 'expand_path': no implicit conversion of nil into String (TypeError)`

```
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /Users/foo/project1
        to: /home/vagrant/project1
    -
        to: /home/vagrant/project2
sites:
    -
        map: project1.test
        to: /home/vagrant/project1/public
    -
        map: project2.test
        to: /home/vagrant/project2/public
databases:
    - project1
    - project2
name: project1
hostname: project1
```

## Steps to reproduce
1. Set up Homestead so it's using the per project configuration
2. Delete your `Homestead.yml` file
3. Create a `Homestead.yml.example` file using the example from above
4. Run `php vendor/bin/homestead make`
