### ISSUE TITLE
undefined local variable or method `scriptDir`

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1095]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6.0.6
  - Homestead: 7.2.1

## Host operating system
Ubuntu 16.04 - Xenial

## Homestead.yaml
```yaml
---
# box: laravel/homestead-7
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
version: ">=0.5.0"

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/sites
      to: /home/vagrant/sites

sites:
    - map: cobaia.test
      to: /home/vagrant/sites/cobaia

databases:

variables:
    - key: 'APP_ENV'
      value: 'local'

crystal: true
dotnetcore: true
golang: true
ruby: true
webdriver: true

```

## Vagrant destroy & up output
[https://gist.github.com/ricardoseriani/e9393d14e03fe4e8601265c5bc67542e](https://gist.github.com/ricardoseriani/e9393d14e03fe4e8601265c5bc67542e)

## Expected behavior
Vagrant up should run the install scripts specified in Homestead.yaml or Homestead.json

## Actual behavior
Vagrant up complains about invalid variable scriptDir

## Steps to reproduce
1. vagrant destroy
2. vagrant up
