### ISSUE TITLE
`path` for shell provisioner does not exist on the host system: homestead/scripts/install-ohmyzsh.sh

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1097]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6.0.6
  - Homestead: 7.2.1

## Host operating system
Ubuntu 16.04 - Xenial

## Homestead.yaml
```yaml
---
# box: laravel/homestead-7
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
version: ">=0.5.0"

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/sites
      to: /home/vagrant/sites

sites:
    - map: cobaia.test
      to: /home/vagrant/sites/cobaia

databases:

variables:
    - key: 'APP_ENV'
      value: 'local'

ohmyzsh: true
```

## Vagrant destroy & up output
[https://gist.github.com/ricardoseriani/aad7bb8f00091414cb05ae11747e90b2](https://gist.github.com/ricardoseriani/aad7bb8f00091414cb05ae11747e90b2)

## Expected behavior
Should run the install scripts for oh-my-zsh

## Actual behavior
Vagrant up complains that scripts/install-ohmyzsh.rb is missing

## Steps to reproduce
1. vagrant destroy
2. vagrant up
