### ISSUE TITLE
File $HOME/.dotnetcore should be owned by vagrant

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1103]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6.0.6
  - Homestead: 7.2.1

## Host operating system
Ubuntu 16.04 - Xenial

## Homestead.yaml
```yaml
---
# box: laravel/homestead-7
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
version: ">=0.5.0"

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/sites
      to: /home/vagrant/sites

sites:
    - map: cobaia.test
      to: /home/vagrant/sites/cobaia

databases:

variables:
    - key: 'APP_ENV'
      value: 'local'

dotnetcore: true
```

## Vagrant destroy & up output
Everything happens OK

## Expected behavior
The file $HOME/.dotnetcore should be owned by vagrant, and not by root

## Actual behavior
The $HOME/.dotnetcore is owned by root

## Steps to reproduce
1. vagrant up
2. vagrant ssh
3. check owner of $HOME/.dotnetcore file (ls -lah in $HOME folder)
