### ISSUE TITLE
Mysql install error

### ISSUE THREAD

**Issue by ndberg** [laravel/homestead#1117]
Trying to vagrant up gives a mysql install error

## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6.0.6
  - Homestead: v.8.3.2

## Host operating system
macOS Mojave 10.14.4

## Homestead.yaml
```yaml
ip: 192.168.10.14
memory: 1024
cpus: 1
provider: virtualbox
mysql8: true
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /Users/Andi/Code/fotogecko
        to: /home/vagrant/code
        type: nfs
sites:
    -
        map: fotogecko.test
        to: /home/vagrant/code/public
        schedule: true
        backup: false
databases:
    - fgapp
name: fotogecko
hostname: fotogecko
```

## Vagrant destroy & up output
[https://gist.github.com/ndberg/a2723827b7a5ebf94b13c968ff354a68](url)

## Expected behavior
Installation of mysql 8

## Actual behavior
Does not install mysql, output: Version '8.0.15-1ubuntu18.04' for 'mysql-server' was not found. Breaks the script with output: Failed to restart mysql.service: Unit mysql.service not found.

## Steps to reproduce
1. vagrant up
