### ISSUE TITLE
`homestead make` ignores xhgui site setting

### ISSUE THREAD

**Issue by m4olivei** [laravel/homestead#1123]
`homestead make` command doesn't copy over `xhgui` settings for sites in `Homestead.yaml.example`.

## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 5.2.26
  - Homestead: 8.4.0

## Host operating system
macOS High Sierra 10.13.6

## Homestead.example.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 4
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: .
      to: /home/vagrant/code

sites:
    - map: drupal-homestead.local
      to: /home/vagrant/code/web
      php: "7.3"
      type: "apache"
      xhgui: "true"

databases:
    - drupal_homestead


name: drupal-homestead
hostname: drupal-homestead.local
mariadb: true
mongodb: true
```

## Expected behavior
Given a `Homestead.yaml.example` file above
When I run `homestead make`
Then I should get `Homestead.yaml` with a site that has `xhgui: "true"`

## Actual behavior
The site listed in the generated `Homestead.yaml` file is missing `xhgui: "true"`.

## References
- [xhgui option aded here](https://github.com/laravel/homestead/pull/1073)
- [Related issue](https://github.com/laravel/homestead/issues/1071)
