### ISSUE TITLE
zsh broke ruby install script

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1131]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6.0.6
  - Homestead: 7.2.1

## Host operating system
Ubuntu 16.04 - Xenial

## Homestead.yaml
```yaml
---
# box: laravel/homestead-7
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
version: ">=0.5.0"

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    # Bin
    - map: ~/bin/
      to: /home/vagrant/bin

    - map: ~/sites
      to: /home/vagrant/sites

    - map: ~/dev
      to: /home/vagrant/dev

    - map: ~/docker
      to: /home/vagrant/docker

sites:
    - map: cobaia.test
      to: /home/vagrant/sites/cobaia

databases:
    - homestead
    - cobaia

variables:
    - key: 'APP_ENV'
      value: 'development'

ohmyzsh: true
ruby: true
```

## Vagrant destroy & up output
https://gist.github.com/ricardoseriani/2c6987a869a28e2bca6049d9b0cdfc99

## Expected behavior
Vagrant up should install oh-my-zsh and ruby.

## Actual behavior
After installing oh-my-zsh, the ruby script cannot run due to not load .zshrc during provision.

## Steps to reproduce
1. vagrant destroy
2. vagrant up
