### ISSUE TITLE
Port proxying issues with sockjs for vue-cli app

### ISSUE THREAD

**Issue by Tarasovych** [laravel/homestead#1134]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6.0.6 r130049
  - Homestead: v8.3.2

## Host operating system
Ubuntu 18.04

## Homestead.yaml
```yaml
ip: "192.168.2.10"
memory: 6144
cpus: 4
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/dev/myvueapp
      to: /home/vagrant/dev/myvueapp

sites:
    - map: myvueapp.local
      to: /home/vagrant/dev/myvueapp.local/public
```

## Vagrant destroy & up output
https://gist.github.com/Tarasovych/7441e25a240bc61b57fd6f94816e05d2

## Expected behavior
I'm trying to make `vue-cli` hot reload work. I run `npm run serve` in my VM. I can access Vue app from my host machine by myvueapp.local in browser.

## Actual behavior
Hot reload does not work. `sockjs` connection is calling not `myvueapp.local` but `myvueapp.local:8080`. So, I'm getting

> https://myvueapp.local:8080/sockjs-node/info?t= net::ERR_CONNECTION_REFUSED

## Steps to reproduce
1. Create `vue-cli` app as described [here](https://cli.vuejs.org/guide/creating-a-project.html)
and add `vue.config.js` in the root:
```js
module.exports = {
  devServer: {
    host: 'myvueapp.local',
    https: true
  }
}
```
2. Run `npm run serve` inside VM
3. Try to access Vue app from your host machine

`Nginx` config:
```
server {
    listen 80;
    listen 443 ssl http2;
    server_name .myvueapp.local;
    root "/home/path/to/myvueapp.local/public";

    index index.html index.htm;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html =404;
        proxy_pass https://myvueapp.local:8080;
    }

    sendfile off;
}
```
`hosts` on host machine:
```
192.168.10.10  myvueapp.local
```
`hosts` in VM:
```
127.0.0.1       myvueapp.local
```
