### ISSUE TITLE
Formatting problem for apache error logs

### ISSUE THREAD

**Issue by ajoliveau** [laravel/homestead#1135]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox
  - Homestead: v8.2.0

## Host operating system
macOS 10.14.3
## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox
mariadb: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/sites
      to: /home/vagrant/sites
      type: "nfs"
    
    - map: ~/logs
      to: /var/log/apache2

sites:
    - map: dev.homestead-test.com
      to: /home/vagrant/sites/homestead-test
      type: apache
      php: "7.3"

databases:
    - homestead


# ports:
#     - send: 3001
#       to: 3001
#     - send: 3002
#       to: 3002
```

## Expected behavior
The error.log files have a normal formatting and are displayed on multiple lines

## Actual behavior

The error.log from PHP in `/var/log/apache2/dev.homestead-test.com-error.log` doesn't wrap around new line characters and every log with its stack trace are on a single line.

Here is an extract from an error.log file : 
`[Fri May 10 18:17:59.468472 2019] [proxy_fcgi:error] [pid 5329:tid 139917577398016] [client 192.168.10.1:61684] AH01071: Got error 'PHP message: PHP Notice:  Undefined variable: bar in /home/vagrant/sites/homestead-test/index.php on line 13PHP message: PHP Stack trace:PHP message: PHP   1. {main}() /home/vagrant/sites/homestead-test/index.php:0PHP message: PHP   2. Test->test1() /home/vagrant/sites/homestead-test/index.php:19PHP message: PHP   3. Test->test2() /home/vagrant/sites/homestead-test/index.php:5PHP message: PHP   4. Test->test3() /home/vagrant/sites/homestead-test/index.php:9'`

## Steps to reproduce
1. Clone this very simple project that just generates an error with a stack trace : https://github.com/ajoliveau/homestead-test
2. Check the apache error log when
