### ISSUE TITLE
Functions defined in aliases use invalid absolute path in per-project homestead installation

### ISSUE THREAD

**Issue by Genchou** [laravel/homestead#1137]
## Versions
  - Vagrant: `2.2.4`
  - Provider: Virtualbox 6.0
  - Homestead: `8.4.0` (homestead installed "pre-project" with `composer require --dev laravel/homestead`)

## Host operating system
macOS 10.14.4

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: . # mapped to the current folder as the project needs to be shared between the dev team. An absolute path would not work.
        to: /home/vagrant/code
sites:
    -
        map: homestead.test
        to: /home/vagrant/code/public
databases:
    - homestead
name: homestead-example
hostname: homestead-example
```

## Vagrant destroy & up output
https://gist.github.com/Genchou/30010744c1dc2582cb0d9bbadadfb644

## Expected behavior
Functions should work as described in the documentation.

## Actual behavior
Any function defined in `aliases` will error as they are calling scripts located in the folder `/vagrant/vendor/laravel/homestead/scripts/`, which doesn't exist. Per-project homestead scripts are in `~/<mapped-folder>/vendor/bin/laravel/homestead/scripts` and the aliases file should reflect that.

## Steps to reproduce
1. Create any kind of php project.
    - `mkdir -p homestead_example/public/`
    - `cd homestead_example`
    - `echo "<?php echo '<h1>Hello Homestead</h1>';" > public/index.php`
2. Add homestead as a dev dependency and initialize it `composer require --dev laravel/homestead` & `php vendor/bin/homestead make`.
3. Modify `Homestead.yaml` if needed (ie remove the absolute path in folders).
4. `vagrant up` then `vagrant ssh` into the VM.
5. Try any function, like `flip`, it will error : `bash: /vagrant/vendor/laravel/homestead/scripts/flip-webserver.sh: No such file or directory`.

**Comment by svpernova09** [comment]
Sorry this took me so long to get back to. I keep thinking I would need to wait until I had some solid time to debug this, and looking over it again when I couldn't reproduce it I see the issue.

From your `Homestead.yaml`

```
folders:
    -
        map: . # mapped to the current folder as the project needs to be shared between the dev team. An absolute path would not work.
        to: /home/vagrant/code
```

Don't do this. It's a Vagrant anti pattern and breaks when Vagrant machines are *expecting to be able to use `/vagrant`.  There's nothing for us to fix here.
