### ISSUE TITLE
vagrant up: /vagrant/scripts/hosts-add.sh: command not found

### ISSUE THREAD

**Issue by AlexJMohr** [laravel/homestead#1161]
## Versions
  - Vagrant: Vagrant 2.2.4
  - Provider: Virtualbox 5.2.18_Ubuntu r123745
  - Homestead: Laravel Homestead 8.5.1

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Linux Mint 19.1

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /home/amohr/projects/php/roommates
        to: /home/vagrant/code
sites:
    -
        map: homestead.test
        to: /home/vagrant/code/public
databases:
    - homestead
name: roommates
hostname: roommates
```

## Vagrant destroy & up output
https://gist.github.com/AlexJMohr/21834622735e8530bcea0b1f463e1f26

## Expected behavior
`/vagrant/scripts` should exist?

## Actual behavior
After creating a fresh laravel homestead project (see steps to reproduce), running `vagrant up` results in the error:
```
roommates: /vagrant/scripts/hosts-add.sh: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

*edit: I can `vagrant ssh` into the box after `vagrant up` finishes. There is no /vagrant/scripts folder. Should there be?*

## Steps to reproduce
1. `composer create-project --prefer-dist laravel/laravel roommates`
2. `composer require laravel/homestead --dev`
3. `vendor/bin/homestead make`
4. `vagrant up`
