### ISSUE TITLE
Grafana install error

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1167]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6.0.8
  - Homestead: 7.2.1
  - Homestead git: version_9

## Host operating system
Ubuntu 16.04 - Xenial

## Homestead.yaml
```yaml
---
# box: laravel/homestead-7
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
version: ">=0.5.0"

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/sites
      to: /home/vagrant/sites

sites:
    - map: cobaia.test
      to: /home/vagrant/sites/cobaia

databases:
    - cobaia

variables:
    - key: 'APP_ENV'
      value: 'development'

ports:
    - send: 63790
      to: 6379

features:
    - grafana: true

```

## Vagrant destroy & up output
https://gist.github.com/ricardoseriani/b4393555d1db5abcfd81b9c49ca19437

## Expected behavior
Install grafana.

## Actual behavior
Doesn't install grafana due to `GPG error: https://packagecloud.io/grafana/stable/debian stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40F370A1F9081B64`

## Steps to reproduce
1. vagrant destroy
2. vagrant up
