### ISSUE TITLE
Couchdb install error

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1168]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6.0.8
  - Homestead: 7.2.1
  - Homestead git: version_9

## Host operating system
Ubuntu 16.04 - Xenial

## Homestead.yaml
```yaml
---
# box: laravel/homestead-7
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
version: ">=0.5.0"

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/sites
      to: /home/vagrant/sites

sites:
    - map: cobaia.test
      to: /home/vagrant/sites/cobaia

databases:
    - cobaia

variables:
    - key: 'APP_ENV'
      value: 'development'

ports:
    - send: 63790
      to: 6379

features:
    - couchdb: true

```

## Vagrant destroy & up output
https://gist.github.com/ricardoseriani/726004747519d85b17f7950e01f7c81e
## Expected behavior
Install grafana.

## Actual behavior
Doesn't install grafana due to `The repository 'http://ppa.launchpad.net/couchdb/stable/ubuntu bionic Release' does not have a Release file.`

## Steps to reproduce
1. vagrant destroy
2. vagrant up
