### ISSUE TITLE
`homestead make` ignores options folder setting

### ISSUE THREAD

**Issue by m4olivei** [laravel/homestead#1171]
The `homestead make` command doesn't copy over options setting for folders in `Homestead.yaml.example`.

## Versions
- Vagrant: 2.2.4
- Provider: Virtualbox 5.2.26
- Homestead: 8.5.3

## Host operating system
macOS High Sierra 10.13.6

## Homestead.example.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 4
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
      map: .
      to: /home/vagrant/code
      type: rsync
      options:
          rsync__exclude: [".git/", ".idea", "web/sites/*/files", "web/sites/*/files-private", "web/artifacts", "web/sites/simpletest"]
          rsync__args: ["--verbose", "--archive", "--delete", "-z", "--chmod=g+rwX"]
sites:
    -
        map: drupal-homestead.local
        to: /home/vagrant/code/web
        type: apache
        php: '7.3'
        xhgui: 'true'
databases:
    - drupal_homestead
name: drupal-homestead
hostname: drupal-homestead.local
mariadb: true
mongodb: true
```

## Expected behavior
Given a `Homestead.yaml.example` file above
When I run `homestead make`
Then I should get `Homestead.yaml` with a folder that includes the `options`, eg.:
```
folders:
    -
        map: /Users/m4olivei/projects/drupal_homestead
        to: /home/vagrant/code
        type: rsync
        options:
            rsync__exclude: [".git/", ".idea", "web/sites/*/files", "web/sites/*/files-private", "web/artifacts", "web/sites/simpletest"]
            rsync__args: ["--verbose", "--archive", "--delete", "-z", "--chmod=g+rwX"]
```

## Actual behavior
I get `Homestead.yaml` with a folder that is missing the `options`, eg.
```
folders:
    -
        map: /Users/m4olivei/projects/drupal_homestead
        to: /home/vagrant/code
        type: rsync
```

## References
- Related issue fixed: #1123
