### ISSUE TITLE
Laravel app throwing Facade Root Exception after running vagrant reload

### ISSUE THREAD

**Issue by mccordgh** [laravel/homestead#1178]
Posting this per @svpernova09 's advice from a laracasts post (linked at bottom)

## Versions
  - Vagrant:`2.2.4`
  - Provider: Virtualbox `Version 5.2.30`
  - Homestead: `8.0.0-alpha2`

## Host operating system
OS X Mojave `10.14.5`

## Homestead.yaml
```yaml
ip: 192.168.33.50
memory: 4096
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: ../
        to: /home/vagrant/code
sites:
    -
        map: my-app.test
        to: /home/vagrant/code/web/public
databases:
    - homestead
name: web
hostname: web
```

## Vagrant destroy & up output
[vagrant destroy gist](https://gist.github.com/mccordgh/3111113eca864405bcc5dad5cac2ddba)

[vagrant up gist](https://gist.github.com/mccordgh/a093b1b50347409f5467e17ed02d8308)

## Expected behavior
After `vagrant --reload` or a `vagrant halt && vagrant up` I should be able to access my web app at `my-app.test`.

## Actual behavior
1. After `vagrant --reload` or a `vagrant halt && vagrant up`, I get this error screen when trying to navigate to `my-app.test`:
![Screen Shot 2019-06-03 at 12 05 26 PM](https://user-images.githubusercontent.com/11222008/58827463-f24c1700-85f7-11e9-90b0-4833e683b8b3.png)

If I run (from OUTSIDE the vagrant box):
`$ php artisan cache:clear`
`$ php artisan route:cache`
`$ php artisan config:cache`
`$ php artisan view:clear`
I can get "past" this error screen, but then get a new one saying that "[...]/storage/logs" does not exist and could not be built: Permission Denied:
![Screen Shot 2019-06-03 at 12 11 14 PM](https://user-images.githubusercontent.com/11222008/58827780-b6fe1800-85f8-11e9-9d1e-091a2e980844.png)

If I try to run any of those cache clearing commands from INSIDE vagrant (after `vagrant ssh`), I get this error:
<img width="205" alt="Screen Shot 2019-06-03 at 12 12 11 PM" src="https://user-images.githubusercontent.com/11222008/58827828-d7c66d80-85f8-11e9-8ca2-1ad6330d56bd.png">

Permissions seem to be a false flag as I've tried changing permissions, etc and the directory definitely does exist.

I haven't found anyway to get any further besides doing `vagrant destroy && vagrant up` again. But, of course, the errors begin again anytime I do a `vagrant reload` or `vagrant halt && vagrant up` or restart my machine, etc.

## Steps to reproduce
1. `$ vagrant up` to bring box up
1. Navigate in browser to your box's mapped url
1. Verify everything is working correctly
1. Run `$ vagrant reload` or `$ vagrant halt && vagrant up`
1. Navigate in browser to your box's mapped url again.
1. Facade Root error should appear.

## References
I arrived here through these links:
1. https://laracasts.com/discuss/channels/laravel/laravel-app-throwing-exception-after-running-vagrant-reload?page=1
2. https://github.com/laravel/homestead/issues/1174#issuecomment-498104987

**Comment by svpernova09** [comment]
First thing to try would be changing your folder mounts:

```
folders:
    -
        map: ../
        to: /home/vagrant/code
```

To

```
folders:
    -
        map: /Full/Path/To/Code/Project
        to: /home/vagrant/code
```
