### ISSUE TITLE
oh my zsh support broken and doesn't handle repeated provisioning

### ISSUE THREAD

**Issue by m4olivei** [laravel/homestead#1191]
## Versions
- Vagrant: 2.2.4
- Provider: Virtualbox 5.2.26
- Homestead: 8.5.3

## Host operating system
macOS High Sierra 10.13.6

## Homestead.example.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 4
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: .
        to: /home/vagrant/code
        type: rsync
        options:
            rsync__exclude: [".git/", ".idea", "web/sites/*/files", "web/sites/*/files-private", "web/artifacts", "web/sites/simpletest"]
            rsync__args: ["--verbose", "--archive", "--delete", "-z", "--chmod=g+rwX"]
sites:
    -
        map: mysite.local
        to: /home/vagrant/code/web
        type: apache
        php: '7.3'
        xhgui: 'true'
databases:
    - mysite
name: mysite
hostname: mysite.local
mongodb: true
ohmyzsh: true
variables:
    -
        key: ZSH_THEME
        value: robbyrussell
```

## Expected behavior

Should install oh my zsh as the shell with the robbyrussell theme.

## Actual behavior

I get errors on provision:

```
==> mysite: Running provisioner: shell...
    mysite: Running: script: Installing Oh-My-Zsh
    mysite: Cloning into '/home/vagrant/.oh-my-zsh'...
    mysite: fatal: unable to connect to github.com:
    mysite: github.com[0: 192.30.253.113]: errno=Connection timed out
    mysite: cp: cannot stat '/home/vagrant/.oh-my-zsh/templates/zshrc.zsh-template': No such file or directory
```
Also as I debugged and ran `vagrant provision` multiple times, I noticed that the script for installing oh my zsh doesn't check for a prior install and not all the commands are idempotent.

**Comment by svpernova09** [comment]
> mysite: github.com[0: 192.30.253.113]: errno=Connection timed out

Homestead can't do anything about your connection to Github (or any other server for that matter) timing out.

```
variables:
    -
        key: ZSH_THEME
        value: robbyrussell
```

`variables` is for nginx FPM settings. Not for feature use.

```
...and ran vagrant provision multiple times...
```

Running `vagrant provision` is not the suggested way to provision Homestead because it incorrectly assumes all scripts are idempotent when in the current stable release is not always the case (as you've discovered). The only true debugging method is `vagrant destroy && vagrant up`. Idempotency is more a recent thing we've been doing for the next version because of situations exactly like this, we're trying to protect people from themselves. Also, Homestead can't use `vagrant provision` as a suggested provisioning method because we can't assume end users build `after.sh` or `user-customizations.sh` in an idempotent way.
