### ISSUE TITLE
MySql 8 not available in v9.0.0-beta

### ISSUE THREAD

**Issue by RalphMRivera** [laravel/homestead#1200]
## Versions
  - Vagrant: Vagrant 2.2.5
  - Provider: Virtualbox 5.2.30 r130521 (Qt5.6.3)
  - Homestead: laravel/homestead (virtualbox, 8.0.0-beta)

## Host operating system
macOS Mojave 10.14.15

## Homestead.yaml
```yaml
---
ip: "10.10.10.10"
memory: 2048
cpus: 1
mysql8: true
provider: virtualbox
```

## Vagrant destroy & up output
https://gist.github.com/RalphMRivera/b29a098c696a26531d3fcae86428591f

## Expected behavior
I was expecting MySql 8

## Actual behavior
mysqld  Ver 5.7.26-0ubuntu0.18.04.1 for Linux on x86_64 ((Ubuntu))

## Steps to reproduce
1. Install a clean copy of Homestead
2. Checkout `v9.0.0-beta`
3. Add `mysql8: true` to `homestead.yaml`
4. run `vagrant up`
5. run `mysqld --version`
