### ISSUE TITLE
VM name isn't set right, which breaks vagrant-hostmanager

### ISSUE THREAD

**Issue by Lucky-Loek** [laravel/homestead#1208]
## Versions
  - Vagrant: 2.2.5
  - Provider: Virtualbox 6.0.8
  - Homestead: Both master and v9.0.0

## Host operating system
Windows 10 Professional (build 1809)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 1024
cpus: 1
provider: virtualbox

folders:
   - map: C:/Code
     to: /home/vagrant/code

sites:
   - map: package.test
     to: /home/vagrant/code/Laravel-Package-Development/public
   - map: itp-portfolio-generator.test
     to: /home/vagrant/code/itp-portfolio-generator/public
   - map: lmdb.test
     to: /home/vagrant/code/LMDb/public
   - map: blog-papa.test
     to: /home/vagrant/code/blog-papa/public

databases:
   - homestead
   - itp-portfolio
   - lmdb
```

## Vagrant destroy & up output
https://gist.github.com/Lucky-Loek/c9be61189e3cc715d0bfe45304894b62

## Expected behavior
VM name should be the same across the board. 

## Actual behavior
Naming in `homestead.rb` is different than the VM actually recieves. Now it's "homestead" for Vagrant and "homestead-7" for vagrant-hostmanager. See terminal output above for name that the VM receives (line 6) and see output below to see what the scripts say that the name should be.
```bash
$ grep "homestead-7" -R .
./Homestead/scripts/homestead.rb:      vb.name = settings['name'] ||= 'homestead-7'
./Homestead/scripts/homestead.rb:      v.vmx['displayName'] = settings['name'] ||= 'homestead-7'
./Homestead/scripts/homestead.rb:      h.vmname = settings['name'] ||= 'homestead-7'
./Homestead/scripts/homestead.rb:      v.name = settings['name'] ||= 'homestead-7'
```

## Steps to reproduce
1. Clean install of newest version of homestead (v9.0.0)
2. `vagrant up`
