### ISSUE TITLE
Problem when installing blackfire feature

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1212]
## Versions
  - Vagrant: Vagrant 2.2.5
  - Provider: 6.0.8
  - Homestead: master or release.

## Host operating system
Ubuntu 16.04

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/sites
      to: /home/vagrant/sites

sites:
    - map: homestead.test
      to: /home/vagrant/sites/homestead/public

databases:
    - homestead

features:
    - blackfire: "server_id" "server_token" "client_id" "client_token"
```

## Vagrant destroy & up output
https://gist.github.com/ricardoseriani/1dfe7ebeac467a9d4e86176776ea7b45

## Expected behavior
Should install blackfire with the credentials provided

## Actual behavior
Vagrant up is broken due to errors when parsing the Homestead.yaml

## Steps to reproduce
1. vagrant destroy
2. config Homestead.yaml as defined
3. vagrant up

The current blackfire.sh script uses the variables $1, $2, $3, $4, but AFAIK yaml can't understand the yaml using multiple values in the same key, like in the example.

I can think of some approaches:
 - We can set some kind of "separator" in the parsing of yaml features value, but this can create some problems with the separator being used in the string value
 - Create a new section with the variables, parse it before all the features try to run, and use that in the script, but will make less explicit that this value refers to that feature
 - Create some kind of sub-parameters in each feature, but this will make the features harder to create and to parse

Any thoughts on this ?

**Comment by svpernova09** [comment]
What about a syntax list this (That would be specific to this feature) where we take the array in Ruby and pass it to the installer script as params? This would make the YAML explicit and readable, and keep the Ruby bits readable as well.

```
features:
    - blackfire: 
        - server_id: VALUE
        - server_token: VALUE
        -  client_id: VALUE
        - client_token: VALUE
```
