### ISSUE TITLE
Feature/Grafana install error

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1217]
## Versions
  - Vagrant: Vagrant 2.2.5
  - Provider: 6.0.8
  - Homestead: master or release.

## Host operating system
Ubuntu 16.04

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/sites
      to: /home/vagrant/sites

sites:
    - map: homestead.test
      to: /home/vagrant/sites/homestead/public

databases:
    - homestead

features:
    - grafana: true
```

## Vagrant destroy & up output
https://gist.github.com/ricardoseriani/afe17ec064ff527ece44ad98c71d22d6

## Expected behavior
Should install grafana

## Actual behavior
Vagrant up is broken due to invalid grafana ppa repository

## Steps to reproduce
1. vagrant destroy
2. config Homestead.yaml as defined
3. vagrant up
