### ISSUE TITLE
Unable to load the "app" configuration file.  

### ISSUE THREAD

**Issue by lloricode** [laravel/homestead#1219]
## Versions
  - Vagrant: Vagrant 2.2.5
  - Provider: Virtualbox
  - Homestead: v9.0.2
  - Settler: v8.0.0

## Host operating system
Release Linux Mint 19.1 Tessa 64-bit
Kernel Linux 4.15.0-54-generic x86_64
MATE 1.20.1

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Documents/homestead
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/homestead/public
databases:
    - homestead

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Expected behavior
when I run `art` it should return `artisan information`

## Actual behavior
```
vagrant@homestead:~/code/homestead$ art

In LoadConfiguration.php line 68:
                                                
  Unable to load the "app" configuration file.  
                                               
```

## Steps to reproduce
1. update latest homestead and settler
2. just run `art` on homestead inside project
