### ISSUE TITLE
composer create-project fails

### ISSUE THREAD

**Issue by mtulikowski** [laravel/homestead#1226]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6
  - Homestead: release branch

## Host operating system
Windows 10 Home

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: c:/Users/zleek/.ssh/id_rsa.pub

keys:
    - c:/Users/zleek/.ssh/id_rsa

folders:
    - map: d:/htdocs/symfony4
      to: /home/vagrant/symfony4

sites:
    - map: symfony4.local
      to: /home/vagrant/symfony4/public
      type: symfony4

databases:
    - homestead

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
- destroy: https://gist.github.com/mtulikowski/7e2a4a7a2aee90d1a4cee90c870c0b63
- up: https://gist.github.com/mtulikowski/205681029d4f01c3d0655f53839e1f5c

## Expected behavior
I should be able to run in vagrant container following command:
composer create-project symfony/website-skeleton symfony4 

## Actual behavior
I have following error (composer cannot delete files):
https://gist.github.com/mtulikowski/e35267ff19c25dfa6fe1c82b2a76b4c2

## Steps to reproduce
1. Run container
2. Enter by vagrant ssh and run command: composer create-project symfony/website-skeleton symfony4 

Note:
If I run command: "composer create-project symfony/website-skeleton {dir}" to not mapped directory, all works fine and project is created.
