### ISSUE TITLE
mariadb has errors with schemas

### ISSUE THREAD

**Issue by pOmelchenko** [laravel/homestead#1228]
## Versions
  - Vagrant: Vagrant 2.2.5
  - Provider: Virtualbox 6.0.6
  - Homestead: It is `release` branch.
  - phpstorm 2019.1.3

## Host operating system
macOS 10.14.5

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mariadb: true

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
https://gist.github.com/pOmelchenko/7dcfa7bf1304a587156a7e26a5c2cb9f

## Expected behavior
Connect to `homestead` db without errors

## Actual behavior
Connect with errors
```
2019-07-08
18:41	Connected

18:41	select
		event_name,
		event_comment,
		definer,
		event_type = 'RECURRING' recurring,
		interval_value,
		interval_field,
		cast(coalesce(starts, execute_at) as char) starts,
		cast(ends as char) ends,
		status,
		on_completion = 'PRESERVE' preserve,
		last_executed
		from information_schema.events
		where event_schema = ?
		[HY000][1577] Cannot proceed, because event scheduler is disabled

18:41	homestead@localhost
		[HY000][1577] Cannot proceed, because event scheduler is disabled.
		Error encountered when performing Introspect schema h ... more
```

## Steps to reproduce
1. Open/create project in phpstorm
2. Create connection to database
<img width="912" alt="Снимок экрана 2019-07-08 в 18 40 37" src="https://user-images.githubusercontent.com/3578284/60823916-4cb93400-a1b1-11e9-9877-bc907b4f6d73.png">
<img width="912" alt="Снимок экрана 2019-07-08 в 18 40 43" src="https://user-images.githubusercontent.com/3578284/60823922-4f1b8e00-a1b1-11e9-9120-44f7cb0e88c3.png">
3. Check connection
<img width="912" alt="Снимок экрана 2019-07-08 в 18 40 58" src="https://user-images.githubusercontent.com/3578284/60823844-28f5ee00-a1b1-11e9-9567-bc26951a4e87.png">
<img width="912" alt="Снимок экрана 2019-07-08 в 18 40 54" src="https://user-images.githubusercontent.com/3578284/60823866-3317ec80-a1b1-11e9-973d-bd3c4f94fed6.png">
4. Click `synchronize` into database panel
<img width="525" alt="Снимок экрана 2019-07-08 в 18 51 26" src="https://user-images.githubusercontent.com/3578284/60824021-87bb6780-a1b1-11e9-92a4-4c62658befd4.png">
5. Read logs into `event logs` panel
<img width="671" alt="Снимок экрана 2019-07-08 в 18 41 21" src="https://user-images.githubusercontent.com/3578284/60824100-acafda80-a1b1-11e9-880e-92e99bed112c.png">
<img width="968" alt="Снимок экрана 2019-07-08 в 18 41 30" src="https://user-images.githubusercontent.com/3578284/60824130-b89b9c80-a1b1-11e9-87f0-c0b9e8bb31cd.png">
