### ISSUE TITLE
The shell provisioner's `env` option must be a hash.

### ISSUE THREAD

**Issue by Eldair** [laravel/homestead#1230]
## Versions
  - Vagrant: 2.2.4
  - Provider: Virtualbox 6.0.6
  - Homestead: commit 1be2640e63d2f1e9eb87198f63f545ab714bd1c0

## Host operating system
Windows 10 1903

## Homestead.yaml
```yaml
---
ip: '192.168.10.10'
memory: 4096
cpus: 4
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: E:/Code/
      to: /home/vagrant/Code

sites:
    - map: domaindata.test
      to: /home/vagrant/Code/domain-data/public

databases:
    - domaindata

features:
    - elasticsearch: 6
    - ohmyzsh: true
```

## Vagrant destroy & up output
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* The shell provisioner's `env' option must be a hash.
```

## Actual behavior
Vagrant up doesn't work starting with commit mentioned above (checking out commit before that one or any v9 works fine)
