### ISSUE TITLE
General issues on Windows 10

### ISSUE THREAD

**Issue by gbryant200** [laravel/homestead#1242]
folder mapping not working / default aliases not working / Apache flip not working

## Versions
  - Vagrant: version  2.2.5
  - Provider: Virtualbox 6.0.8 r130520 (Qt5.6.2)
  - Homestead: 9.03

## Host operating system
Windows 10 Enterprise 10.0.17763 Build 17763 (Legacy Bios mode) - Version 1809

## Homestead.yaml
I've tried numerous different ways to get the folders to map - none have worked - single quotes, no quotes, double quotes with one and or two backslashes, etc.
```
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "c:\\Users\\a04029\\projects\\ep"
      to: /var/www/ep

    - map: "c:\\Users\\a04029\\projects\\sa"
      to: /var/www/sa

    - map: "c:\\Users\\a04029\\projects\\na"
      to: /var/www/na

sites:
    - map: ep.test
      to: /var/www/ep/public
      type: apache

    - map: sa.test
      to: /var/www/sa/public
      type: apache

    - map: na.test
      to: /var/www/na/public
      type: apache

databases:
    - ep
    - sa
    - na
      
backup: true

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
https://gist.github.com/gbryant200/3185613ee0fde395fd80c8a49249166e
