### ISSUE TITLE
homestead.test HTTPS error

### ISSUE THREAD

**Issue by cmfactory** [laravel/homestead#1256]
## Versions
  - Vagrant: 2.2.5
  - Provider: Virtualbox 6.0.10
  - Homestead: Release (9.0.7)
  - Box: 8.0.1

## Host operating system
Windows 10 1903

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code
      type: "nfs"

sites:
    - map: homestead.test
      to: /home/vagrant/code/c9ws

databases:
    - c9db
    - c9cr
    - c9kms
    - c9audit
    - c9log
    - c9mgmt
    - c9portal

```

## Vagrant destroy & up output
https://gist.github.com/cmfactory/4c369c571e46ddfb7c541c50f0bd728b

## Expected behavior
Considering Homestead Root CA is Trusted in Chrome, I expected to be able to access site using HTTPS without issues.

## Actual behavior
Using default settings I'm unable to access HTTPS without certificate errors on Chrome 76.0.3809.100. Homestead Root CA is accepted normally, but for homestead.test it says invalid digital signature for homestead.test certificate. I also tried generating stronger SSH keys for auth but result is the same.
Also tried other domains such as homestead.local and homestead.localhost (which doesn't want to load).

## Steps to reproduce
1. Do `vagrant destroy && vagrant up` using default Homestead.yaml
2. Connect site to IP in C:\Windows\System32\Drivers\Etc\Hosts file
3. Load the site (https://homestead.test)

## References
#755 
#754
