### ISSUE TITLE
Box 'laravel/homestead' (v8.0.1) is running the latest version

### ISSUE THREAD

**Issue by repat** [laravel/homestead#1264]
## Versions
  - Vagrant: 2.2.5
  - Provider: virtualbox 6.0.10
  - Homestead: `release`

## Host operating system
`Darwin Renes-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64`

## Homestead.yaml
```yaml
ip: "192.168.42.10"
memory: 2048
cpus: 1
provider: virtualbox
mysql8: true
ssl: true
authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Documents/GitHub/foobar
      to: /home/vagrant/foobar
sites:
    - map: foobar.test
      to: /home/vagrant/foobar/public
      php: "7.3"
databases:
    - foobar
```

## Expected behavior
Update to [9.0.7](https://github.com/laravel/homestead/releases) or at the very least 8.6.0.

## Actual behavior
```
➜ vagrant box update
==> homestead: Checking for updates to 'laravel/homestead'
    homestead: Latest installed version: 8.0.1
    homestead: Version constraints: >= 8.0.0
    homestead: Provider: virtualbox
==> homestead: Box 'laravel/homestead' (v8.0.1) is running the latest version.
```

This matches: https://app.vagrantup.com/laravel/boxes/homestead. So this is not exactly a bug report, but:

1. why is this version not the latest one?
2. how do you update to 9.0.7 instead?

## References
- https://app.vagrantup.com/laravel/boxes/homestead
