### ISSUE TITLE
Laravel apps slow / unresponsive over local domain name [linux]

### ISSUE THREAD

**Issue by Davincible** [laravel/homestead#1265]
## Versions
  - Vagrant: Vagrant 2.2.5
  - Provider: Virtualbox 6.0.10
  - Homestead: downlaoded v9 but when booting vagrant says v8

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Pop OS (Ubuntu 19)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

# added this later as I saw it in some other issue
natdnshostresolver: off

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /home/tyler/Launchpad/www
      to: /home/vagrant/code

sites:
    - map: lsapp.test
      to: /home/vagrant/code/lsapp/public/
      
    - map: phpmyadmin.test
      to: /home/vagrant/code/phpmyadmin/

databases:
    - homestead
    - lsapp

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
    

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

My /etc/hosts:

```
127.0.0.1	localhost
::1		localhost
127.0.1.1	unavailable.localdomain	unavailable
192.168.69.34	anderson
192.168.10.10	lsapp.test unavailable
192.168.10.10	phpmyadmin.test unavailable

```

## Vagrant destroy & up output
https://gist.github.com/Davincible/dee6526dd12a3c16e65fbe9b42bd45d2

## Expected behavior
Web app access over domain name works just as smoothly as when directly accessing the website over the ip `192.168.10.10`

## Actual behavior
Access over ip works as expected, however, when using the domain name it gets randomly stuck in loading loops. I can browse a few pages, and then it will get stuck. Usually also gets stuck when trying to login using POST, although I do login errors sometimes suggesting it's not necisarrliy only during POST methods.

## Steps to reproduce
1. installed vagrant & homestead as instructed
2. ported my project that I devlopped on windows to my current linux machine
3. run
