### ISSUE TITLE
#mysql50#lost+found

### ISSUE THREAD

**Issue by treyssatvincent** [laravel/homestead#1267]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.5
  - Provider: Virtualbox 6.0.10
  - Homestead: `release` branch (a3534ac)

## Host operating system
ArchLinux (5.2.11-arch1-1-ARCH)

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_ed25519.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code/bip
      to: /home/vagrant/bip
      type: "nfs"
      options:
        rsync__exclude: ["node_modules"]

sites:
    - map: bip.home.local
      to: /home/vagrant/bip/public

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
```

## Vagrant destroy & up output
https://gist.github.com/treyssatvincent/db8f7ad6ebad61b4573776ae87a8b930

## Expected behavior
During the virtual machine creation only theses database should be created : 

~~~
+---------------------+
| Database            |
+---------------------+
| information_schema  |
| homestead           |
| mysql               |
| performance_schema  |
| sys                 |
+---------------------+
~~~

## Actual behavior
There is a `#mysql50#lost+found` created during the virtual machine creation resulting in this list of databases : 

~~~
+---------------------+
| Database            |
+---------------------+
| information_schema  |
| homestead           |
| #mysql50#lost+found |
| mysql               |
| performance_schema  |
| sys                 |
+---------------------+
~~~

## Steps to reproduce
1. Create a homestead virtual machine and SSH into it.
2. run `mysql -e "show databases"`

## References
[MySQL ticket #22615](https://bugs.mysql.com/bug.php?id=22615)
