### ISSUE TITLE
mapping values are not allowed in this context

### ISSUE THREAD

**Issue by crisleiria** [laravel/homestead#1274]
Hi everyone,

On vagrant up comand, using latest version of vagrant and fresh installation of Win 10.
My homestead file is attached, but basically is the default one with small changes, so it should not have any parsing issues.
I am using Laravel/Homestead.
Anyone with the same problem?

## Versions
  - Vagrant: 2.2.5
  - Provider: Virtualbox 6.0
  - Homestead: latest branch (from yesterday)

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/ProjetosLaravel
      to: /home/vagrant/code

sites:
    - map: teste.test
      to: /home/vagrant/code/teste/public

databases:
    - homestead

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.

```

## Vagrant destroy & up output

[vagrant up output.txt](https://github.com/laravel/homestead/files/3604456/vagrant.up.output.txt)

## Expected behavior

Homestead start with no issues

## Actual behavior
Error on vagrant up command

## Steps to reproduce
1.Simply followed Laravel webpage installation for homestead
https://laravel.com/docs/5.8/homestead

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- https://github.com/hashicorp/vagrant/issues/11062
