### ISSUE TITLE
Provide a complete and usable SSH key pair

### ISSUE THREAD

**Issue by alinnert** [laravel/homestead#1275]
> Please note that the Homestead issue tracker is reserved for (...)

(*psst. You can put comments in GitHub issue templates that don't get printed in the final issue body by using HTML comment syntax. That way users don't have to delete them or get confused about what is allowed to be deleted and what isn't.*)

## Versions
- Vagrant: Run `vagrant -v` to show the version.
  - 2.2.5
- Provider: Virtualbox, VMWare, Hyper-V, or Parallels and its version.
  - VirtualBox 6.0.12
- Homestead: You should be on the most recent `release` branch.
  - Where can I see the currently used Homestead version? But I've just installed the recent version as of 13th of Sept 2019.

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Windows 10 Pro 1903

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

# folders:
    # - map: ~/code
    #   to: /home/vagrant/code

sites:
    - map: site-1.homestead.net.local
      to: /home/vagrant/projects/project-1/public/site-1
    - map: site-2.homestead.net.local
      to: /home/vagrant/projects/project-1/public/site-2

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
```

## Vagrant destroy & up output
*I don't think this is necessary. It's not a bug report.*

## Expected behavior
I expect there to be a fully usable private/public key pair in `~/.ssh/`: `id_rsa` and `id_rsa.pub`.

Plus the passphrase should be known so users can actually use the key pair by using the known passphrase or changing it to a new one.

## Actual behavior
There's only `id_rsa`.

Why? This is needed to make SSH connections to other servers from within Homestead. My use case is to `git clone` my projects directly into Homestead. Now that there's the VS Code Remote extension developers can edit files directly inside Homestead using the VS Code instance on the host system.

I've had issues with Craft CMS in VirtualBox. These were caused by the fact that the project files get synced between the host and the virtual client. I don't remember much details. But I think Windows being the host system was part of the issue. Editing files in Homestead directly should hopefully cause less such issues.

Interestingly the public key can be found in `~/.ssh/authorized_keys`, but I still can't use it because a passphrase is needed and it's not `vagrant` at least.

I can create a new key pair. That's actually what I've done. But it shouldn't be necessary to have two key pairs inside Homestead.

## Steps to reproduce
none

## References
#58 - this issue is about the same thing but it has been closed because of inactivity.

**Comment by svpernova09** [comment]
> I expect there to be a fully usable private/public key pair in ~/.ssh/: id_rsa and id_rsa.pub.

Homestead does not provide keys in this instance. You would need to create your own keys.

**Comment by alinnert** [comment]
@svpernova09 Yes, that's what I did. But why? There are keys already. Why can't I use them?

**Comment by svpernova09** [comment]
> Yes, that's what I did. But why? There are keys already. Why can't I use them?

Based on https://github.com/laravel/homestead/blob/master/scripts/homestead.rb#L141-L158

You need to update your `Homestead.yaml` to something like this:

```
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa
    - ~/.ssh/id_rsa.pub

# folders:
    # - map: ~/code
    #   to: /home/vagrant/code

sites:
    - map: site-1.homestead.net.local
      to: /home/vagrant/projects/project-1/public/site-1
    - map: site-2.homestead.net.local
      to: /home/vagrant/projects/project-1/public/site-2

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
```

Then `vagrant destroy && vagrant up` will rebuild the box for you. Then you should have both keys as you're expecting.
