### ISSUE TITLE
npm fails to run on fresh Homestead and Laravel install on MacOS host

### ISSUE THREAD

**Issue by liamoreilly** [laravel/homestead#1286]
Upon running `npm install` on a fresh install of Homestead, in a fresh laravel website on a shared folder, I get the following error:

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/vagrant/Laravel/testsite/node_modules/yargs/node_modules/yargs-parser/package.json.2388346558
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/Laravel/testsite/node_modules/yargs/node_modules/yargs-parser/package.json.2388346558'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2019-09-28T14_50_09_294Z-debug.log
```

I have seen many other threads whihc look similar however, they all discuss the root cause to be interplay between VirtualBox and shared flders with a windows host. I am not using a Windoes host but MacOS.

That said, the above npm command was run on a fresh laravel website (inside the Homestead virtual machine) in a folder which was mapped in from the host. When I ran the test from the home directory of Homestead (i.e., no sshared folders involved) then npm worked as expected.

I am really not sure where the bug is here. **I do not belive Windows is not involved in this problem as the host is MacOS**. This has worked for many years with no trouble.

## Versions
  - Vagrant: 2.2.5
  - Provider: Virtualbox 6.0.12
  - Homestead: Release branch (9.2.0)

## Host operating system
MacOS version 10.14.6

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_homestead.pub

keys:
    - ~/.ssh/id_homestead

folders:
    - map: /Users/liamoreilly/Desktop/Laravel
      to: /home/vagrant/Laravel

sites:
    - map: testsite.test
      to: /home/vagrant/Laravel/testsite/public

databases:
    - testsite

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
[https://gist.github.com/liamoreilly/88d9c1517f65d6d489874dd513165d2c](https://gist.github.com/liamoreilly/88d9c1517f65d6d489874dd513165d2c)

## Expected behavior
npm fails to install the node modules.

## Actual behavior
npm should work as expected installing the node modules. See above for details

## Steps to reproduce
1. cd within the Homestead virtual machine to a shared folder
2. laravel new testsite
3. cd testsite
4. npm install

## References
[https://github.com/laravel/homestead/issues/1239](https://github.com/laravel/homestead/issues/1239)
