### ISSUE TITLE
"Configuring proxy for (git|npm|PEAR)..." runs ~45 times and increases provisioning time by ~50%

### ISSUE THREAD

**Issue by cbj4074** [laravel/homestead#1287]
## Versions
  - Vagrant: 2.2.5
  - Provider: Hyper-V
  - Homestead: 9.2.0

## Host operating system
Windows 10 build 1908.

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
Rather than paste all of it, it probably makes sense only to paste the part that is unexpected.

For every script that is run during provisioning, the following output occurs:

```
    homesteadstock: Running: inline script
==> homesteadstock: Configuring proxy for Git...
==> homesteadstock: Configuring proxy for npm...
==> homesteadstock: Configuring proxy for PEAR...
```

## Expected behavior
I expect that configuring these proxies would be irrelevant for the vast majority of scripts that run during provisioning.

## Actual behavior
The above `Configuring proxy` lines are printed for every script, and they seem to consume precious seconds each time they run (i.e., they take between 3 and 7 seconds to run, times 3 `Configuring proxy` calls per provisioning script that runs).

While I haven't benchmarked it, this change seems to have increased provisioning time considerably. Conservatively, this group of scripts runs 45 times while provisioning, and at 9 seconds per instance, that adds about 7 minutes to the process, which is significant.

## Steps to reproduce
1. Install the latest Homestead version.
2. Run `vagrant up` from a clean state.
