### ISSUE TITLE
Problem with xhgui

### ISSUE THREAD

**Issue by Ignaciooc5** [laravel/homestead#1290]
When run vagrant provision in cmd with admin permissions show me the following error:

`
homestead: Running: inline script
    homestead: ln: failed to create symbolic link '/home/vagrant/proyectos/prj1/public/xhgui': Protocol error
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
`

And dont working xhgui

This is me homstead.yaml

```
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: E:/Proyectos
      to: /home/vagrant/proyectos

sites:
    - map: prj1.test
      to: /home/vagrant/proyectos/prj1/public
      php: "7.3"
      type: "apache"
      xhgui: "true"

databases:
    - homestead

features:
    - mariadb: true
    - ohmyzsh: false
    - webdriver: false
```
