### ISSUE TITLE
MySQL 8 doesn't appear to be installed when setting the mysql8 option to true in the Homestead.yaml file

### ISSUE THREAD

**Issue by gkimpson** [laravel/homestead#1296]
I have set the `mysql8` option to true within the Homestead.yaml file but when open up the mysql terminal and check the versions I see 5.7 and not version 8 that I would expect - what am I doing wrong or is this a bug?

## Versions
  - Vagrant: 2.2.5
  - Provider: Virtualbox Version 6.0.12 r133076 (Qt5.6.3)
  - Homestead: laravel/homestead 8.2.1

## Host operating system
MacOS Mojave (but running Ubuntu within Vagrant box)

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
mysql8: true
authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: ~/vagrant/code

sites:
    - map: homestead.local
      to: ~/vagrant/code/public

databases:
    - homestead
```

## Vagrant destroy & up output
https://gist.github.com/gkimpson/510e0fc4e4877ef5fcf318e7331a0507 (vagrant up)

## Expected behavior
It should have installed mysql v8.x

## Actual behavior
It has installed mysql 5.7.x

## Steps to reproduce
1. Install the latest versions of Vagrant, Homestead & VirtualBox
2. Using the yaml above run the `vagrant up` command
3. Once loaded - do `vagrant ssh` and then `mysql` - once inside the mysql terminal run `SHOW VARIABLES LIKE "%version%";` to show you the version number (it states the following below)
4. Or do mysql -v or mysqld --version from inside the vagrant box

```
+-------------------------+-------------------------+
| Variable_name           | Value                   |
+-------------------------+-------------------------+
| innodb_version          | 5.7.27                  |
| protocol_version        | 10                      |
| slave_type_conversions  |                         |
| tls_version             | TLSv1,TLSv1.1           |
| version                 | 5.7.27-0ubuntu0.18.04.1 |
| version_comment         | (Ubuntu)                |
| version_compile_machine | x86_64                  |
| version_compile_os      | Linux                   |
+-------------------------+-------------------------+
```

**Comment by svpernova09** [comment]
Your configuration is outdated. Check https://laravel.com/docs/6.x/homestead#installing-optional-features

**Comment by gkimpson** [comment]
```
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: ~/vagrant/code

sites:
    - map: homestead.local
      to: ~/vagrant/code/public

databases:
    - homestead

features:
    - mongodb: true
    - mysql8: true
    - pm2: true
```
