### ISSUE TITLE
Flip command not found (trying to switch between apache and nginx)

### ISSUE THREAD

**Issue by gkimpson** [laravel/homestead#1306]
Flip command is seemingly no longer working for me within the Homestead box environment.

## Versions
  - Vagrant: 2.2.6
  - Provider: VirtualBox 6.0.12 r133076 (Qt5.6.3)
  - Homestead: Homestead v9.2.2 released

## Host operating system
MacOS Mojave 10.14.6

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Sites
      to: /home/vagrant/www

sites:
    - map: dev.myapp.com
      to: /home/vagrant/www/myapp/public
      type: "apache"

    - map: laravel.local
      to: /home/vagrant/www/laravel/public

    - map: lumen.local
      to: /home/vagrant/www/lumen/public

databases:
    - homestead
    - dev

features:
    - mysql8: true

variables:
    - key: MY_APP
      value: vagrantdev
```

## Expected behavior
flip - should change from apache to nginx server and vice-versa
## Actual behavior
When logged into the homestead ssh box and I run `flip` the following error is returned :
`bash: flip: command not found`

## Steps to reproduce
1. Use the Homestead.yaml file above
2. Run vagrant reload --provision to run the modified yaml file
3. SSH into the box and run the flip command

## References
