### ISSUE TITLE
vagrant up failing

### ISSUE THREAD

**Issue by striderwhite** [laravel/homestead#1315]
## Versions
  - Vagrant: Vagrant 2.2.6
  - Provider: Virtualbox
  - Homestead: release branch

## Host operating system
Win 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: "c:\\Users\\STRIDER\\.ssh\\id_rsa.pub"

keys:
  — "c:\\Users\\STRIDER\\.ssh\\id_rsa"

folders:
  - map: "c:\\Users\\STRIDER\\Desktop\\projects\\Laravel"
    to: /home/vagrant/code

sites:
  - map: homestead.test
    to: /home/vagrant/code/public

databases:
  - homestead

features:
  - mariadb: false
  - ohmyzsh: false
  - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
```
$ vagrant up
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: C:/Users/STRIDER/homestead/scripts/homestead.rb
Line number: 146
Message: undefined method `each'
```

## Expected behavior
Homestead should start

## Actual behavior
See the error, it fails.

I have been following several tutorials on getting homestead running [1](https://laravel.com/docs/6.x/homestead) [2](https://medium.com/@eaimanshoshi/i-am-going-to-write-down-step-by-step-procedure-to-setup-homestead-for-laravel-5-2-17491a423aa) and it is always failing when I try to `vagrant up`. I think the issue is within the Vagrantfile but I have no idea what to do.

**Comment by svpernova09** [comment]
Your YAML in `Homestead.yaml` is not correctly formatted because you're not quoting your paths (It's a Windows thing)

Give this a shot:
```
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: "c:\\Users\\STRIDER\\.ssh\\id_rsa.pub"

keys:
  — "c:\\Users\\STRIDER\\.ssh\\id_rsa"

folders:
  - map: "c:\\Users\\STRIDER\\Desktop\\projects\\Laravel"
    to: /home/vagrant/code

sites:
  - map: homestead.test
    to: /home/vagrant/code/public

databases:
  - homestead

features:
  - mariadb: false
  - ohmyzsh: false
  - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```
