### ISSUE TITLE
After homestead update: permission denied to storage/log

### ISSUE THREAD

**Issue by rabol** [laravel/homestead#1320]
## Versions
  - Vagrant: 2.2.6
  - Provider: Virtualbox - 6.06 r130049
  - Homestead: Latest.

## Host operating system
MacOS v10.15.1

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 4096
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

backup: true

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code/web/
      to: /home/vagrant/code

sites:
    - map: test.test
      to: /home/vagrant/code/test/public
      php: "7.3"

databases:
    - test
```

## Expected behavior
Site is working

## Actual behavior
UnexpectedValueException
The stream or file "/home/vagrant/code/test/storage/logs/laravel-2019-11-28.log" could not be opened: failed to open stream: Permission denied

## Steps to reproduce
1. homestead halt
2. cd ~/Homestead 
3. vagrant destroy
4. git fetch
5. git pull origin release
6. vagrant box update
7. vagrant up
8. open browser and go to test.test
