### ISSUE TITLE
Bug 10.0 - Redis not starting on boot

### ISSUE THREAD

**Issue by tomcoonen** [laravel/homestead#1328]
## Versions
  - Vagrant: 2.2.6
  - Provider: Virtualbox
  - Homestead: 10.0.1

## Host operating system
macOS 10.15.1

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 2
hostname: homestead-test
name: homestead-test
provider: virtualbox

features:
  - mariadb: true
  - python: true
  - ohmyzsh: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa


folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead
```

## Vagrant destroy & up output
No errors

## Expected behavior
redis-cli can't connect

## Actual behavior
redis-cli connecting to local Redis

## Steps to reproduce
1. vagrant up (after destroy)
2. vagrant ssh
3. redis-cli
