### ISSUE TITLE
Xdebug not enabled

### ISSUE THREAD

**Issue by juliuscaesarnl** [laravel/homestead#1329]
## Versions
  - Vagrant: 2.2.6
  - Provider: Virtualbox 6.0.14
  - Homestead: 10.0.1
  - Box: 9.0.1

## Host operating system
Windows 10 Pro (18363.476)

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 4
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: 'C:\projects\portal'
        to: /home/vagrant/code
sites:
    -
        map: portal.com
        to: /home/vagrant/code/public
databases:
    - pdw
name: portal
hostname: portal
```

## Vagrant destroy & up output
[Gist of output](https://gist.github.com/juliuscaesarnl/955424f2ec2241d8ce4fad927e97b591)

## Expected behavior
Xdebug is enabled and running by default.

## Actual behavior
Xdebug is not enabled and not running for any PHP version. It seems like Xdebug is not installed. In commit https://github.com/laravel/settler/commit/eb8bbf0dfb51cdf022f9f5b9678631caba7894c6 I noticed that php-xdebug has been removed. Could this be by accident?

## Steps to reproduce
1. Vagrant up
2. Vagrant ssh
3. php-fpm7.4 -v (no xdebug)
4. cd /etc/php/7.4/fpm/conf.d (20-xdebug.ini does not exist)
5. sudo phpenmod xdebug (creates config file)
6. vagrant reload (xdebug still not running)

## References
None
