### ISSUE TITLE
homestead keeps asking for updating vagrant box

### ISSUE THREAD

**Issue by yabasha** [laravel/homestead#1334]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.6
  - Provider: Virtualbox 6.0.14 r133895
  - Homestead: branch v10.0.1

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: code/
      to: /home/vagrant/code

backup: true

variables:
    - key: APP_ENV
      value: local

sites:
    - map: admin.immi.test
      to: /home/vagrant/code/backpack-demo/public
      php: "7.2"

databases:
    - backpack_demo_db
```

## Expected behavior
Run without any issue

## Actual behavior
Each time I switch on my VM homestead asks for updating the vagrant box from `9.0.1` to `9.1.0`, and I run `vagrant box update` but the next time I switch it back on it asks me for updating the box

The following message appears:
```
λ vagrant up
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Checking if box 'laravel/homestead' version '9.0.1' is up to date...
==> homestead: A newer version of the box 'laravel/homestead' for provider 'virtualbox' is
==> homestead: available! You currently have version '9.0.1'. The latest is version
==> homestead: '9.1.0'. Run `vagrant box update` to update.
.
.
```

## Steps to reproduce
1. clone the repo switch to branch v10.0.1
2. run vagrant up
