### ISSUE TITLE
Composer self-update fails when host is behind proxy

### ISSUE THREAD

**Issue by lukewatts** [laravel/homestead#1336]
When I run vagrant up from homestead behind a corporate proxy on windows the composer self-update step in homewstead.rb fails every time because there is no proxy configuration done in the guest VM at that point. Removing composer self-update fixed it for me without any issues, so perhaps this should not happen until after vagrant-proxyconf plugin has run (which happens after this). Just an idea

## Versions
  - Vagrant: 2.2.6
  - Provider: VirtualBox (6.0.14-133895)
  - Homestead: v10.0.1

## Host operating system
Windows 8.1 Enterprise

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/projects/laravel/homestead/0.0.1/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
[https://gist.github.com/lukewatts/2c82f08a88f5d40f5f00c5f719416e5b#file-laravel-homestead_error-report-txt](https://gist.github.com/lukewatts/2c82f08a88f5d40f5f00c5f719416e5b#file-laravel-homestead_error-report-txt)

## Expected behavior
Finished running homestead.rb then use proxyconf plugin to set proxy and only then run composer self-update with new proxy settings

## Actual behavior
See above

## Steps to reproduce
1. Behind corporate proxy on windows 8.1/10 (proxy working correctly on host)
2. Follow homestead docs
3. See errors above on vagrant up or vagrant reload --provision

## References
Nope
