### ISSUE TITLE
Vagrant Box version 9.1 Hyper V processors at 4

### ISSUE THREAD

**Issue by coopers98** [laravel/homestead#1337]
The issue is that the Vagrant Box hypervv box config file, there is an entry for <processors>4</processors>  

See: C:\Users\Username\.vagrant.d\boxes\laravel-VAGRANTSLASH-homestead\9.1.0\hyperv\box.xml

## Versions
  - Vagrant: 2.2.6
  - Provider: Hyper-V
  - Homestead: 9.1

## Host operating system
Windows 10 Pro
2 CPUs

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 8192
cpus: 2
hostname: hostname
name: hostname
provider: hyperv

authorize: ~/.ssh/id_rsa.pub
keys:
  - ~/.ssh/id_rsa

features:
  - mariadb: false
  - postgres: false
  - ohmyzsh: false
  - webdriver: false

folders:
  - map: "C:\\Project"
    to: /home/vagrant/code

sites:
  - map: test.localhost
    to: /home/vagrant/code/public
    type: "laravel"
    schedule: true
    php: "7.3"

databases:
  - app_db

```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
Vagrant box should provision and come up

## Actual behavior
Vagrant box fails to provision and come up with message about processor count

## Steps to reproduce
1. Have a Windows Host with fewer than 4 CPUs
2. vagrant box add laravel/homestead
3. vagrant up
