### ISSUE TITLE
Can not connect to postgres over port 54320 on local machine

### ISSUE THREAD

**Issue by lukeholder** [laravel/homestead#1338]
## Versions
  - Vagrant 2.2.6
  - Provider: VMWare
  - Homestead: Most recent release

## Host operating system
MacOS Catalina

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: vmware_fusion
backup: true
authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code/Sites/craft-commerce2.test
      to: /home/vagrant/Code/Sites/craft-commerce2.test
      type: "nfs"
    - map: ~/Code/Sites/craft-commerce3.test
      to: /home/vagrant/Code/Sites/craft-commerce3.test
      type: "nfs"
    - map: ~/Code/Repositories
      to: /home/vagrant/Code/Repositories
      type: "nfs"
    - map: ~/Code/Work/tenina3
      to: /home/vagrant/Code/Work/tenina3
      type: "nfs"
    - map: ~/Code/Sites/myshop
      to: /home/vagrant/Code/Sites/myshop
      type: "nfs"
    - map: ~/Code/Projects/storyloupe
      to: /home/vagrant/Code/Projects/storyloupe
      type: "nfs"

sites:
    - map: craft-commerce2.test
      to: /home/vagrant/Code/Sites/craft-commerce2.test/web
      php: "7.1"
    - map: craft-commerce3.test
      to: /home/vagrant/Code/Sites/craft-commerce3.test/web
      php: "7.1"
    - map: tenina.test
      to: /home/vagrant/Code/Work/tenina3/web
      php: "7.1"
    - map: myshop.test
      to: /home/vagrant/Code/Sites/myshop/public
      php: "7.1"
    - map: storyloupe.test
      to: /home/vagrant/Code/Projects/storyloupe/web
      php: "7.1"

databases:
    - craft-commerce2
    - craft-commerce3
    - tenina
    - myshop
    - storyloupe

features:
    - mariadb: false
    - ohmyzsh: true
    - webdriver: false
```

## Vagrant destroy & up output
no errors/ everything works as expected including port forwarding setup.'

## Expected behavior
Should be able to connect to postgres from local machine over port 54320

## Actual behavior
Getting this error when connecting:

https://github.com/laravel/framework/issues/11339

```
FATAL:  no pg_hba.conf entry for host "192.168.23.2", user "homestead", database "postgres", SSL on
FATAL:  no pg_hba.conf entry for host "192.168.23.2", user "homestead", database "postgres", SSL off

```

Solution is to do update the `pg_hba.conf` file:

https://github.com/laravel/framework/issues/11339#issuecomment-284167217

Once that change has been made, and postgres service restarted, the issue is resolved and connection to postgres works over port 54320 just fine.
