### ISSUE TITLE
Provision/vagrant up stuck at the set up of mysql-apt-config (mysql 8)

### ISSUE THREAD

**Issue by MichaelBelgium** [laravel/homestead#1339]
## Versions
  - Vagrant: 2.2.6
  - Provider: Virtualbox 6.0.14
  - Homestead: checked out at version 10.0.1

## Host operating system
Windows 10 1903

## Homestead.yaml
```yaml
---
ip: "192.168.99.100"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:\athenasoft_dev\athenasoft
      to: /home/vagrant/athenasoft.kisp.devel

sites:
    - map: www.kisp.devel
      to: /home/vagrant/athenasoft.kisp.devel/web
      php: "7.2"
      type: "apache"

    - map: www.miras.devel
      to: /home/vagrant/athenasoft.kisp.devel/web
      php: "7.2"
      type: "apache"

    - map: www.creo.devel
      to: /home/vagrant/athenasoft.kisp.devel/web
      php: "7.2"
      type: "apache"

    - map: athenasoft.kisp.devel
      to: /home/vagrant/athenasoft.kisp.devel/web
      php: "7.2"
      type: "apache"

    - map: athenasoft.miras.devel
      to: /home/vagrant/athenasoft.kisp.devel/web
      php: "7.2"
      type: "apache"

    - map: athenasoft.creo.devel
      to: /home/vagrant/athenasoft.kisp.devel/web
      php: "7.2"
      type: "apache"

databases:
    - athena_kisp
    - athena_miras
    - athena_creo

features:
    - blackfire: false
    - cassandra: false
    - chronograf: false
    - couchdb: false
    - crystal: false
    - docker: false
    - elasticsearch: false
    - gearman: false
    - golang: false
    - grafana: false
    - influxdb: false
    - mariadb: false
    - minio: false
    - mongodb: false
    - mysql8: true
    - neo4j: false
    - ohmyzsh: false
    - openresty: false
    - pm2: false
    - python: false
    - rabbitmq: false
    - solr: false
    - webdriver: false

backup: true

variables:
    - key: PHP_IDE_CONFIG
      value: "serverName=athena.kisp.devel"
    - key: XDEBUG_CONFIG
      value: "idekey=PHPSTORM"

```

## Vagrant up output
Can't really copy and paste in a gist as the output overlaps previous output:
![image](https://user-images.githubusercontent.com/8951045/70697408-bf30c180-1cc5-11ea-91ff-dde4225a3342.png)

It's expecting a selection in bash but when doing vagrant up, there's no way to select.

## Expected behavior
When setting up mysql-apt-get, that it selects mysql8 by default without asking for a choice

## Actual behavior
When doing vagrant up, its installing the VM perfectly untill the point it wants to set up mysql-apt-config, its showing a modal/choice where the user has to select which mysqlversion it should set up the package for but there's no way to select it.

To solve it i have to run `vagrant ssh` and execute `sudo dpkg --configure -a` to continue the process and to select "ok"

## Steps to reproduce
1. Install homestead latest version + vagrant box latest version
2. use mysql8 (i assume this doesnt happen with mysql 5.7?)
3. run `vagrant up`
