### ISSUE TITLE
Homestead wont work if WSL2 is enabled

### ISSUE THREAD

**Issue by pacharrin** [laravel/homestead#1347]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.6
  - Provider: Virtualbox
  - Homestead: 9.1.0

## Host operating system
Windows 10 Home
version 2004
build 19041.1

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
mariadb: true

authorize: C:/Users/alexi/.ssh/id_rsa.pub

keys:
    - C:/Users/alexi/.ssh/id_rsa

folders:
    - map: C:\Users\alexi\Documents\GitHub
      to: /home/vagrant/Code

sites:
    - map: admin.aurochat.test
      to: /home/vagrant/Code/aurochat-frontend/public
    - map: local.aurochat.test
      to: /home/vagrant/Code/aurochat-frontend/public
    - map: aurochat.test
      to: /home/vagrant/Code/aurochat-frontend/public

databases:
    - homestead
    - aurochat
```

## Vagrant destroy & up output
not required
## Expected behavior
After installing WSL2 hyper v was disabled which made vagrant up to stop working (WAI).

This is not  really a problem but i think in the next major windows (april 2020) release most people will start using WSL2 and wanted to give you a heads up.

I don't know if supporting wsl2 is in the roadmap but if there is anything i can help with im up to help in whatever is needed. (i don't have a lot of expertise in this, but with the proper guidance i think i could make it work)
