### ISSUE TITLE
version

### ISSUE THREAD

**Issue by Lewiscowles1986** [laravel/homestead#1352]
osx trys to download alpha until I specify a version. I had to work that out by reading the ruby file. Perhaps having it available and commented out would help?

## Versions
  - Vagrant: 2.2.6
  - Provider: 6.0.4
  - Homestead: 10.1.0

## Host operating system
<img width="698" alt="Screenshot 2020-01-15 at 23 58 37" src="https://user-images.githubusercontent.com/2605791/72481685-3b518400-37f3-11ea-89cf-df818079c112.png">

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/2018-12-kalo_rsa.pub

keys:
    - ~/.ssh/2018-12-kalo_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: true
    - webdriver: true

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output

```
lewiscowles@Lewiss-MacBook-Pro homestead % vagrant up
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Box 'laravel/homestead' could not be found. Attempting to find and install...
    homestead: Box Provider: virtualbox
    homestead: Box Version: >= 9.0.0
==> homestead: Loading metadata for box 'laravel/homestead'
    homestead: URL: https://vagrantcloud.com/laravel/homestead
==> homestead: Adding box 'laravel/homestead' (v9.2.2.pre.alpha1) for provider: virtualbox
```

goes on to complain that sha512 is invalid and only sha256 is supported 🤷‍♂ 

## Expected behavior

I thought select 9.1.1 as it reports it's available, but strangely the only version I could specify and have work was 9.1.0

## Actual behavior

Refused to run, complaining about sha512 🤷‍♂ 

## Steps to reproduce
1. `git clone this repo`
2. `git checkout v10.1.0`
3. `bash init.sh`
4. `vagrant up`

## References

No open issues at time of opening. I also worked around by specifying `version: 9.1.0`, but a heads up this may be blocking some first-time users
