### ISSUE TITLE
Boot issue on Homestead VM

### ISSUE THREAD

**Issue by luisdiaswiz** [laravel/homestead#1363]
## Versions
  - Vagrant: 2.2.7
  - Provider: Virtualbox 6.0.16 r135674 (Qt5.6.3)
  - Homestead: release.

## Host operating system
MacOs High Sierra
10.13.6

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox

authorize: ~/.ssh/homestead.pub

keys:
    - ~/.ssh/homestead

folders:
    - map: ~/Documents/Repos
      to: /home/vagrant/code

sites:
    - map: roady.local
      to: /home/vagrant/code/roady/www/roady
      php: "5.6"
    - map: pepo.local
      to: /home/vagrant/code/pepo/www/pepo
      php: "5.6"
    - map: bricomarche.local
      to: /home/vagrant/code/bricomarche/www/bricomarche
      php: "5.6"
    - map: museu-do-dinheiro.local
      to: /home/vagrant/code/museu-do-dinheiro/www/museu-do-dinheiro
      php: "5.6"
    - map: edp-live-bands.local
      to: /home/vagrant/code/edp-live-bands/www/edp-live-bands
      type: apache
      php: "7.0"
    - map: boutique-dos-relogios.local
      to: /home/vagrant/code/boutique-dos-relogios/www/boutique-dos-relogios
      php: "7.1"
    - map: museu-do-fado.local
      to: /home/vagrant/code/museu-do-fado/public
      type: apache
    - map: frulact-presentations.local
      to: /home/vagrant/code/frulact-presentations/www/frulact-presentations
      php: "7.1"
    - map: frulact.local
      to: /home/vagrant/code/frulact
    - map: quinta-da-fonte.local
      to: /home/vagrant/code/quinta-da-fonte-wp
    - map: oasrs.local
      to: /home/vagrant/code/oasrs/www/oasrs
      php: "7.1"
    - map: imm.local
      to: /home/vagrant/code/imm
    - map: comte.local
      to: /home/vagrant/code/comte
    - map: sirp.local
      to: /home/vagrant/code/sirp/www/sirp
      php: "7.0"
    - map: sied.local
      to: /home/vagrant/code/sirp/www/sirp
      php: "7.0"
    - map: sis.local
      to: /home/vagrant/code/sirp/www/sirp
      php: "7.0"
    - map: turbotec.local
      to: /home/vagrant/code/turbotec
    - map: etic.local
      to: /home/vagrant/code/etic
    - map: tabernas.local
      to: /home/vagrant/code/tabernas
    - map: arquivo-sonoro.local
      to: /home/vagrant/code/arquivo-sonoro/public
      type: apache
    - map: roteiro-fado.local
      to: /home/vagrant/code/roteiro-do-fado/public
      type: apache
    - map: wiz.local
      to: /home/vagrant/code/wiz_2018_website/public
      type: apache
databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

backup: true


# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
https://gist.github.com/luisdiaswiz/3ad71e6b105600dd171d3b2694bcafa3

## Expected behavior
Vagrant up, halt, reload operations should work
## Actual behavior
I am using a Homestead vagrant VM and the strangest thing is happening. After working fine for a few months the VM just stopped working. I tried reinstalling everything and setting up again and what happened was that after installing everything and running the VM for the first time with vagrant up everything works fine. It takes some time to provision the VM but it runs for the first time.

The subsequent times after halting the VM for the first time, the VM stops booting, entering emergency mode.
I am attaching a recording of the VM's boot sequence with the errors.
[homestead.webm.zip]
(https://github.com/laravel/homestead/files/4166131/homestead.webm.zip)

I have tried removing the box twice and reinstalling VirtualBox and Vagrant but the same keeps happening.

Can anyone provide some help?

Thanks in advance.

Luis Dias

## Steps to reproduce
1. vagrant up or vagrant reload.
