### ISSUE TITLE
Laravel 6.2 on Homestead showing ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by rileyff** [laravel/homestead#1364]
I am trying to set up a Laravel 6.2 project on Homestead. I have 3 Laravel 5.8 projects with identical configurations that are all working properly, but the new project just shows `ERR_CONNECTION_REFUSED` when I try to view the site in a browser.

## Versions
  - Vagrant: 2.2.7
  - Provider: Virtualbox 6.0.14
  - Homestead: 9.0.2

## Host operating system
MacOS Mojave 10.14.6

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Documents/fireflower/ceri
      to: /home/vagrant/code/ceri
    - map: ~/Documents/fireflower/feed-sam
      to: /home/vagrant/code/feed-sam
    - map: ~/Documents/fireflower/alberta-beef
      to: /home/vagrant/code/alberta-beef
    - map: ~/Documents/fireflower/reembody
      to: /home/vagrant/code/reembody


sites:
    - map: ceri.test
      to: /home/vagrant/code/ceri/public
      php: "7.3"
    - map: feed-sam.test
      to: /home/vagrant/code/feed-sam/public
      php: "7.3"
    - map: alberta-beef.test
      to: /home/vagrant/code/alberta-beef/public
      php: "7.3"
    - map: reembody.test
      to: /home/vagrant/code/reembody/public
      php: "7.3"

databases:
    - homestead
    - ceri
    - feed-sam
    - feed-sam-testing
    - alberta-beef
    - reembody

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
https://gist.github.com/rileyff/e4c4105bc7685d81d1125f1b44ee15b7

## Expected behavior
What should have happened? Please include as much detail as possible.

I should be able to view the site at the test domain I have set.

## Actual behavior
What actually happened? Please include as much detail as possible.

I see "This site can’t be reached" ERR_CONNECTION_REFUSED in Google Chrome.

## Steps to reproduce
1. Install Laravel 6.2
2. Add site to Homestead.yaml as shown above
3. Try to view in a browser
