### ISSUE TITLE
Unable to install elasticsearch

### ISSUE THREAD

**Issue by matsava** [laravel/homestead#1369]
## Versions
  - Vagrant: Vagrant 2.2.7
  - Provider: Virtualbox
  - Homestead: https://github.com/laravel/homestead/commit/9aa511fda4dc4e67bd771f21cf0cd56f7b90a279

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.56.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: D:\Code\
      to: /home/vagrant/code

sites:
    - map: xxx.test
      to: /home/vagrant/code/xxx/public

databases:
    - xxx

features:
    - elasticsearch: true
    - ohmyzsh: false
    - webdriver: false

ports:
    - send: 9200
      to: 9200
```

## Vagrant destroy & up output
https://gist.github.com/matsava/bec90573e45693beb90f825b78e2fd46

## Expected behavior
Should have included ES and return no error

## Actual behavior
```
Failed to fetch https://artifacts.elastic.co/packages/7.x/apt/pool/main/e/elasticsearch/elasticsearch-7.6.0-amd64.deb  Hash Sum mismatch
```

## Steps to reproduce
1. git clone
2. git checkout release
3. edited the Homestead.yaml file
4. vagrant up

## References
- https://github.com/laravel/homestead/issues/637
