### ISSUE TITLE
XHGUI not working for PHP7.4

### ISSUE THREAD

**Issue by nal-chris** [laravel/homestead#1370]
## Versions
  - Vagrant: 2.2.6
  - Provider: 6.0.16
  - Homestead: 10.3.1

## Host operating system
macOS Catalina v10.15.2

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 3
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code/Websites
      to: /home/vagrant/code
      type: "nfs"

sites:
    - map: project.x
      to: /home/vagrant/code/projectx/public
      schedule: true
      xhgui: "true"

databases:
    - projectx

features:
    - minio: true

buckets:
    - name: public
      policy: public
    - name: documents
      policy: none
```

## Vagrant destroy & up output
https://gist.github.com/nal-chris/15b56a8c8362e21d8d14fe5591acb64b

## Expected behavior
The xhgui dashboard should appear when visiting http://project.x/xhgui

## Actual behavior
A slim error appears.
<img width="863" alt="Slim application error" src="https://user-images.githubusercontent.com/16105234/75024021-afd1af80-5490-11ea-9f97-c0bc82db99df.png">

## Steps to reproduce
1. Install homestead with xhgui set, using php7.4
2. Visit the xhgui dashboard for the site
3. See the error page

I have tried setting the php version in nginx to 7.3:
```
location /xhgui {
        try_files $uri $uri/ /xhgui/index.php?$args;
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
}
```

That just yields a blank page.
