### ISSUE TITLE
Elasticsearch version needs to be specified.

### ISSUE THREAD

**Issue by nal-chris** [laravel/homestead#1371]
## Versions
  - Vagrant: 2.2.6
  - Provider: 6.0.16
  - Homestead: 10.3.1

## Host operating system
macOS Catalina version 10.15.2

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 3
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code/Websites
      to: /home/vagrant/code
      type: "nfs"

sites:
    - map: project.x
      to: /home/vagrant/code/projectx/public

databases:
    - projectx

features:
    - elasticsearch:
        version: 7
```

## Vagrant destroy & up output
https://gist.github.com/nal-chris/515110ac562c223f04be50e3fe7c5f5d

## Expected behavior
Homestead should have installed without a problem.

## Actual behavior
Elasticsearch failed to install:
```
homestead: Version '7' for 'elasticsearch' was not found
```

## Steps to reproduce
1. Configure homestead with elasticsearch feature enabled for version 7.
2. Run vagrant up and check the output.
3. Elasticsearch is not installed.

Elasticsearch does install correctly when using a specific version or using wildcards.
```yaml
- elasticsearch:
    version: 7.6.0
```
and
```yaml
- elasticsearch:
    version: 7.*
```
both work.

However in the [homestead documentation](https://laravel.com/docs/6.x/homestead#installing-optional-features) it is stated that you can set up Elasticsearch with just the major version number.
This has changed since Homestead version 10.3.0, before that using the plain major version worked fine.

I'm not sure if this is intended behaviour for Homestead, but if it is, it would be helpful if the Homestead installation guide be updated to reflect this change.
