### ISSUE TITLE
homestead: tee: /home/vagrant/.ssh/authorized_keys: No such file or directory

### ISSUE THREAD

**Issue by erdemkeren** [laravel/homestead#1378]
## Versions
  - Vagrant: 2.2.7
  - Provider: Virtual Box 6.1.2
  - Homestead: release

## Host operating system
macOS Catalina 10.15.3

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa_homestead.pub

keys:
    - ~/.ssh/id_rsa_homestead

folders:
    - map: ~/dev
      to: /home/vagrant

sites:
    - map: homestead.test
      to: /home/vagrant/code/homestead/public

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
https://gist.github.com/erdemkeren/c2a1337836698bdff4a08a394b9741b9

## Expected behavior
Install homestead

## Actual behavior
```
homestead: tee: /home/vagrant/.ssh/authorized_keys: No such file or directory
```

Exit status is non-zero, if I `vagrant ssh`, it asks for pwd.

## Steps to reproduce
1. Checkout/pull from release (tried both)
2. run vagrant up

**Comment by svpernova09** [comment]
https://laravel.com/docs/6.x/homestead#configuring-homestead

> You should always map individual projects to their own folder mapping instead of mapping your entire ~/code folder. When you map a folder the virtual machine must keep track of all disk IO for every file in the folder. This leads to performance issues if you have a large number of files in a folder.

```
folders:
    - map: ~/dev
      to: /home/vagrant

sites:
    - map: homestead.test
      to: /home/vagrant/code/homestead/public
```

Don't map a folder to the vagrant user's home folder. this breaks *a lot of things*

Change it to

```
folders:
    - map: ~/dev/code/homestead
      to: /home/vagrant/project1

sites:
    - map: homestead.test
      to: /home/vagrant/project1/public
```
