### ISSUE TITLE
$_SERVER variables are not cleared for all PHP versions.

### ISSUE THREAD

**Issue by ProjectCleverWeb** [laravel/homestead#1380]
## Versions
  - Vagrant: 2.2.7
  - Provider: VirtualBox 6.1
  - Homestead: 10.3.1

## Host operating system
Mac 10.15.2 (Catalina)

## Homestead.yaml
```yaml
---
###########################################################################
# HOMESTEAD CONFIGURATION FILE                                            #
# ----------------------------                                            #
# Each time you edit this file you will need to run "yarn vm:update" to   #
# apply the changes.                                                      #
###########################################################################

aliases:
  # Theses settings are going to be specific to you and your machine
  - &devUsername "[REDACTED]" # This must be usable in a domain name (avoid periods)
  - &localFrontendPath "/absolute/path/to/frontend/on/your/machine"
  - &localApiPath "/absolute/path/to/api/on/your/machine"
  - &dbUserName "[REDACTED]"
  - &dbBase64Password "[REDACTED]" # [IMPORTANT] MAKE SURE THIS PASSWORD IS BASE64 ENCODED!
  - &dbHost "[REDACTED]" # Change this to "_gateway" if you want to use your local DB
  - &apiUrl "[REDACTED]" # Change to "[REDACTED]" to not require an internet connection. NEVER SET THIS TO PRODUCTION!
  - &sshKeyFile "~/.ssh/id_rsa.pub" # Any *.pub file should work
  - &sshKeyId "~/.ssh/id_rsa" # this should be the same as *sshKeyFile except without the ".pub"
  # The below settings will generally work for everyone. You probably will never
  # NEED to change these, but they are here if you want to.
  - &cpus "1"
  - &ram "512" # Below 512 starts to take MUCH LONGER to deploy VMs
  - &ip "10.100.100.10"
  - &phpVersion "7.0"
  - &vmProjectsPath "/home/vagrant/projects"
  - &frontendDomain "frontend.test"
  - &apiDomain "api.test"
  - &vmFrontendPath "/home/vagrant/projects/frontend" # Must be a subdirectory of *vmProjectsPath
  - &vmApiPath "/home/vagrant/projects/api" # Must be a subdirectory of *vmProjectsPath


###########################################################################
# NOTICE:                                                                 #
# The configuration below this line will probably never change. Please    #
# consult the documentation for Laravel Homestead prior to changing it.   #
###########################################################################

# These just make it easier for programs reading this file
environment:
  devUsername: *devUsername 
  localFrontendPath: *localFrontendPath
  localApiPath: *localApiPath
  dbUserName: *dbUserName 
  dbBase64Password: *dbBase64Password 
  dbHost: *dbHost
  apiUrl: *apiUrl
  sshKeyFile: *sshKeyFile
  sshKeyId: *sshKeyId
  cpus: *cpus 
  ram: *ram
  ip: *ip 
  phpVersion: *phpVersion 
  vmProjectsPath: *vmProjectsPath
  frontendDomain: *frontendDomain 
  apiDomain: *apiDomain 
  vmFrontendPath: *vmFrontendPath
  vmApiPath: *vmApiPath

# Configure VM Specs
ip: *ip
memory: *ram
cpus: *cpus
provider: virtualbox
ssl: true

# This will be automatically transferred to the VM
authorize: *sshKeyFile

# Local SSH keys
keys:
  - *sshKeyId

# Mount local directories in the VM
folders:
  - map: *localFrontendPath # Local Directory
    to: *vmFrontendPath # VM Directory
  - map: *localApiPath # Local Directory
    to: *vmApiPath # VM Directory

# Sites hosted on the VM (Mapped locally)
sites:
  - map: *frontendDomain # Local-only domain
    to: *vmProjectsPath # VM Directory (Frontend needs to be hosted in any subdirectory)
    php: *phpVersion # PHP Version
    type: "custom-frontend" # Custom Nginx Config
  - map: *apiDomain # Local-only domain
    to: *vmApiPath # VM Directory
    php: *phpVersion # PHP Version
    type: "custom-api" # Custom Nginx Config

variables:
  - key: FRONTEND_PATH
    value: *vmFrontendPath
  - key: BACKEND_PATH
    value: *vmApiPath
  - key: DB_HOST
    value: *dbHost
  - key: DB_USERNAME
    value: *dbUserName
  - key: DB_BASE64_PASSWORD
    value: *dbBase64Password
  - key: DEV_USERNAME
    value: *devUsername
  - key: API_URL
    value: *apiUrl

```

## Vagrant destroy & up output
N/A (Wouldn't Help) 

## Expected behavior
When ever `vagrant reload --provision` is called, it should be resetting the PHP INI file for all PHP versions.

## Actual behavior
When ever `vagrant reload --provision` is called, it only resets the PHP INI files for PHP versions 7.1 &amp; 7.2 but not 5.6, 7.0, 7.3, or 7.4

See: [`/scripts/clear-variables.sh`](https://github.com/CHHJIT/homestead/blob/9aa511fda4dc4e67bd771f21cf0cd56f7b90a279/scripts/clear-variables.sh) (Linked to code at version 10.3.1)

## Steps to reproduce
1. Add/Remove/Edit variables to your `Homestead.yaml`
2. `vagrant reload --provision`
3. Check the bottom of `/etc/php/7.0/fpm/pool.d/www.conf` on the VM

## References
None

## Suggested Change
Update `/scripts/clear-variables.sh` to be this:

```bash
#!/usr/bin/env bash

# Clear The Old Environment Variables

sed -i '/# Set Homestead Environment Variable/,+1d' /home/vagrant/.profile
sed -i '/env\[.*/,+1d' /etc/php/5.6/fpm/pool.d/www.conf
sed -i '/env\[.*/,+1d' /etc/php/7.0/fpm/pool.d/www.conf
sed -i '/env\[.*/,+1d' /etc/php/7.1/fpm/pool.d/www.conf
sed -i '/env\[.*/,+1d' /etc/php/7.2/fpm/pool.d/www.conf
sed -i '/env\[.*/,+1d' /etc/php/7.3/fpm/pool.d/www.conf
sed -i '/env\[.*/,+1d' /etc/php/7.4/fpm/pool.d/www.conf
```
