### ISSUE TITLE
MariaDB corrupt on vagrant windows

### ISSUE THREAD

**Issue by RSpeekenbrink** [laravel/homestead#1382]
## Versions
  - Vagrant: 2.2.7
  - Provider: Virtualbox 6.0.14, homestead box: v9.3.0
  - Homestead: 10.4

## Host operating system
Windows 10

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: 'D:\Projects\vagrant'
        to: /home/vagrant/code
sites:
    -
        map: homestead.test
        to: /home/vagrant/code/public
databases:
    - homestead
features:
    -
        mariadb: true
    -
        ohmyzsh: false
    -
        webdriver: false
name: vagrant
hostname: vagrant
```

## Vagrant destroy & up output
https://pastebin.com/ZLDE0w0K

## Expected behavior
Boot without corrupted database that disrupts the booting process.

## Actual behavior
MariaDB corrupt error

## Steps to reproduce
1. Have windows computer
2. Make a fresh homestead box with `mariadb: true`
3. vagrant up
