### ISSUE TITLE
composer self-update fails which causes provisioning to fail

### ISSUE THREAD

**Issue by selected-pixel-jameson** [laravel/homestead#1384]
```
....
....
...
    homestead: Running: script: Creating MySQL Database: healthmeans-laravel
==> homestead: Running provisioner: Creating Postgres Database: healthmeans-laravel (shell)...
    homestead: Running: script: Creating Postgres Database: healthmeans-laravel
==> homestead: Running provisioner: Creating MySQL Database: key-collector-full (shell)...
    homestead: Running: script: Creating MySQL Database: key-collector-full
==> homestead: Running provisioner: Creating Postgres Database: key-collector-full (shell)...
    homestead: Running: script: Creating Postgres Database: key-collector-full
==> homestead: Running provisioner: Creating MySQL Database: experience_builder (shell)...
    homestead: Running: script: Creating MySQL Database: experience_builder
==> homestead: Running provisioner: Creating Postgres Database: experience_builder (shell)...
    homestead: Running: script: Creating Postgres Database: experience_builder
==> homestead: Running provisioner: Update Composer (shell)...
    homestead: Running: script: Update Composer
    homestead:                                                                                                                     
    homestead:   [Composer\Downloader\TransportException]                                                                          
    homestead:   The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Connection timed out  
    homestead:                                                                                                                     
    homestead: 
    homestead: self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--set-channel-only] [--] [<version>]
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
```

```
vagrant ssh


* Homestead v10.3.0 released
* Settler v9.2.0 released

0 packages can be updated.
0 updates are security updates.

vagrant@homestead:~$ composer self-update
                                                                                                                    
  [Composer\Downloader\TransportException]                                                                          
  The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: Connection timed out  
```
                                                                                                                    
```
---
networks:
    - type: "public_network"
      bridge: "en0: Wi-Fi (Wireless)"
memory: 2048
cpus: 4
provider: virtualbox

authorize: ~/.ssh/github_rsa.pub

keys:
    - ~/.ssh/github_rsa

folders:
    - map: ~/Documents/healthmeans/healthmeans-laravel
      to: /home/vagrant/code/healthmeans-laravel
      type: "nfs"
    - map: ~/Documents/experience-builder/
      to: /home/vagrant/code/experience-builder
      type: "nfs"

sites:
    - map: homestead.expbuilder
      to: /home/vagrant/code/experience-builder/public
    - map: homestead.healthmeans
      to: /home/vagrant/code/healthmeans-laravel/public

databases:
    - homestead
    - healthmeans-laravel
    - key-collector-full
    - experience_builder

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.
```
