### ISSUE TITLE
sed: can't read /etc/php/7.4/fpm/pool.d/www.conf: No such file or directory

### ISSUE THREAD

**Issue by brooksvb** [laravel/homestead#1387]
## Versions
  - Vagrant: 2.2.7
  - Provider: Virtualbox 6.1.4
  - Homestead: 8.0 (Composer package 10.6)

## Host operating system
Windows 10

## Homestead.yaml
```yaml
ip: 192.168.10.20
name: metools.test
hostname: metools.test
version: 8.0.0
memory: 2048
cpus: 1
provider: virtualbox
folders:
    -
        map: ./
        to: /home/vagrant/code
sites:
    -
        map: metools.test
        to: /home/vagrant/code/public
        type: "symfony4"
        php: "7.2"
databases:
    - metools
backup: true
```

## Vagrant destroy & up output
Vagrant up output: https://gist.github.com/brooksvb/f14196cf791f019cba1da8888d93be1f
There is no Vagrant destroy output because it errors on trying to make a database backup on the destroy trigger, because the database did not get created during provision. To test different changes I completely deleted the `.vagrant` directory, removed the VM from Virtualbox, and ran `vagrant box remove laravel/homestead`.

## Expected behavior
The virtual machine should provision and run correctly.

## Actual behavior
The provisioning of the virtual machine errors because php7.4 is not installed: `sed: can't read /etc/php/7.4/fpm/pool.d/www.conf: No such file or directory`

## Steps to reproduce
1. Run `vagrant up`
