### ISSUE TITLE
Automatic domain resolution not working for Windows 10

### ISSUE THREAD

**Issue by PatrickRose** [laravel/homestead#1388]
## Versions
  - Vagrant: vagrant 2.2.7
  - Provider: Virtualbox 6.0.18
  - Homestead: Project specific install (10.6.0)

## Host operating system
Windows 10

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: 'C:\Users\44790\code\quantitative-easing'
        to: /home/vagrant/code
sites:
    -
        map: homestead.test
        to: /home/vagrant/code/public
databases:
    - homestead
features:
    -
        mariadb: false
    -
        ohmyzsh: false
    -
        webdriver: false
name: quantitative-easing
hostname: quantitative-easing
```

## Vagrant destroy & up output
[Gist](https://gist.github.com/PatrickRose/904602ab0f8f2ad43cfbdd7ed81588d5)

## Expected behavior
I can go to `quantitative-easing.local` in my browser and my site is loaded.

## Actual behavior
Chrome tells me `quantitative-easing.local’s server IP address could not be found.`

## Steps to reproduce
1. Create a new laravel project `composer create-project --prefer-dist laravel/laravel quantitative-easing`
2. Add homestead `composer require --dev laravel/homestead`
3. Make the file `vendor/bin/homestead make`
4. Run `vagrant up`

My guess is that `mDNS` isn't working correctly, but I can't seem to find where the broadcast is done in homestead's code so that I can try and do a bit more debug from this end.

I _did_ have this working previously with a different test project but it's now stopped working again (and isn't working now)
