### ISSUE TITLE
Configuring and enabling network interfaces... `await_response_state': Agent pid 3330 (RuntimeError)

### ISSUE THREAD

**Issue by ryancwalsh** [laravel/homestead#1394]
Thanks in advance for any thoughts about why I've been running into these problems.

I've spent hours and hours and hours trying to narrow down why I'd been running into [this 'await_response_state' error](https://github.com/hashicorp/vagrant/issues/11456) so frequently (and then always would need to run `vagrant destroy`, and the backups would work, so this was a serious problem).

## Versions
  - Vagrant 2.2.7
  - Provider: Virtualbox 6.1.4
  - Homestead: 10.7.0 (but I was mostly on v10.5.1 until today)

## Host operating system
Windows 10

## Homestead.yaml
```
#https://laravel.com/docs/7.x/homestead
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
hostname: vboxHomestead
name: vboxHomestead
#backup: true
#gui: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

features:
    - webdriver: true

folders:
    - map: c:/code
      to: /home/vagrant/Code  
      
sites:
    - map: f.192.168.1.102.xip.io
      to: /home/vagrant/Code/FontGalleryLaravel/public
      schedule: false
    - map: d.192.168.1.102.xip.io
      to: /home/vagrant/Code/daily/public
      schedule: false
    - map: fonts.192.168.1.102.xip.io
      to: /home/vagrant/Code/FontGallery
      schedule: false    

databases:
    - homestead
    - homestead_daily
    - homestead_daily_testing
    - homestead_fonts
    
#https://laravel.com/docs/7.x/homestead#network-interfaces and https://www.vagrantup.com/docs/networking/public_network.html
networks:
    - type: "public_network"
      ip: "192.168.1.119"
      bridge: "Realtek RTL8811AU Wireless LAN 802.11ac USB 2.0 Network Adapter"

```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.
https://gist.github.com/ryancwalsh/8ec567644f010e72d19252b532157ac1

## Expected behavior
I expect to be able to run `vagrant halt` and later `vagrant reload --provision` without error.

## Actual behavior
What actually happened? Please include as much detail as possible.
See steps.

## Steps to reproduce
1. Run the gist above to prove everything works fine.
1. Create a `.bashrc` file like https://gist.github.com/ryancwalsh/7925b0541a9bf7f83048a6c23fe5960d
1. In your `after.sh`, source the `.baschrc`:

```
cp /home/vagrant/Code/env/homestead/.bashrc ~/.bashrc
dos2unix ~/.bashrc
source ~/.bashrc
```
4. Now running `vagrant halt` and then `vagrant reload --provision` leads to error: https://gist.github.com/ryancwalsh/af7f75849d82eef3faf60d9057332ca4

I don't know when this started happening, but none of those lines in my `.bashrc` are new, so I think it must have started happening when I upgraded either to Homestead v10.5.1 or box `laravel/homestead (virtualbox, 9.3.0)` (or maybe it was even before that?) or Virtualbox 6.1.4.

Do you see something wrong?

Thanks so much!

## References
- https://github.com/hashicorp/vagrant/issues/11456
