### ISSUE TITLE
EPROTO: protocol error, symlink '../jsesc/bin/jsesc'

### ISSUE THREAD

**Issue by tienqn** [laravel/homestead#1409]
Hi every one, i have a problem when try to `npm install` in laravel project
Hope some can help me. Thank you so much.
## Versions
  - Vagrant: 2.2.7
  - Provider: Virtualbox
  - Homestead: You should be on the most recent `release` branch.

## Host operating system
windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: c:/Users/admin/.ssh/id_rsa.pub

keys:
    - c:/Users/admin/.ssh/id_rsa

folders:
    - map: c:/Users/admin/Projects2019/vy_spa/html/labeauty
      to: /home/vagrant/Projects2019/vy_spa/html/labeauty

    - map: c:/Users/admin/Projects2019/wit/admin/web-wit
      to: /home/vagrant/Projects2019/wit/admin/web-wit

    - map: c:/Users/admin/Projects2019/demo/homstead
      to: /home/vagrant/Projects2019/demo/homstead

      type: "nfs"

sites:
    - map: labeauty.test
      to: /home/vagrant/Projects2019/vy_spa/html/labeauty/public

    - map: wit.test
      to: /home/vagrant/Projects2019/wit/admin/web-wit/public

    - map: demo.test
      to: /home/vagrant/Projects2019/demo/homstead

databases:
    - labeauty
    - db_test

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

```

## Steps to reproduce
1. vagrant up && vagrant ssh
2. cd Projects2019/vy_spa/html/labeauty
3. npm install

![Screenshot_1](https://user-images.githubusercontent.com/54127625/79945083-47ef1380-8497-11ea-914a-1dcd98c883a4.png)
