### ISSUE TITLE
Homestead having date in future.

### ISSUE THREAD

**Issue by hnnweb** [laravel/homestead#1413]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: $ Vagrant 2.2.7
  - Provider: Virtualbox 6.1.6_Ubuntu
  - Homestead: Release

## Host operating system
Ubuntu 20.04 LTS

## Homestead.yaml
```yaml
$ cat Homestead/Homestead.yaml                              
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/src
      to: /home/vagrant/src
      type: "nfs"

sites:
    - map: nojestorget.test
      to: /home/vagrant/src/nojestorget/public

databases:
    - homestead
    - nojestorget

features:
    - mariadb: true
    - ohmyzsh: true
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

after.sh
```yaml
sudo systemctl stop postgresql
sudo systemctl disable postgresql

sudo sed 's/log_bin/#log_bin/g' /etc/mysql/my.cnf > ~/my.cnf
sudo mv /etc/mysql/my.cnf /etc/mysql/my.bak
sudo mv ~/my.cnf /etc/mysql/my.cnf
sudo systemctl restart mariadb

grep 'log_bin' /etc/mysql/my.cnf

sudo apt-get install pv

echo 'Importing SQL file...'
pv ~/src/db.sql.gz | gunzip | mysql -u 'homestead' -psecret nojestorget


sudo mv /etc/mysql/my.bak /etc/mysql/my.cnf
sudo systemctl restart mariadb
```
## Vagrant destroy & up output
 [GitHub Gist](https://gist.github.com/hnnweb/aabca387162e539d464f6683d28e9f23) 

## Expected behavior
Date not in future. Homestead isn't a timemachine...

## Actual behavior
```$ homestead ssh                                       10 ↵  
zsh: correct 'ssh' to '.ssh' [nyae]? n
You are required to change your password immediately (password aged)
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)


17 packages can be updated.
14 updates are security updates.


**Last login: Sun Nov 24 07:13:32 2024 from 10.0.2.2**
WARNING: Your password has expired.
You must change your password now and login again!
Changing password for vagrant.
(current) UNIX password: 
```

``` Last login: Sun Nov 24 07:15:19 2024 from 10.0.2.2
[Oh My Zsh] Would you like to update? [Y/n]: 
Updating Oh My Zsh
fatal: unable to access 'https://github.com/ohmyzsh/ohmyzsh.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
There was an error updating. Try again later?
vagrant@homestead ~$ date                                                      
Sat Feb  6 20:12:33 UTC 2297
vagrant@homestead ~$            
```
## Steps to reproduce
1. vagrant up ; vagrant ssh
2. 
3.

## References
No references i'm aware of...
