### ISSUE TITLE
DevToolsActivePort file doesn't exist (Dusk, Homestead)

### ISSUE THREAD

**Issue by moxyrus** [laravel/homestead#1414]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.2.7.
  - Provider: Virtualbox 6.1.
  - Homestead: 10.8.0.

## Host operating system
Linux ema-PC 5.0.0-050000-generic #201903032031 SMP Mon Mar 4 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /home/ema/www/sites/test
        to: /home/vagrant/code
sites:
    -
        map: homestead.test
        to: /home/vagrant/code/public
databases:
    - homestead
features:
    -
        mariadb: false
    -
        ohmyzsh: false
    -
        webdriver: true
name: test
hostname: test
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.

https://gist.github.com/moxyrus/07defe9b32a1b1cd615eebc4d74838b8

## Expected behavior

Browser test go through properly. 

## Actual behavior

I get the next error:
1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\UnknownErrorException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

/home/vagrant/code/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:139
/home/vagrant/code/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:370
/home/vagrant/code/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:136
/home/vagrant/code/tests/DuskTestCase.php:40
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:200
/home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/helpers.php:404
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:201
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:95
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:65
/home/vagrant/code/tests/Browser/ExampleTest.php:21

## Steps to reproduce
1. composer create-project --prefer-dist laravel/laravel ./
2. composer require laravel/homestead --dev
3. php vendor/bin/homestead make
4. vagrant up
5. vagrant ssh
6. composer require --dev laravel/dusk
7. php artisan dusk:install
ChromeDriver binaries successfully installed for version 81.0.4044.69
8. php artisan dusk
9. changed file DuskTestCase.php
https://gist.github.com/moxyrus/d0828153e95e3a932fd77618132dceed
10. I get the same error

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- GH-1234
- ...
