### ISSUE TITLE
How to add username , password smb using share folders

### ISSUE THREAD

**Issue by VietHebis** [laravel/homestead#1417]
![image](https://user-images.githubusercontent.com/37867770/81770835-99754600-950b-11ea-9445-a32d6b96de86.png)
where is I can add user and password for share folder

**Comment by svpernova09** [comment]
Something like

```
folders:
    - map: "D:\Homestead\code"
       to: /home/vagrant/code
       smb_host: "smb host"
       smb_username: "smb username"
       smb_password: "smb password"
```

This is likely going to be *really* slow and I don't recommend it.
