### ISSUE TITLE
Docker does not work within the homestead.

### ISSUE THREAD

**Issue by alex-oliveira** [laravel/homestead#1428]
## Versions
  - Vagrant 2.2.9
  - Virtualbox: 6.1.8r137981
  - Homestead: v10.8.0

## Host operating system
 - OS Name: Microsoft Windows 10 Pro
 - Version: 10.0.18363 Build 18363

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4056
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: D:/Workspace/www/homestead
      to: /home/vagrant/www/homestead

sites:
    - map: homestead.loc
      to: /home/vagrant/www/homestead/public

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
    - docker: true
```

## Vagrant destroy & up output
https://gist.github.com/alex-oliveira/8876964babdb099139cfb78e3d2b31b2

## Expected behavior
I think I should be able to use the docker normally inside the homestead.

## Actual behavior
Apparently, there are several errors related to the "hash" comparison. This prevents perfect installation.

## Steps to reproduce
1. Just add "- docker: true" to the file and try to run "vagrant up".
2. If you remove "- docker: true", everything works fine.
