### ISSUE TITLE
php 7.3 modified www.conf installation prompt breaking setup

### ISSUE THREAD

**Issue by bwml** [laravel/homestead#1430]
## Versions
  - Vagrant: 9.5.1
  - Provider: Virtualbox
  - Homestead: 9.4.1

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
I have upgrade Vagrant and Homestead to latest versions

## Host operating system
Ubuntu 18.04.4 LTS

## Homestead.yaml
```yaml
ip: 192.168.10.20
memory: 2048
cpus: 1
provider: virtualbox
ssl: true
folders:
  -
    map: /var/www/abc/
    to: /home/vagrant/abc
sites:
  -
    map: abc.local.net
    to: /home/vagrant/abc/src
    php: "7.3"
    type: "apache"
databases:
  - abc
name: abc
hostname: abc
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.
https://gist.github.com/bwml/b153cf198d1a9fe9300a06702c7e81b2

## Expected behavior
PHP 7.3 should be installed without errors.

## Actual behavior
During core provisioning, PHP 7.3 configuration/installation is failing because it is detecting previous installation files (www.conf).  This is happening before the custom provisioning step (after.sh).

## Steps to reproduce
1. vagrant up

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
This issue seems similar, but the solution there involved a change to after.sh.  This issue occurs before custom provisioning.
https://github.com/laravel/homestead/issues/893
