### ISSUE TITLE
artisan dusk fails when run inside Homestead

### ISSUE THREAD

**Issue by tedmasterweb** [laravel/homestead#1437]
## Versions
  - Vagrant: Vagrant 2.2.9
  - Provider: Virtualbox 6.0.20 r137117 (Qt5.6.3)
  - Homestead: 9.5.1

## Host operating system
Mac OS X 10.15.5

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Sites/laravel/obfuscated
      to: /home/vagrant/obfuscated
      type: "nfs"

    - map: ~/Sites/wordpress/obfuscated
      to: /home/vagrant/obfuscated
      type: "nfs"

    - map: ~/Projects/obfuscated
      to: /home/vagrant/obfuscated
      type: "nfs"

    - map: ~/Sites/laravel/obfuscated
      to: /home/vagrant/obfuscated
      type: "nfs"

    - map: ~/Sites/laravel/obfuscated
      to: /home/vagrant/obfuscated
      type: "nfs"

    - map: ~/Sites/laravel/obfuscated
      to: /home/vagrant/obfuscated
      type: "nfs"

    - map: ~/Sites/laravel/obfuscated
      to: /home/vagrant/obfuscated
      type: "nfs"

sites:
    - map: nhsbeds.test
      to: /home/vagrant/obfuscated/public

    - map: wpdev.test
      to: /home/vagrant/obfuscated

    - map: privaterepos.test
      to: /home/vagrant/obfuscated

    - map: polymateria.test
      to: /home/vagrant/obfuscated/public

    - map: dracula.test
      to: /home/vagrant/obfuscated/public

    - map: reactvue.test
      to: /home/vagrant/obfuscated/public

    - map: mh.test
      to: /home/vagrant/obfuscated/public

databases:
    - obfuscated
    - obfuscated
    - obfuscated
    - obfuscated
    - obfuscated
    - obfuscated

features:
    - mariadb: false
    - ohmyzsh: true
    - webdriver: true
    - python: true
    - solr: true

networks:
    - type: "public_network"
      bridge: "en0: Wi-Fi (AirPort)"

ports:
     - send: 8181
       to: 8181
     - send: 3001
       to: 3001
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
https://gist.github.com/tedmasterweb/eeeaae32d62f40a73646f8b74a96d4c0

## Summary
We need to be able to run Dusk tests inside Homestead (headless mode). Unfortunately, it seems that `- webdriver: true` is not installing all the pieces necessary to be able to run `artisan dusk` inside Homestead.

## Expected behavior
By setting `- webdriver: true` in Homestead.yaml, when running `artisan dusk` while logged in to the homestead box via ssh, tests are run (and either pass or fail)

## Actual behavior
We get the error:

> session not created: This version of ChromeDriver only supports Chrome version 83

## Steps to reproduce
1. In a default Homestead install, install dusk (`composer require --dev laravel/dusk`)
2. And then `artisan dusk:install`
3. Followed by `artisan dusk`

## References
https://github.com/laravel/homestead/issues/516#issuecomment-285903030
https://github.com/laravel/dusk/issues/651#issuecomment-500617890

## Workarounds
Follow the instructions in this comment (except the last command, which isn't necessary in our testing): https://github.com/laravel/homestead/issues/516#issuecomment-285903030
