### ISSUE TITLE
MariaDB fails to install in v10.8.1

### ISSUE THREAD

**Issue by Braunson** [laravel/homestead#1438]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.9
  - Provider: Virtualbox
  - Homestead: v10.8.1

## Host operating system
Windows 10 Home

## Homestead.yaml
```yaml
ip: 192.168.12.120
memory: 2048
cpus: 2
provider: virtualbox
name: project-homestead
hostname: project-homestead

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: '~/Documents/GitHub/project'
      to: /home/vagrant/project

sites:
    - map: project.local
      to: /home/vagrant/project/public
      schedule: true

databases:
    - homestead
    - project

features:
    - mariadb: true
    - ohmyzsh: true
    - webdriver: true

```

## Expected behavior
MariaDB should install, it does not, throws issues.

## Actual behavior

```
    project-homestead: Setting up mariadb-server-10.4 (1:10.4.13+maria~bionic) ...
    project-homestead: Failed to stop mysql.service: Unit mysql.service not loaded.
    project-homestead: Created symlink /etc/systemd/system/mysql.service → /lib/systemd/system/mariadb.service.
    project-homestead: Created symlink /etc/systemd/system/mysqld.service → /lib/systemd/system/mariadb.service.
    project-homestead: Created symlink /etc/systemd/system/multi-user.target.wants/mariadb.service → /lib/systemd/system/mariadb.service.
    project-homestead: Job for mariadb.service failed because the control process exited with error code.
    project-homestead: See "systemctl status mariadb.service" and "journalctl -xe" for details.
    project-homestead: Job for mariadb.service failed because the control process exited with error code.
    project-homestead: See "systemctl status mariadb.service" and "journalctl -xe" for details.
    project-homestead: Setting up libcgi-fast-perl (1:2.15-1) ...
    project-homestead: Setting up mariadb-server (1:10.4.13+maria~bionic) ...
    project-homestead: Processing triggers for man-db (2.9.1-1) ...
    project-homestead: Processing triggers for libc-bin (2.31-0ubuntu9) ...
    project-homestead: ERROR
    project-homestead:  2002 (HY000)
    project-homestead: : Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
    project-homestead: Job for mariadb.service failed because the control process exited with error code.
    project-homestead: See "systemctl status mariadb.service" and "journalctl -xe" for details.
    project-homestead: ERROR
    project-homestead:  2002 (HY000)
    project-homestead: : Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
    project-homestead: ERROR
    project-homestead:  2002 (HY000)
    project-homestead: : Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
    project-homestead: ERROR
    project-homestead:  2002 (HY000)
    project-homestead: : Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
    project-homestead: ERROR
    project-homestead:  2002 (HY000)
    project-homestead: : Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
    project-homestead: Job for mariadb.service failed because the control process exited with error code.
```

Before `vagrant up` finishes it tries to create the datbaase and throws `Cannot connect to local MySQL server through socket `/var/run/mysqld/mysqld.sock'`

## Steps to reproduce
1. Copy down `Homestead.yaml`
2. Run `vagrant up`
3. Watch up logs.
