### ISSUE TITLE
Per-project install, serve-laravel fails due to missing /vagrant/scripts

### ISSUE THREAD

**Issue by Braunson** [laravel/homestead#1439]
## Versions
  - Vagrant: 2.2.9
  - Provider: Virtualbox
  - Homestead: v10.8.1

## Host operating system
Windows 10 Home

## Expected behavior
Should run the serve script

## Actual behavior

Trying to run `serve-laravel` that's defined in `aliases` but `/vagrant/scripts` doesn't seem to exist and thus the command throws errors

```
bash: /vagrant/scripts/create-certificate.sh: No such file or directory
dos2unix: /vagrant/scripts/site-types/laravel.sh: No such file or directory
dos2unix: Skipping /vagrant/scripts/site-types/laravel.sh, not a regular file.
bash: /vagrant/scripts/site-types/laravel.sh: No such file or directory
```

I think this may be related to #574 but not sure of a workaround..  I'm trying to use `serve-laravel` function to register another site (i.e. phpMyAdmin) -- Any ideas of a workaround without duplicating the code from `/vagrant/scripts/{create-certificate,site-types/laravel}` into my `after.sh` script (where this is all called from)?

## Steps to reproduce
1. Copy down `Homestead.yaml`
2. Run `vagrant up`
3. Watch up logs.

**Comment by Braunson** [comment]
I just noticed `homestead/resources/localized/aliases` 🤦‍♂️

**Comment by Braunson** [comment]
Having issues with this still, running the script in `after.sh` and it's still saying `serve-laravel: command not found`. Any ideas?

**Comment by svpernova09** [comment]
post your `Homestead.yaml` Are you manually mapping `.` (current folder)?

**Comment by Braunson** [comment]
## Homestead.yaml
```yaml
ip: 192.168.12.120
memory: 2048
cpus: 2
provider: virtualbox
name: project-homestead
hostname: project-homestead

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: '~/Documents/GitHub/project'
      to: /home/vagrant/project

sites:
    - map: project.local
      to: /home/vagrant/project/public
      schedule: true

databases:
    - homestead
    - project

features:
    - mariadb: true
    - ohmyzsh: true
    - webdriver: true

```
