### ISSUE TITLE
Homestead.yaml doesn't follow .editorconfig

### ISSUE THREAD

**Issue by guoyunhe** [laravel/homestead#1447]
The Homestead.yaml created by by `homestead make` uses 4 spaces indention:
```
ip: 192.168.10.10
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /home/guo/git/laravel-react-demo
        to: /home/vagrant/code
sites:
    -
        map: homestead.test
        to: /home/vagrant/code/public
databases:
    - homestead
features:
    -
        mariadb: false
    -
        ohmyzsh: false
    -
        webdriver: false
name: laravel-react-demo
hostname: laravel-react-demo

```
But in .editorconfig shipped by `laravel new` command is to use 2 spaces for yaml:
```
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 4
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false

[*.{yml,yaml}]
indent_size = 2
```
