### ISSUE TITLE
Unable to add new project on Windows 10 when using release version v10.10.1

### ISSUE THREAD

**Issue by mnaderian** [laravel/homestead#1453]
When updating to the latest release (v10.10.1) on Windows 10 (by checking out to release inside homestead) vagrant shows errors instead of provisioning the machine.

## Versions
  - Vagrant: 2.2.9
  - Provider: Virtualbox
  - Homestead: 10.10.1 (The most recent release)

>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

# authorize: ~/.ssh/id_rsa.pub

# keys:
#     - ~/.ssh/id_rsa

folders:
    - map: C:\Users\MN\Desktop\Laravel\Projects\project1
      to: /home/vagrant/code/project1

    - map: C:\Users\MN\Desktop\Laravel\Projects\doc-test
      to: /home/vagrant/code/doc-test

    - map: C:\Users\MN\Desktop\Laravel\Projects\tweety
      to: /home/vagrant/code/tweety

    - map: C:\Users\MN\Desktop\Laravel\Projects\onlinefavoritslist
      to: /home/vagrant/code/onlinefavoritslist

    - map: C:\Users\MN\Desktop\Laravel\Projects\OnlineFavoritesList3
      to: /home/vagrant/code/OnlineFavoritesList3

    - map: C:\Users\MN\Desktop\Laravel\Projects\sobheshahrvand
      to: /home/vagrant/code/sobheshahrvand

    - map: C:\Users\MN\Desktop\Laravel\Projects\livewire
      to: /home/vagrant/code/livewire

sites:
    - map: homestead.test
      to: /home/vagrant/code/project1/public

    - map: doc-test.test
      to: /home/vagrant/code/doc-test/public

    - map: tweety.test
      to: /home/vagrant/code/tweety/public

    - map: onlinefavoriteslist3.test
      to: /home/vagrant/code/OnlineFavoritesList3/public

    - map: sobheshahrvand.test
      to: /home/vagrant/code/sobheshahrvand/public

    - map: livewire.test
      to: /home/vagrant/code/livewire/public

    - map: onlinefavoriteslist-old.test
      to: /home/vagrant/code/onlinefavoritslist

databases:
    - homestead
    - laravel_doc_test
    - tweety
    - onlinefavoriteslist3
    - onlinefavoriteslist
    - sobheshahrvand
    - livewire

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Steps to reproduce
1. Checkout to the latest release of homestead (currently v10.10.1) using ```git checkout release```
2. Try to add new folder and site settings to your Homestead.yaml
3. Run ```vagrant reload --provision``` or ```vagrant up```

## What I did next
I checked out to the master branch and it works without any problem now!
```git checkout master```
