### ISSUE TITLE
It works with Virtualbox but not with vmware_fusion

### ISSUE THREAD

**Issue by maxacarvalho** [laravel/homestead#1455]
Hello,

I've been trying to solve my issue for one and a half now so I think an issue is not justifiable.

I'm not a Laravel Homestead user but my current project requires it so I'm diving in.

I followed the instructions from the Laravel website and had the local environment working flawlessly with Virtualbox.  

Since I saw many reports about the VMWare performance improvements I decided to give it a try.  
Again, I followed the instructions, installed VMWare Fusion (`Version 11.5.5 (16269456)`) and the `VMware Vagrant plug-in`.

I changed the `provider` on my `Homestead.yaml` file and provisioned the machine.  
Once it finished I tried to access my website but it hangs for several seconds before timing out.  
I checked and I can access the Vagrant machine via `vagrant ssh`. I see no errors on the Nginx logs.

Everything is pretty standard, I didn't do any custom thing, and it was working fine with the Virtualbox provider.  

I'd like to ask some help, maybe you guys already faced something similar.

Thanks

## Versions
  - Vagrant 2.2.9
  - Provider: VMWare Fusion Version 11.5.5 (16269456)
  - Homestead: latest `release` branch

## Host operating system
macOS Catalina 10.15.6

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: vmware_fusion

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code/core-api
      to: /home/vagrant/core-api
      type: "nfs"

sites:
    - map: api.core-api.test
      to: /home/vagrant/core-api/public

databases:
    - eshop_production_rec

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
    - rabbitmq: true

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Expected behavior
I should be able to access the website.

## Actual behavior
The request times out.
