### ISSUE TITLE
Configuration caching fails. (php artisan config:cache)

### ISSUE THREAD

**Issue by aezur** [laravel/homestead#1457]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.9 (also checked on 2.2.7)
  - Provider: Virtualbox 6.1.12 r139181 (Qt5.6.2)
  - Homestead v10.9.1
  - Settler v9.5.1 (Virtualbox, Parallels, Hyper-V, VMware)

## Host operating system
Windows 10 Home - Build 18363

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: c:/Users/aezur/.ssh/homestead_rsa.pub

keys:
    - c:/Users/aezur/.ssh/homestead_rsa

folders:
    - map: c:/Users/aezur/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/economygame/backend/public

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: true
    - webdriver: false

```

## Vagrant destroy & up output
https://gist.github.com/aezur/7828d5af2b78f37b311ccaed80265b4f

## Expected behavior
When running the command `php artisan config:cache` from inside the vagrant box, I expect the configuration to be cached in the filesystem.

## Actual behavior
I get the following output in terminal:
```
Configuration cache cleared!

   Symfony\Component\Finder\Exception\DirectoryNotFoundException 

  The "" directory does not exist.

  at vendor/symfony/finder/Finder.php:589
    585|             } elseif ($glob = glob($dir, (\defined('GLOB_BRACE') ? GLOB_BRACE : 0) | GLOB_ONLYDIR | GLOB_NOSORT)) {
    586|                 sort($glob);
    587|                 $resolvedDirs = array_merge($resolvedDirs, array_map([$this, 'normalizeDir'], $glob));
    588|             } else {
  > 589|                 throw new DirectoryNotFoundException(sprintf('The "%s" directory does not exist.', $dir));
    590|             }
    591|         }
    592|
    593|         $this->dirs = array_merge($this->dirs, $resolvedDirs);

      +21 vendor frames
  22  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

Full output log: https://gist.github.com/aezur/ac39539cced08e2e3d9b15cd8f416434

## Steps to reproduce
1. Install and set up virtual box 6.1, vagrant 2.2.9, and homestead 9.5.1.
2. SSH into vagrant box.
3. Run `php artisan config:cache`
