### ISSUE TITLE
MariaDB failed to install

### ISSUE THREAD

**Issue by RSpeekenbrink** [laravel/homestead#1461]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.9.
  - Provider: Virtualbox 6.0.20
  - Homestead: 11.0.0

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Windows 10 proffesional

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    - map: ./
      to: /home/vagrant/code
sites:
    - map: vagrant.test
      to: /home/vagrant/code/public
databases:
    - homestead
features:
    - mariadb: true
    - ohmyzsh: true
    - webdriver: false
name: vagrantbox
hostname: vagrantbox
```

## Vagrant destroy & up output
https://gist.github.com/RSpeekenbrink/a9823b6e9de85fa0f19d13517999cfb9

## Expected behavior
After vagrant up a succesfull installation including mariadb

## Actual behavior
MariaDB error causing the provisioning to stop (see output)

## Steps to reproduce
1. Create a fresh project with homestead per project installation
2. Enable mariadb in the homestead yaml
3. Vagrant up

## References
- https://github.com/laravel/homestead/issues/1438 (Looks like the same issue?)
