### ISSUE TITLE
MariaDB does not create databases

### ISSUE THREAD

**Issue by RSpeekenbrink** [laravel/homestead#1462]
## Versions
  - Vagrant: 2.2.9.
 - Provider: Virtualbox 6.0.20
 - Homestead: 11.0.1

## Host operating system
Windows 10 proffesional

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    - map: ./
      to: /home/vagrant/code
sites:
    - map: vagrant.test
      to: /home/vagrant/code/public
databases:
    - homestead
features:
    - mariadb: true
    - ohmyzsh: true
    - webdriver: false
name: vagrantbox
hostname: vagrantbox
```

## Vagrant destroy & up output
https://gist.github.com/RSpeekenbrink/dfc11e2a01e4d4d1ac8ae1fefda149ad

## Expected behavior
Box booted and created homestead database.

## Actual behavior
No database got created.

## Steps to reproduce
1. Install laravel homestead 11.0.1
2. Enable mariadb in Homestead.yaml
3. Vagrant up

## References
- This got mentioned that this is an effect of https://github.com/laravel/homestead/issues/1461. Made this issue for reference.
