### ISSUE TITLE
Redis is not started automatically

### ISSUE THREAD

**Issue by michaeldzjap** [laravel/homestead#1465]
## Versions
  - Vagrant: 2.2.9
  - Provider: Virtualbox 6.1.12
  - Homestead: 11.0.1

## Host operating system
macOS 10.15.6

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Sites/WebDev/php
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/laravel/public

databases:
    - homestead

features:
    - webdriver: true
```

## Vagrant destroy & up output
https://gist.github.com/michaeldzjap/8515acea457c657cf7bb4bee22b32b6b

## Expected behavior
I would expect `sudo service redis-server status` to show an "Active: active (running) ..." status.

## Actual behavior
Instead I get:

```shell
● redis-server.service - Advanced key-value store
     Loaded: loaded (/lib/systemd/system/redis-server.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: http://redis.io/documentation,
             man:redis-server(1)
```

After manually running `sudo service redis-server start` I get:

```shell
● redis-server.service - Advanced key-value store
     Loaded: loaded (/lib/systemd/system/redis-server.service; disabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-07-27 07:48:47 UTC; 2s ago
       Docs: http://redis.io/documentation,
             man:redis-server(1)
    Process: 4497 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=0/SUCCESS)
   Main PID: 4513 (redis-server)
      Tasks: 5 (limit: 2320)
     Memory: 3.6M
     CGroup: /system.slice/redis-server.service
             └─4513 /usr/bin/redis-server 127.0.0.1:6379
```

## Steps to reproduce
1. Install laravel homestead 11.0.1
2. vagrant up

## References
- Came across this closed issue which seems related: GH-1328
