### ISSUE TITLE
Laravel Homestead

### ISSUE THREAD

**Issue by CleoCTech** [laravel/homestead#1477]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Run `vagrant 2.2.9` to show the version.
  - Provider: Virtualbox 6.1.12.
  - Homestead: version 9.5.1.

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Windows 10.

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: c:/Users/user/.ssh/id_rsa.pub

keys:
    - c:/Users/user/.ssh/id_rsa

folders:
    - map: d:/Homestead_Projects
      to: /home/vagrant/Code

sites:
    - map: homestead.test
      to: /home/vagrant/Code/Project101/public

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
`vagrant up && vagrant destroy`
https://gist.github.com/CleoCTech/ca92827a0433e6cb9b8109b1fdf4eeb3

## Expected behavior
I excepted once I run vagrant up/provision command I should access the registered domain of homestead.test in my browser

## Actual behavior
This is what happened: 
homestead.test’s server IP address could not be found.

## Steps to reproduce
1.
2.
3.

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- GH-1234
- ...
