### ISSUE TITLE
Apache no longer starting automatically

### ISSUE THREAD

**Issue by staudenmeir** [laravel/homestead#1478]
## Versions
  - Vagrant: 2.2.9
  - Provider: Virtualbox 6.1.12
  - Homestead: 11.0.2

## Host operating system
macOS 10.15.6

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /Users/jonas/PhpstormProjects/homestead
        to: /home/vagrant/code
sites:
    -
        map: homestead.test
        to: /home/vagrant/code
        type: apache
databases:
    - homestead
features:
    -
        mariadb: false
    -
        ohmyzsh: false
    -
        webdriver: false
name: homestead
hostname: homestead

```

## Vagrant destroy & up output
https://gist.github.com/staudenmeir/4903bc98d4673461592fb07dc0062849

## Expected behavior
Homestead starts Apache automatically for Apache sites.

## Actual behavior
Homestead no longer starts Apache automatically for Apache sites. Apache is only running after the initial `vagrant up` but not after reloads. I need to manually add it to the enabled services:

```yaml
services:
    - enabled:
          - 'apache2'
```

I saw "Apache is now installed and disabled by default which should result in faster provisioning for site type apache." in the release notes, but I think Homestead should still start Apache if one of the sites is running on it.

## Steps to reproduce
1. Define an Apache site.
2. `vagrant up`
3. `vagrant reload`
4. Visit the Apache site.
