### ISSUE TITLE
vagrant box update not downloading newest one

### ISSUE THREAD

**Issue by mechoriet** [laravel/homestead#1493]
## Versions
  - Vagrant: 2.2.9
  - Provider: Virtualbox 6.1.14 r140239 (Qt5.6.2)
  - Homestead: v11.1.2 via composer per project

## Host operating system
Windows 10 pro 2004

## Homestead.yaml
```yaml
ip: 192.168.10.11
name: fscareer
hostname: fscareer
memory: 4096
cpus:
natdnshostresolver: 'off'
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    - map: 'F:\developement\backend'
      to: /home/vagrant/backend
      type: "rsync"
      options:
        rsync__exclude: [".git/","node_modules"]
    - map: 'F:\developement\frontend'
      to: /home/vagrant/frontend
      type: "rsync"
      options:
        rsync__exclude: [".git/"]
sites:
    - map: api.fscareer.test
      to: /home/vagrant/backend/public
    - map: fscareer.test
      to: 3000
      type: proxy
databases:
    - fscareer
features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
services:
    - enabled:
        - "redis-server"
```

## Expected behavior

download the new box v10.1.0 as of writing this it was created 15 hours ago
don't know if this issue is vagrant side or something within homestead itself

## Actual behavior
$ vagrant box update
==> fscareer: Checking for updates to 'laravel/homestead'
    fscareer: Latest installed version: 10.0.0
    fscareer: Version constraints: ~> 10.0.0
    fscareer: Provider: virtualbox
==> fscareer: Box 'laravel/homestead' (v10.0.0) is running the latest version.

$ vagrant box outdated
Checking if box 'laravel/homestead' version '10.0.0' is up to date...

$ vagrant box outdated --force
Checking if box 'laravel/homestead' version '10.0.0' is up to date..

## Extra
also tried composer update on the whole project
that updated laravel/homestead from v11.1.2 => v11.2.0 with the same result as above
