### ISSUE TITLE
Error during vagrant up - Command '['udevadm', 'settle']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by ethanclevenger91** [laravel/homestead#1501]
## Versions
  - Vagrant: 2.2.10
  - Provider: Virtualbox, 6.1.14
  - Homestead: You should be on the most recent `release` branch - yup

## Host operating system
Win10 build 19041.508

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
backup: true,

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - { type: "nfs", map: ~/code/phpmyadmin, to: /home/vagrant/code/phpmyadmin }
    - { type: "nfs", map: ~/code/mysql_backups, to: /home/vagrant/code/mysql_backups }
    - { type: "nfs", map: ~/code/pond, to: /home/vagrant/code/pond }
    - {
          type: "nfs",
          map: ~/code/oregon-truffle-festival,
          to: /home/vagrant/code/oregon-truffle-festival,
      }
    # etc etc etc
sites:
    - { map: homestead.test, to: /home/vagrant/dev }
    - { map: phpmyadmin.test, to: /home/vagrant/code/phpmyadmin }
    - { map: pond.test, to: /home/vagrant/code/pond/public, schedule: true }
    - {
          map: oregontrufflefestival.test,
          to: /home/vagrant/code/oregon-truffle-festival/web,
      }
    # etc etc etc

databases:
    [
        homestead,
        american_inkjet_systems,
        apislabs_wp,
        # etc etc etc
    ]

services:
    - enabled: 
        - "mysql"

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
https://gist.github.com/ethanclevenger91/01a11898b5b87984b12a9c3bdf174408

## Expected behavior
Homestead should launch ready for use

## Actual behavior
See error in `vagrant up` output.

## Steps to reproduce
I assume it's environment-specific, so run the above Win10 version and try get started w/ Homestead according to the docs.

## References
Someone mentioned in #1498 that there could be an issue with VirtualBox and a recent Windows update. Can't really speak to that, but seems plausible. I know WSL has interfered w/ VirtualBox in the past.
