### ISSUE TITLE
wildcard ssl certificate was installed in nginx as '*.test.crt' instead of 'mysite.test.crt'

### ISSUE THREAD

**Issue by winkbrace** [laravel/homestead#1507]
## Versions
  - Vagrant: Vagrant 2.2.10
  - Provider: Virtualbox 6.1.14
  - Homestead: release, commit 960edbf

## Host operating system
macOS 10.15.7

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
ssl: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/repos/verlanglijstjes
      to: /home/vagrant/code/verlanglijstjes
    - map: ~/repos/shifting/dashboard
      to: /home/vagrant/code/shifting/dashboard

sites:
    - map: vl.test
      to: /home/vagrant/code/verlanglijstjes/public
    - map: dashboard.test
      to: /home/vagrant/code/shifting/dashboard/public
      wildcard: "yes"

databases:
    - homestead
    - landlord
    - tenant_default
    - tenant_demo
    - landlord_test
    - tenant_test
    - verlanglijstjes

variables:
    # This variable lets us know we are in Homestead.
    - key: HOMESTEAD
      value: 1

ports:
    # ports for ssh tunnels to aws
    - send: 9001
      to: 9001
    - send: 9002
      to: 9002
    # redis
    - send: 6379
      to: 6379
    # websockets
    - send: 6001
      to: 6001
```

## Steps to reproduce
1. vagrant destroy && vagrant up
1. vagrant ssh 
1. sudo nano /etc/nginx/sites-enabled/dashboard.test
1. insert at the top
    ```
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name dashboard.test;
        return 301 https://dashboard.test;
    }
    ```
1. sudo cp /etc/nginx/ssl/dashboard.test.crt ~/code/shifting/dashboard/
1. drag dashboard.test.crt into my Keychain
1. quit chrome
1. open chrome on https://demo.dashboard.test

This should open my local site on https, but it gives me the invalid SSL certificate warning of chrome. 
In the end I found that in the nginx configuration `ssl_certificate` was set to `/etc/nginx/ssl/*.test.crt` instead of `/etc/nginx/ssl/dashboard.test.crt`. After making that change the certifcate was accepted by the browser again.

I've been attempting so many things to figure this out that I'm not 100% sure I didn't do something wrong, but I have the feeling this wildcard ssl certificate is not entirely setup as expected.

**Comment by svpernova09** [comment]
I believe this is working as intended. You can rename the certificate to whatever you want to import into your browser/keychain/application. Homestead doesn't cover that aspect of SSL keys.

**Comment by winkbrace** [comment]
hm, maybe I wasn't clear. In the nginx config file located at `/etc/nginx/sites-enabled/dashboard.test` in homestead, the config is:

```
    ssl_certificate     /etc/nginx/ssl/*.test.crt;
    ssl_certificate_key /etc/nginx/ssl/*.test.key;
```

instead of 

```
    ssl_certificate     /etc/nginx/ssl/dashboard.test.crt;
    ssl_certificate_key /etc/nginx/ssl/dashboard.test.key;
```

So when I imported the dashboard.test.crt in Keychain, the ssl key wasn't accepted. I don't understand how that is working as intended?

**Comment by svpernova09** [comment]
> 
> 
> hm, maybe I wasn't clear. In the nginx config file located at `/etc/nginx/sites-enabled/dashboard.test` in homestead, the config is:
> 
> ```
>     ssl_certificate     /etc/nginx/ssl/*.test.crt;
>     ssl_certificate_key /etc/nginx/ssl/*.test.key;
> ```
> 
> instead of
> 
> ```
>     ssl_certificate     /etc/nginx/ssl/dashboard.test.crt;
>     ssl_certificate_key /etc/nginx/ssl/dashboard.test.key;
> ```
> 
> So when I imported the dashboard.test.crt in Keychain, the ssl key wasn't accepted. I don't understand how that is working as intended?

Importing keys into your browser/keychain is outside of the scope of Homestead.

> ssl_certificate     /etc/nginx/ssl/*.test.crt;

This is the wildcard certificate.

>     ssl_certificate     /etc/nginx/ssl/dashboard.test.crt;

This is the standard/non-wildcard certificate.

If you're wanting to add the SSL cert for `dashboard.test` use `dashboard.test.crt`. If you wanting to add the wildcard SSL cert use `*.test.crt`.

AFAIK this is all working as intended. I'm happy to help, but I'm not understanding what isn't working.

**Comment by svpernova09** [comment]
> 
> 
> Thanks for your reply!
> 
> The `dashboard.test.crt` is also a wildcard certificate for `*.dashboard.test`. That's why I only expected that. I hope this helps explain the issue and otherwise it's apparently something I misunderstand :)

Ah ha! I see. I'll have to look into this later.

**Comment by svpernova09** [comment]
This should be fixed in `master` branch now. 

Fix Issue where wildcard SSL certificates were not being named correctly.

`Homestead.yaml`:
```
sites:
    - map: foo.test
      to: /home/vagrant/foo/public_html
      wildcard: "yes"
```


```
root@homestead:/etc/nginx/ssl# openssl x509 -subject -noout -in '*.foo.test.crt'
subject=O = Vagrant, C = UN, CN = *.foo.test
root@homestead:/etc/nginx/ssl# openssl x509 -subject -noout -in foo.test.crt
subject=O = Vagrant, C = UN, CN = foo.test
root@homestead:/etc/nginx/ssl#
```
