### ISSUE TITLE
php_network_getaddresses: error

### ISSUE THREAD

**Issue by pepijndik** [laravel/homestead#1521]
## Versions
  - Vargrant 2.2.10
  - Provider: Virtualbox 6.0.1
  - Homestead:  `release` branch.

## Host operating system
Windows 10 pro

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: A:/projecten/code
      to: /home/vagrant/code
sites:
    - map: quidro.test
      to: /home/vagrant/code/quidro/public

databases:
    - quidro

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

When trying to run vagrant provision

I am getting the following error,

homestead:   [Composer\Downloader\TransportException]

    homestead:   The "https://getcomposer.org/versions" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resol
ution
    homestead:   failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
