### ISSUE TITLE
Trying to install mysql db "mydb" when disabling mysql

### ISSUE THREAD

**Issue by xoco70** [laravel/homestead#1522]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.2.10
  - Provider: Virtualbox 6.1
  - Homestead: 10.14.0

## Host operating system
Ubuntu 20.04

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code/sun-acc
      to: /home/vagrant/code

sites:
    - map: sun-acc.test
      to: /home/vagrant/code/public
      schedule: true

services:
    - enabled:
        - "postgresql@12-main"
    - stop:
        - "mysql"
    - disabled:
        - "mysql"
databases:
    - sun

features:
    - mariadb: false
    - mysql: false
    - ohmyzsh: true
    - webdriver: false
    - minio: true
    - timescaledb: true
```

homestead: ERROR
    homestead:  2002 (HY000)
    homestead: : Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

## Expected behavior
It should not try to create a MySQL DB when mysql has been disabled

## Actual behavior

When provisionning the VM, it is trying to create a DB in MySQL, but it was previously disabled, so it can't work.
