### ISSUE TITLE
vagrant up is not creating databases from Homestead.yaml

### ISSUE THREAD

**Issue by ndberg** [laravel/homestead#1528]
Thanks a lot for your help

## Versions
  - Vagrant: 2.2.10
  - Provider: Virtualbox 6.1.16
  - Homestead: 11.3.0 on osx

## Host operating system
macOS catalina 10.15.7

## Homestead.yaml
```yaml
ip: 192.168.10.23
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /Users/XXX/Code/laravel-jetstream-livewire
        to: /home/vagrant/code
sites:
    -
        map: j-l.test
        to: /home/vagrant/code/public
databases:
    - homestead
    - live
features:
    -   mariadb: false
    -   mysql8: true
    -   ohmyzsh: true
    -   webdriver: false
name: laravel-jetstream-livewire
hostname: laravel-jetstream-livewire

```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
https://gist.github.com/ndberg/a6ddd4765eb7a3a30ad7e481d2acdb0a

## Expected behavior
vm should have db homestead & live

## Actual behavior
vm does only have db homestead, has not created db live

## Steps to reproduce
1. create new laravel/homestead per-project project
2. add new database to Homestead.yaml.
3. vagrant up
