### ISSUE TITLE
Windows 10 2008 w/ HyperV doesn't mount. 

### ISSUE THREAD

**Issue by pvdochtend** [laravel/homestead#1530]
## Versions
  - Vagrant: Vagrant 2.2.10
  - Provider: Hyper-V
  - Homestead: 11.3.0

## Host operating system
Windows 10 2008 Update

## Homestead.yaml
```yaml
---
ip: "192.168.178.180"
memory: 4096
cpus: 4
provider: hyperv

authorize: c:/Users/xxxxxx/.ssh/id_rsa.pub

keys:
    - c:/Users/xxxxxx/.ssh/id_rsa

folders:
    - map: C:\Sources
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/Laravel/public

databases:
    - homestead

features:
    - mysql: false
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
Clean attempt: https://gist.github.com/pvdochtend/c0c20c742680cf62ab922ff5334c4668
Strange thing is here.. I chose for hyperv, in homestead.rb is a line that if defaulf_provider == hyperv, then smb. But that doesn't work.
When I enter type: "smb"  in my homestead.yaml under folders, it also goes to NFS...

## Expected behavior
He never mounts my local drive.
On SMB mode (in the past) he created a share but the mount from the box was no permissions.

## Actual behavior
It start VM, does some configuring, see log below. And then it stops with the message:
_No valid IDs were given to the NFS synced folder implementation to
prune. This is an internal bug with Vagrant and an issue should be
filed._

## Steps to reproduce
1. Clean install, see here script & results: https://gist.github.com/pvdochtend/594c0bd3693f695f7a031fb820ad3cc5
2. Vagrant up. (two times, the second time different result.
3. Homestead is up and running. I can ssh into it. But no folders shared so no site to be displayed

## References
I really start to doubt if this works for a Windows 10, HyperV combination.
With VMWAer i have to buy a 80 euro plugin and I have to run hyperv because of other processes (work)

I also tried it with installing vagrant-winnfsd, but the same results
