### ISSUE TITLE
MariaDB database is not created when 'mariadb: true' and 'mysql: false'

### ISSUE THREAD

**Issue by buismaarten** [laravel/homestead#1532]
## Host operating system
macOS Catalina v10.15.7

## Homestead.yaml
```yaml
ip: 192.168.10.13
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub

keys:
  - ~/.ssh/id_rsa

folders:
  - map: '..'
    to: /home/vagrant/code

sites:
  - map: project.local
    to: /home/vagrant/code/public
    php: '7.4'
    schedule: true

databases:
  - homestead

features:
  - mysql: false
  - mariadb: true
  - ohmyzsh: true
  - webdriver: false

name: project
hostname: project
```

## Vagrant destroy & up output
`(vagrant destroy -f && vagrant up) > homestead.txt` outputs: https://gist.github.com/buismaarten/e80205418e28fd4f8f10361ea607396c

## Expected behavior
The database is created and the Laravel migrations working as expected (like last week).

## Actual behavior
Yesterday I ran my Laravel migrations for the first time (inside the box of course), the following error appeared:
```
   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [1049] Unknown database 'homestead' (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667▕         // If an exception occurs when attempting to run a query, we'll format the error
    668▕         // message to include the bindings with SQL, which will make this exception a
    669▕         // lot more helpful to the developer instead of just the database's errors.
    670▕         catch (Exception $e) {
  ➜ 671▕             throw new QueryException(
    672▕                 $query, $this->prepareBindings($bindings), $e
    673▕             );
    674▕         }
    675▕ 

  • Database name seems incorrect: You're using the default database name `homestead`. This database does not exist.
    
    Edit the `.env` file and use the correct database name in the `DB_DATABASE` key. 
    https://laravel.com/docs/master/database#configuration

      +41 vendor frames 
  42  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

The database settings from `.env`:
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

When I do the following:
```
...

features:
  - mysql: true
  - mariadb: false

...
```

The database is created and the Laravel migrations run succesfully.

## Steps to reproduce
1. `vagrant up` for the first time after destroying.
2. `cd ...` to the project directory (+ Composer dependencies installed of course).
3. `php artisan migrate`

## References
- GH-1531
