### ISSUE TITLE
Question: How to enable Xdebug

### ISSUE THREAD

**Issue by ukenpachi** [laravel/homestead#1536]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.2.10
  - Provider: Virtualbox
  - Homestead: release

## Host operating system
Windows 10

## Homestead.yaml
```yaml
--- 
authorize: ~/.ssh/id_rsa.pub
cpus: 1
databases: 
  - lumen
folders: 
  - 
    map: C:\projects\umen
    to: /home/vagrant/code/api
ip: "192.168.10.10"
keys: 
  - ~/.ssh/id_rsa
memory: 2048
provider: virtualbox
sites: 
  - 
    map: lumen.local
    to: /home/vagrant/code/lumen-api/public
```

Having issues enabling xdebug 
I have done the 
`sudo nano /etc/php/7.4/fpm/conf.d/20-xdebug.ini`

``` zend_extension=/usr/lib/php/20151012/xdebug.so
xdebug.remote_autostart=1
xdebug.remote_enable = 1
xdebug.remote_connect_back = 1
xdebug.remote_port = 9000
xdebug.scream = 0
xdebug.cli_color = 1
xdebug.show_local_vars = 1
xdebug.idekey="PHPSTORM"
```
in my application did ``phpinfo();` xdebug is not enabled. 

I tried `sudo phpenmod xdebug` and then ```php -v``` and xdebug still not enabled.

I downloaded old school xampp and then in ther php.ini file, enabled xdebug and it does show. So I am thinking what am I doing wrong?
