### ISSUE TITLE
Homestead can not create postgres database

### ISSUE THREAD

**Issue by mikeslinkman** [laravel/homestead#1538]
## Versions
  - Vagrant: 2.2.10
  - Provider: Virtualbox
  - Homestead: 11.3.3

## Host operating system
Ubuntu 20.04

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects/graphql-api
      to: /home/back-ends/graphql-api

sites:
    - map: promptus.test
      to: /home/back-ends/graphql-api/public

databases:
    - homestead
    - customdatabase

features:
    - mysql: false
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
        - "postgresql@12-main"

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
https://gist.github.com/mikeslinkman/c588bcbf882b39743640732cfe90a7d6

## Expected behavior
Being able to create PostgreSQL database either by providing the database as shown in the `homestead.yaml` above or by moving into PostgreSQL and then running the command to create a database. `psql -U homestead -h localhost` followed by the next command `CREATE DATABASE customDatabase`  

## Actual behavior
What actually happened? Please include as much detail as possible.

Tried several ways to create the database in the homestead environment for me to be able to migrate my database. I've tried to add it to the `homestead.yml` file followed by the `vagrant reload --provision`. Then I've tried migrating the database and this would result in the error that my database doesn't exist. I verified that the database actually doesn't exist by moving to postgres and running the `\l` command which will list all databases. The strange thing is that the homestead mentioned in the yml is actually created. 

## Steps to reproduce
1. Freshly cloned version of homestead
2. checkout release branch
3. Adjust the homestead yml file to create a new database
4. run `vagrant reload --provision` 
5. ssh into the machine and try to migrate
6. error is displayed that indicates the database doesn't exist

## References
Are there any other (open or closed) that should be linked here?
- [Laracast discussion](https://laracasts.com/discuss/channels/laravel/homestead-can-not-create-postgres-databases)
