### ISSUE TITLE
Error when attempting to backup disabled database

### ISSUE THREAD

**Issue by BenceSzalai** [laravel/homestead#1540]
## Versions
  - Vagrant: v2.2.9
  - Provider: vagrant-parallels v2.0.1
  - Homestead: v11.3.3

## Host operating system
MacOS v10.14.6 (irrelevant)

## Homestead.yaml
```yaml
#...
databases:
  - homestead
backup: true
features:
  - mysql8: true
  - postgres: false
#...
```

## Expected behavior
Homestead should only try to backup the enabled databases.

## Actual behavior
Homestead attempts to backup both `mysql` and `postgres` without checking if they are enabled. This causes a `pg_dump: error: connection to database "homestead" failed: could not connect to server: Connection refused` error when destroying.

## Steps to reproduce
1. Add `backup: true` and `false` for one of the `mysql8` or `postgres` databses under the `features` array in `Homestead.yaml` (see example above).
2. run `vagrant destroy`
