### ISSUE TITLE
PHP < 7.3 + Mariadb: Malformed communication packet

### ISSUE THREAD

**Issue by MichaelBelgium** [laravel/homestead#1541]
I did an update of settler + homestead and I think i'm too early .. This (very recent) issue is not technicaly from Homestead but it can be prevented.

## Versions
  - Vagrant: 2.2.10
  - Provider: Virtualbox
  - Homestead: v11.3.3

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: D:\Websites\bakkerijverlinde_web
      to: /home/vagrant/bakkerijverlinde_web
    - map: D:\Websites\flarum
      to: /home/vagrant/flarum
    - map: D:\Websites\mybb
      to: /home/vagrant/mybb
    - map: D:\Websites\athenasoft
      to: /home/vagrant/athena.kisp.devel
    - map: D:\Websites\testInstance
      to: /home/vagrant/laratest
    - map: D:\Websites\something-else\website
      to: /home/vagrant/somethingelse

sites:
    - map: bakkerijverlinde.devel
      to: /home/vagrant/bakkerijverlinde_web/public
      type: "apache"
      php: "7.2"
    - map: flarum.devel
      to: /home/vagrant/flarum/public
      type: "apache"
      php: "7.2"
    - map: mybb.devel
      to: /home/vagrant/mybb
      type: "apache"
      php: "7.2"
    - map: athena.kisp.devel
      to: /home/vagrant/athena.kisp.devel/web
      type: "apache"
      php: "7.2"
    - map: laratest.devel
      to: /home/vagrant/laratest/public
      type: "apache"
      php: "7.2"
    - map: somethingelse.devel
      to: /home/vagrant/somethingelse
      type: "apache"

databases:
    - mybb
    - servermonitor
    - homestead
    - flarum
    - athena_kisp
    - laratest

features:
    - blackfire: false
    - cassandra: false
    - chronograf: false
    - couchdb: false
    - crystal: false
    - docker: false
    - elasticsearch: false
    - eventstore: false
    - gearman: false
    - golang: false
    - grafana: false
    - influxdb: false
    - mariadb: true
    - minio: false
    - mongodb: false
    - mysql8: false
    - neo4j: false
    - ohmyzsh: false
    - openresty: false
    - pm2: false
    - python: false
    - rabbitmq: false
    - rvm: false
    - solr: false
    - timescaledb: false
    - webdriver: false

backup: true
```

## Actual behavior
When mariadb is enabled and php version 7.2 (in my case) is set on a site, it's not possible to connect to the database. Mariadb errors with message `SQLSTATE[HY000]: General error: 1835 Malformed communication packet`  The mariadb version that gets installed is 10.5.7 but an update made it **incompatible with PHP < 7.3** (see references)

## Expected behavior
It should've connected to the database. Either we wait for a mariadb update or Homestead can force install version 10.5.6 instead of 10.5.7 ? Can it be fixed with a downgrade command? I know `yum` has `yum downgrade` but ubuntu has not.

## Steps to reproduce
1. Enable feature mariadb in yaml (mysql8 is false)
2. Set the php version of  a site to 7.2
3. Browse to the laravel project

## References
- [Mariadb Jira - MDEV-24121](https://jira.mariadb.org/browse/MDEV-24121?focusedCommentId=171281&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-171281)
- [Also occured at WHMCS](https://help.whmcs.com/m/troubleshooting/l/1325182-troubleshooting-a-critical-error-could-not-connect-to-the-database-error)
