### ISSUE TITLE
Unable to run when disable_cfq set to true

### ISSUE THREAD

**Issue by om4csaba** [laravel/homestead#1546]
## Versions
  - Vagrant 2.2.13
  - Provider: Virtualbox, 6.1.16 r140961 (Qt5.6.3)
  - Homestead: v11.3.3
  - Box version: 10.1.1

## Host operating system
macOS Catalina 10.15.7 (19H15)

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/bin/homestead
      to: /home/vagrant/bin
    - map: ~/dev
      to: /home/vagrant/dev

sites:
    - map: homestead.local
      to: /home/vagrant/dev/local-sites/homestead
    - map: phpmyadmin.local
      to: /home/vagrant/dev/local-sites/phpmyadmin
    - map: whmcs.local
      to: /home/vagrant/dev/whmcs
      php: "7.2"
    - map: thegreatmusician.local
      to: /home/vagrant/dev/local-sites/thegreatmusician
    - map: clonk.local
      to: /home/vagrant/dev/clonk-dashboard/public
    - map: multistore.local
      to: /home/vagrant/dev/local-sites/multistore

databases: {}

features:
    - mysql: false
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
    - postgresql: false

variables:
    - key: WP_TESTS_DIR
      value: /home/vagrant/dev/wordpress-develop/tests/phpunit
    - key: WP_DIR
      value: /home/vagrant/dev/wordpress-develop
    - key: WC_DIR
      value: /home/vagrant/dev/woocommerce
    - key: WS_DIR
      value: /home/vagrant/dev/woocommerce-subscriptions
    - key: WZ_DIR
      value: /home/vagrant/dev/woocommerce-zapier

default_ports: false
disable_cfq: true
```

## Vagrant destroy & up output
https://gist.github.com/om4csaba/a075171b00d86d6272e42ced5e6087c7

## Expected behavior
Successfully provision.

## Actual behavior
`vagrant up` fails 

## Steps to reproduce
1. checkout v11.3.3
2. add `disable_cfq: true` t the `Homesteasd.yaml`
3. run `vagrant up`

## References
none
