### ISSUE TITLE
Composer Update Fails Inside Homestead VM but not on external servers

### ISSUE THREAD

**Issue by tonyclemmey** [laravel/homestead#1549]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.7
  - Provider: Virtualbox 6.0.22
  - Homestead: 10.13.3
 -  Composer: 2.0.6

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
MacOS 10.15.6

## Homestead.yaml
```
---
ip: "192.168.10.10"
memory: 1024
cpus: 1
provider: virtualbox
ssl: true
backup: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/homestead-sites/fb-hub-v3-dev
      to: /home/vagrant/code/fb-hub-v3-dev

sites:
    - map: fb-hub-v3-dev.test
      to: /home/vagrant/code/fb-hub-v3-dev/web
      php: "7.4"
      type: "apache"

databases:
    - db

features:
    - mariadb: true
    - ohmyzsh: false
    - webdriver: false

```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
What should have happened? Please include as much detail as possible.

`vagrant ssh` > cd into a craft 3 project > run `composer update` and everything installs/updates.

## Actual behavior
What actually happened? Please include as much detail as possible.

Composer update fails, tried to clear-cache, remove lock file, composer install, bump up or change ~ and ^ versions and manually removing the directory fails on etc.

```
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 52 updates, 0 removals
  - Upgrading craftcms/plugin-installer (1.5.5 => 1.5.6): Extracting archive
Plugin initialization failed (file_get_contents(/home/vagrant/code/fb-hub-v3-dev/vendor/craftcms/plugin-installer/src//Plugin.php): failed to open stream: No such file or directory), uninstalling plugin
  - Removing craftcms/plugin-installer (1.5.6)
Update of craftcms/plugin-installer failed

[RuntimeException]
  Could not delete /home/vagrant/code/fb-hub-v3-dev/vendor/craftcms/plugin-installer/src:
```

Issues related to same problem referencing Homestead/Vagrant

https://github.com/craftcms/cms/issues/4358
https://github.com/craftcms/cms/issues/4358#issuecomment-702480899

## Steps to reproduce
1. Composer update on a Craft 3 CMS project, updating craftcms/plugin-installer 1.5.5 > 1.5.6
2.
3.

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
https://github.com/craftcms/cms/issues/4358
https://github.com/craftcms/cms/issues/4358#issuecomment-702480899
