### ISSUE TITLE
No database using MariaDB

### ISSUE THREAD

**Issue by MrReeds** [laravel/homestead#1550]
## Versions
  - Vagrant: 2.2.14 
  - Vagrant VMware utility: 1.0.17
  - Provider: VMware Workstation 16.0.0
  - Homestead: 11.3.2 
  - Vagrant Box: laravel/homestead (vmware_desktop, 10.1.1)

## Host operating system
Windows 10 Pro (Build 190401)

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 8192
cpus: 4
provider: vmware_workstation
...
ports:
    - send: 6001
      to: 6001
      
databases:
    - homestead

features:
    - mariadb: true
    - ohmyzsh: true
```

## Expected behavior
Previous releases there was homestead database by default [as defined by yaml]

## Actual behavior
On the latest release, on clean vagrant UP there is no homestead database anymore

## Steps to reproduce
1. Use mariadb feature and database homestead in yaml
2. Start the machine
3. No database
