### ISSUE TITLE
PHPRedis Extension does not install when PHP 8.0 is enabled

### ISSUE THREAD

**Issue by ajnorman-dev** [laravel/homestead#1551]
The phpredis extension for PHP 8.0 does not install during provision of the virtual machine. I've run ```vagrant destroy``` and ```vagrant up``` multiple times and the bug persists.

Note:
I'm using a slightly modified version of Homestead to add some extra features on provision such as Meilisearch and PHPDocumentor hence why some other services are listed, but nothing that changes the default provisioning behaviour.

## Versions
  - Vagrant: 2.2.14
  - Provider: Virtualbox 6.1.16
  - Homestead: 11.4.0

## Host operating system
Windows 10

## Homestead.yaml
```yaml
memory: 12288
cpus: 4

authorize: '%UserProfile%\.ssh\id_rsa.pub'

keys:
    - ~/.ssh/id_rsa

folders:
    - map: 'homestead'
      to: /home/vagrant/code
      type: 'nfs'

sites:
    - map: homestead.local
      to: /home/vagrant/code/public
      type: 'laravel'
      php: '8.0'


ip: "192.168.10.10"
provider: virtualbox
name: "homestead"
hostname: "homestead"

backup: true
databases:
    - homestead

features:
    - mariadb: true
    - meilisearch: true
    - phpdocumentor: false
    - ohmyzsh: false
    - webdriver: true

services:
    - enabled:
        - "redis-server"
        - "mailhog"
        - "nginx"
    - disabled:
        - "postgresql"

ports:
    - send: 7770
      to: 7700
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Expected behaviour
PHP Redis for PHP 8 should install

## Actual behaviour
PHP Redis does not install for PHP 8, giving a logic exception when trying to access redis with the PHP Redis extension. Image attached with the exception

## Steps to reproduce
1. Add ```php: '8.0'``` to ```sites``` configuration
2. Run ```vagrant up```
3. Run any code that's puts to or gets from the cache

## Temporary Workaround
Running ```sudo apt install php8.0-redis``` within the VM installs the required extension

![Redis extension is not installed](https://user-images.githubusercontent.com/24577267/100211994-bb14a880-2f04-11eb-8cc6-3eb741968a0e.png)
