### ISSUE TITLE
phpize and php-config binaries are not being installed

### ISSUE THREAD

**Issue by DieterHolvoet** [laravel/homestead#1556]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.14
  - Provider: Virtualbox 6.1
  - Homestead: I am on the most recent `release` branch.

## Host operating system
macOS Big Sur Version 11.0.1

## Homestead.yaml
```yaml
---
name: homestead
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox
backup: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

variables:
    - key: APP_ENV
      value: local

features:
    - mysql: false
    - mariadb: true
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
    - blackfire:
        server_id: [redacted]
        server_token: [redacted]
        client_id: [redacted]
        client_token: [redacted]
    - elasticsearch:
        version: 6

default_ports: false
ports:
    # SSH
    - send: 2222
      to: 22
    # HTTP
    - send: 8000
      to: 80
    # HTTPS
    - send: 44300
      to: 443
    # Elasticsearch
    - send: 9200
      to: 9200

folders: [redacted]
sites: [redacted]
databases: [redacted]
```

## Vagrant destroy & up output
I'd rather not, let me know if you can't reproduce the issue and I'll try.

## Expected behavior
- Files such as `/usr/bin/phpize7.3` and `/usr/bin/php-config7.3` (but for all PHP versions) should exist
- The provided functions for switching between PHP versions shouldn't error because of these missing files

## Actual behavior
The provided functions for switching between PHP versions errored.

## Steps to reproduce
1. Create a new VM using the latest `release` branch.
