### ISSUE TITLE
php 8 support breaks web server. 

### ISSUE THREAD

**Issue by CharlesBilbo** [laravel/homestead#1561]
## Versions
  - Vagrant: 2.2.10
  - Provider: Virtualbox

## Host operating system
mac os 10.15.7

## Homestead.yaml
```yaml
    - map: sandbox.test
      to: /home/vagrant/projects/sandbox/public
      php: "8.0"
```

## Expected behavior
To be able to reach the home page of a new Laravel project.

## Actual behavior
502 bad gateway
