### ISSUE TITLE
PHP Version does not change to php7.4

### ISSUE THREAD

**Issue by Drengel1990** [laravel/homestead#1564]
## Versions
  - Vagrant: 2.2.13
  - Provider: Virtualbox v6.1.16 r140961.
  - Homestead: release branch.
  - OS: MacOS Big Sur v11.0.1

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects/XXX
      to: /home/vagrant/XXX
    - map: ~/Projects/SSS
      to: /home/vagrant/SSS

sites:
    - map: xxx.test
      to: /home/vagrant/XXX/public
      php: "7.4"
    - map: sss.test
      to: /home/vagrant/SSS/public
      php: "7.4"

databases:
    - xxx
    - sss

features:
    - mysql: false
    - mariadb: false
    - postgresql: true
    - ohmyzsh: false
    - webdriver: false

name: homesteadPersonal
```
## Vagrant destroy & up output
https://gist.github.com/Drengel1990/686f66d5eeb438c199bbce586b009a90

**Comment by svpernova09** [comment]
You forgot a link to a gist of `vagrant destroy && vagrant up`

**Comment by Drengel1990** [comment]
Update

**Comment by svpernova09** [comment]
To be clear: you're saying the PHP version of the nginx website isn't being set to PHP 7.4?

I'm unable to reproduce:

```
sites:
    - map: vcdt.test
      to: /home/vagrant/vcdt/public
      php: "7.4"
```

![image](https://user-images.githubusercontent.com/967362/101060065-99df3800-3554-11eb-90f0-6bac0c8cfad4.png)

If you've run `php -v` from inside the VM and you're wondering why you're seeing:

```.sh
vagrant@homestead:~$ php -v
PHP 8.0.0 (cli) (built: Nov 27 2020 12:26:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies
vagrant@homestead:~$
```

This is because Homestead defaults to PHP 8.0 as of the 9.7.x vagrant box version.To change the CLI version of PHP you can use one of the functions found in your `aliases` file in Homestead. If you're missing the function for 8.0, you may need to update this file.
