### ISSUE TITLE
Databases not backed up on vagrant destroy

### ISSUE THREAD

**Issue by LewisCraik** [laravel/homestead#1575]
## Versions
  - Vagrant: 2.2.14
  - Provider: Virtualbox 6.1.16 r140961
  - Homestead: v9.7.2

## Host operating system
macOS 10.13.6

## Homestead.yaml
```yaml
---
ip: "192.168.50.15"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code/LaravelTest
      to: /home/vagrant/LaravelTest
    - map: ~/Code/HKTWDL
      to: /home/vagrant/HKTWDL

sites:
    - map: homestead.test
      to: /home/vagrant/LaravelTest/public
      type: "apache"
    - map: winter.hkt
      to: /home/vagrant/HKTWDL/public
      type: "apache"

databases:
    - homestead

features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

backup: true

```

## Vagrant destroy & up output
[Vagrant destroy and vagrant up log output Gist](https://gist.github.com/LewisCraik/6a1bafa7fc3df4baca2cb8ea3f3bb6de).

## Expected behavior
Database should have been backed up (it was on previous versions)

## Actual behavior
No backup of MySQL database was made to the 'mysql_backup' folder.

## Steps to reproduce
1. `vagrant destroy`

## References
Possibly linked to #1540?
