### ISSUE TITLE
vagrant ssh

### ISSUE THREAD

**Issue by ivanradojevic-web-dev** [laravel/homestead#1577]
I followed the installation process and adjusted the homestead.yml. file:
```
folders:
    - map: C:/Projects_Laravel
      to: /home/vagrant/Projects_Laravel

sites:
    - map: homestead.test
      to: /home/vagrant/Projects_Laravel/Project1/public
 ```
 but, when I try vagrant ssh and ls homestead folder I dont have folder Projects_Folder
