### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ivanradojevic-web-dev** [laravel/homestead#1587]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.2.14
  - Provider: Virtualbox, 
  - Homestead v10.17.0, v11.4.0

## Homestead.yaml

---
```
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:/Projects_Laravel
      to: /home/vagrant/Projects_Laravel    

sites:
    - map: homestead.test
      to: /home/vagrant/Projects_Laravel/Project1/public

databases:
    - homestead
    
# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Expected behavior
to install npm into project...

## Actual behavior
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/vagrant/Projects_Laravel/Project1/node_modules/babel-code-frame/node_modules/ansi-styles/package.json.2634078580
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/Projects_Laravel/Project1/node_modules/babel-code-frame/node_modules/ansi-styles/package.json.2634078580'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2021-01-03T21_50_37_309Z-debug.log
