### ISSUE TITLE
Unable to connect to postgres-12 on port 5433

### ISSUE THREAD

**Issue by JonoB** [laravel/homestead#1591]
## Versions
  - Vagrant: 2.2.14
  - Provider: Virtualbox 6.0.2 r128162
  - Homestead: Just installed most recent release (9.7.2)

## Host operating system
Ubuntu 18.04.

## Homestead.yaml
```yaml
---
ip: "192.168.10.11"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:

databases:
    - homestead

features:
    - mysql: false
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

ports:
    - send: 54321
      to: 5433

```

## Vagrant destroy & up output
https://gist.github.com/JonoB/81c6178625f4fb7b4b7a23643ecfe56c

## Expected behavior
Can't log into postgres-12, which is running on port 5433
```
vagrant@homestead:~$ pg_lsclusters
Ver Cluster Port Status Owner    Data directory               Log file
9.6 main    5436 online postgres /var/lib/postgresql/9.6/main /var/log/postgresql/postgresql-9.6-main.log
10  main    5435 online postgres /var/lib/postgresql/10/main  /var/log/postgresql/postgresql-10-main.log
11  main    5434 online postgres /var/lib/postgresql/11/main  /var/log/postgresql/postgresql-11-main.log
12  main    5433 online postgres /var/lib/postgresql/12/main  /var/log/postgresql/postgresql-12-main.log
13  main    5432 online postgres /var/lib/postgresql/13/main  /var/log/postgresql/postgresql-13-main.log
```

## Actual behavior
Connection to postgres seems fine, but password is rejected.  I'm using "secret" as the password - should the user or password be something else?
```
vagrant@homestead:~$ psql -p 5433 -U homestead -h localhost
Password for user homestead: 
psql: error: FATAL:  password authentication failed for user "homestead"
FATAL:  password authentication failed for user "homestead"
```
Note that connecting to port 5432 works fine:
```
vagrant@homestead:~$ psql -p 5432 -U homestead -h localhost
Password for user homestead: 
psql (13.1 (Ubuntu 13.1-1.pgdg18.04+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.
```

## Steps to reproduce
Run the following command: `psql -p 5433 -U homestead -h localhost`
