### ISSUE TITLE
If you follow the doc you get 2 box's and homestead does not work

### ISSUE THREAD

**Issue by rabol** [laravel/homestead#1604]
## Versions
vagrant v 2.1.4
provider:virtual box
Homestead: latest

## Host operating system
Mac OsX v11.1

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code/web
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/homestead/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp


```

## Expected behavior
What should have happened? Please include as much detail as possible.

A homestead installed and working

## Actual behavior

2 vagrant boxes downloaded laravel/ homestead v9.7.2 and v10.0.1
the homestead box is not working

What actually happened? Please include as much detail as possible.

## Steps to reproduce
I followed the documentation: https://laravel.com/docs/8.x/homestead#first-steps 
1. ```vagrant box add laravel/homestead ``` 
box v 10.0.1 was added
2. ```git clone https://github.com/laravel/homestead.git ~/Homestead ```
3. ```cd ~/Homestead ````
4. ```git checkout release````
5. ```bash init.sh````
6. Modified my shared folder
7. modified the sites
8. ```vagrant up```
this aded vagrant box 9.7.2
9. ```vagrant ssh```
10. cd code
11. ```laravel new homestead```
during execution: Skipped installation of bin bin/commonmark for package league/commonmark: file not found in package

12. ```composer require laravel/breeze --dev````
13. modify .env
14. php artisan breeze:install
15. npm install && npm run dev
result:

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/vagrant/code/homestead/node_modules/postcss-loader/node_modules/cosmiconfig/package.json.140144829
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/code/homestead/node_modules/postcss-loader/node_modules/cosmiconfig/package.json.140144829'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2021-02-01T05_36_22_536Z-debug.log

I have tried to remove the homestead 'web' and done a few ```laravel new homestead```and everytime there seems to be something 'missing' e.g. ```Skipped installation of bin bin/carbon for package nesbot/carbon: file not found in package```

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- GH-1234
- ...
