### ISSUE TITLE
Feature/Mongodb install error on branch 20.04

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1605]
## Versions
  - Vagrant: Vagrant 2.2.14
  - Provider: 6.1.18
  - Homestead: branch 20.04.

## Host operating system
Ubuntu 16.04

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/sites/homestead/public

databases:
    - homestead

features:
    - mongodb: true
```

## Vagrant destroy & up output
https://gist.github.com/ricardoseriani/7c10127844a5a8e67b2c63848fbd217a
 The vagrant up log keeps going, but the main point  is the error on mongodb install

## Expected behavior
Should install mongodb

## Actual behavior
Vagrant up is broken due to invalid mongodb ppa repository

## Steps to reproduce
1. vagrant destroy
2. config Homestead.yaml as defined
3. vagrant up
