### ISSUE TITLE
Timed out while waiting for the machine to boot

### ISSUE THREAD

**Issue by juliuscaesarnl** [laravel/homestead#1607]
## Versions
  - Vagrant: 2.2.14
  - Provider: Virtualbox 6.1.16
  - Homestead: 11.4.0
  - Box (settler): 10.1.1

## Host operating system
Windows 10 build 19042.746

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
  - ~/.ssh/id_rsa
folders:
  - map: 'C:\projects\portal'
    to: /home/vagrant/code
sites:
  - map: portal.test
    to: /home/vagrant/code/public
databases:
  - portal
features:
  - mysql: true
  - mariadb: false
  - ohmyzsh: false
  - webdriver: false
backup: false
name: portal
hostname: portal
```

## Vagrant destroy & up output
[Vagrant output](https://gist.github.com/juliuscaesarnl/a8c933b825c5165185dab259fbf5c9f8)
Note: creation of VM and first time booting always succeed.

## Expected behavior
The VM boots up without timeouts.

## Actual behavior
Almost every time, the 'vagrant up' command times out. It seems that there's some process inside the VM which is stalling the CPU on boot. What I've noticed is that booting continues as soon as I open the display output of the VM from VirtualBox. It also shows in the display output that the CPU is stalling. See the screenshot:
![image](https://user-images.githubusercontent.com/39700840/106621662-100f1380-6573-11eb-89a8-eca415f78e39.png)

Here's what I've tried so far:
- Use different versions of Vagrant down to 2.2.10
- Use different VirtualBox versions down to 6.1.12
- Clean install both Vagrant and Virtualbox
- Different versions of Homestead and Settler

On top of this, the rest of my team is also experiencing the same issue, so it's not isolated to my machine.
The issue seems to be introduced since Homestead v11.x and Settler v10.x

## Steps to reproduce
1. Execute 'vagrant up'
2. Wait until the VM boots up

## References
None
