### ISSUE TITLE
 Outdated MongoDB GPG key

### ISSUE THREAD

**Issue by lostsnow** [laravel/homestead#1613]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.14
  - Provider: Virtualbox 6.1.18
  - Homestead: 20.04

## Host operating system

Win 10

## Homestead.yaml
```yaml
---
ip: "172.22.22.10"
memory: 2048
cpus: 2
provider: virtualbox
box: laravel/homestead
version: 11.0.0

backup: true

hostname: leah
name: leah

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "f:/projects"
      to: /home/vagrant/projects
      type: nfs

databases:
    - test

features:
    - docker: true
    - golang: true
    - mongodb: true
    - mysql: true
    - python: true
    - webdriver: true

services:
    - disabled:
        - "postgresql"
        - "memcached"
        - "beanstalkd"
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior

Install mongodb successfully

## Actual behavior

```
GPG error: https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4B7C549A058F8B6B
```
