### ISSUE TITLE
lmm status - Volume group "mysql" not found

### ISSUE THREAD

**Issue by BenceSzalai** [laravel/homestead#1618]
## Versions
  - Vagrant: v2.2.14
  - Provider: Parallels v13.3.1
  - Homestead: v12.0.0

## Host operating system
macOS v10.14.6 - Mojave

## Homestead.yaml
The issue can be reproduced with the default `Homestead.yaml` (only change is the provider to `parallels`):
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: parallels

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/test
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
```

## Vagrant destroy & up output
[GitHub Gist](https://gist.github.com/BenceSzalai/e45f8ba6bcbb392dcdc70ee8f9cc5a14)

## Expected behavior
No issue when using `sudo lmm status` command.

## Actual behavior
```
vagrant@homestead:~$ sudo lmm status
Active snapshot: /homestead-vg/master

Database snapshots:
  mysql-master
  root        
  swap_1      
  Volume group "mysql" not found
  Cannot process volume group mysql

% used by MySQL databases.
(standard_in) 1: syntax error
/opt/lmm/functions.sh: line 48: [: -eq: unary operator expected
```

## Steps to reproduce
1. SSH into the box: `ssh vagrant`
2. Run this command: `sudo lmm status`

## References
- Similar issue was reported here: https://github.com/laravel/homestead/issues/1112

## Note
There is a message in the `vagrant up` output: `homestead: Invalid feature: mysql`, but that is not supposed to be related. The issue is the same even if I completely remove the `features` section from `Homestead.yaml`.
