### ISSUE TITLE
HyperV Version of Release 11.0?

### ISSUE THREAD

**Issue by alexhackney** [laravel/homestead#1621]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
Vagrant 2.2.14

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 4
provider: hyperv
ssl: true

authorize: C:\Users\Alex\.ssh\id_rsa.pub

keys:
    - C:\Users\Alex\.ssh\id_rsa

folders:
    - map: C:\dev\code
      to: /home/vagrant/code
      smb_username: vagrant
      smb_password: vagrant


sites:
    - map: website.wip
      to: /home/vagrant/code/website/public

databases:
    - website
features:
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
    - postgres: true

ports:
    - send: 54320
      to: 5432
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
```
c:\dev>vagrant destroy
==> homestead: VM not created. Moving on...
```
## Expected behavior
Should have an option for Hyper-V

## Actual behavior
What actually happened? Please include as much detail as possible.
Does not

## Steps to reproduce
1. Install Windows 10
2. Install Vagrant
3. Install Homestead
4. VMUP

## References

I know the provider for Hyper-V is not in the box release and I understand that's why its not there. Maybe there arent many of use using Hyper-V but from what I can tell, I cant have VirtualBox and Docker running at the same time but I can have vagrant and docker running if I use hyper-v. 

I was able to set the box to the older version by adding
```
version: 10.1.1
```

To my Homestead.yaml file, so I'm sure that's fine for now. I'm not doing anything on PHP8 so it's not a big deal. Would appreciate the hyper-v provider at some point with Homestead.

Really appreciate the work you're doing!
