### ISSUE TITLE
Kernel panic - not syncing: corrupted stack end detected inside scheduler

### ISSUE THREAD

**Issue by legendarydrew** [laravel/homestead#1622]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.14
  - Provider: Virtualbox 6.1.16 r140961 (Qt5.6.2)
  - Homestead: `release` branch

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.30.10"
memory: 4096
cpus: 1
provider: virtualbox

authorize: C:\Users\Drew\.ssh\id_ed25519.pub

keys:
    - C:\Users\Drew\.ssh\id_ed25519

folders:
    - map: C:\Users\Drew\Documents\Projects\swapfig-1
      to: /home/vagrant/code/swapfig-1
      php: "7.3"
    - map: C:\Users\Drew\Documents\Projects\smtv
      to: /home/vagrant/code/smtv
      php: "7.3"

sites:
    - map: swapfig.local
      to: /home/vagrant/code/swapfig-1/public
    - map: smtv.local
      to: /home/vagrant/code/smtv/public

databases:
    - smtv
    - smtv_test
    - swapfig
    - swapfig_test

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
https://gist.github.com/legendarydrew/063376ce52e0c3ed5ebcd233ce83e71a

## Expected behaviour
VM should start as usual.

## Actual behaviour
VM starts with an error, not apparent until viewing in VirtualBox. It is inaccessible via ssh.
`Kernel panic - not syncing: corrupted stack end detected inside scheduler`
![Screenshot - 23_02_2021 , 12_54_21](https://user-images.githubusercontent.com/168335/108846331-5b4a9e00-75d6-11eb-98e8-f0bf35c60c31.png)

## Steps to reproduce
1. Removed existing virtual machines and images.
2. From the Homestead directory, `vagrant up`.
3. After the error message, opened VirtualBox to see the output.
