### ISSUE TITLE
Homestead VM freezes randomly

### ISSUE THREAD

**Issue by petcumihai** [laravel/homestead#1624]
## Versions
  - Vagrant: Vagrant 2.2.14
  - Provider: Virtualbox 6.1.16 r140961 (Qt5.6.3)
  - Homestead: release branch 

## Host operating system
macOS Big Sur 11.2.1 (20D74)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 4
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /Users/user/Projects/one
      to: /home/vagrant/one
    - map: /Users/user/Projects/two
      to: /home/vagrant/two
sites:
    - map: one.local.com
      to: /home/vagrant/one/public
      php: "7.4"
    - map: two.local.com
      to: /home/vagrant/two/public
      php: "7.1"
databases:
    - one
    - two
features:
    - mysql: true
    - rabbitmq: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

ports:
    - send: 80
      to: 80
    - send: 3306
      to: 3306
    - send: 15672
      to: 15672
```

## Vagrant destroy & up output
https://gist.github.com/petcumihai/0276d8ed753c7938e850cfd766bfe612

## Expected behavior
Don't freeze

## Actual behavior
It freezes randomly. I gradually increased the VM's resources (CPU and RAM) and it still froze. 
At first I thought it was related to RabbitMQ but it happens with the service turned off as well.

I manage to do everything I need (SSH into the machine, run the app, develop, etc) but for no reason it freezes to the point I have to forcefully remove the VM and recreate the box. 
I'm not able to figure out any pattern or trigger for this behaviour. It freezes for no apparent reason.

## Steps to reproduce
Just wait I guess
