### ISSUE TITLE
In Homeastead.yaml, mysql is assigned false

### ISSUE THREAD

**Issue by barobba** [laravel/homestead#1625]
I am using the per project installation.

Everything works, but I am confused why the YAML file has **mysql** assigned to **false**, but I am still able to use MySQL in the virtual machine. (Which is good, just confusing. It makes me question how to use the **features** keyword.)

## Versions
  - Vagrant: Vagrant 2.2.14
  - Provider: Virtualbox
  - Homestead: Whatever composer installs

## Host operating system
MacOS

## Homestead.yaml
```yaml
features:
    -
        mysql: false
    -
        mariadb: false
    -
        postgresql: false
    -
        ohmyzsh: false
    -
        webdriver: false
```

## Expected behavior
I would expect the Homstead.yaml file to omit **mysql** or assign it to **true**.

## Actual behavior
From the Homestead.yaml file **mysql** is assigned to **false**.

## Steps to reproduce
Run: composer require laravel/homestead --dev
Then inspect the Homestead.yaml file

## References
(none)
