### ISSUE TITLE
Problems with MinIO

### ISSUE THREAD

**Issue by EvilLooney** [laravel/homestead#1632]
## Versions
  - Vagrant: Vagrant 2.2.14
  - Provider: Virtualbox 6.1.18
  - Homestead: 12.1.1

## Host operating system
MacOS 11.2.3

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code/test-minio
      to: /home/vagrant/Code/test-minio

sites:
    - map: homestead.test
      to: /home/vagrant/Code/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
    - minio: true

buckets:
    - name: test-minio
      policy: public
```

## Vagrant destroy & up output
[https://gist.github.com/EvilLooney/6dd70172b1505f94d2ed494290f5c139](url)

## Expected behavior
Laravel can manipulate "s3" files with MinIO.

## Actual behavior
I cannot my the life of me understand why the `S3Client` is having problems connecting to my MinIO bucket. I have installed a fresh install of Laravel as well as a fresh Homestead box following the docs. I can access the MinIO control panel and upload files through there. If I use the `Storage` facade or even directly using the `S3Client`, I will always get this output when trying to upload a file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>BadRequest</Code>
  <Message>An error occurred when parsing the HTTP request PUT at &#39;/&#39;</Message>
  <Resource>/</Resource>
  <RequestId></RequestId>
  <HostId>c3000035-d453-4b47-a685-cbb98929cc6d</HostId>
</Error>
```

If I upload the file through the control panel, `Storage::cloud()->files()` will always return an empty array but if I use the MinIO client, I can see the files (ie. `mc tree /usr/local/share/minio`).

## Steps to reproduce
1. Create a fresh Laravel project (`laravel new test-minio`)
2. Add `league/flysystem-aws-s3-v3 ~1.0` to composer.
3. Change config/filesystems s3 entry to: ```'s3' => [
    'driver' => 's3',
    'key' => env('AWS_ACCESS_KEY_ID'),
    'secret' => env('AWS_SECRET_ACCESS_KEY'),
    'region' => env('AWS_DEFAULT_REGION'),
    'bucket' => env('AWS_BUCKET'),
    'endpoint' => env('AWS_URL'),
    'use_path_style_endpoint' => true,
]```
4. Add entries to `.env` file : ```
AWS_ACCESS_KEY_ID=homestead
AWS_SECRET_ACCESS_KEY=secretkey
AWS_DEFAULT_REGION=us-east-1
AWS_URL=http://localhost:9600```
5. Try adding a test file through artisan: `Storage::cloud()->put('text.txt', 'test');`

## References
None found
