### ISSUE TITLE
Was the "Wildcard SSL" section intentionally removed from the Homestead documentation page?

### ISSUE THREAD

**Issue by JackWH** [laravel/homestead#1634]
I had a problem setting up Wildcard SSL certificates, so went to the Laravel 8.x docs to check how to do it correctly. I noticed the Wildcard SSL section had been removed. I assume this was unintentional?

It looks like it was removed in https://github.com/laravel/docs/commit/0ab96f0b7c55966f5402b99e37268a0e9dacd03e#diff-8d4ec4caf613bdaf02fe6e0d001023ebcb5b95fa9ec18412f4f205e9c02cb72cL488 

---

FWIW, my existing `Homestead.yaml` file was configured like this...

```yaml
sites:
    - map: '*.mysite.test'
      to: /home/vagrant/mysite/public
      wildcard: "yes"
      use_wildcard: "yes"
      php: "8.0"
    - map: '*.myothersite.test'
      to: /home/vagrant/myothersite/public
      wildcard: "yes"
      use_wildcard: "yes"
      php: "8.0"
```

After upgrading to Homestead 12.1.2, the `*.mysite.test` format I was previously using seems to no longer be valid. It was also cause path mapping issues, when I visited `mysite.test` it would load the code from `myothersite.test`.

I've been using that format in my Homestead YAML file for years, so I'm not sure when I first set it up like that — but in case anybody else has issues and finds this through Google, the solution is to change `*.mysite.test` to simply `mysite.test`.
