### ISSUE TITLE
Feature Request: Add site-types/proxy support to wsl

### ISSUE THREAD

**Issue by litan1106** [laravel/homestead#1638]
## Versions
  - Provider: Ubuntu 20.04 WSL2
  - Homestead: `release`

## Host operating system
Windows 10 Pro

## Homestead.yaml
```yaml
sites:
    - map: laravel-octane.test # Create proxy for Laravel Octane
      to: http://127.0.0.1:8000
      type: proxy
```

Atm, the WslCreateSiteCommand.php only serve laravel site-type as default.
https://github.com/laravel/homestead/blob/main/src/WslCreateSiteCommand.php#L83
![image](https://user-images.githubusercontent.com/1310539/113779126-1429ef80-96e2-11eb-8d48-d0ee98902eb7.png)
