### ISSUE TITLE
Errors and unable to load sites after Homestead update

### ISSUE THREAD

**Issue by ligne13** [laravel/homestead#1641]
## Versions
  - Vagrant: Vagrant 2.2.15
  - Provider: Virtualbox 6.1.18
  - Homestead: 12.2.0

## Host operating system
Mac OS 11.2.3

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Documents/Work/_Sites/CMCP/www
      to: /home/vagrant/code/CMCP/www

sites:
    - map: www.cmcp.test
      to: /home/vagrant/code/CMCP/www/htdocs

databases:
    - cmcp

backup: true
```

## Expected behavior & Actual behavior
I have updated vagrant, virtualbox, and homestead to their latest versions. My hosts file is OK :
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

## vagrant-hostmanager-start id: 93536df9-fadb-4ed0-8e7c-2ad3d8081b90
192.168.10.10	www.cmcp.test
## vagrant-hostmanager-end
```

Though, I cannot reach any of my sites in the browser. It says ERR_CONNECTION_REFUSED.

I have reloaded with --provision, restarted my Mac. Still the same ERR_CONNECTION_REFUSED... always...

Please help !
