### ISSUE TITLE
homestead: Package 'libssl1.0-dev' has no installation candidate

### ISSUE THREAD

**Issue by didotsonev** [laravel/homestead#1647]
## Versions
  - Vagrant: 2.2.16
  - Provider: Virtualbox
  - Homestead: latest

## Host operating system
Debian 10

## Homestead.yaml
```yaml
ip: "192.168.111.10"
memory: 2048
cpus: 2
provider: virtualbox
mariadb: true
folders:
    - map: ~/dev
      to: /home/vagrant/code
      type: "nfs"

sites:
    - map: test.laravel
      to: /home/vagrant/code/laravel/public
      php: "8.0"

databases:
    - laravel_dev

features:
    - mysql: true
```

## Vagrant destroy & up output
https://gist.github.com/didotsonev/cfed7de4c67ea9a3e2d1ff9cd6a1d872

## Expected behavior
To build the machine without errors

## Actual behavior
Homestead failed to install `libssl1.0-dev`

If I try to install it manually I get (as the response):

```bash
vagrant@homestead:~$ sudo apt-get install libssl1.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl1.0-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0-dev' has no installation candidate
```

It's managable to install it if you first remove `libssl-dev` but this removes other packages and breaks some functionalities
```bash
sudo apt-get remove libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libpcre2-16-0 libpcre2-32-0 libpcre2-dev libpcre2-posix2 php-json pkg-config pkg-php-tools shtool
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  libssl-dev php-dev php5.6-dev php7.0-dev php7.1-dev php7.2-dev php7.3-dev php7.4-dev php8.0-dev
```

## Steps to reproduce
- vagrant up / provision
