### ISSUE TITLE
`gsub': invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by darrel15** [laravel/homestead#1648]
## Versions
  - Vagrant: 2.2.16
  - Provider: Virtualbox
  - Homestead: release

## Host operating system
  - Windows 10 Pro

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: D:/ssh/ssh_key.ppk

keys:
    - D:/ssh/ssh_key

folders:
    - map: D:/Projects
      to: /home/vagrant/code

sites:
    - map: project.local
      to: /home/vagrant/code/my-project/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
https://gist.github.com/darrel15/5863e834dba8f347cd7d4c2d538758d6

## Expected behavior
It should provision the site based on my Homestead.yaml

## Actual behavior
Getting gsub invalid byte sequence and destroying the container afterwards

## Steps to reproduce
1. Download and install Virtualbox-6.1.22 
2. Download and install Vagrant 2.2.6
3. Clone the latest release of homestead
4. vagrant up
