### ISSUE TITLE
Memcached not installed in 11.1.0

### ISSUE THREAD

**Issue by iblank** [laravel/homestead#1650]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.16
  - Provider: Virtualbox
  - Homestead: release branch
  - Virtualbox: 6.1.22

## Host operating system
Mac 10.14.6

## Homestead.yaml
```yaml
---
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

cpus: 1
php: "7.3"

folders:
    - map: ~/Documents/core
      to: /home/vagrant/Documents/core

ip: "192.168.10.10"
keys:
    - ~/.ssh/id_rsa

memory: 2048
sites:
    - map: sample.site.test
      to: /home/vagrant/Documents/core/sample/public
      php: "7.3"
      
variables:
    - key: APP_ENV
      value: local
```

## Vagrant destroy & up output
https://gist.github.com/iblank/edd734fef09c6eec71543351e228cfbc (shows 11.0.0 output, which is nearly same as 11.1.0 output... don't want to destroy database solely for this issue output)

## Expected behavior
Should install Memcached by default, as stated in the documentation. 

## Actual behavior
Memcached not installed properly

## Steps to reproduce
1. Run site with CACHE_DRIVER=memcached in homestead 11.0.0
2. Upgrade to homestead 11.1.0
3. Class 'Memcached' not found errors, running site

## References
N/A
