### ISSUE TITLE
Cannot create the VM on fedora 34

### ISSUE THREAD

**Issue by kevinpita** [laravel/homestead#1651]
## Versions
  - Vagrant: 2.2.9
  - Provider: 6.1.22
  - Homestead: 12.2.0

## Host operating system
Fedora 34 Gnome Wayland - Linux fedora 5.11.18-300.fc34.x86_64 #1 SMP Mon May 3 15:10:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
https://gist.github.com/kevinpita/aa431eed6265e8ed9c93239b4fe20d2c

## Expected behavior
To work

## Actual behavior
It creates the VM but destroys it within seconds

## Steps to reproduce
1. Clone the repo
2. checkout to release and run init.sh
3. vagrant up
