### ISSUE TITLE
php 7.4 and opcache (Settler 11.2.0)

### ISSUE THREAD

**Issue by piotr-cz** [laravel/homestead#1652]
## Versions
  - Vagrant: 2.2.16
  - Provider: Virtualbox
  - Homestead: 12.2.0, Settler 11.2.0

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: d:/localhost
      to: /home/vagrant/localhost

sites:
    - map: localhost
      to: /home/vagrant/localhost
      type: apache
      php: "7.4"

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
Applications running on php 7.4 should work fine

## Actual behavior
There is a problem when running php applications which use `require` or `require_once` more than 2x:

```
Fatal error: Uncaught Error: Call to undefined method ComposerAutoloaderInitc75ac39ffcf63d5de1cfd976cd853be2::getLoader() in /home/vagrant/localhost/vendor/autoload.php:12
--
Stack trace:
#0 /home/vagrant/localhost/config/bootstrap.php(30): require()
#1 /home/vagrant/localhost/public/index.php(21): require('/home/vagrant/l...')
#2 {main}
thrown in /home/vagrant/localhost/vendor/autoload.php on line 12
```

- Error appears on php 7.4, specific version 7.4.18 (and does not on 7.3 and 8.0); I wasn't able to downgrade to 7.4.3
- Error disappears for one time after restarting php fpm (`sudo systemctl restart php7.4-fpm.service`)
- Error does not appear when disabling opcache (`ini_set('opcache.enable', '0');` in front controller
- Error does not appear when resetting opcache (`opcache_reset`) in front controller
- I haven't changed default opcache settings

I upgraded from homestead v10.17.0 (settler 9.7.2), and issue doesn't appeared there on php 7.4

## Steps to reproduce
1. Create site with php 7.4
2. Start application which uses `require` or `require_once` like application with composer managed dependencies
3. See error

## References
none
