### ISSUE TITLE
MariaDB cannot be installed

### ISSUE THREAD

**Issue by Olray** [laravel/homestead#1656]
## Versions
  - Vagrant: 2.2.16
  - Box: laravel/homestead v11.3.0
  - Provider: Parallels 16.1.2
  - Homestead: 12.2.0
  - Settler: v11.3.0

## Host operating system
MacOS 10.15.7 "Catalina"

## Homestead.yaml
```
ip: 192.168.10.11
memory: 2048
cpus: 2
provider: parallels
name: bertha-dudde
hostname: bertha
version: '~> 11'
backup: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /Users/sakura/Documents/Projekte/Bertha/www
      to: /home/vagrant/code

    - map: /Users/sakura/Documents/Projekte/Bertha/dl
      to: /home/vagrant/dl

sites:
    - map: www.bertha-dudde.local
      to: /home/vagrant/code/public
      php: "8.0"
      type: apache

    - map: dl.bertha-dudde.local
      to: /home/vagrant/dl
      type: apache

databases:
    - bertha_www

features:
    - mariadb: true
```

## Vagrant destroy & up output
https://gist.github.com/Olray/1d7b7fa561d8e0dc0f190ef65b95ba95

## Actual behavior
The script laravel/homestead/scripts/features/mariadb fails due to a missing configuration file being targeted by a sed command after the package `00-mariadb-server-10.5_1%3a10.5.10+maria~focal_amd64.deb` fails to install
```
    bertha-dudde: Errors were encountered while processing:
    bertha-dudde:  /tmp/apt-dpkg-install-xQxR8W/00-mariadb-server-10.5_1%3a10.5.10+maria~focal_amd64.deb
    bertha-dudde: E: Sub-process /usr/bin/dpkg returned an error code (1)
    bertha-dudde: sed: can't read /etc/mysql/mariadb.conf.d/50-server.cnf: No such file or directory
```
The reason __might__ be an unreliable package repository. Happened before with bintray.com.

## Expected behavior
MariaDB should be installed

## Steps to reproduce
1. Add `features: \n  - mariadb: true` to Homestead.yaml
2. vagrant up

## Solution
Just omit `features: \n - mariadb:true` or set it to false will prevent the script from running. Server is using the preinstalled Mysql 8 instead. However, I decided to use MariaDB because my production server is using MariaDB as well and I would like to keep the development VM as close to the production server as possible.
I'm using Homestead to code Symfony apps but that shouldn't cause any issues provisioning the VM because `vagrant up` is agnostic to the type of app developed.
