### ISSUE TITLE
Backup not created when using MySQL 8

### ISSUE THREAD

**Issue by Olray** [laravel/homestead#1657]
## Versions
  - Vagrant: 2.2.16
  - Box: laravel/homestead v11.3.0
  - Provider: Parallels 16.1.2
  - Homestead: 12.2.0
  - Settler: v11.3.0

## Host operating system
MacOS 10.15.7 "Catalina"

## Homestead.yaml
```
ip: 192.168.10.11
memory: 2048
cpus: 2
provider: parallels
name: bertha-dudde
hostname: bertha
version: '~> 11'
backup: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /Users/sakura/Documents/Projekte/Bertha/www
      to: /home/vagrant/code

    - map: /Users/sakura/Documents/Projekte/Bertha/dl
      to: /home/vagrant/dl

sites:
    - map: www.bertha-dudde.local
      to: /home/vagrant/code/public
      php: "8.0"
      type: apache

    - map: dl.bertha-dudde.local
      to: /home/vagrant/dl
      type: apache

databases:
    - bertha_www

#features:
#
```

## Vagrant destroy & up output
not applicable

## Actual behavior
When using the default MySQL 8 install from the laravel/homestead box the setup "backup: true" is ignored, causing the database to _not_ being backed up on `vagrant destroy`. Reason: in ./scripts/Homestead.rb around line 610 you check for the features "mysql" "mariadb" or "postgres" but since Mysql is preinstalled in the box there is no feature script for Mysql. It should be added to the documentation that, in order to use the backup feature for Mysql, you have to add `features: \n - mysql` to your Homestead.yaml even if there is no feature script. OR do the following to make it work:

I understand this to mean that Mariadb and Mysql are alternative, as MariaDB is a drop-in replacement for Mysql, but Postgresql may still be installed as an alternative, second data source.

I saw Ruby for the first time today, so I apologise if I have syntax errors in my proposal. Also, I don't work with Git so I can't start a "pull request". So I apologise for the trouble.

In this case, I would like to make the suggestion to make the following change in the Homestead.rb from line 630. The backup should then also take place if both "mysql" and "mariadb" are not included in the list of features.
```
      backup_mysql_anyways = (! enabled_databases.include? 'mysql') && (! enabled_databases.include? 'mariadb')
      # Loop over each DB
      settings['databases'].each do |database|
        # Backup MySQL/MariaDB
        if (enabled_databases.include? 'mysql') || (enabled_databases.include? 'mariadb') || backup_mysql_anyways
          Homestead.backup_mysql(database, "#{dir_prefix}/mysql_backup", config)
        end
```
And in function mysql_backup around line 655 you have to add the credentials for your development database:
```
      trigger.run_remote = {inline: "mkdir -p #{dir}/#{now} && mysqldump -u homestead --password=secret --routines #{database} > #{dir}/#{database}-#{now}.sql"}
```

After adding/changing these three lines the database is backed up even when no database feature is configured explicitely:
```
% vagrant destroy
==> bertha-dudde: Running action triggers before destroy ...
==> bertha-dudde: Running trigger...
==> bertha-dudde: Backing up mysql database dudde_www...
    bertha-dudde: Running: inline script
    bertha-dudde: mysqldump: 
    bertha-dudde: [Warning] Using a password on the command line interface can be insecure.
    bertha-dudde: Are you sure you want to destroy the 'bertha-dudde' VM? [y/N] y
==> bertha-dudde: Forcing shutdown of VM...
==> bertha-dudde: Clearing any previously set forwarded ports...
==> bertha-dudde: Destroying VM and associated drives...
==> bertha-dudde: Destroying unused networking interface...
```

## Expected behavior
Mysql (default) Database should be backed up on vagrant destroy and placed into ./mysql_backup/

## Steps to reproduce
1. Omit any database feature in features: section of Homestead.yaml
2. vagrant up
3. vagrant destroy

## I hope this saved you a little time. Great tool by the way! :)

I wouldn't bother with these reports if I wasn't absolutely convinced about Homestead.
