### ISSUE TITLE
Folder being deleted while provisioning

### ISSUE THREAD

**Issue by archansel** [laravel/homestead#1665]
## Versions
  - Vagrant: 2.2.9
  - Provider: Virtualbox 6.1.16
  - Homestead: 11.3.0

## Host operating system
MacOS

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Desktop/Repositories
      to: /home/vagrant/Repositories

sites:
    - map: rekreasi.test
      to: "/home/vagrant/Repositories/Projects/Rekreasi App"

databases:
    - rekreasi

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
Nothing wrong here

## Expected behavior
When provisioning, homestead should not delete user folder

## Actual behavior
Notice that I point my site to "Rekreasi App" folder, in my finder I also have "Rekreasi" folder alongside it, so the structure looks like this
```
> Projects
>>> Rekreasi
>>> Rekreasi App
>>> ....many other folders
```
When you run `vagrant up --provision`, the folder "Rekreasi" will be deleted

## Steps to reproduce
1. Set up site with whitespace in its path
2. Run provision
3. Some folder will be deleted

**Comment by svpernova09** [comment]
You forgot to include a link to the gist showing the full output of `vagrant destroy`, `vagrant up`.

**Comment by svpernova09** [comment]
https://laravel.com/docs/8.x/homestead#configuring-shared-folders

> You should always map individual applications to their own folder mapping instead of mapping a single large directory that contains all of your applications. When you map a folder, the virtual machine must keep track of all disk IO for every file in the folder. You may experience reduced performance if you have a large number of files in a folder

Your configuration:

```
folders:
    - map: ~/Desktop/Repositories
      to: /home/vagrant/Repositories

sites:
    - map: rekreasi.test
      to: "/home/vagrant/Repositories/Projects/Rekreasi App"
```


Should become:

```
folders:
    - map: ~/Desktop/Repositories/Projects/Rekreasi App"
      to: /home/vagrant/rekreasi_app

sites:
    - map: rekreasi.test
      to: "/home/vagrant/rekreasi_app/public"
```

Make the above changes, then `vagrant destroy` and then `vagrant up`. If the issue persists please post a gist to the full log of the destroy and up commands.
