### ISSUE TITLE
Upgrading SQLite to 3.36 for math functions

### ISSUE THREAD

**Issue by cariboufute** [laravel/homestead#1666]
Is it possible to upgrade SQLite version of Laravel Homestead to latest version, 3.36? The major improvements between 3.31 (Homestead version) and 3.36 are the addition of math functions (like sin, cos, etc.).

I tried to upgrade it with `apt`, but it stayed at 3.31. I manually installed it into my Homestead box with the SQLite download : https://www.sqlite.org/draft/download.html. I downloaded the files and installed `sqlite` file into `/etc/bin/`. The version was reading 3.36, but when running PHPUnit tests with SQLite, I was still having errors of unknown functions for `cos` and `acos`.

How can I upgrade SQLite myself in Homestead then?

## Versions
  - Vagrant: 2.2.16
  - Provider: Virtualbox  6.1.22 r144080
  - Homestead: latest release branch

## Host operating system
Mac OS 11.4

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
php: "8.0"

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    -   map: ~/Sites/FredericChiasson8
        to: /home/vagrant/code/FredericChiasson8
    -   map: ~/Sites/FredericChiasson
        to: /home/vagrant/code/FredericChiasson
    -   map: ~/Sites/CaribouFute
        to: /home/vagrant/code/CaribouFute
    -   map: ~/Sites/AtoutFrance
        to: /home/vagrant/code/AtoutFrance
    -   map: ~/Sites/MarcAndrePepin
        to: /home/vagrant/code/MarcAndrePepin
    -   map: ~/Sites/LocaleRoute
        to: /home/vagrant/code/LocaleRoute
    -   map: ~/Sites/LocaleRouteExample
        to: /home/vagrant/code/LocaleRouteExample
    -   map: ~/Sites/passport-minette
        to: /home/vagrant/code/passport-minette
    -   map: ~/Sites/passport-minou
        to: /home/vagrant/code/passport-minou
    -   map: ~/Sites/Agrienergie
        to: /home/vagrant/code/Agrienergie
    -   map: ~/Sites/Agrienergie-test-js
        to: /home/vagrant/code/Agrienergie-test-js
    -   map: ~/Sites/october-vue
        to: /home/vagrant/code/october-vue
    -   map: ~/Sites/diagnostic-marketing
        to: /home/vagrant/code/diagnostic-marketing
    -   map: ~/Sites/dudesnude-webchat
        to: /home/vagrant/code/dudesnude-webchat
    -   map: ~/Sites/dn2
        to: /home/vagrant/code/dn2
    -   map: ~/Sites/agmq
        to: /home/vagrant/code/agmq
    -   map: ~/Sites/acsg
        to: /home/vagrant/code/acsg
    -   map: ~/Sites/eventmanager
        to: /home/vagrant/code/eventmanager
    -   map: ~/Sites/Form-ARTM
        to: /home/vagrant/code/Form-ARTM
    -   map: ~/Sites/FredericChiassonVieux
        to: /home/vagrant/code/FredericChiassonVieux
    -   map: ~/Sites/volpe
        to: /home/vagrant/code/volpe

sites:
    -   map: fredericchiasson8.test
        to: /home/vagrant/code/FredericChiasson8/public
    -   map: fredericchiasson.test
        to: /home/vagrant/code/FredericChiasson/public
    -   map: cariboufute.test
        to: /home/vagrant/code/CaribouFute/public
    -   map: atout-france.test
        to: /home/vagrant/code/AtoutFrance/public
    -   map: marcandrepepin.test
        to: /home/vagrant/code/MarcAndrePepin/public
    -   map: locale-route.test
        to: /home/vagrant/code/LocaleRouteExample/public
    -   map: minette.test
        to: /home/vagrant/code/passport-minette/public
    -   map: minou.test
        to: /home/vagrant/code/passport-minou/public
    -   map: agrienergie.test
        to: /home/vagrant/code/Agrienergie
    -   map: agrienergie-test-js.test
        to: /home/vagrant/code/Agrienergie-test-js
    -   map: october-vue.test
        to: /home/vagrant/code/october-vue
    -   map: diagnostic-marketing.test
        to: /home/vagrant/code/diagnostic-marketing/public
    -   map: dudesnude.test
        to: /home/vagrant/code/dudesnude-webchat
    -   map: dn2.test
        to: /home/vagrant/code/dn2/public
    -   map: agmq.test
        to: /home/vagrant/code/agmq/public
        type: symfony4
    -   map: membre.agmq.test
        to: /home/vagrant/code/agmq/public
        type: symfony4
    -   map: gestion.agmq.test
        to: /home/vagrant/code/agmq/public
        type: symfony4
    -   map: acsg.test
        to: /home/vagrant/code/acsg/public
        type: symfony4
        php: "7.3"
    -   map: gestion.acsg.test
        to: /home/vagrant/code/acsg/public
        type: symfony4
        php: "7.3"
    -   map: eventmanager.test
        to: /home/vagrant/code/eventmanager/public
        type: symfony4
        php: "7.3"
    -   map: form-artm.test
        to: /home/vagrant/code/Form-ARTM/public
    -   map: fred-vieux.test
        to: /home/vagrant/code/FredericChiassonVieux
        php: "5.5"
    -   map: volpe.test
        to: /home/vagrant/code/volpe/public

databases:
    - frederi_site
    - fredericchiasson8
    - fredericchiasson
    - atout_france
    - cariboufute
    - marcandrepepin
    - minette
    - minou
    - october-vue
    - diagnostic-marketing
    - dn2
    - agmq
    - acsg
    - eventmanager
    - form-artm
    - volpe

features:
    -   mysql: false
    -   mariadb: true
    -   postgresql: false
    -   ohmyzsh: false
    -   webdriver: false

#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
https://gist.github.com/cariboufute/af17e872e0f4e5e285d06410dce56737
