### ISSUE TITLE
backup property not work

### ISSUE THREAD

**Issue by chan15** [laravel/homestead#1668]
## Versions
  - Vagrant: 2.2.16
  - Provider: Virtualbox
  - Homestead: 1a13308406079cc4585a00ad6eb2711d840ea03c

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox

authorize: C:/Users/schan/.ssh/id_rsa.pub

keys:
  - C:/Users/schan/.ssh/id_rsa

folders:
    - map: d:/projects
      to: /home/vagrant/code
      type: nfs

sites:
    - map: chan.local
      to: /home/vagrant/code/chan/public
      php: "7.4"

databases:
    - homestead

backup: true

features:
    - mysql: false
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
    - xdebug: true

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

https://laravel.com/docs/8.x/homestead#database-backups homestead mentioned need to install `vagrant-triggers` for database backup，but after I install it got:

```
WARNING: Vagrant has detected the `vagrant-triggers` plugin. This plugin conflicts
with the internal triggers implementation. Please uninstall the `vagrant-triggers`
plugin and run the command again if you wish to use the core trigger feature. To
uninstall the plugin, run the command shown below:
```

and backup seems not work when not install that plugin

**Comment by svpernova09** [comment]
>To utilize this feature, you must be using Vagrant 2.1.0 or greater. Or, if you are using an older version of Vagrant, you must install the vagrant-triggers plug-in.

You're using Vagrant `Vagrant: 2.2.16` which is higher than "Vagrant 2.1.0" So you do *not* need the `vagrant-triggers` plugin. 

Most importantly you're trying to use the Database Backup feature without having any databases enabled in your `features:`

```
features:
    - mysql: false
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
    - xdebug: true
```

(Also: `xdebug` is not currently a valid official feature)

Enable whichever database you need and try again. Does the issue persist? Show me the new logs/configs
