### ISSUE TITLE
Brand new Homestead installation fails to respond to ssh after first ssh into machine

### ISSUE THREAD

**Issue by Steve-MP** [laravel/homestead#1669]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Run `vagrant -v` to show the version.
  - Provider: Virtualbox, VMWare, Hyper-V, or Parallels and its version.
  - Homestead: You should be on the most recent `release` branch.

Vagrant 2.2.16
Virtualbox 6.1
Homestead release branch (as per the date of this post)

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

Latest versions of Vagrant, Virtualbox and Homestead installed today.

## Host operating system
This is the operating system that you run locally.

OSX 10.14.6

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects/my_project/
      to: /home/vagrant/code/my_project

sites:
    - map: my.project
      to: /home/vagrant/code/my_project/public
      php: "7.4"

databases:
    - my_database

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

variables:
    - key: APP_ENV
      value: local
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

https://gist.github.com/Steve-MP/264782b08c705a5179b29d32b449703c

## Expected behavior
Upon performing a standard installation of Homestead and after SSHing into the VM, it should be possible to restart the VM  successfully or to halt and start the VM without an indefinite loop of authentication failure.

## Actual behavior
If I have never SSHed into the VM with the vagrant ssh command, the VM can be rebooted or stopped/started without any problem. However, after the first `vagrant ssh` into the machine, attempting to stop the machine produces the following error:

```bash
==> homestead: Attempting graceful shutdown of VM...
    homestead: Guest communication could not be established! This is usually because
    homestead: SSH is not running, the authentication information was changed,
    homestead: or some other networking issue. Vagrant will force halt, if
    homestead: capable.
```

and attempting to start the machine hangs indefinitely on this error:

```bash
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
    homestead: Warning: Authentication failure. Retrying...
```

## Steps to reproduce
1. Run the following commands:
```bash
vagrant box add laravel/homestead
git clone https://github.com/laravel/homestead.git ~/Homestead
cd ~/Homestead
git checkout release
bash init.sh
# see Homestead.yaml file above
vagrant up
```
2. After installation, note that running `vagrant reload` succeeds
3. `vagrant ssh` - note that ssh succeeds
4. `exit` to exit from Homestead box
5. `vagrant reload` note error message:
```bash
    homestead: Guest communication could not be established! This is usually because
    homestead: SSH is not running, the authentication information was changed,
    homestead: or some other networking issue. Vagrant will force halt, if
    homestead: capable.
```
6. As the machine restarts, note the failure to boot, with the following error message running indefinitely:
```
    homestead: Warning: Authentication failure. Retrying...
```
7. Note that manual `vagrant ssh` is successful
