### ISSUE TITLE
"wrong number of arguments error" when trying to specify a default PHP version in Homestead.yaml

### ISSUE THREAD

**Issue by ChrisExP** [laravel/homestead#1674]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.16
  - Provider: Virtualbox 6.1.22
  - Homestead: The most recent `releases` branch

## Host operating system
MacOS Big Sur 11.4

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_ed25519.pub

keys:
    - ~/.ssh/id_ed25519

folders:
    - map: ~/Code/Sites
      to: /home/vagrant/code
      type: "nfs"

php: 7.4

sites:
    - map: site.test
      to: /home/vagrant/code/site/public
      php: "7.4"

databases:
    - homestead

backup: true

features:
    - elasticsearch: true

services:
    - disabled:
        - "postgresql"
        - "memcached"
        - "php5.6-fpm"
        - "php7.0-fpm"
        - "php7.1-fpm"
        - "php7.2-fpm"
        - "php8.0-fpm"

ports:
    - send: 3310
      to: 3310
    - send: 5601
      to: 5601
    - send: 9200
      to: 9200
```

## Vagrant destroy & up output
https://gist.github.com/ChrisExP/41afceecece172ed9e714ecbd4092c30

## Expected behavior
It is an undocumented feature but in the `homestead.rb` script there is a section that allows someone to specify the default PHP version. I was using that and it worked up until about a week ago.

## Actual behavior
After I pulled the latest code from the `release` branch of Homestead it showed the linked error when provisioning my machine.  
When I remove the first argument from the specified line it works fine.

## Steps to reproduce
1. Follow the install instructions for Homestead
2. Add `php: 7.4` to the `Homestead.yaml` file
3. Run `vagrant provision`
