### ISSUE TITLE
MySQL & Homestead SSL

### ISSUE THREAD

**Issue by clarknelson** [laravel/homestead#1676]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.16
  - Provider: Virtualbox 6.1.18
  - Homestead: 11.3.0

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
This is the operating system that you run locally.
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox
ssl: true
backup: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:/Users/clark/Websites
      to: /home/vagrant/Websites

sites:
    - map: clarknelson.test
      to: /home/vagrant/Websites/clarknelson.com/web
      php: "7.2"

databases:
    - clarknelson

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: true
    - webdriver: false

services:
    - enabled:
        - "mysql"
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.
https://gist.github.com/clarknelson/5a40dce3796a8ff83be464bb278eddb6

## Expected behavior
What should have happened? Please include as much detail as possible.

I am trying to connect to the MySQL database on my Vagrant machine via the command line on my host machine `mysql -u homestead -psecret --port=33060` 

The output looks something like `ERROR 2026 (HY000): SSL connection error: unknown error number` not very helpful. There aren't really any logs in the host mysql files. See the Gist for logs from my vagrant mysql logs.

This worked until I enabled SSL, I image that is the issue. I am also running MySQL 8.0 on my host machine and 5.7 on the vagrant machine, but like I said this worked before. 

I will probably need to hook up the MySQL setting with the SSL certificate information but I'm also confused in that regard. There are the certs in /etc/ssl/ but there are also some certs in the MySQL folder. Some tutorials recommend generating certs but I don't believe that in necessary with Homestead.

Thank you for your assistance!

## Actual behavior
What actually happened? Please include as much detail as possible.

## Steps to reproduce
1. Windows machine, latest versions, 
2. connect to MySQL using 33060 port and SSL enabled
