### ISSUE TITLE
Logical MySQL Manager feature is broken

### ISSUE THREAD

**Issue by DieterHolvoet** [laravel/homestead#1677]
## Versions
  - Vagrant: 2.2.15
  - Provider: Virtualbox 6.1.22 r144080
  - Homestead: the most recent `release` branch.

## Host operating system
macOS Big Sur 11.2.3 (20D91)

## Homestead.yaml
```yaml
---
name: homestead
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox
backup: true
force_ssl: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

variables:
    - key: APP_ENV
      value: local

features:
    - elasticsearch: 
        version: 5.6.16
    - mysql: false
    - mariadb: true
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
    - blackfire: {...redacted...}

default_ports: false
ports:
    # SSH
    - send: 2222
      to: 22
    # HTTP
    - send: 8000
      to: 80
    # HTTPS
    - send: 44300
      to: 443
    # Elasticsearch
    - send: 9200
      to: 9200
    # Xdebug
    - send: 9003
      to: 9003

folders: {...redacted...}
databases: {...redacted...}
```

## Expected behavior
[Logical MySQL Manager](https://github.com/Lullabot/lmm) works as expected

## Actual behavior
```bash
vagrant@homestead:~$ sudo lmm status
Active snapshot:

Database snapshots:
  mysql-master
  root
  swap_1
  Volume group "mysql" not found
  Cannot process volume group mysql

% used by MySQL databases.
(standard_in) 1: syntax error
/opt/lmm/functions.sh: line 48: [: -eq: unary operator expected
```

```bash
vagrant@homestead:~$ sudo lmm checkout mysql-master
is the currently active database.
Setting /homestead-vg/mysql-master as the active database.
rm: cannot remove '/var/lib/mysql': Is a directory
ln: failed to create symbolic link '/var/lib/mysql/mysql-master': File exists
```

## Steps to reproduce
Run the commands above.

## References
- I suspect some lmm related code was commented out in this commit: https://github.com/laravel/homestead/commit/f5eca184db55879ecd8f233b4d5a25e76f0121f9
- This issue is similar to https://github.com/laravel/homestead/issues/1383
