### ISSUE TITLE
Vagrant up command not working after update to windows 11

### ISSUE THREAD

**Issue by Shadowalker125** [laravel/homestead#1679]
## Versions
  - Vagrant: 2.2.18
  - Provider: Virtualbox 6.1
  - Homestead: 11.3.0

## Host operating system
Windows 11

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: g:/homesteadprojects
      to: /home/vagrant/code

sites:
    - map: whir.local
      to: /home/vagrant/code/whir/public

databases:
    - homestead

features:
    - mysql: true
    - docker: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
https://gist.github.com/Shadowalker125/7257401d16d7e457aa6f10516aec47de

## Expected behavior
Vagrant to create new VM after update.

## Actual behavior
Vagrant fails with command `startvm`

## Steps to reproduce
1. vagrant destroy
2. vagrant up
