### ISSUE TITLE
Error when creating new Homestead box

### ISSUE THREAD

**Issue by buismaarten** [laravel/homestead#1680]
## Versions
  - Vagrant: `Vagrant 2.2.14`
  - Provider: Virtualbox
  - Homestead: v12.4 (per project installation)

## Host operating system
MacOS Big Sur v11.5.2

## Homestead.yaml
```yaml
ip: 192.168.0.101
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
php: '8.0'

keys:
  - ~/.ssh/id_rsa

folders:
  - map: ..
    to: /home/vagrant/code

sites:
  - map: project.local
    to: /home/vagrant/code/public
    php: '8.0'

databases:
  - project

features:
  - mysql: false
  - mariadb: true
  - postgresql: false
  - ohmyzsh: true
  - webdriver: false

name: homestead-project
hostname: homestead-project

```

## Vagrant destroy & up output
https://gist.github.com/buismaarten/8f8d2e10ddc1ae99a157bf24d5a0c615

## Expected behavior
Successful provisioning Homestead box.

## Actual behavior
Receiving the following error:
```
...

    homestead-project: E
    homestead-project: : 
    homestead-project: Failed to fetch https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/InRelease  403  Forbidden [IP: 52.40.65.167 443]
    homestead-project: E
    homestead-project: : 
    homestead-project: The repository 'https://dl.bintray.com/rabbitmq-erlang/debian bionic InRelease' is no longer signed.
    homestead-project: E
    homestead-project: : 
    homestead-project: Failed to fetch https://dl.bintray.com/rabbitmq/debian/dists/bionic/InRelease  403  Forbidden [IP: 52.40.65.167 443]
    homestead-project: E
    homestead-project: : 
    homestead-project: The repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' is no longer signed.
    homestead-project: W
    homestead-project: : 
    homestead-project: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://cli-assets.heroku.com/apt ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6DB5542C356545CF
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Steps to reproduce
1. `vagrant destroy`
2. Update to version 12.4 (per project installation)
3. `vagrant up`
