### ISSUE TITLE
Mysql is reported as an invalid feature

### ISSUE THREAD

**Issue by michaeldzjap** [laravel/homestead#1681]
## Versions
  - Vagrant: 2.2.18
  - Provider: Virtualbox 6.1
  - Homestead: 12.4.0

## Host operating system
macOS Big Sur

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public
    - ...

databases:
    - homestead
    - ...

backup: true

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: true

services:
    - enabled:
        - mysql
        - supervisor
        - redis-server
```

## Vagrant destroy & up output
https://gist.github.com/michaeldzjap/ade37c2e233a5b5f7637d5a4a0c0d2f9

## Expected behavior
I would expect the output of `vagrant up` not complaining about the `mysql` feature to be invalid.

## Actual behavior
Homestead marks the feature `mysql` as invalid. As such, I removed it from there and only kept it specified under my enabled services. Since I have backup set to `true` I would have expected my databases to be backed up when executing `vagrant destroy`, but unfortunately this isn't the case, resulting in unexpected data loss.

## Steps to reproduce
1. Remove `mysql` from features to get rid of the "Invalid feature" warning
2. Ensure backup is set to `true` in Homestead.yaml
3. Run `vagrant destroy`

## References
- GH-1668
