### ISSUE TITLE
Old php-fpms don't autostart in new homestead

### ISSUE THREAD

**Issue by serg-madency** [laravel/homestead#1682]
## Versions
  - Vagrant: 2.2.18.
  - Provider: Virtualbox 6.1.26.
  - Homestead: 12.4.0.

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
backup: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: e:/code
      to: /home/vagrant/code

sites:
    - map: project1.test
      to: /home/vagrant/code/project1/web
    - map: project2.test
      to: /home/vagrant/code/project2/web
      php: "7.3"

databases:
    - project1
    - project2

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
    
#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 3306 # MySQL/MariaDB
#      to: 33060
#    - send: 4040
#      to: 4040
#    - send: 5432 # PostgreSQL
#      to: 54320
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017
```

## Expected behavior
project2.test should run on php 7.3

## Actual behavior
502 gateway error, because php7.3-fpm autostart is disabled

## Steps to reproduce
1.Install latest homestead
2.Add one project with old php, like 7.3
3.Try to launch it in browser
