### ISSUE TITLE
MariaDB not being installed

### ISSUE THREAD

**Issue by kevmul0929** [laravel/homestead#1683]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: v2.2.18
  - Provider: Virtualbox v6.1.26
  - Homestead: release branch (v12.4.0).

## Host operating system
Windows 10 64-bit 19043.1165

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
ssl: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: code/www
      to: /home/vagrant/code

sites:
    - map: my-project.test
      to: /home/vagrant/code/my-project/public

databases:
    - my-project

features:
    - mariadb: true
    - mysql: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
```

## Vagrant destroy & up output
Here is the [Vagrant Output](https://gist.github.com/kevmul0929/525d20f51192b59e8ede9b8d60426919)

## Expected behavior
Being able to access the Maria/Mysql server. 
Being able to `php artisan migrate`

## Actual behavior
What actually happened? Please include as much detail as possible.

## Steps to reproduce
1. Install fresh VirtualBox
2. Install fresh Vagrant
3. Clone fresh Homestead
4. CD into Homestead and run `bash init.sh` (to initialize Homestead)
5. Add `mariadb:true` to Homestead.yml file
6. Run `vagrant up` from Homestead directory

## References
I think these issues are similar
- GH-1438
- GH-1382

**Comment by svpernova09** [comment]
Looks like it was caused by apt missing some packages: https://gist.github.com/kevmul0929/525d20f51192b59e8ede9b8d60426919#file-vagrant-destroy-vagrant-up-output-L321

**Comment by kevmul0929** [comment]
Excuse my ignorance with this. I am not a server admin.

What do I need to do to fix this? Is it something I have to pull in manually, or is there a package in Homestead that needs to be updated?

**Comment by svpernova09** [comment]
I believe you may just need to try it again, as it might have been caused by a hiccup on your local network. What that error means is the package manager reached out to the internet to install a package and didn't find it, or errored trying to access the expected URL.

**Comment by kevmul0929** [comment]
Thank you.

I have just re-ran `vagrant destroy && vagrant up` Here is my output
[Output](https://gist.github.com/kevmul0929/c62aa267f198da7206c5a6cdf1585cbe)

**Comment by svpernova09** [comment]
^^ That's a different issue. Looks like Virtualbox just didn't boot the VM properly. control/command + c to quit then `vagrant destroy` then `vagrant up`

**Comment by kevmul0929** [comment]
Ah, sorry. Here is a new `vagrant destroy && vagrant up`
(was rushing around on my end)
[Here](https://gist.github.com/kevmul0929/c62aa267f198da7206c5a6cdf1585cbe) is the updated Gist

**Comment by kevmul0929** [comment]
Just as a quick follow up. When powering down the server `vagrant halt` and trying to launch again `vagrant up` I get this:
```
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Checking if box 'laravel/homestead' version '11.4.0' is up to date...
==> homestead: Clearing any previously set forwarded ports...
==> homestead: Clearing any previously set network interfaces...
==> homestead: Preparing network interfaces based on configuration...
    homestead: Adapter 1: nat
    homestead: Adapter 2: hostonly
==> homestead: Forwarding ports...
    homestead: 80 (guest) => 8000 (host) (adapter 1)
    homestead: 443 (guest) => 44300 (host) (adapter 1)
    homestead: 22 (guest) => 2222 (host) (adapter 1)
==> homestead: Running 'pre-boot' VM customizations...
==> homestead: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "f801be3c-7b05-4bcc-9b86-8ba3bb827534", "--type", "headless"]

Stderr: VBoxManage.exe: error: The VM session was closed before any attempt to power it on
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface ISession
```

**Comment by svpernova09** [comment]
Run `vagrant destroy` and answer yes to the prompt to destroy the VM. Then open Virtualbox and if there is any VMs there right-click and remove/delete and confirm you want to delete all files. Then run `vagrant global-status` and ensure there are no virtual machines listed there. Then reboot. When the machine comes back up run `vagrant up`

**Comment by kevmul0929** [comment]
Hey @svpernova09,
I tried what you suggested. It did not work. 

I noticed that the `release` branch was updated yesterday, so I pulled that, but still no joy. 

I then tried to checkout a tag `git checkout v12.3.2` (I don't know if that is the correct way to checkout a tag though...) and this still didn't work. I saw this worked for someone in [StackOverflow](https://stackoverflow.com/questions/67319605/vagarant-homestead-does-not-create-database-unless)

Tomorrow I am going to try to download an older version of Virtual box, and/or Vagrant. I will let you know if that works or not.

**Comment by kevmul0929** [comment]
Quick update. 

I have uninstalled everything and deleted all files that refer to Vagrant and Virtual box. I have uninstalled Homestead as well. This pc should be essentially a clean setup for installing all these. 

I restarted the PC after uninstalling.

Restarted, installed everything fresh. All up-to-date.

Restarted again, just to be sure.

Ran `vagrant up` and everything seems to work. Vagrant boots, I can ssh into it. Everything is running. But the MariaDB is still not accessable.  And typing `mysql` from within the vagrant machine I get `-bash: mysql: command not found`

Here is the latest [Gist](https://gist.github.com/kevmul0929/0ed675ce1dbcdf2dc45d808dce758485) that shows the output from the vagrant up.

It does say something about the PID for mairadb and mysqld couldn't be found.
```
homestead: We didn't find a PID for mysqld, skipping $DB creation
homestead: We didn't find a PID for mariadb, skipping $DB creation
```

And as a final note on this, all of this works flawlessly on my laptop, and it used to work just fine on the current PC I am attempting to install this on again.

**Comment by svpernova09** [comment]
Tested this again and it's still working here.


- Windows 10 21H2 19044.1200
- Virtualbox Version 6.1.26 r145957 (Qt5.6.2
- Vagrant 2.2.16
- Homestead release branch f425fdbc96d2daa354d784a4c036ccd7eb8b223c
- Homestead base box 11.4.0

`Homestead.yaml`:

```
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:\Users\halo\Code\fresh-laravel
      to: /home/vagrant/laravel

sites:
    - map: laravel.test
      to: /home/vagrant/laravel/public

databases:
    - homestead

features:
    - mysql: false
    - mariadb: true
```

`vagrant up` output: https://gist.github.com/svpernova09/e140167d7ee2f0e2e78adcaf6f85b576

![image](https://user-images.githubusercontent.com/967362/130546778-8d89d24d-f9e9-4d15-b7d2-76031015d91d.png)
