### ISSUE TITLE
Vagrant up failed by upgrade process

### ISSUE THREAD

**Issue by chan15** [laravel/homestead#1688]
## Versions
  - Vagrant: 2.2.18
  - Provider: Virtualbox 6.1.26
  - Homestead: relesase f425fdbc96d2daa354d784a4c036ccd7eb8b223c
  - Vagrant box: laravel/homestead (virtualbox, 11.0.0)

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox
version: 11.0.0

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: d:/projects

sites:
    - map: project.local
      to: /home/vagrant/code/project/public
      php: "7.4"


databases:
    - project

backup: true

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

When vagrant up I get:

```
    homestead: Reading package lists...
    homestead: W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://cli-assets.heroku.com/apt ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6DB5542C356545CF
    homestead: E: Failed to fetch https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/InRelease  403  Forbidden [IP: 54.148.26.147 443]
    homestead: E: The repository 'https://dl.bintray.com/rabbitmq-erlang/debian bionic InRelease' is no longer signed.
    homestead: E: Failed to fetch https://dl.bintray.com/rabbitmq/debian/dists/bionic/InRelease  403  Forbidden [IP: 54.148.26.147 443]
    homestead: E: The repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' is no longer signed.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
```

scrips break here therefore the rest stuffs not work.
