### ISSUE TITLE
Unable to connect to Homestead database (Protocol mismatch; server version = 11, client version = 10)

### ISSUE THREAD

**Issue by gamerboy** [laravel/homestead#1689]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.18.
  - Provider: Virtualbox 6.1
  - Homestead: 11.4.0

## Host operating system
Windows 10 Pro 20H2, build 19042.1165

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 3306 # MySQL/MariaDB
#      to: 33060
#    - send: 4040
#      to: 4040
#    - send: 5432 # PostgreSQL
#      to: 54320
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017

```

## Vagrant destroy & up output
* [Vagrant up](https://gist.github.com/gamerboy/fda0b96670dca5c03648c874719f0abe)

## Expected behavior
Connect to Homestead database using Table Plus or any MySQL client (Navicat, HeidiSQL).

## Actual behavior
If I try to connect to database from Windows, using **127.0.0.1** and port **33060** (official documentation) I get this error message:

`Can't connect to MySQL server on '127.0.0.1' (10061)`

If i try to connect configuring also an SSH tunnel with:

* Server: 192.168.10.10 
* Port: 22
* User: vagrant
* Password: vagrant

I get this message:

`Protocol mismatch; server version = 11, client version = 10`

Everything was fine before Homestead box update (I was using an old 9.x version).
Any help?

Thank you.

**Comment by svpernova09** [comment]
In your ports section, update/add this:

```
ports:
   - send: 33060 # MySQL/MariaDB
     to: 3306
```

Note: in your commented-out the ports are flipped, they should be:

```
#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017
```

So to enable access to MySQL you'd want:

```
ports:
   - send: 33060 # MySQL/MariaDB
     to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017
```
