### ISSUE TITLE
Why does my VirtualBox image take up so much space?

### ISSUE THREAD

**Issue by DieterHolvoet** [laravel/homestead#1695]
## Versions
  - Vagrant: 2.2.17
  - Provider: Virtualbox 6.1.26 r145957
  - Homestead: You should be on the most recent `release` branch. 

## Host operating system
macos 11.2.3

## Homestead.yaml
```yaml
name: homestead
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox
backup: true
force_ssl: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

variables:
    - key: APP_ENV
      value: local

features:
    - elasticsearch: 
        version: 5.6.16
    - mysql: false
    - mariadb: true
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
    - blackfire: {...redacted...}

default_ports: false
ports:
    # SSH
    - send: 2222
      to: 22
    # HTTP
    - send: 8000
      to: 80
    # HTTPS
    - send: 44300
      to: 443
    # Elasticsearch
    - send: 9200
      to: 9200
    # Xdebug
    - send: 9003
      to: 9003

folders:
- map: /System/Volumes/Data/Users/dieter/Projects/sites
      to: /home/vagrant/sites
      type: nfs

    - map: /System/Volumes/Data/Users/dieter/.CMVolumes/backups
      to: /home/vagrant/backups
      type: virtualbox

databases: {...redacted...}
```

## Vagrant destroy & up output
/

## Expected behavior
/

## Actual behavior
When checking inside the VM, all files except from the mounted folders take up 8.9 GB. When I look at the VirtualBox interface, it says that the virtual size is 512GB and the actual size is 40GB. 

Does the image grow together with the shared folders or is it a coincidence that my shared folders are around 39GB in size and my image is around 40GB?

## Steps to reproduce
/

## References
/
