### ISSUE TITLE
Mounting fails on virtualbox 6.1.26

### ISSUE THREAD

**Issue by bastien-phi** [laravel/homestead#1698]
## Versions
  - Vagrant: 2.2.18
  - Provider: Virtualbox 6.1.26 / vagrant vbguest 0.30.0
  - Homestead: 12.5.0 (box 11.4.0)

## Host operating system
Ubuntu 20.04

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 4096
cpus: 4
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
  - ~/.ssh/id_rsa
folders:
  - map: /home/philippe/dev/obbo-erp/api
    to: /home/vagrant/code
sites:
  - map: api.obbo-erp.local
    to: /home/vagrant/code/public
databases:
  - homestead
services:
  - enabled:
      - "postgresql@13-main"
  - disabled:
      - "beanstalkd"
      - "memcached"
      - "mysql"
features:
  - minio: true
buckets:
  - name: obbo-bucket
    policy: public
name: api.obbo-erp
hostname: api.obbo-erp.local
```

## Vagrant destroy & up output
https://gist.github.com/bastien-phi/4a9adb4fb59d1a35a59b6205d03c1b4e

## Expected behavior
The vagrant is up, provisionned and folders are mounted.

## Actual behavior
Folder is not mounted and `vagrant up` fails

## Steps to reproduce
Nothing more than to have specified setup

## Workaround
Even if `vagrant up` fails, it is still possible to run `vagrant provision` with a custom shell provision
```rb
    config.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y linux-headers-generic linux-headers-5.4.0-81-generic
      /sbin/rcvboxadd setup
    SHELL
```

and then `vagrant reload` finally works and folders are correctly mounted.
