### ISSUE TITLE
Homestead starts without mounted folder

### ISSUE THREAD

**Issue by inwoker** [laravel/homestead#1704]
## Versions
  - Vagrant: 2.2.18
  - Provider: Virtualbox(tried version 6.1.20 through 6.1.26)
  - Homestead: 12.5.0

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
backup: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: e:/code
      to: /home/vagrant/code

sites:
    - map: project.test
      to: /home/vagrant/code/project/public

databases:
    - project

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017

```

## Vagrant destroy & up output
https://gist.github.com/inwoker/72261409c8abe4d7e30f1c6d0ee326fa

## Expected behavior
Vagrant started with folder code mounted

## Actual behavior
Vagrant starts without folder code mounted

## Steps to reproduce
1. Install everything of the latest versions
2. vagrant up
