### ISSUE TITLE
Problem in vagrant up with MariaDB

### ISSUE THREAD

**Issue by MrJmpl3** [laravel/homestead#1705]
## Versions
  - Vagrant: 2.2.18
  - Provider: Virtualbox
  - Homestead: 12.6.0

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: "D:\\Documentos\\+MrJmpl3\\Proyectos\\Desarrollados\\laravel\\homestead\\ssh\\id_rsa.pub"

keys:
    - "D:\\Documentos\\+MrJmpl3\\Proyectos\\Desarrollados\\laravel\\homestead\\ssh\\id_rsa"

folders:
    - map: "D:\\Documentos\\+MrJmpl3\\Proyectos\\Desarrollados\\glen-soft\\wip--nuxtjs--frontend-recave-see-multi-company"
      to: /home/vagrant/glen-soft/nuxtjs--frontend-recave-see-multi-company
      
    - map: "D:\\Documentos\\+MrJmpl3\\Proyectos\\Desarrollados\\glen-soft\\wip--laravel--backend-recave-see-multi-company"
      to: /home/vagrant/glen-soft/laravel--backend-recave-see-multi-company
      
sites:      
    - map: recave-see-multi-company.test
      to: 3000
      type: proxy
      
    - map: api.recave-see-multi-company.test
      to: /home/vagrant/glen-soft/laravel--backend-recave-see-multi-company/public
      php: "8.0"
      
databases:
    - consultas-sunat
    - recave-see-single-company
    - recave-see-multi-company

features:
    - mysql: false
    - mariadb: true
    - postgresql: false
    - ohmyzsh: true
    - webdriver: false

#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

ports:
    - send: 33060 # MySQL/MariaDB
      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017
```

## Vagrant destroy & up output
https://gist.github.com/MrJmpl3/7a74f7bb74a2eb120601070ac522328c

## Expected behavior
MariaDB 

## Actual behavior
MariaDB has error in the configuration, I think the problem is the command https://github.com/laravel/homestead/blob/release/scripts/features/mariadb.sh#L50, because that command override the default configuration

## Steps to reproduce
Only run vagrant up
