### ISSUE TITLE
The repository 'https://deb.nodesource.com/node_14.x focal Release' no longer has a Release file.

### ISSUE THREAD

**Issue by lloricode** [laravel/homestead#1707]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.18
  - Provider: Virtualbox, 6.1.26 r145957
  - Homestead: release branch with tag v12.6

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
 linux mint 20.2 Cinnamon

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
#version: 11.3.0

authorize: ~/.ssh/id_rsa.pub

keys:
  - ~/.ssh/id_rsa
 folders:
  # tool
  - map: /xxxx/phpmyadmin
    to: /home/vagrant/code/tools/phpmyadmin
  sites:
  # tools
  - map: db.test
    to: /home/vagrant/code/tools/phpmyadmin
databases:
  #test
  - laravel
  
features:
  - mysql: true
  - mariadb: false
  - postgresql: false
  - ohmyzsh: false
  - webdriver: true
```

## Vagrant destroy & up output
containing the complete output of `vagrant destroy && vagrant up`.
https://gist.github.com/lloricode/85ec916c94e369a5107b0fed0357cb95

## Expected behavior
What should have happened? Please include as much detail as possible.

should work as normal

## Actual behavior

stop with result 
```
   homestead: E: The repository 'https://deb.nodesource.com/node_14.x focal Release' no longer has a Release file.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
````

## Steps to reproduce
1. homestead destroy
2. homestead up
