### ISSUE TITLE
Python Django installation duplicate

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1708]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.2.18
  - Provider: 6.1.26
  - Homestead:  v12.6.1

## Host operating system
Ubuntu 16.04

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/sites/homestead/public

databases:
    - homestead

features:
    - python: true
```

## Vagrant destroy & up output
[vagrant up](https://gist.github.com/ricardoseriani/4d059db765ee2622ede219b893acea64)

## Expected behavior
Should only install django using pip (or only install it using venv if the user require that package).

## Actual behavior
Install django using pip and using apt.

## Steps to reproduce
1. vagrant destroy
2. config Homestead.yaml as defined
3. vagrant up
