### ISSUE TITLE
NFS failed to mount after windows update on 03-10-2021

### ISSUE THREAD

**Issue by ukenpachi** [laravel/homestead#1709]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
 Vagrant 2.2.18

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: D:\Working\projects\lumen
      to: /home/vagrant/code/lumen-api
      type: "nfs"
      
sites:
    - map: lumen-api.local
      to: /home/vagrant/code/lumen-api/public
      schedule: true

databases:
    - homestead
    - lumen-api

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
    - backup: true
```

## Actual behavior
```
==> homestead: Preparing to edit nfs mounting file.
[NFS] Status: halted
[NFS] Start: started
==> homestead: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mount -o vers=3,udp,actimeo=1,nolock 192.168.10.1:/D/Working/projects/lumen /home/vagrant/code/lumen-api
Stdout from the command:
Stderr from the command:
mount.nfs: Connection timed out
```

## Steps to reproduce
1. Update to latest windows 10 version
2. if error can not reproduce git pull latest homestead version and install latest Oracle VM and vagrant
- ...

Please note that the last time everything was working fine was on Friday 1st October 2021. I did a windows update on 03-10-2021
