### ISSUE TITLE
Docker and docker-compose is already installed on homestead base (settler)

### ISSUE THREAD

**Issue by ricardoseriani** [laravel/homestead#1715]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.2.18
  - Provider: 6.1.26
  - Homestead:  v12.7.1

## Host operating system
Ubuntu 20.04

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/sites/homestead/public

databases:
    - homestead
```

## Vagrant destroy & up output
[vagrant up](https://gist.github.com/ricardoseriani/1d2fee24b623e864bfcd7e7c66ced011)

## Expected behavior
Should not contain docker and docker-compose, since it's not listed in homestead.yaml.

## Actual behavior
Already has docker and docker-compose, because homestead base image (settler) already installed it.

## Steps to reproduce
1. vagrant destroy
2. config Homestead.yaml as defined
3. vagrant up
