### ISSUE TITLE
Update macOS monterey (12.0.1) return an issue while run vargent up

### ISSUE THREAD

**Issue by xerk** [laravel/homestead#1724]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: `Vagrant 2.2.16`
  - Provider: Virtualbox 6.1.28.
  - macOS: 12 Monterey
  - Homestead: `release` branch.

## Host operating system
This is the operating system that you run locally.

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code/Laravel
      to: /home/vagrant/code

sites:
    - map: prooflo.test
      to: /home/vagrant/code/prooflo/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017
```

## Vagrant destroy & up output
https://gist.github.com/xerk/1fb1a15f0930eae8e1967cc87b403737

## Expected behavior
Homestead was working on macOS 11 after I update to the new macOS 12 it returns the issue above.

## Actual behavior
When the update is finished I try to run `vargent up` and it returns the issue above and I tried to remove homestead and `VirtualBox VMs` then I installed everything steps by step but It returns the same issue.
