### ISSUE TITLE
The repository 'https://dlm.mariadb.com/repo/mariadb-server/10.6/repo/ubuntu focal Release' does not have a Release file.

### ISSUE THREAD

**Issue by tonyclemmey** [laravel/homestead#1730]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.2.19
  - Provider: Virtualbox 6.1.28r147628
  - Homestead: release branch with tag v12.8.0.

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
macOS Big Sur 11.6.1

## Homestead.yaml
```
features:
    - mysql: false
    - mariadb: true
    - postgresql: true
    - ohmyzsh: false
    - webdriver: false
    
services:
    - enabled:
          - "mariadb"
          - "postgresql"
#    - disabled:
#        - "postgresql@11-main"
```

## Vagrant destroy & up output
```
    homestead: Ign:11 https://dlm.mariadb.com/repo/mariadb-server/10.6/repo/ubuntu focal InRelease
    homestead: Hit:12 https://downloads.mariadb.com/MaxScale/6.1.4/apt focal InRelease
    homestead: Err:13 https://dlm.mariadb.com/repo/mariadb-server/10.6/repo/ubuntu focal Release
    homestead:   404  Not Found [IP: 104.17.191.14 443]
    homestead: Reading package lists...
    homestead: E: The repository 'https://dlm.mariadb.com/repo/mariadb-server/10.6/repo/ubuntu focal Release' does not have a Release file.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Expected behavior
To work

## Actual behavior
Output 

```
homestead: E: The repository 'https://dlm.mariadb.com/repo/mariadb-server/10.6/repo/ubuntu focal Release' does not have a Release file.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Steps to reproduce
1. homestead destroy
2. homestead up
