### ISSUE TITLE
apt update fails on hash checksums

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/homestead#1731]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.2.10
  - Provider: Virtualbox 6.1.14
  - Homestead: v12.8.0

## Host operating system
Windows 10 Pro

## Homestead.yaml
```yaml
ip: 192.168.56.56
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /mnt/c/Users/lasleh/Development/onix-refactor
        to: /home/vagrant/code
sites:
    -
        map: onix.test
        to: /home/vagrant/code/public
databases:
    - homestead
features:
    -
        mysql: true
    -
        mariadb: false
    -
        postgresql: false
    -
        ohmyzsh: false
    -
        webdriver: false
services:
    -
        enabled: [mysql]
name: onix
hostname: onix

```

## Vagrant destroy & up output
https://gist.github.com/lasselehtinen/3b5fec03c14f20cea0f1f71f6cc7e50e

## Actual behavior
I created a new per project Homestead and run in to the issue that some repositorys are reporting hash checksum errors on the packages. Cleaning up the cache did not seem to help.

```
sudo apt-get clean
sudo rm -R /var/lib/apt/lists/*
sudo apt-get update
```
