### ISSUE TITLE
Mac M1 | Webdriver: True | Unable to locate package google-chrome-stable

### ISSUE THREAD

**Issue by StanBarrows** [laravel/homestead#1732]
## Versions
  - Vagrant 2.2.19
  - Provider:  Parallels 17.1.0 (51516)
  - Homestead: Checked: Response Already up to date.

## Host operating system
macOS Big Sur / 11.6 / Apple M1 | MacBook Pro (13-inch)

## Homestead.yaml
```yaml
---

ip: "192.168.56.56"
memory: 4096
cpus: 2

provider: parallels
box: laravel/homestead-arm
ssl: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: project.test
      to: /home/vagrant/Code/project/public
      schedule: true
      php: "8.0"

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: true

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

ports:
    - send: 23517 # Ray
      to: 23517
    - send: 33060 # MySQL/MariaDB
      to: 3306
    - send: 3000 # Laravel Mix
      to: 3000
    - send: 9515 # Laravel Dusk
      to: 9515
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017

```

## Vagrant destroy & up output
https://gist.github.com/StanBarrows/0b14d95992a0f88c52f68d58bdf0457e

## Expected behavior
- Install Webdriver correctly
- Run 'php artisan dusk'

## Actual behavior

**vagrant destroy & vagrant up**

```
homestead: Running provisioner: Installing webdriver (shell)...
    homestead: Running: script: Installing webdriver
    homestead: Warning: apt-key output should not be parsed (stdout is not a terminal)
    homestead: OK
    homestead: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    homestead: Hit:1 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu focal InRelease
    homestead: Hit:2 https://download.docker.com/linux/ubuntu focal InRelease
    homestead: Hit:3 https://deb.nodesource.com/node_14.x focal InRelease
    homestead: Hit:4 http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease
    homestead: Get:5 http://dl.google.com/linux/chrome/deb stable InRelease [1,811 B]
    homestead: Hit:6 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease
    homestead: Hit:7 http://us.ports.ubuntu.com/ubuntu-ports focal InRelease
    homestead: Hit:8 http://us.ports.ubuntu.com/ubuntu-ports focal-updates InRelease
    homestead: Get:9 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,098 B]
    homestead: Hit:10 http://us.ports.ubuntu.com/ubuntu-ports focal-backports InRelease
    homestead: Hit:11 http://us.ports.ubuntu.com/ubuntu-ports focal-security InRelease
    homestead: Fetched 2,909 B in 1s (2,028 B/s)
    homestead: Reading package lists...
    homestead: Reading package lists...
    homestead: Building dependency tree...
    homestead: Reading state information...
    homestead: E: Unable to locate package google-chrome-stable
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**php artisan dusk**
```
Browser\Tenant\TenantTest::verifty_tenant_section
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["--window-size=1920,1080","--disable-gpu","--no-sandbox","--headless"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","chromeOptions":{"args":["--window-size=1920,1080","--disable-gpu","--no-sandbox","--headless"]}}}

Failed to connect to localhost port 9515: Connection refused

/home/vagrant/Code/promoscreens.sonepar/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:333
/home/vagrant/Code/promoscreens.sonepar/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:131
/home/vagrant/Code/promoscreens.sonepar/tests/DuskTestCase.php:47
/home/vagrant/Code/promoscreens.sonepar/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:219
/home/vagrant/Code/promoscreens.sonepar/vendor/laravel/framework/src/Illuminate/Support/helpers.php:234
/home/vagrant/Code/promoscreens.sonepar/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:220
/home/vagrant/Code/promoscreens.sonepar/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:98
/home/vagrant/Code/promoscreens.sonepar/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:66
/home/vagrant/Code/promoscreens.sonepar/tests/Browser/Tenant/TenantTest.php:44
```

## Steps to reproduce
1. vagrant destroy & vagrant up
