### ISSUE TITLE
Vagrant was unable to mount VirtualBox shared folders

### ISSUE THREAD

**Issue by lloricode** [laravel/homestead#1733]
## Versions
  - Vagrant: Vagrant 2.2.19
  - Provider: Virtualbox
  - Homestead: v12.8.0

## Host operating system
Linux Mint 20.2 Cinnamon

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
  - ~/.ssh/id_rsa

folders:
  # tool
  - map: /home/lloricode/Documents/homestead/tools/phpmyadmin
    to: /home/vagrant/code/tools/phpmyadmin

  - map: /home/lloricode/Documents/homestead/laravel/laravel-boilerplate
    to: /home/vagrant/code/laravel/laravel-boilerplate

sites:
  # tools
  - map: db.test
    to: /home/vagrant/code/tools/phpmyadmin

  - map: laravel-boilerplate-8.test
    to: /home/vagrant/code/laravel/laravel-boilerplate/public
    php: "8.0"
  - map: laravel-boilerplate.test
    to: /home/vagrant/code/laravel/laravel-boilerplate/public
    php: "7.4"

databases:
  - laravel_boilerplate

features:
  - mysql: true
  - mariadb: false
  - ohmyzsh: false
  - webdriver: true # for dusk https://laravel.com/docs/8.x/homestead#laravel-dusk

services:
  - enabled:
      - "mysql"
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017
```

## Vagrant destroy & up output
https://gist.github.com/lloricode/df4ecdee9c8237a0c29a5f731a494494

## Expected behavior
will shared the folder just like before this issue

## Actual behavior
Output the `Vagrant was unable to mount VirtualBox shared folders` when ruuning `vagrant up` or `vagrant reload --provision`

## Steps to reproduce
1. Destroy homestead by running `vagrant destroy`
2. Recreate by `vagrant up`
3. Output will be `Vagrant was unable to mount VirtualBox shared folders`

## References
https://github.com/laravel/homestead/issues/517
