### ISSUE TITLE
mount.nfs: requested NFS version or transport protocol is not supported

### ISSUE THREAD

**Issue by tonyclemmey** [laravel/homestead#1735]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.19.
  - Provider: Virtualbox 6.1.30r148432
  - Homestead:  release branch with tag v12.8.0.

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
macOS Big Sur 11.6.1

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/homestead-sites/example
      to: /home/vagrant/code/example
      type: "nfs"
sites:
    - map: example.test
      to: /home/vagrant/code/example
      php: "8.0"
      type: "apache"
```

## Actual behavior
`vagrant destroy && vagrant up` works as expected but anytime after the first initial vagrant up, when running `vagrant reload` / `vagrant reload --provision` an error is outputted.

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp,actimeo=1,nolock 192.168.56.1:/Users/<USER>/Homestead-Sites/example /home/vagrant/code/example

Stdout from the command:

Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```

## Steps to reproduce
1.  use the NFS mount option in Homestead.yaml
2. `vagrant destroy && vagrant up`
3. `vagrant reload` or `vagrant reload --provision` 
4.  vagrant-vbguest already installed
5.  allowed "full disk access" to /sbin/nfsd already set

## References
https://github.com/hashicorp/vagrant/issues/8704
