### ISSUE TITLE
cURL Segmentation Fault

### ISSUE THREAD

**Issue by intrepidws** [laravel/homestead#1737]
In short, I am unable to run cURL commands to certain SSL domains. I found this out when I tried to run my test suite, which makes a cURL call to https://secure.bluepay.com/interfaces/a.net.test.

This looks like an issue with OpenSSL, specific to ARM builds of Ubuntu 20.04. Again, I don't know if there is anything that the Homestead team can actually do about this, but I wanted to report just in case rolling back to a prior version of something is a possibility.

Here is the information that I was able to find:
- https://issueexplorer.com/issue/curl/curl/7932
- https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1951279

## Versions
  - Vagrant: 2.2.19
  - Provider: Parallels Version 17.1.0 (51516
  - Homestead: v12.8.0

## Host operating system
Mac OS X 12.0.1

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: parallels
box: laravel/homestead-arm
ssl: false

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code/employers-amt
      to: /home/vagrant/code/employers-amt
      type: "nfs"

sites:
    - map: employers-amt.test
      to: /home/vagrant/code/employers-amt/public

databases:
    - employers_amt

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
        - "mysql"
    # - disabled:
    #     - "postgresql@11-main"

ports:
    - send: 33060 # MySQL/MariaDB
      to: 3306
    #    - send: 4040
    #      to: 4040
    #    - send: 54320 # PostgreSQL
    #      to: 5432
    #    - send: 8025 # Mailhog
    #      to: 8025
    #    - send: 9600
    #      to: 9600
    #    - send: 27017
    #      to: 27017
```

## Vagrant destroy & up output
https://gist.github.com/intrepidws/3a4690e813c9ed029c9d7ccdbc004675

## Steps to reproduce
1. SSH into vagrant box
2. Run from command line `openssl s_client -showcerts -connect graph.facebook.com:443 </dev/null `

## Expected behavior
Command should return details about SSL certificate.

## Actual behavior
Command returns:
```
CONNECTED(00000003)
Segmentation fault (core dumped)
```
