### ISSUE TITLE
Can't connect to database after upgrading to macOs Monterey

### ISSUE THREAD

**Issue by ibarral** [laravel/homestead#1740]
Hello! I just upgraded to macOs Monterey and I cannot longer connect to the MySQL database using Sequel Pro.

I get the error Can't connect to MySQL server on '127.0.0.1'.

## Versions
  - Vagrant: 2.2.19
  - Provider: Virtualbox 6.1.30
  - Homestead: v12.8.0

## Host operating system
macOs Monterey 12.0.1

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Web/Homestead/app
      to: /home/vagrant/app

sites:
    - map: app.test
      to: /home/vagrant/app/public
      php: "7.4"

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017

```

## Expected behavior
Connect to MySQL database using Sequel Pro using IP 127.0.0.1 on port 33060 as detailed here https://laravel.com/docs/8.x/homestead#connecting-to-databases

## Actual behavior
I get the error Can't connect to MySQL server on '127.0.0.1'.
