### ISSUE TITLE
Mac M1 ARM fails to install minio, mongodb if enabled

### ISSUE THREAD

**Issue by josezenem** [laravel/homestead#1748]
## Versions
  - Vagrant: Vagrant 2.2.19
  - Provider:Parallels (17.1.1)
  - Homestead: release branch commit (187b27043206405daafa471dd4c7e1425d02e6c1)
  - Box: laravel/homestead-arm

## Host operating system
MacBook Pro M1
Mac OS 12.1 (21C52)

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: parallels
box: laravel/homestead-arm
name: testing

authorize: ~/.ssh/vagrant_rsa.pub

keys:
    - ~/.ssh/vagrant_rsa

folders:
    - map: ~/code
      to: /home/vagrant/Code

sites:
    - map: homestead.test
      to: /home/vagrant/Code/test/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
    - mongodb: true
    - minio: true

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

buckets:
    - name: test
      policy: public

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017

```

## Vagrant destroy & up output
https://gist.github.com/josezenem/0ef881aaf0601f7c11b7b996de1add8b

## Expected behavior
Minio and mongodb should have installed successfully.

## Actual behavior
During install, system fails to install mongo/minio with messages such as: : can't read /etc/mongod.conf: No such file or directory.

I've set the setting for each to true separately to test individually and both will fail individually as well.

## Steps to reproduce
1. enable minio and run `vagrant up`
2. enable mongodb and run `vagrant up`
