### ISSUE TITLE
Version 12.x of the MariaDB box doesn't exist, unable to provision with "box: laravel/homestead-mariadb"

### ISSUE THREAD

**Issue by stevegrunwell** [laravel/homestead#1750]
## Versions
  - Vagrant: Vagrant 2.2.19
  - Provider: Virtualbox 6.1.22
  - Homestead: v13.0.2

## Host operating system
macOS Big Sur (11.6.2)

## Homestead.yaml
```yaml
ip: 192.168.10.42
memory: 2048
cpus: 2
provider: virtualbox
box: laravel/homestead-mariadb
authorize: ~/.ssh/id_rsa.pub
keys:
  - ~/.ssh/id_rsa
folders:
  - map: /Users/steve/my-app/app
    to: /home/vagrant/code
sites:
  - map: my-app.test
    to: /home/vagrant/code/public
    schedule: true
    php: '8.0'
databases:
    - myapp_development
services:
  - enabled:
    - mariadb
    - redis-server
  - disabled:
    - beanstalkd
    - docker
    - memcached
features:
    - ohmyzsh: true
    - postgres: false
name: my-app
hostname: my-app
in-flight-service: true
```

## Vagrant destroy & up output

https://gist.github.com/stevegrunwell/ee700ab26fba65b44afc67099682d8c7

## Expected behavior
I would expect that the MariaDB-specific Homestead box (established in #1710) would be loaded.

## Actual behavior
I get told that the MariaDB variant doesn't exist within the constraint of >= 12.0.0, < 13.0.0

> The box you're attempting to add has no available version that matches the constraints you requested. Please double-check your settings. Also verify that if you specified version constraints, that the provider you wish to use is available for these constraints.

## Steps to reproduce
1. Set `box: laravel/homestead-mariadb` in the `Homestead.yaml` file, per https://github.com/laravel/homestead/issues/1710#issuecomment-955068410
2. Run `vagrant up`

It appears that the MariaDB box isn't getting published with the same frequency as the main Homestead box, meaning it can't be used with the latest version of the `homestead.rb` script ([which sets the constraint of ">= 12.0.0, < 13.0.0"](https://github.com/laravel/homestead/blob/main/scripts/homestead.rb#L22).
