### ISSUE TITLE
mariadb in services instead of mysql or not?

### ISSUE THREAD

**Issue by highstrike** [laravel/homestead#1752]
Hello,

I just updated my homestead because it wouldn't start anymore after upgrading to macos 11.6.2 (from 11.6.1)

Went ahead and installed the latest virtualbox, latest vagrant, vagrant plugins, got homestead from git as per laravel homestead docs, anyway

I saw some new stuff in homestead.yaml
services appeared where it previously was only features

**So my issue is that I use mariadb instead of mysql**

I went ahead and disabled mysql from features and enabled mariadb
My file now looks something like this:
```
features:
    - mysql: false
    - mariadb: true
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"
```

Now I'm confused, in enabled services should I replace `mysql` with `mariadb`? Or just leave it like that.

Homestead documentation says mariadb is drop in replacement of mysql.
I also know that even though I'm using mariadb, I still use CLI tools named mysql

So, what's the correct way for me to use mariadb with homestead?
Do I need to replace enabled services `mysql` with `mariadb` or not?

Thanks
