### ISSUE TITLE
Minio is borked

### ISSUE THREAD

**Issue by mbalandis** [laravel/homestead#1753]
I am not certain since when but all of the sudden minio doesn't boot anymore and it may be because some changes in recent updates. I used fresh and latest everything (virtual box, homestead, vagrant, etc) and new box without any other stuff. Tried restarting, reinstalling. Removing minio configuration from Homestead.yaml boots the machine. I use this for local dev so would be great to get this working again. 

## Versions
  - Vagrant 2.2.19
  - Provider: Virtualbox
  - Homestead: v13.0.2

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Mac OS Monterey 12.1

## Homestead.yaml
```yaml
ip: 192.168.56.56
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /Users/martybalandis/Projects/project-template
        to: /home/vagrant/code
sites:
    -
        map: project-template.test
        to: /home/vagrant/code/public
databases:
    - homestead
features:
    -
        mysql: true
    -
        mariadb: false
    -
        postgresql: false
    -
        ohmyzsh: false
    -
        webdriver: false
    -
        minio: true
buckets:
  -
    name: minio-local
    policy: public
services:
    -
        enabled: [mysql]
name: project-template
hostname: project-template

```

## Vagrant destroy & up output

https://gist.github.com/mbalandis/42b1dfa74cb1dbf21e2594d05518d497

## Expected behavior

Installs minio and boots like normal

## Actual behavior

Doesn't boot and throws error that it cannot connect

## Steps to reproduce
1. add minio configuration to Homeastead.yaml
2. vagrant up
