### ISSUE TITLE
Per Project Installation add site-type

### ISSUE THREAD

**Issue by tommy66374** [laravel/homestead#1761]
## Versions
  - Vagrant: 2.2.19
  - Provider: Virtualbox
  - Homestead: `release` branch.
  - VirtualBox: 6.1.32
  - Laravel: 9.0.0

## Host operating system
Windows 10

## Homestead.yaml
```yaml
sites:
    - map: example.test
      to: /home/vagrant/code/example/public
      type: "myhome"
      php: "8.1"
```

I copy the file from

`C:\Users\xxxxx\Homestead\scripts\site-types\laravel.sh`

to a new file called

`C:\Users\xxxxx\Homestead\scripts\site-types\myhome.sh`

and in the `myhome.sh` added 1 line for the Nginx setting

`client_max_body_size 500M;`

How to in Per Project Installation use another site-type?

when i vagrant up the example project, got this error

```
shell provisioner:
* `path` for shell provisioner does not exist on the host system: D:/web/code/example/vendor/laravel/homestead/scripts/site-types/myhome.sh
```
