### ISSUE TITLE
We hope that we can create a website of webman framework in homestead.

### ISSUE THREAD

**Issue by mouyong** [laravel/homestead#1764]
## Versions
  - Vagrant: 2.2.19
  - Provider: Virtualbox 6.1.32
  - Homestead: v12.5.0

## Host operating system

Windows 21H1 19043.1526

## Homestead.yaml

```yaml
sites:
    - map: homestead.test
      to: /home/vagrant/code/public
    - map: webman.test
      to: /home/vagrant/code/php/webman-test/public
      php: "8.0"
      type: webman
      upstreamPort: 8788
```

## Problem

Hope to add `upstreamPort` to `s.args` and add new site type for `webman framework `

can see this link: https://www.workerman.net/a/1287
