### ISSUE TITLE
Composer curl error 92

### ISSUE THREAD

**Issue by ametad** [laravel/homestead#1769]
## Versions
  - Vagrant: 2.2.19
  - Provider: Virtualbox 6.1.26_Ubuntu r145957
  - Homestead: 13.2.1

## Host operating system
Ubuntu 20.04.4 LTS

## Homestead.yaml
```yaml
ip: 192.168.10.15
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
backup: true
folders:
    -
        map: /home/anne/WebDev/webplaats/laravel-app
        to: /home/vagrant/code/laravel-app
    -
        map: /home/anne/WebDev/webplaats/laravel-package-media
        to: /home/vagrant/code/laravel-package-media
    -
        map: /home/anne/WebDev/webplaats/laravel-package-invite-users
        to: /home/vagrant/code/laravel-package-invite-users
sites:
    -
        map: laravel-app.test
        to: /home/vagrant/code/laravel-app/public
        type: "apache"
        schedule: true
    -
        map: support.laravel-app.test
        to: /home/vagrant/code/laravel-app/public
        type: "apache"
databases:
    - homestead
    - tenancy
features:
    -
        mariadb: false
    -
        ohmyzsh: false
    -
        webdriver: false
name: laravel-app
hostname: laravel-app
```

## Vagrant destroy & up output
Homestead as a system is working fine.

## Expected behavior
After provisioning Composer is updated from version 2.0.x to 2.2.7. When executing `composer update` all packages are correctly downloaded and installed, just as before with the earlier version of Composer.

We have some custom repos in our `composer.json` where our private packages lives. This setup always worked well:

```json
"repositories": {
        "gitlab.redacted.domain/14": {
            "type": "composer",
            "url": "https://gitlab.redacted.domain/api/v4/group/14/-/packages/composer/packages.json"
        },
        "gitlab.redacted.domain/35": {
            "type": "composer",
            "url": "https://gitlab.redacted.domain/api/v4/group/35/-/packages/composer/packages.json"
        },
        "0": {
            "type": "path",
            "url": "../*"
        }
    },
```

Note: "redacted.domain" is not our real domain, for safety reasons.

## Actual behavior
In the provisioning of our fresh install of Homestead, Composer is updated to version 2.2.7. This version is somehow not working to download the packages, it fails with an curl error 92.

With Composer version 2.2.7

When I first do a `composer self-upate --rollback` to version 2.0.7, composer does work again correctly!

## Steps to reproduce
1. vagrant destroy && vagrant up
2. cd code/laravel-app
3. composer update
4. Do you trust "slince/composer-registry-manager" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] d
5. this error:

```
[Composer\Downloader\TransportException]                                                                                                                                                     
  curl error 92 while downloading https://gitlab.edacted.domain/api/v4/group/35/-/packages/composer/p2/doctrine/dbal~dev.json: HTTP/2 stream 217 was not closed cleanly: REFUSED_STREAM (err 7)
```

Strange thing is that `doctrine/dbal` is not on our Gitlab server, but somehow it is trying to get it from our server anyway. 

This behavior started- and is only present with Composer version 2.2.x
When - after a newly installed Homested instance - I **first** do a rollback to earlier version of Composer, the problem is gone.

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
- https://github.com/composer/composer/issues/10566
