### ISSUE TITLE
Why is the load so high

### ISSUE THREAD

**Issue by mouyong** [laravel/homestead#1770]
![image](https://user-images.githubusercontent.com/10336437/156479928-2d4a36f7-cb5d-409e-94ab-fb1fcec5fa5b.png)

![image](https://user-images.githubusercontent.com/10336437/156480002-d2615e13-ba57-48ed-8d48-330ea0c63cd4.png)

![image](https://user-images.githubusercontent.com/10336437/156479726-43d98830-e789-41b0-8c40-058397dca702.png)

**Comment by mouyong** [comment]
When i comment `type: nfs`, it's started. and sometimes cpu1 or cpu2 stack.

```
folders:
    - map: z:\code
      to: /home/vagrant/code
      # type: "nfs"
```
