### ISSUE TITLE
Documentation Possible Update?

### ISSUE THREAD

**Issue by webdevnerdstuff** [laravel/homestead#1781]
In the documentation it says that the database backup locations are `mysql_backup` and `postgres_backup`. The files are actually backed up in `.backup/mysql_backup` and `.backup/postgres_backup`.

https://laravel.com/docs/9.x/homestead#database-backups

## Versions
  - Vagrant: 2.2.7
  - Provider: Virtualbox 6.1.4 r136177 (Qt5.6.3)
  - Homestead: ^13.2

## Host operating system
Mac 10.15.7 (19H1615)

## Homestead.yaml
```yaml
ip: 192.168.88.88
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
backup: true
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: ~/foobar
        to: /home/vagrant/code/public_html/foobar
sites:
    -
        map: dev.foobar.com
        to: /home/vagrant/code/public_html/foobar/public
        php: "8.0"
        type: "apache"
databases:
    - homestead
features:
    -
        mysql: true
    -
        mariadb: false
    -
        postgresql: false
    -
        ohmyzsh: true
    -
        webdriver: false
services:
    -
        enabled: [mysql]
name: foobar
hostname: foobar

```
## Expected behavior
It works as expected, just a documentation possible update.

## Actual behavior
It works as expected, just a documentation possible update.

## Steps to reproduce
1. vagrant destroy
