### ISSUE TITLE
Proxy Site Type support for Apache

### ISSUE THREAD

**Issue by Sn0wCrack** [laravel/homestead#1788]
## Versions
  - Vagrant: Vagrant 2.2.19
  - Provider: Virtualbox, VMWare, Hyper-V, or Parallels and its version.
  - Homestead: You should be on the most recent `release` branch.

## Host operating system
macOS 12.4

## Homestead.yaml
```yaml
    - map: atlas.test
      to: /home/vagrant/atlas/public
      php: "8.1"
      type: apache

    - map: atlas-octane.test
      to: 8000
      php: "8.1"
      type: proxy
```

## Expected behavior
Proxy configuration should either generate a proxy configuration for both web servers or should detect the currently running web server configuration and generate it for that.

## Actual behavior
Proxy configuration is only generated for Nginx and not apache

## Steps to reproduce
1. Set one site in Homestead.yaml to a type of apache and another to proxy
2. Provision or reprovision Homestead with Vagrant
3. Proxy configuration has not been generated.
