### ISSUE TITLE
Bad permissions with NFS on macOs Monterey

### ISSUE THREAD

**Issue by Bartiff** [laravel/homestead#1794]
## Versions
  - Vagrant: Vagrant 2.3.0
  - Provider: Virtualbox 6.1.36
  - Homestead: Most recent `release` branch.

## Host operating system
macOs Monterey 12.5.1

## Homestead.yaml
```yaml
---
ip: "192.168.56.10"
memory: 4096
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code
      type: "nfs"

sites:
    - map: local.med
      to: /home/vagrant/code
```

## Expected behavior
1. When I run vagrant up I don't want to have to type my password after these lines:
```
==> homestead: Exporting NFS shared folders...
==> homestead: Preparing to edit /etc/exports. Administrator privileges will be required...
```
2. Once my machine is mounted I must have the right permissions on my folder synchronized with NFS.

## Actual behavior
On a fresh install of macOs Monterey in my MacBook Pro, I installed the latest version of Virtualbox, Vagrant and Homestead. I enabled the Virtualbox app in my System Preferences and allowed nfsd full disk access.
1. Yet I still get the admin password request during the vagrant up.
2. When I do ```vagrant ssh``` then an ```ls -la``` from my home folder I have bad permissions on my code folder (502:dialout):
```
vagrant@homestead:~$ ls -la
total 76
drwxr-xr-x 10 vagrant vagrant 4096 Aug 19 13:24 .
drwxr-xr-x  3 root    root    4096 Aug  9 23:42 ..
-rw-r--r--  1 vagrant vagrant 8840 Aug 19 13:15 .bash_aliases
-rw-------  1 vagrant vagrant   68 Aug 19 13:24 .bash_history
-rw-r--r--  1 vagrant vagrant  220 Feb 25  2020 .bash_logout
-rw-r--r--  1 vagrant vagrant 3771 Feb 25  2020 .bashrc
drwx------  4 vagrant vagrant 4096 Aug 19 13:19 .cache
drwxr-xr-x  9     502 dialout  288 Aug 19 13:23 code
drwxr-xr-x  4 vagrant vagrant 4096 Aug  9 23:55 .config
drwxr-xr-x  2 vagrant vagrant 4096 Aug 19 13:19 .homestead-features
drwxrwxr-x  5 vagrant vagrant 4096 Aug 19 13:20 .local
-rw-r--r--  1 vagrant vagrant   61 Aug 19 13:20 .my.cnf
drwxrwxr-x  2 vagrant vagrant 4096 Aug 19 13:21 .ngrok2
drwxr-xr-x  5 vagrant vagrant 4096 Aug  9 23:56 .npm
-rw-r--r--  1 vagrant vagrant  895 Aug 19 13:20 .profile
drwx------  2 vagrant vagrant 4096 Aug 19 13:15 .ssh
-rw-r--r--  1 vagrant vagrant    0 Aug  9 23:42 .sudo_as_admin_successful
-rw-r--r--  1 vagrant vagrant    6 Aug  9 23:42 .vbox_version
-rw-r--r--  1 vagrant vagrant  346 Aug  9 23:58 .wget-hsts
```
When I remove ```type: "nfs"``` in my yaml config the permissions are ok.
