### ISSUE TITLE
Premission denied for github repo during install

### ISSUE THREAD

**Issue by rbruhn** [laravel/homestead#1797]
## Versions
  - Vagrant: 2.3.0
  - Provider: Virtualbox 6.1.38 r 153438
  - Homestead: latest release

## Host operating system
Windows 10

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 6144
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    -   map: D:\Sites\biospex
        to: /home/vagrant/sites/biospex
        type: "nfs"
        mount_opts: ['nolock,vers=3,udp,noatime,actimeo=1']
    -   map: D:\Sites\rapid
        to: /home/vagrant/sites/rapid
        type: "nfs"
        mount_opts: ['nolock,vers=3,udp,noatime,actimeo=1']
sites:
    -   map: biospex.test
        to: /home/vagrant/sites/biospex/public
        type: biospex
        php: "8.1"
    -   map: api.biospex.test
        to: /home/vagrant/sites/biospex/public
        type: redirect
        php: "8.1"
    -   map: rapid.biospex.test
        to: /home/vagrant/sites/rapid/public
        type: redirect
        php: "8.1"
features:
    - mongodb: true
    - python: true
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

```

## Vagrant destroy & up output
https://gist.github.com/rbruhn/9799b2f559dfd6398ad04820c9a989ad

## Expected behavior
Run vagrant reload & provision to add new site in yaml.

## Actual behavior
When adding a new site to yaml file and running provision to create the new site, I received the error show in the gist. I decided to run a clean install by running vagrant destroy, removing all boxes, updating Homestead to be sure I was running the latest version, and still ended up with the same error. 
It appears permission is denied when trying to access GitHub repo for  uNetworking/uWebSockets

## Steps to reproduce
1. Delete everything
2. vagrant up

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
Could not find anything related.
