### ISSUE TITLE
Reload stuck in "Running: script: Update Composer" step after PHP version change

### ISSUE THREAD

**Issue by mhcgolds** [laravel/homestead#1821]
## Versions
  - Vagrant: 2.3.0
  - Provider: Virtualbox 6.1.38 r153438 (Qt5.6.2)
  - Homestead: laravel/homestead (virtualbox, 12.2.0)

## Host operating system
Windows 11 21H2

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 1024
cpus: 2
provider: virtualbox
name: TytoHomestead

folders:
    - map: D:/Tyto/tyto_erp_v1
      to: /home/vagrant/tyto

sites:      
    - map: tyto
      to: /home/vagrant/tyto/public
      php: "8.1.12"

databases:
    - homestead

features:
    - postgresql: true
    - mariadb: false
    - ohmyzsh: false
    - webdriver: false
```

## Vagrant destroy & up output
I prefer to skip this step if possible, otherwise i would need to import a huge test database what would consume some time. However I can do it if really necessary.

## Expected behavior
I only changed the PHP version of the site from "7.4" to "8.0" and then runned `vagrant reload --provision` and expected the VM would start with a new PHP version running.

## Actual behavior
The process stuck in these lines:

    ==> TytoHomestead: Running provisioner: Update Composer (shell)...
    TytoHomestead: Running: script: Update Composer

I left it running about 30 minutes but it didn't proceeded. I then killed the Ruby process, changed the PHP version to "8.1.12" and runned reload again. Same problem.

## Steps to reproduce
1. Change site's PHP version from "7.4" to "8.0"
2. Run `vagrant reload --provision`

## Command outupu
[Gism](https://gist.github.com/mhcgolds/e51ddabeeeface9ab4022981645d0071)
