### ISSUE TITLE
By use the feature MariaDB get error "Access denied for user 'root'@'localhost'"

### ISSUE THREAD

**Issue by p4rad0xus** [laravel/homestead#1824]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.19
  - Provider: Virtualbox 6.1
  - Homestead: 13.3.2

## Host operating system
macOS Big Sure 11.7.1

## Homestead.yaml
```yaml
ip: 192.168.56.56
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_ed25519.pub
keys:
    - ~/.ssh/id_ed25519
folders:
    -
        map: /Users/p4rad0xus/Developer/github_issue
        to: /home/vagrant/code
sites:
    -
        map: homestead.test
        to: /home/vagrant/code/public
databases:
    - homestead
features:
    -
        mysql: false
    -
        mariadb: true
    -
        postgresql: false
    -
        ohmyzsh: false
    -
        webdriver: false
services:
    -
        enabled: [mysql]
name: github-issue
hostname: github-issue
```

## Vagrant destroy & up output
vagrant up
https://gist.github.com/p4rad0xus/411623f39b83aaf449f7c85e207a282a#file-vagrant_up

vagrant destroy
https://gist.github.com/p4rad0xus/9f0e5bd46f844cd0d9cc8b17553332fb#file-vagrant_destroy

## Expected behavior
The command `vagrant up` should proceed successful and create the named database in the Homestead.yaml.

## Actual behavior
The script stoped at the point when the database should be created with the error "Access denied for user 'root'@'localhost'".

## Steps to reproduce
1. Create a new Homestead project
2. Set the feature `mysql` to `false` and `mariadb` to `true`
3. Run `vagrant up`

## MySQL-User-Table

It looks like a password for root@localhost is never set.

MariaDB [(none)]> Select User, Host, Password from mysql.user;
```
+-------------+-----------+-------------------------------------------+
| User        | Host      | Password                                  |
+-------------+-----------+-------------------------------------------+
| mariadb.sys | localhost |                                           |
| root        | localhost | invalid                                   |
| mysql       | localhost | invalid                                   |
| root        | 0.0.0.0   | *14E65567ABDB5135D0CFD9A70B3032C179A49EE7 |
| homestead   | 0.0.0.0   | *14E65567ABDB5135D0CFD9A70B3032C179A49EE7 |
| homestead   | %         | *14E65567ABDB5135D0CFD9A70B3032C179A49EE7 |
+-------------+-----------+-------------------------------------------+
```
