### ISSUE TITLE
VBoxManage.exe: error: Unknown option: --host-only-net9=HostOnly

### ISSUE THREAD

**Issue by chan15** [laravel/homestead#1830]
## Versions
  - Vagrant: 2.3.4
  - Provider: Virtualbox 7.0.4

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: d:/projects
      to: /home/vagrant/code
    - map: d:/www/php
      to: /home/vagrant/php

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
```

## Vagrant destroy & up output

https://gist.github.com/chan15/496a4bf39985381aac77652eda395d52

My homestead branch is on `release`, I run git pull for the update, when it was done, run init.bat, then run `vagrant up --provision`, and I got:

```
VBoxManage.exe: error: Unknown option: --host-only-net9=HostOnly
```

Before updating the script everything is fine
