### ISSUE TITLE
Is it possible to specify NFS options in homestead.yml file ?

### ISSUE THREAD

**Issue by sdespont** [laravel/homestead#1832]
In my homestead.yml file I have :

```
folders:
    - map: C:\MySite\Sites\www
      to: /MySite
      type: "nfs"
```
Is it possible to declare options I want to use liek `nolock,vers=3,udp,noatime` ?

I [have found](https://laravel.com/docs/9.x/homestead#configuring-shared-folders) that it is possible to declare options for rsync, but I cannot figure ot out how to declare options for nfs.

![image](https://user-images.githubusercontent.com/646632/211205819-2fed0370-5fc3-498d-bd4d-5478a2f7a4c0.png)

Thanks

**Comment by sdespont** [comment]
OK, I found how to specify the options 👍 

```
folders:
    - map: C:\MySite\Sites\www
      to: /MySite
      type: "nfs"
      options:
          mount_options: ["nolock", "vers=3", "tcp", "noatime", "rsize=65536", "wsize=65536"]
```

I don't understand why, but `actimeo=1` cache value makes the page render 2.5x more slower after Windows 22H2 upgrade on my laptop ?!

Any advices about the mount options tuning ?
