### ISSUE TITLE
Not able load the project

### ISSUE THREAD

**Issue by keatwei** [laravel/homestead#1835]
Any working version for homestead at the moment?

## Versions
  - Vagrant 2.3.4
  - Provider: Virtualbox 7.0.4 and 6.1.4
  - Homestead: 14
  - Laravel/Homestead box 12.2 (as 13 only available for parallels)

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/VM/Projects/Web
      to: /home/vagrant/VM/Projects/Web

sites:
    - map: homestead.test
      to: /home/vagrant/VM/Projects/Web/homestead/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017

```

## Vagrant destroy & up output
vagrant up

## Issue
homestead.test not able to load
```
---
This site can’t be reached
homestead.test took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_TIMED_OUT

```

## Host File

```
192.168.56.56 homestead.test
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
```
