### ISSUE TITLE
vagrant up throw Constraints: >= 13.0.0, < 14.0.0

### ISSUE THREAD

**Issue by avinashseth** [laravel/homestead#1838]
## Versions
  - Vagrant: 2.3.4
  - Provider: Virtualbox Version 7.0.4 r154605 (Qt5.15.2)
  - Homestead: using project-wise homestead installer instead of global installer

## Host operating system
Windows 11

## Homestead.yaml
```
ip: 192.168.56.56
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
  - ~/.ssh/id_rsa
folders:
  - map: 'C:\dev\folder\laravel-project'
    to: /home/vagrant/code
sites:
  - map: laravel-project.local
    to: /home/vagrant/code/public
databases:
  - laravel-project
features:
  - mysql: true
  - mariadb: false
  - postgresql: false
  - ohmyzsh: false
  - webdriver: false
services:
  - enabled: [mysql]
name: laravel-project
hostname: laravel-project
```

## Vagrant destroy & up output
[GitHub Gist](https://gist.github.com/avinashseth/f7ede6d46abe6508f97d254a17d93ff2)

## Expected behavior
It should run vagrant

## Actual behavior
Getting error that Box Version: >= 13.0.0, < 14.0.0 should be like that, but official support for virtual box v13.0.0 is not available in the [laravel vagrant box](https://app.vagrantup.com/laravel/boxes/homestead)

## Steps to reproduce
1. Install new laravel project
2. Follow per project homestead installation [Offical Documentation](https://laravel.com/docs/9.x/homestead#per-project-installation)

## References
None

## Temporary Solution
1. Goto C:\dev\folder\laravel-project\vendor\laravel\homestead\scripts\homestead.rb
2. Goto line 22
3. update '>= 13.0.0, < 14.0.0' to '>= 12.0.0, < 14.0.0'
4. Now vagrant up work

## Conclusion
Not sure if temporary solution is correct, as everytime someone will install via composer install will have to make the changes again and again
