### ISSUE TITLE
The specified host network collides with a non-hostonly network!

### ISSUE THREAD

**Issue by browner12** [laravel/homestead#1852]
## Versions

  - Vagrant: 2.3.4
  - Provider: Virtualbox 7.06. (also tried with 6.1)
  - Homestead: `release` branch

## Host operating system

MacOS Catalina (10.15.7)

## Homestead.yaml

```yaml
---
ip: "192.168.56.56"
memory: 6144
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/homestead/public

databases:
    - homestead

backup: true

features:
    - mysql: true
    - webdriver: true

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017


```

## Vagrant destroy & up output

```sh
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Checking if box 'laravel/homestead' version '13.0.0' is up to date...
==> homestead: Clearing any previously set network interfaces...
The specified host network collides with a non-hostonly network!
This will cause your specified IP to be inaccessible. Please change
the IP or name of your host only network so that it no longer matches that of
a bridged or non-hostonly network.

Bridged Network Address: '192.168.56.0'
Host-only Network 'vnic2': '192.168.56.0'
```

## Expected behavior

Homestead should provision and boot.

## Actual behavior

The error message was reached.
