### ISSUE TITLE
rsync folder map type does not set files as executable from Windows rsync.exe

### ISSUE THREAD

**Issue by humandevs** [laravel/homestead#1858]
## Versions
  - Vagrant: 2.3.4
  - Provider: Virtualbox 7.0.6 (though I've tried 6.1.3 as well, which was my previous version)
  - Homestead: latest release fetch 9a8191f (Jan 28th 2023 merge branch main)

## Host operating system
Windows 10 Pro 21H2 19044.2486
CigWinx64 (for rsync, though according to this bug Vagrant comes with rsync.exe on Windows in 2.2.4+ https://github.com/hashicorp/vagrant/issues/11268

## Homestead.yaml
```yaml
yaml
---
ip: "172.16.172.59"
memory: 4096
cpus: 2
provider: virtualbox
name: homestead-2

authorize: c:/Users/Username/.ssh/id_rsa.pub

keys:
    - c:/Users/Username/.ssh/id_rsa

folders:
    - map: f:/Users/Nate/GitHub/craft-digipedia
      to: /home/vagrant/sites/craft-digipedia
      type: "rsync"
      # install nfs driver else will get file not found errors type: "nfs"
      # install on windows with: vagrant plugin install vagrant-winnfsd
      # then reload with ./homestead reload
      # confirm working by ./homestead ssh, then cd into folder to check contents

sites:
    - map: craft-digipedia.test
      to: /home/vagrant/sites/craft-digipedia/web
      php: "8.0"

databases:
    - craft_digipedia

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
    
backup: true
#services:
#    - enabled:
#        - "postgresql@12-main"
#    - disabled:
#        - "postgresql@11-main"

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
[(https://gist.github.com/humandevs/c1718dc81e95a21b31737dbf2f1c9644)](https://gist.github.com/humandevs/c1718dc81e95a21b31737dbf2f1c9644)

## Expected behavior
rsync should set the synced files as executable

## Actual behavior
All files synced with rsync are set with no execute bit set

## Steps to reproduce
1. Set a folder to type: "rsync"
2. bring up homestead
3. note the files are not executable, like "NFS" or default "SMB" folder sync types.

Note: This happens with rsync installed via Cygwin or with native Vagrant rsync.exe included in latest vagrant

This seems related to the vagrant bug in 2.2.10 described here: https://github.com/hashicorp/vagrant/issues/11959

Note: I have also tried the NFS driver (along with the native Virtualbox shared folders) to fix the file slowness issues in Windows, which are causing composer zip extracts to hang/fail with file not found errors. This is unrelated to rsync not setting permissions properly. The slowness in Virtualbox is most likely a WSL2 / Hyper-V issue with Virtualbox, which is documented here, but there's not much that can be done about it other than move to a Hyper-V or WSL2 VM.  https://github.com/MicrosoftDocs/WSL/issues/798

## References
https://github.com/hashicorp/vagrant/issues/11268
https://github.com/hashicorp/vagrant/issues/11959
