### ISSUE TITLE
Last release of today PHP fpm error

### ISSUE THREAD

**Issue by swingamel** [laravel/homestead#1868]
Hello, I would like to report a problem to you.
Thank you!

## Versions
  - Vagrant 2.3.1
  - Homestead version 2023-04-14
  - VirtualBox 6.1.38
  - Windows 22H2

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 4
provider: virtualbox
ssl: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/www
      to: /home/vagrant/code
      type: "nfs"

sites:
    - map: platform.test
      to: /home/vagrant/code/platform/public
      type: symfony4
      php: "8.0"
    - map: core.test
      to: /home/vagrant/code/core/public
      type: symfony4
      php: "8.0"


databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: true
    - webdriver: false

```
## Bug :
1. vagrant --provision && vagrant ssh
2. ssh access successful
3. localhost file OK
4. In all web browsers, we receive the nginx 502 Bad Gateway

## Solution :
1. service php8.0-fpm restart
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to restart 'php8.0-fpm.service'.
Authenticating as: vagrant
Password:
==== AUTHENTICATION COMPLETE ===

2. Restart OK
3. All site OK
