### ISSUE TITLE
Can't launch Homestead Vagrant Box on M1 Mac with Parallels

### ISSUE THREAD

**Issue by estevao** [laravel/homestead#1870]
## Versions
  - Vagrant: Vagrant 2.3.4
  - Provider: Parallels Desktop 18.2.0
  - Homestead: v14.3.0

## Host operating system
  - macOS Ventura 13.3.1 (M1)

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: parallels
box: laravel/homestead-arm

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/dev/example-app
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017
```

## Vagrant destroy & up output
vagrant up gist: https://gist.github.com/estevao/9e3f618f9930ae207632658b64a71e7c

## Expected behavior
Homestead VM should have been created and started.

## Actual behavior
Machine was not created with exception as per gist - "Can't assign requested address - connect(2) for 0.0.0.0:8000 (Errno::EADDRNOTAVAIL)"
 
## Steps to reproduce
I followed instructions provided on https://laravel.com/docs/10.x/homestead
