### ISSUE TITLE
"No input file specified" on new homestead but everything looks configured correctly?

### ISSUE THREAD

**Issue by baradhili** [laravel/homestead#1873]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.2.6.
  - Provider: Virtualbox 6.1.26
  - Homestead:   did 'git checkout release'

## Host operating system
Ubuntu 18.04

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: virtualbox
name: picsi-laravel-test

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /home/bret/Documents/Sites/picsi-laravel-test/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mysql: false
    - mariadb: true
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

```

## Vagrant destroy & up output
[gist](https://gist.github.com/baradhili/c2e68020560fab664c10fd0bec3da400)

## Expected behavior
What should have happened? Please include as much detail as possible.
Dropping a laravel build into this should work!. 

## Actual behavior
What actually happened? Please include as much detail as possible.
Dreaded "No input file specified. "

```
more /var/log/nginx/homestead.test-error.log :
2023/05/19 04:09:50 [error] 1294812#1294812: *1 FastCGI sent in stderr: "Unable to open primary script: /home/vagrant/code/public/index.php (No such file or directory)" while
 reading response header from upstream, client: 192.168.56.1, server: homestead.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", hos
t: "homestead.test"
```
But file exists!
```
vagrant@homestead:~$ ls -al /home/vagrant/code/public/index.php
-rw-rw-r-- 1 vagrant vagrant 1710 May  5 02:42 /home/vagrant/code/public/index.php
```

## Steps to reproduce
1. following normal laravel instructions - create a homestead instance
2. modify homestead.yaml and create a directory 'code'
3. copy laravel build into 'code' make sure composer install, art key:generate done
4. Atttempt to reach homestead.test

## References
Many talk about 'no input file specified' but none seem to make a difference?
