### ISSUE TITLE
Missing PHP Aliases upon fresh installation.

### ISSUE THREAD

**Issue by Cuji12** [laravel/homestead#1874]
I just want to preface this with: I have resolved this by updating my Homestead version, it's just something I spent a lot of time with before finding the issue and thought it could perhaps be useful for cases where people cannot update their Homestead version (if that even is a common enough scenario for this ticket to be relevant).

## Versions
  - Vagrant: 2.3.4
  - Provider: Virtualbox 7.0.6, 
  - Homestead: 12.8

## Host operating system
Ubuntu 22.04.1 LTS

## Homestead.yaml
```
yaml
ip: 192.168.56.56
memory: 2048
cpus: 4
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
  - ~/.ssh/id_rsa
folders:
  - map: /home/cuji/Work/Professional/organise
    to: /home/vagrant/code
sites:
  - map: homestead.test
    to: /home/vagrant/code/public
    php: "8.1"
databases:
  - organise
name: organise
hostname: organise
ports:
  - send: 54320
    to: 5432
protocol: udp
services:
  - enabled:
    - "redis-server"
    - "postgresql"
  - disabled:
    - "beanstalkd"
    - "memcached"
    - "mysql"
features:
  - webdriver: true
  - postgresql: true
backup: true
```

## Vagrant destroy & up output
https://gist.github.com/Cuji12/25d27930a64d18fd28c26aad83a402b7

## Expected behavior
The machine should consist of aliases `php56` > `php81`. It should also configure the machine to use PHP 8.1.

## Actual behavior
Looking at `/tmp/bash_aliases`, I can only see aliases for `php56` > `php71`. The machine has PHP 8.0 (the default for this Homestead version) set.

## Steps to reproduce
1. Create a machine using `laravel/homestead: "^12", configure it to use PHP 8.1.
2. Run `cat /tmp/bash_aliases` to check only the PHP aliases `php56` > `php71` exist.
3. Run php -v to confirm the machine has erroneously been configured to use PHP 8.0.
