### ISSUE TITLE
php82 not working

### ISSUE THREAD

**Issue by inwoker** [laravel/homestead#1880]
## Versions
  - Vagrant: 2.3.5.
  - Provider: Virtualbox 7.0.8.
  - Homestead: v14.4.1.

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: virtualbox
backup: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: e:/code
      to: /home/vagrant/code

sites:
    - map: project1.test
      to: /home/vagrant/code/project1/web
      php: "8.2"
    - map: project2.test
      to: /home/vagrant/code/project2/web
      php: "8.1"

databases:
    - ss_project1
    - ss_project2

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
```

## Vagrant destroy & up output
https://gist.github.com/inwoker/c59a84f239d747224bfb7e9422a731e1

## Expected behavior
Should have switched default php in command line to 8.2

## Actual behavior
Nothing happens and it outputs: -bash: php82: command not found

## Steps to reproduce
1. Switch to php 8.1 by typing php81
2. Try to switch to 8.2 by typing php82
