### ISSUE TITLE
Is it possible to support Ubuntu 22.04?

### ISSUE THREAD

**Issue by john1726** [laravel/homestead#1882]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Run `vagrant -v` to show the version.
 Vagrant 2.3.7
  - Provider: 
  Virtualbox 7.0.8
  - Homestead: You should be on the most recent `release` branch.

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
This is the operating system that you run locally.

## Homestead.yaml
```yaml
# Copy-paste your Homestead.yaml here
```
```
---
ip: "192.168.56.56"
memory: 4096
cpus: 4
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: D:\Workspace\GResources\Courses\Lynda\BuildingLaravelVuejsWebApps\Homestead\nadias
      to: /vagrant/nadias

sites:
    - map: dev.nadias
      to: /vagrant/nadias/public

databases:
    - nadias

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
What should have happened? Please include as much detail as possible.
Is it possible to use Homestead with Ubuntu 22.04?  

## Actual behavior
What actually happened? Please include as much detail as possible.
At this time Ubuntu 20.04 is the most recent release supported

## Steps to reproduce
1.
2.
3.

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- GH-1234
- ...
