### ISSUE TITLE
New install results in MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by rbruhn** [laravel/homestead#1886]
## Versions
  - Vagrant: 2.3.7
  - Provider: Virtualbox 7.0.10 r158379
  - Homestead: `release` branch

## Host operating system
Windows 11

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 6144
cpus: 4
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    -   map: C:\Sites\biospex
        to: /home/vagrant/sites/biospex
        type: "nfs"
        mount_opts: ["nolock", "vers=3", "tcp", "noatime", "rsize=65536", "wsize=65536"]
    
sites:
    -   map: biospex.test
        to: /home/vagrant/sites/biospex/public
        type: laravel
        php: "8.1"

features:
    - mongodb: true
    - python: true
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
```

## Vagrant destroy & up output
https://gist.github.com/rbruhn/1ac076a032c731ac6d90c728da780c96

## Expected behavior
Expectations were Homestead creating the server.

## Actual behavior
Getting error trying to connect to mongo
MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017

I turned off the Windows firewall while performing this. Made no difference.
Any ideas?

## Steps to reproduce
1. New Install
