### ISSUE TITLE
Error connecting MariaDB 11.1.2 from host machine database client 

### ISSUE THREAD

**Issue by arce701** [laravel/homestead#1900]
## Versions
  - Vagrant: Vagrant 2.3.7
  - Provider: Virtual Box 7.0
  - Homestead: Homestead v14.2.0

## Host operating system
Windows 11 Home Single Language 64 bits

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 4096
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: D:\projects
      to: /home/vagrant/projects

sites:
    - map: website.test
      to: /home/vagrant/projects/website/public

databases:
    - homestead

features:
    - mysql: false
    - mariadb: true
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mariadb"
#    - disabled:
#        - "postgresql@11-main"

#ports:
    - send: 33060 # MySQL/MariaDB
      to: 3306
#    - send: 4040
#      to: 4040
```

## Summary
Everything works great except you can't connect to the database using a program like Navicat, HeidiSQL with the default credentials:
Host: 127.0.0.1
Puerto: 33060
Usuario: homestead
Contraseña: secret

returns the following message:
2003 - Can't connect to MySQl server on '127.0.0.1' (10061 "Unknown error")

However, within homestead the service is installed and working, as you can see in the image
![Data](https://i.imgur.com/s2vBilC.png)

I suspect it is due to the change MariaDB made, renaming the service from mysql to mariadb.

help please, I am without my work environment
