### ISSUE TITLE
Creating databases for influxdb was not updated, thus failing provision execution

### ISSUE THREAD

**Issue by PerikiyoXD** [laravel/homestead#1919]
> Other irrelevant details were skipped

## Homestead.yaml
> Relevant section defined
```yaml

databases:
    - example_database

features:
    - influxdb: true

services:
    - enabled:
          - "influxdb"
```

## Expected behavior
Create the database if it isn't created

## Actual behavior
It will halt the script execution as the current database script is not compatible with old behaviour.

Caused by `scripts\create-influxdb.sh` as it wasn't updated to v2 InfluxDB
