### ISSUE TITLE
Constraint Issues with laravel/homestead

### ISSUE THREAD

**Issue by Speedy059** [laravel/homestead#1934]
Vagrant Version: 2.4.0
Virtualization: virtualbox

I followed the official documentation of setting up a new laravel/homestead and once I run `vagrant up` it provides me this error:
```
D:\Homestead(release -> origin)
λ vagrant up
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Box 'laravel/homestead' could not be found. Attempting to find and install...
    homestead: Box Provider: virtualbox
    homestead: Box Version: >= 14.0.2, < 15.0.0
==> homestead: Loading metadata for box 'laravel/homestead'
    homestead: URL: https://vagrantcloud.com/api/v2/vagrant/laravel/homestead
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constraints.

Box: laravel/homestead
Address: https://vagrantcloud.com/api/v2/vagrant/laravel/homestead
Constraints: >= 14.0.2, < 15.0.0
Available versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.3.0, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 1.0.0, 1.0.1, 1.1.0, 2.0.0, 2.1.0, 2.2.0, 3.0.0, 3.1.0, 4.0.0, 5.0.1, 5.1.0, 5.2.0, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 7.0.0, 7.1.0, 7.2.1, 8.0.0.pre.alpha1, 8.0.0.pre.alpha2, 8.0.0.pre.alpha3, 8.0.0.pre.alpha4, 8.0.0.pre.beta, 8.0.0, 8.0.1, 8.1.0, 8.2.0, 8.2.1, 9.0.0, 9.0.1, 9.1.0, 9.1.1, 9.2.0, 9.3.0, 9.4.0, 9.5.0, 9.5.1, 9.6.0, 9.6.1, 9.7.2, 10.0.0, 10.1.0, 10.1.1, 11.0.0, 11.1.0, 11.3.0, 11.4.0, 11.5.0, 12.0.0, 12.1.0, 12.2.0, 13.0.0, 14.0.0, 14.0.1, 14.0.2
```

Any idea how to resolve this? I noticed the exact time I destroyed my older box, v15 was JUST released and not sure if this has something to do with it. I tried deleting my entire Homestead folder and starting over with the git clone, but to no avail.

Homestead.yaml
```
ip: "192.168.56.56"
memory: 8192
cpus: 8
provider: virtualbox

authorize: C:\Users\{EDITED}\.ssh\id_rsa.pub

keys:
    - C:\Users\{EDITED}\.ssh\id_rsa

folders:
    - map: d:\projects
      to: /home/vagrant/code

sites:
    - map: login.kbo.local
      to: /home/vagrant/code/AuthApplication/public
      php: "8.3"
    - map: login.kbo.com
      to: /home/vagrant/code/AuthApplication/public
      php: "8.3"
    - map: tm.kbo.local
      to: /home/vagrant/code/TeacherManager/public
      php: "8.3"

databases:
    - homestead

features:
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailpit
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017
```
