### ISSUE TITLE
Incompatible configuration requested

### ISSUE THREAD

**Issue by baradhili** [laravel/homestead#1942]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.4.0
  - Provider: Virtualbox - 6.1.48.
  - Homestead: release.

## Host operating system
Ubuntu 20.04.6 LTS

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: virtualbox
name: laravel-api

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /home/bret/Documents/Sites/laravel-api/laravel-api/
      to: /home/vagrant/code

sites:
    - map: laravel-api.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"

```

## Vagrant destroy & up output
https://gist.github.com/baradhili/9e1df1bd71b600c28d466c06857ce5eb

## Expected behavior
The box should have launched as it did this morning

## Actual behavior
as per the Gist - it did not launch

## Steps to reproduce
I am not sure, I think an apt update went through this morning - so possibly VirtualBox upgraded

## References
none
