### ISSUE TITLE
Issue with NFS on Windows

### ISSUE THREAD

**Issue by slobich** [laravel/homestead#1966]
When I add NFS support to a site I get this error when I try to visit the site in the browser:
```php
Notice: Unknown: Read of 253 bytes failed with errno=5 Input/output error in Unknown on line 0

Fatal error: Failed opening required '/home/vagrant/code/public/index.php' (include_path='.:/usr/share/php') in Unknown on line 0
```
If I remove `type: "nfs"` everything works as expected.

I have [vagrant-winnfsd](https://github.com/winnfsd/vagrant-winnfsd) plugin installed and if I use an earlier version of homestead NFS works as expected. 

## Versions
  - Vagrant: 2.4.1
  - Provider: Virtualbox 7.0.14
  - Homestead: 14.0.2

## Host operating system
Windows
Edition	Windows 10 Pro
Version	22H2
Installed on	‎25.‎3.‎2024.
OS build	19045.4239
Experience	Windows Feature Experience Pack 1000.19055.1000.0

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: virtualbox

authorize: C:\Users\Neuralab\.ssh\id_ed25519.pub

keys:
    - C:\Users\Neuralab\.ssh\id_ed25519

folders:
    - map: C:\Users\Neuralab\code
      to: /home/vagrant/code
      type: "nfs"

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

features:
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailpit
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017

```

## Vagrant destroy & up output
https://gist.github.com/slobich/fd4eacc924eba473ef285e4f5b54bdea

## Expected behavior
I should be able to access the site via http://homestead.test/

## Actual behavior
When I add NFS support to a site I get this error when I try to visit the site in the browser:
```php
Notice: Unknown: Read of 253 bytes failed with errno=5 Input/output error in Unknown on line 0

Fatal error: Failed opening required '/home/vagrant/code/public/index.php' (include_path='.:/usr/share/php') in Unknown on line 0
```
If I remove `type: "nfs"` everything works as expected.

## Steps to reproduce
1. Install Homestead on Windows computer as described [here](https://laravel.com/docs/11.x/homestead#installation-and-setup).
2. Enable NFS as described [here](https://laravel.com/docs/11.x/homestead#installation-and-setup).
3. Provision the server.
4. Create an `index,php` file in the `public` directory.
5. Try to access http://homestead.test/.
