### ISSUE TITLE
Adding type: "nfs" in homestead.yaml causes Internal Server Error 500 on website

### ISSUE THREAD

**Issue by hcanning** [laravel/homestead#1968]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Run `vagrant -v` to show the version. = Vagrant 2.4.1
  - Provider: Virtualbox, VMWare, Hyper-V, or Parallels and its version. = Virtual Box 6.1.5.0
  - Homestead: You should be on the most recent `release` branch. = latest

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
This is the operating system that you run locally. Windows 11 Pro

## Homestead.yaml
```
---
ip: "192.168.56.56"
memory: 16384
cpus: 4
provider: virtualbox
ssl: true
natdnshostresolver: off

authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:\Users\hcann\vagrant\drupaldefault
      to: /home/vagrant/drupaldefault
      type: "nfs"
   
sites:
    - map: drupaldefault.test
      to: /home/vagrant/drupaldefault/web
      
databases:
    - homestead
  
mariadb: true

backup: true
    

```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
What should have happened? Please include as much detail as possible.

Drupal website loads fine without nfs. Adding  type: "nfs" causes internal server error. Nothing in error log to suggest how to fix.
nfs plugin is installed.

## Actual behavior
What actually happened? Please include as much detail as possible.

## Steps to reproduce
1. Create a wordpress or drupal website and try and display it with nfs enabled
2.
3.

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- GH-1234
- ...
