### ISSUE TITLE
Xdebug not enabled for PHP 5.6

### ISSUE THREAD

**Issue by ChrisTaylorDeveloper** [laravel/homestead#1974]
## Versions
  - Vagrant: 2.4.1
  - Provider: Virtualbox 7.0
  - Homestead: On commit 9db11b4e2b609caba6d48cac4b352c24db42eac4

## Host operating system
Ubuntu 22.04.4 LTS

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
  - ~/.ssh/id_rsa

folders:
  - map: ~/xdebug-test
    to: /home/vagrant/xdebug-test

sites:
  - map: xdebug-test.test
    to: /home/vagrant/xdebug-test/public
    php: "5.6"

databases:
  - homestead

features:
  - mariadb: false
  - postgresql: false
  - ohmyzsh: false
  - webdriver: false

services:
  - enabled:
      - "mysql"

```

## Vagrant destroy & up output
https://gist.github.com/ChrisTaylorDeveloper/46f178d0af7349d481c2a53ca8c8a4d3

## Expected behavior
xdebug for php5.6 should be enabled.

## Actual behavior
xdebug for php5.6 is not enabled.  If I run `ls /etc/php/5.6/fpm/conf.d/` the xdebug.ini is not in the list of enabled modules.

## Steps to reproduce
1. `vagrant up` using my Homestead.yml
2. Run `ls /etc/php/5.6/fpm/conf.d/`
3. Look for the xdebug.ini
