### ISSUE TITLE
NPM issue

### ISSUE THREAD

**Issue by Kukindoo** [laravel/homestead#1981]
When I run vagrant

## Versions
  - Vagrant: Vagrant 2.4.1
  - Provider: Virtualbox 7.0.12
  - Homestead: 14.0.2

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 4096
cpus: 4
provider: virtualbox
version: 14.0.2

authorize: ~/.ssh/id_rsa.pub

keys:
  - ~/.ssh/id_rsa

folders:
    - map: C:\Users\user\A_codes\dev\laravel-10-website
      to: /home/vagrant/code/mrams
    - map: C:\Users\user\A_codes\dev\csu_automation\csu_website
      to: /home/vagrant/code/csu
    - map: C:\Users\user\A_codes\dev\laravel-11-website\pmmrc
      to: /home/vagrant/code/pmmrc

sites:
  - map: mrams.test
    to: /home/vagrant/code/mrams/public
    php: "8.1"
  - map: csu.test
    to: /home/vagrant/code/csu/public
    php: "8.1"
  - map: pmmrc.test
    to: /home/vagrant/code/pmmrc/public
    php: "8.2"

databases:
    - mrams
    - csu
    - pmmrc

features:
  - mariadb: false
  - postgresql: false
  - ohmyzsh: false
  - webdriver: false

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

ports:
   - send: 33060 # MySQL/MariaDB
     to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
   - send: 8025 # Mailhog
     to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017

```

## Expected behavior
npm installing the packages

## Actual behavior
vagrant@homestead:~/code/pmmrc$ npm run build
npm ERR! code ENOTSUP
npm ERR! syscall read
npm ERR! errno -95
npm ERR! Could not read package.json: Error: ENOTSUP: operation not supported on socket, read

vagrant@homestead:~/code/pmmrc$ sudo npm install
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string or an instance of Buffer or URL. Received null

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-06-13T00_23_22_908Z-debug-0.log

## Steps to reproduce
0. Vagrant up & vagrant ssh
1. cd into pmmrc folder
2. Follow livewire path of https://jetstream.laravel.com/installation.html installation in pmmrc folder
3. When php artisan jetstream:install livewire, then npm ERR! code ENOTSUP happens.
