### ISSUE TITLE
laravel/homestead could not be found

### ISSUE THREAD

**Issue by tjerkhamer** [laravel/homestead#1982]
## Versions
  - Vagrant: 2.4.1
  - Provider: Virtualbox: 7.0.18
  - Homestead: current (15.0.3)

**I'm using a complete fresh / new install for my pc**

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
  - ~/.ssh/id_rsa

folders:
  - map: ~/code
    to: /home/vagrant/code

sites:
  - map: homestead.test
    to: /home/vagrant/code/public

databases:
  - homestead

features:
  - mariadb: false
  - postgresql: false
  - ohmyzsh: false
  - webdriver: false

services:
  - enabled:
      - "mysql"

```

## Vagrant destroy & up output
[Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.](https://gist.github.com/tjerkhamer/8281b6122cf2603ac10f2b3ce9224c62)
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
I would expect the homestead box to be created as described in the documentation

## Actual behavior
Vagrant up is not possible, laravel/homestead could not be found and is not downloading from vagrantcloud.com

## Steps to reproduce
1. clean windows install
2. git clone https://github.com/laravel/homestead.git ~/Homestead
3. git checkout release
4.  ./init.bat
5. vagrant up
