### ISSUE TITLE
Slashes and backslashes on Windows

### ISSUE THREAD

**Issue by taai** [laravel/homestead#25]
I ran into a problem on Windows 7 x64.

Error was thrown:

```
/tmp/vagrant-shell: line 1: /home/vagrant/.ssh/$2: ambiguous redirect
```

My `Homestead.yaml` contents:

```

---
authorize: C:\Users\Me\.ssh\id_rsa.pub

keys:
    - C:\Users\Me\.ssh\id_rsa

folders:
    - map: C:\var\www
      to: /home/vagrant/www

sites:
    - map: awesome.app
      to: /home/vagrant/www/awesome/public
```

Everything went went fine after I replaced all backslashes `\` with slashes `/`.

Would be cool if Homestead did at least tell me to use forward-slashes only, even on Windows.

Otherways, good job! :wink:
