### ISSUE TITLE
Not able to connect to VM on Windows 7

### ISSUE THREAD

**Issue by jaden** [laravel/homestead#370]
### Vagrant version
Vagrant 1.9.0

### Provider & Provider version
VirtualBox 5.0.30 r112061

### Host operating system
Windows 7 x64 Ultimate SP1

### Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 1024
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: D:\Dev\projects
      to: /home/vagrant/projects

sites:
    - map: '~^(?<project>.+)\.app$'
      to: /home/vagrant/projects/\$project/public

databases:
    - homestead
```

### Vagrant up output
https://gist.github.com/jaden/ea07b79d9f55e84d80244486b84fbac6

### Expected behavior
192.168.10.10 should have been set as the static IP

### Actual behavior
The VM appears to hang, but the console shows the following message (updating until the 5 minutes have elapsed)

[***   ] A start job is running for Raise network interface (2min 35s / 5min 3)

Once the VM boots, it has no static ip, as ifconfig shows:
```
enp0s3    Link encap:Ethernet  HWaddr 08:00:27:b5:5b:5e
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:144901 errors:0 dropped:0 overruns:0 frame:0
          TX packets:39078 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:69 errors:0 dropped:0 overruns:0 frame:0
          TX packets:69 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:36681 (36.6 KB)  TX bytes:36681 (36.6 KB)
```

### Steps to reproduce
1. Run vagrant up with the laravel/homestead box version 0.6.0 on a Windows 7 host.
2. Wait for the 5 minute time-out

Using the previous box version (0.5.0) by adding the following line to Homestead.yaml sets the static IP and boots up normally:
version: "0.5.0"
