### ISSUE TITLE
Issue upgrading to 0.3.3

### ISSUE THREAD

**Issue by willdoran** [laravel/homestead#377]
Please note that the Homestead issue tracker is reserved for bug reports and
enhancements. We are not always able to debug Vagrant, Virtualbox, VMWare, or Operating System issues but will do our best to help. Thank you!

### Vagrant version
1.9.0

### Provider & Provider version
5.1.10

### Host operating system
OS X

### Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
hostname: rollcall
name: rollcall
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "./"
      to: "/home/vagrant/rollcall"

sites:
    - map: rollcall.dev
      to: "/home/vagrant/rollcall/public"

databases:
    - rollcall

variables:
    - key: APP_ENV
      value: local

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 93000
#       to: 9300
#     - send: 7777
#       to: 777
#       protocol: udp
```

### Vagrant up output
https://gist.github.com/willdoran/0c457bc552f3e68ac7af653b97c04aee

### Expected behavior
Vagrant should update to a newer version of homestead and vagrant up should correctly boot and provision the VM

### Actual behavior
Provisioning fails due to an expired password
Repaired by the following:
vagrant ssh
mysql -uhomestead -psecret -e "SET PASSWORD  = PASSWORD('secret')" --connect-expired-password;
mysql -uroot -psecret -e "SET PASSWORD  = PASSWORD('secret')" --connect-expired-password;
exit
vagrant provision

### Steps to reproduce
1. On version 0.3.0 run vagrant box update
2. Run vagrant up
