### ISSUE TITLE
Virtualbox doesn't connect the network adapter cable

### ISSUE THREAD

**Issue by JulienTant** [laravel/homestead#383]
### Vagrant version
Vagrant 1.9.0

### Provider & Provider version
Virtualbox 5.0.30 ; Virtualbox 5.0.10 ; Virtualbox 5.1.2

### Host operating system
Sierra ; Windows 10

### Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
hostname: reploc
name: reploc
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "/Users/a/Sites/Reploc"
      to: "/home/vagrant/reploc"

sites:
    - map: homestead.app
      to: "/home/vagrant/reploc/public"

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

### Vagrant up output
https://gist.github.com/JulienTant/f81d9f9b2bafa76a784946400214314f

### Expected behavior
Vagrant creates a virtualbox machine with a connected cable

### Actual behavior
Vagrant creates a virtualbox machine with a **dis**connected cable

### Steps to reproduce
1. vagrant destroy
2. vagrant up

### Steps to fix manually
1. vagrant destroy
2. vagrant up
3. vagrant halt
4. Go to the VM VB settings to connect the cable manually
5. vagrant up

### References
- https://github.com/mitchellh/vagrant/issues/7648
- Fix proposal : https://github.com/laravel/homestead/pull/382
