### ISSUE TITLE
[BUG] PHP Version and Location in /etc/nginx/sites-enabled/homestead.app 

### ISSUE THREAD

**Issue by j-jmdk** [laravel/homestead#405]
The currently released version created 16 days ago (as of this post) in the "virtualbox" provider contains a bug in the homstead.app file.
This bug shows when running "vagrant up", whereby it is told that PHP7.1 is not found.
Fix is posted below.

## Versions
  - Vagrant: Vagrant 1.9.1
  - Provider: VirtualBox 5.1.12
  - Homestead: homestead 1.0.1

## Host operating system
Windows 8.1

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

folders:
    - map: C:/Users/Administrator/homestead_improved-master
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Project/public

databases:
    - homestead

variables:
    - key: APP_ENV
      value: local

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 93000
#       to: 9300
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant up output
SSH error: Git Bash displays that PHP7.0 is not found (and thus does not load).

## Expected behavior
Homestead 1.0.1 contains PHP7.1 and not PHP7.0, and should have loaded normally and displayed web pages normally.

## Actual behavior
PHP7.1 is not loaded, and 502 Gateway errors arise.

## Fixing the bug manually
In the VM, in this file: /run/php/php7.1-fpm.sock
It is written:

`
...
 fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
...
`

Modify it to:

`...
 fastcgi_pass unix:/run/php/php7.1-fpm.sock;
...
`

 And then manually restart:
`sudo service nginx restart`
`sudo service php7.1-fpm reload`

However every time I provision the bug reappears.
Please release an update to fix this issue.

## References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- Same bug reported in a different thread (my mistake)
https://github.com/laravel/framework/issues/16904
