### ISSUE TITLE
IPv6 DNS Resolution Broken

### ISSUE THREAD

**Issue by orediggerco** [laravel/homestead#409]
## Versions
  - Vagrant: 1.9.1
  - Provider: VirtualBox 5.1.10
  - Homestead: 4.0.0

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
hostname: test
name: test
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "C:/Users/Adam/workspace/test"
      to: "/home/vagrant/test"

sites:
    - map: test.app
      to: "/home/vagrant/test/public"

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Expected behavior
IPv6 DNS resolution from inside the Homestead vm should work correctly whether this is via OS tools such as dig/nslookup or php commands such as dns_get_record(). 

## Actual behavior
IPv6 (AAAA type) queries are failing using any method.

### Examples
From inside Homestead VM:
```
~$ php artisan tinker
Psy Shell v0.8.0 (PHP 7.1.0-2+deb.sury.org~xenial+1 — cli) by Justin Hileman
>>> dns_get_record('google.com', DNS_A+DNS_AAAA);
PHP warning:  dns_get_record(): A temporary server error occurred. on line 1
>>> dns_get_record('google.com', DNS_A);
=> [
     [
       "host" => "google.com",
       "class" => "IN",
       "ttl" => 3600,
       "type" => "A",
       "ip" => "216.58.217.46",
     ],
   ]
>>> dns_get_record('google.com', DNS_AAAA);
PHP warning:  dns_get_record(): A temporary server error occurred. on line 1

(homestead)~$ nslookup -type=AAAA google.com
Server:         10.0.2.3
Address:        10.0.2.3#53

** server can't find google.com: NOTIMP
```

From host machine:
```
$ php artisan tinker
Psy Shell v0.8.0 (PHP 7.1.0 — cli) by Justin Hileman
>>> dns_get_record('google.com', DNS_AAAA);
=> [
     [
       "host" => "google.com",
       "class" => "IN",
       "ttl" => 146,
       "type" => "AAAA",
       "ipv6" => "2607:f8b0:400f:803::200e",
     ],
   ]

(host)$ nslookup -type=AAAA google.com
Server:  cdns01.comcast.net
Address:  75.75.75.75

Non-authoritative answer:
Name:    google.com
Address:  2607:f8b0:400f:802::200e
```
## References
Moving conversation from https://github.com/laravel/framework/issues/14846 regarding active_url validation rule not working within homestead VMs.

## My Investigation
It appears that this issue is due to the VirtualBox network setting "natdnshostresolver1" which is set to "on" in the [homestead.rb script](https://github.com/laravel/homestead/blob/master/scripts/homestead.rb#L37).

Changing this setting to "off" (the VirtualBox default) and reloading the vagrant configuration allows IPv6 name resolution to work just fine.
```
$ vagrant suspend
==> test: Saving VM state and suspending execution...
$ VBoxManage modifyvm "test" --natdnshostresolver1 off
$ vagrant up
Bringing machine 'test' up with 'virtualbox' provider...
// redacted output
$ vagrant ssh
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-51-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

3 packages can be updated.
0 updates are security updates.


Last login: Sat Dec 24 19:08:10 2016 from 10.0.2.2
vagrant@test:~$ nslookup -type=AAAA google.com
Server:         10.0.2.3
Address:        10.0.2.3#53

Non-authoritative answer:
google.com      has AAAA address 2607:f8b0:400f:803::200e

Authoritative answers can be found from:

vagrant@test:~$
```

I'm not sure if there are other things within Homestead that rely on this `natdnshostresolver1` option being set, but it does appear that it's causing IPv6 name queries to fail, which in turn make Laravel's `active_url` validation rule to fail since the `DNS_AAAA` type will result in an exception.
