### ISSUE TITLE
no kex alg

### ISSUE THREAD

**Issue by merodiro** [laravel/homestead#414]
## Versions
  - Vagrant: Run `vagrant -v` to show the version.
  - Provider: Virtualbox 5.1.12
  - vagrant: 1.9.1

## Host operating system
windows 8.1

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 4
provider: virtualbox
mariadb: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Desktop/Code
      to: /home/vagrant/Code

sites:
    - map: laravel-vue.app
      to: /home/vagrant/Code/laravel-vue/public
    - map: blog.dev
      to: /home/vagrant/Code/blog-laravel/public

databases:
    - homestead
```

## problem

I get that error when I run `cagrant ssh`
> no kex alg

## vagrant up
https://gist.github.com/merodiro/2abaceb4ef65019d30cb91f7f13755f6
