### ISSUE TITLE
Cannot run vagrant ssh -c command

### ISSUE THREAD

**Issue by cwandling** [laravel/homestead#417]
## Versions
  - Vagrant: Vagrant 1.9.1
  - Provider: Virtualbox 5.12
  - Homestead: Laravel Homestead version 3.0.2

## Host operating system
OSX 10.12.2

## Homestead.yaml
```yaml
---
ip: "192.168.10.12"
memory: 4096
cpus: 2
hostname: maestro
name: maestro
provider: virtualbox
version: 0.5.0
shell: bash
authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "~/code/seneca/maestro"
      to: "/home/vagrant/maestro"

sites:
    - map: maestro.senecatank.dev
      to: "/home/vagrant/maestro/public"

databases:
    - maestro_dev
    - maestro_test
    - maestro_acceptance
```

## output
I run
```sh
vagrant ssh -c ls
```
and it leaves me at the bash prompt in the vagrant vm as if I had just done
```sh
vagrant ssh
```
## Expected behavior
It should (in this case) login to the vagrant instance, perform and `ls` and then exit from the ssh session.

## Actual behavior
It just logins into the vagrant instance and leaves you at a bash shell.
