### ISSUE TITLE
Vagrant could not ssh into the box

### ISSUE THREAD

**Issue by nWidart** [laravel/homestead#423]
## Versions
  - Vagrant: 1.9.1
  - Provider: Virtualbox 5.0.30-11
  - Homestead: 4

I installed latest version of vagrant and virtualbox to make sure.

## Host operating system
MacOS

## Homestead.yaml
```yaml

---
ip: "192.168.10.10"
memory: 2048
cpus: 1
hostname: site-name
name: site-name
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "/Users/nicolaswidart/Sites/Freelance/Client/site-name"
      to: "/home/vagrant/site-name"

sites:
    - map: site-name.app
      to: "/home/vagrant/site-name/public"

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant up output
https://gist.github.com/nWidart/56efeaebde588c9c382da0d1546c729e

## Expected behavior
It should provision the server

## Actual behavior
It errored when trying to ssh into the box.

## Steps to reproduce
1. composer require --dev laravel/homestead
2. php vendor/bin/homestead make --after --aliases
3. vagrant up

Thanks.
