### ISSUE TITLE
yarn run watch not working + yarn run dev very slow

### ISSUE THREAD

**Issue by Mayesters** [laravel/homestead#439]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues but will do our best to help. Thank you!

## Versions
  - Vagrant: 1.9.1
  - Provider: Virtualbox  5.1.14
  - Homestead: homestead --version command is not available inside the VM.

## Host operating system
Windows 8.1 (i7 4770k, 16GB RAM)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
hostname: test
name: test
provider: virtualbox

authorize: ssh/id_rsa.pub

keys:
    - ssh/id_rsa

folders:
    - map: "F:/test"
      to: "/home/vagrant/test"

sites:
    - map: homestead.app
      to: "/home/vagrant/test/src/testtool/public"

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant up output
https://gist.github.com/Mayesters/8e3e501e35b121cf447df8596ef4b376

## Expected behavior

1.
Whenenver I run yarn run watch, I think all updates to the code should be packed automatically without the need to run yarn again.

2.
Running yarn run dev should take a few (1-5) seconds.

## Actual behavior
What actually happened?

1.
When running yarn run watch in my main laravel folder (where the package.json is located), after compiling it does not notice any file changes done to the Javascript files. Nothing happens if a change occures.

2.
Running yarn run dev (and watch) takes over 20 seconds to compile, with an i7 4770k and 16GB. That's not normal, is it? Atleast from the Laravel videos I've watched, compiling (packing) should be much faster.

## Steps to reproduce
1. Install Laravel Homestead
2. Run yarn run watch in the main project folder
3. Change your code, nothing happens if you reload the page (+ no new console output)
