### ISSUE TITLE
Root mysql login not working

### ISSUE THREAD

**Issue by josecybertill** [laravel/homestead#453]
I updated to the latest version of the Homestead box and am no longer able to login to mySQL as root, I used to do it using 'secret' as the password, has something changed?

**Comment by svpernova09** [comment]
Please fill out the entire issue template so we don't have to ask you what versions of everything your using to properly help you. https://github.com/laravel/homestead/issues/new

**Comment by josecybertill** [comment]
Hi @svpernova09, here are the details, just so you know, it may be 'settler' related, same problem with box version 1.1.0 and 1.0.1

I have tested with 0.2.7 and it works just fine, haven't tested any other box versions.

## Versions
  - Vagrant 1.9.1
  - Provider: Virtualbox
  - Homestead: I installed manually, don't have the homestead command, but am in the latest commit '5570bcb', I believe tagged as 4.0.5

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
  - ~/.ssh/id_rsa

folders:
  - map: ~/projects
    to: /home/vagrant/projects

sites:
  - map: cybertill.app
    to: /home/vagrant/projects/info
```
