### ISSUE TITLE
Using serve-apache.sh script to setup and config apache

### ISSUE THREAD

**Issue by martijnimhoff** [laravel/homestead#455]
## Versions
  - Vagrant 1.9.1
  - Provider: Virtualbox 5.1.2 r108956
  - Homestead: laravel/homestead 1.1.0

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "D:/devprojects/valemus-starter"
      to: "/home/vagrant/valemus-starter"

sites:
    - map: valemus-starter.nodots
      to: "/home/vagrant/valemus-starter"

databases:
    - valemus-starter
```

## after.sh content
```
#!/bin/sh

# If you would like to do some extra provisioning you may
# add any commands you wish to this file and they will
# be run after the Homestead machine is provisioned.

sudo npm install -g n
sudo n stable

sudo service nginx stop
sudo apt-get remove nginx
sudo sh /vagrant/scripts/serve-apache.sh
```

## Vagrant up output
https://gist.github.com/martijnimhoff/b46abc3c468515c1ebd05394a1d657a2

## Expected behavior
I expected this script install and configure apache acording to Homestead.yaml. (I don't know if it is actually meant to this, if not how can i do this?) Can this script be used to config the sites specified in Homestead.yaml?

## Actual behavior
Apache did install but no config was made in `/etc/apache2/sites-available`

## Steps to reproduce
1. Use `Homestead.yaml` and `after.sh` as mentioned above
2. `vagrant up`
