### ISSUE TITLE
Old Versions, PHP5

### ISSUE THREAD

**Issue by EvodiaAut** [laravel/homestead#460]
Hi,

i use the release "v4.0.5" it's work perfect!
So now i need a downgrade for a old website and it's run in php5.

On the documentation stay write in Homestead.yaml `version: 0.6.0`.

Now i installed `laravel/homestead -–box-version 0.3.0`  and write in Homestead.yaml `version: 0.3.0`.
But it doesn't work (PHP-7 is installed every time)

I read this https://laravel.io/forum/02-03-2016-install-specific-laravel-homestead-version-and-502-bad-gateway-nginx-solved or other documentations but all is so confused. Can you said me the right way to downgrade current stable version?

**Comment by svpernova09** [comment]
https://laravel-news.com/using-older-versions-of-homestead

Follow the section "How to Use PHP 5.5 With Laravel Homestead"

**Comment by EvodiaAut** [comment]
Thx!

A small idea is to add optional a php version.

**on site**
```yaml
sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public
      php: 5.6
```
**or global**
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
php: 5.6
```
