### ISSUE TITLE
[MariaDB 10.2.4] Can't import dump

### ISSUE THREAD

**Issue by tomcoonen** [laravel/homestead#508]
## Versions
  - Vagrant: 1.9.2
  - Provider: Virtualbox 5.1.14
  - Homestead: 1.9.2

## Host operating system
MacOS 10.12.3

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
mariadb: true

```

When importing a ~75MB .sql dump (mysql-dump) it doesn't process and causes high CPU loads.
Doing exactly the same using MySQL (5.7.17), it's done in seconds.

When using a previous Homestead box with MariaDB 10.1 it worked fine.

I've done some research but don't seem to find a solution.
