### ISSUE TITLE
Inconsitency between folders mapping an sites mapping for `.` containing folder name

### ISSUE THREAD

**Issue by pluxain** [laravel/homestead#509]
When a homestead instance is created locally in a folder containing a `.` the dot is replaced by a `-` in the folders mapping but not in the sites mapping. This breaks the installation.

## Versions
  - Vagrant: 1.9.1
  - Provider: Virtualbox 5.1.16 r113841
  - Homestead: 2.0.17

## Host operating system
MacOS X 10.12.3

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    - { map: /Users/pln/Projects/7s/test.com, to: /home/vagrant/Code/test-com }
sites:
    - { map: test.com.app, to: /home/vagrant/Code/test.com/public }
databases:
    - homestead
name: test-com
hostname: test-com
```

## Vagrant up output
Irrelevant

## Expected behavior
Any `.` contained in the folder name should be replaced by a `-` in the sites mapping.

Expected result :
```yaml
folders:
    - { map: /Users/pln/Projects/7s/test.com, to: /home/vagrant/Code/test-com }
sites:
    - { map: test.com.app, to: /home/vagrant/Code/test-com/public }
```

## Actual behavior
Any `.` contained in the folder name is replaced by a `-` in the folders mapping but remains a `.` in the site mappings which makes the server not working.
Actual :
```yaml
folders:
    - { map: /Users/pln/Projects/7s/test.com, to: /home/vagrant/Code/test-com }
sites:
    - { map: test.com.app, to: /home/vagrant/Code/test.com/public }
```
