### ISSUE TITLE
The option -c (--command) is not working as it should

### ISSUE THREAD

**Issue by diegoholiveira** [laravel/homestead#514]
This problem only happens with Homestead. If I run this with a more simple vagrant environment (like `ubuntu/trusty64`, everything runs fine.

## Versions

VirtualBox: 5.1.14 r112924

```
12:32:47 [✔] $: vendor/bin/homestead --version
Laravel Homestead 4.0.5
```

```
11:32:52 [✔] $: vagrant --version
Vagrant 1.9.2
```

## Host operating system
macOS Sierra (10.12.3)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 256
cpus: 1
hostname: forsocios
name: forsocios
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "/Users/diegoholiveira/Projects/forsocios"
      to: "/home/vagrant/forsocios"

sites:
    - map: www.forsocios.io
      to: "/home/vagrant/forsocios/apps/site/public"
      schedule: true
    - map: admin.forsocios.io
      to: "/home/vagrant/forsocios/apps/admin/public"
      schedule: true
    - map: checkin.forsocios.io
      to: "/home/vagrant/forsocios/apps/checkin/public"
      schedule: true
    - map: convites.forsocios.io
      to: "/home/vagrant/forsocios/apps/convites/public"
      schedule: true

databases:
    - site
    - site_test
    - admin
    - admin_test
    - checkin
    - checkin_test
    - convites
    - convites_test
```

## Vagrant up output
Provide a link to a GitHub Gist containing the complete output.
Do NOT paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior

It should execute the command and exit, like those examples:

```
12:31:32 [✔] $: vagrant ssh -c date
Sat Mar 11 15:31:42 UTC 2017
Connection to 127.0.0.1 closed.

11:46:05 [✔] $: vagrant ssh -- date
Sat Mar 11 14:46:05 UTC 2017
```

## Actual behavior

```
11:41:46 [✔] $: vagrant ssh -c date
vagrant@forsocios:~$

11:45:44 [✔] $: vagrant ssh --command date
vagrant@ forsocios:~$ 
```

## Steps to reproduce
1. Creates an environment with homestead;
2. Run the `vagrant up`;
3. Try to execute a command with `vagrant ssh -c` or `vagrant ssh --command`;
