### ISSUE TITLE
Vagrant was unable to mount VirtualBox shared folders

### ISSUE THREAD

**Issue by svenluijten** [laravel/homestead#517]
This may not actually be an issue with Homestead, but should be reported upstream to either Vagrant or VirtualBox. I apolagize in advance if that is the case, I noticed it happened with the latest VBox and Vagrant versions.

## Versions
  - Vagrant: 1.9.2
  - Provider: Virtualbox (version 5.1.16r113841)

## Host operating system
Windows 10 with Bash for Windows enabled.

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_ed25519.pub

keys:
    - ~/.ssh/id_ed25519

folders:
    - map: E:/Code
      to: /home/vagrant/Code

sites:
    - { map: site.dev, to: /home/vagrant/Code/GitHub/site/public }

databases:
    - site

ports:
    - { send: 8025, to: 8025 }

```

## Vagrant up output
https://gist.github.com/svenluijten/99369ad286d61e5875202567ff75ad49

## Expected behavior
I expected the configured shared folders to be mounted correctly.

## Actual behavior
Instead, the output as shown in the gist is given.

## Steps to reproduce
1. Download the latest versions of VirtualBox (5.1.16r113841) and Vagrant
2. Run `vagrant up` from your `~/Homestead` directory
3. See error
