### ISSUE TITLE
Homestead settings file not found after update

### ISSUE THREAD

**Issue by doncadavona** [laravel/homestead#519]
Can't start homestead upon successful update via $ `vagrant box update` then $ `git pull origin master`. Afterwards, the command $ `vagrant up` can't find the Homestead settings file.

## Versions
  - Vagrant: 1.9.1
  - Provider: Virtualbox 5.1.14
  - Homestead: (Can't see) **homestead: command not found** with the issue. I guess *0.4.4* based on:

```
$ vagrant box list
laravel/homestead (virtualbox, 0.4.4)
laravel/homestead (virtualbox, 2.0.0)
```

## Host operating system
macOS 10.12.3

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code
      type: nfs

sites:
    - map: laravel.app
      to: /home/vagrant/Code/laravel/public


databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant up output
Homestead settings file not found in /Users/doncadavona/Homestead
Homestead settings file not found in /Users/doncadavona/Homestead

## Expected behavior
The homestead app should run.

## Actual behavior
$ `vagrant up` outputs:
Homestead settings file not found in /Users/doncadavona/Homestead
Homestead settings file not found in /Users/doncadavona/Homestead

## Steps to reproduce
1. Update homestead: $ `vagrant box update`
2. Cancel the update by hitting CTRL + C while the update is downloading.
3. Retry update: $ `vagrant box update` (let it finish)
4. Run $ `vagrant up`, `vagrant reload --provision` or `vagrant box add laravel/homestead`.
