### ISSUE TITLE
xDebug Configuration

### ISSUE THREAD

**Issue by mikeerickson** [laravel/homestead#530]
It doesnt seem that xDebug is either installed, or active with the 5.0 box?

## Versions
  - Vagrant: 1.9.3
  - Provider: Virtualbox
  - Homestead: Vagrant 1.9.3
  - VirtualBox: 5.1.18

## Host operating system
macSierra 10.12.3

## Homestead.yaml
```
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Documents/code/laravel
      to: /home/vagrant/code

sites:
    - map: l55-test.app
      to: /home/vagrant/code/l55-test/public

databases:
    - homestead
```

## Expected behavior
I may be wrong, but I thought xDebug would be included in base box

## Actual behavior
No xDebug available
