### ISSUE TITLE
Homestead requires net-tools package for IP access to work.

### ISSUE THREAD

**Issue by david-polak** [laravel/homestead#534]
## Versions                                                                                                                                                                                
Vagrant 1.9.2
VirtualBox Version 5.1.18 r114002
Homestead HEAD detached at v5.1.0

## Host operating system
Arch Linux 4.10.6-1-ARCH

## Homestead.yaml
```
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Data/Code/laravel
      to: /home/vagrant/laravel

sites:
    - map: photshr.app
      to: /home/vagrant/laravel/photshr/public

databases:
    - photshr
```

## /etc/hosts                                                                                                                                                         
```
#
# /etc/hosts: static lookup table for host names
#

#<ip-address>	<hostname.domain.org>	<hostname>
127.0.0.1	localhost.localdomain	localhost
::1		localhost.localdomain	localhost
127.0.0.1	dntb.localdomain	dntb

192.168.10.10  	photshr.app
```

## Expected behavior
photoshr.app should be accessible by ping or http

## Actual behavior
photoshr.app was not accessible. Fixed by installing deprecated net-tools package.

## Steps to reproduce
1. Remove net-tools package
2. vagrant destroy
3. vagrant up
