### ISSUE TITLE
MySQL bandwidth issues on the host

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/homestead#539]
## Versions
  - Vagrant: 1.9.3
  - Provider: Virtualbox
  - Homestead: 5.1.0

## Host operating system
Ubuntu 16.04.2 LTS

## Expected behavior

I was restoring a database from production to Homestead using DBeaver and noticed it being extremely slow even though the dump is relatively small, 255 megabytes. I am getting speeds around 50KiB/s where as on directly on the guest I can get relatively normal speeds. Then I measured this on the command line and having the same results. I used to do the same thing on Windows 10 host and did not have this issue, so it might be something to do with the Ubuntu host.

```
vagrant@homestead:~/Code$ pv dump-digital-distribution-201704101055.sql | mysql -uhomestead -psecret digital-distribution
mysql: [Warning] Using a password on the command line interface can be insecure.
18.5MiB 0:00:03 [6.12MiB/s] [=======================================================================================================>] 100%
```

## Actual behavior

```
lasleh@CPB2189:~/Desktop$ pv dump-digital-distribution-201704101055.sql | mysql -uhomestead -psecret -h127.0.0.1 --port=33060 digital-distribution
mysql: [Warning] Using a password on the command line interface can be insecure.
18,5MiB 0:06:22 [49,6KiB/s] [======================================================================================================>] 100%
```

**Comment by svpernova09** [comment]
Can you share your Homestead.yaml please.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by lasselehtinen** [comment]
I have nothing special in the Homestead config so I thought it is irrelevant to post it. 

```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: digital-distribution.development
      to: /home/vagrant/Code/digital-distribution/public

databases:
    - homestead
    - digital-distribution

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 7777
#       to: 777
#       protocol: udp

```
after.sh
```
# Install SOAP and intl extension plus Java
sudo apt-get -y -qq install php-soap > /dev/null 2>&1
sudo apt-get -y -qq install php-intl > /dev/null 2>&1
sudo apt-get -y -qq install default-jre > /dev/null 2>&1
```
