### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by dqlopez** [laravel/homestead#547]
## Versions
  - Vagrant: Vagrant 1.9.3
  - Provider: Virtualbox
  - Homestead: v5.2.1

## Host operating system
Lubuntu 16.04 32-bit

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 512
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Web
      to: /var/www/html
      type: "nfs"

sites:
    - map: base.local
      to: /var/www/html/base
```

## Vagrant up output
```
homestead-7: Forwarding ports...
homestead-7: 80 (guest) => 8000 (host) (adapter 1)
```

## Expected behavior
Access site http://base.local:8000/ on my host browser

## Actual behavior
Cannot access it with the forwarded port (base.local refused to connect.), instead I can access it directly on port 80 http://base.local/. My question is, shouldn't the port forwarding works the other way around?
