### ISSUE TITLE
How to specify port on proxy pass of nginx

### ISSUE THREAD

**Issue by dqlopez** [laravel/homestead#548]
Trying to figure out on documentation but cannot seem to find it. How can I specify the port that will be serve here `proxy_pass http://127.0.0.1:${2};`?

## Homestead.yaml
```
---
ip: "192.168.10.10"
memory: 512
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Web
      to: /var/www/html
      type: "nfs"

sites:
    - map: test.local
      to: /var/www/html/test
      type: proxy
```
With the YAML above, it will generate this error on nginx during provision:
```
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
```
And looking at the generated sites-available, the port on **proxy_pass** has no value which cause the error:
```
location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:/var/www/html/test;
    }
```

**Comment by svpernova09** [comment]
From the `aliases` file:

```
function serve-proxy() {
    if [[ "$1" && "$2" ]]
    then
        sudo dos2unix /vagrant/scripts/serve-proxy.sh
        sudo bash /vagrant/scripts/serve-proxy.sh "$1" "$2" 80
    else
        echo "Error: missing required parameters."
        echo "Usage: "
        echo "  serve-proxy domain port"
    fi
}
```

You should be using `serve-proxy domain port`, where the port is the `${2}` value.

If you are using Homestead per project, you may be missing your `aliases` file. If so just run`php vendor/bin/homestead make --aliases`.

You can verify your aliases are working by `vagrant ssh` and inspecting the `.bash_aliases` file in `/home/vagrant`

**Comment by dqlopez** [comment]
I am not using Homestead per project. Where is the value of `${2}` being fetched?

**Comment by svpernova09** [comment]
We pass the value here: https://github.com/laravel/homestead/blob/master/scripts/homestead.rb#L188-L189 You need to ensure you're specifying a port on your site:

```
sites:
    - map: test.local
      to: /var/www/html/test
      type: proxy
      port: <Port>
```

If you don't specify a port, we're passing the default value `80` to that script.

**Comment by taai** [comment]
Hey, @dqlopez , this is correct way how to configure proxy:

```yaml
sites:
    - map: test.local
      to: <Port>
      type: proxy
```

Yeah, I know – there is no documentation about it! 😆
