### ISSUE TITLE
NGINX and Apache conflict

### ISSUE THREAD

**Issue by zela** [laravel/homestead#555]
## Versions
  - Vagrant: 1.9.3
  - Provider: Virtualbox 5.1.20 r114629
  - Homestead: 5.2.3, box: 2.1.0

## Host operating system
MacOS Sierra 10.12.4

## Homestead.yaml
```yaml
ip: "192.168.50.10"
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys: [ ~/.ssh/id_rsa ]
folders:
    - map: ~/Projects/Playground/phpinfo
      to: /home/vagrant/phpinfo
    - map: ~/Projects/Playground/hello
      to: /home/vagrant/hello
sites:
    - map: phpinfo.app
      to: /home/vagrant/phpinfo/
      # type: apache
    - map: hello.app
      to: /home/vagrant/hello/
      type: apache
databases:
    - homestead
variables:
    - key: APP_ENV
      value: local
```

## Vagrant up output
https://gist.github.com/zela/531b3fb6ef41a33e68fa2fab42c06bb3

## Expected behavior
http://phpinfo.app shows phpinfo page
http://hello.app shows hello message

## Actual behavior
Both http://phpinfo.app and http://hello.app show hello message
So Apache servers its site for both URLs

## Going further
Reload vagrant

## Expected behavior
http://phpinfo.app shows phpinfo page
http://hello.app shows hello message

## Actual behavior
Both http://phpinfo.app and http://hello.app show phpinfo
Now nginx serves its site for both URLs!

## Steps to reproduce
1. Destroy proviously provisioned Homestead, to start form scratch
2. Paste contents of Homestead. yaml
3. Call `vagrant up` form Homestead directory
4. Note bug part 1.
5. Call `vagrant reload` form Homestead directory
6. Note bug part 2. :)

So it’s expectable, that since nginx is primary server for Homestead, it should proxy requests to Apache server for websites wich have `type: apache` and serve other types of websites normally.
