### ISSUE TITLE
Can't get Mailhog working

### ISSUE THREAD

**Issue by ClearMarble** [laravel/homestead#561]
I'm using Homestead 5.2.3 with the latest version of the base box (2.1.0), but I can't seem to get Mailhog up and running...

When I go to 192.168.10.10:8025 I get 'ERR_CONNECTION_REFUSED', though when I run `vagrant up` I do see `8025 (guest) => 8025 (host) (adapter 1)`

I've tried running `sudo systemctl enable mailhog` which produces `Failed to execute operation: No such file or directory`. Naturally `sudo systemctl start mailhog` produces `Failed to start mailhog.service: Unit mailhog.service not found`.

Not sure if something is wrong with my installation, but I've not had any problems with any of the other included packages.

Any advice as to what I might try? It'd be greatly appreciated, thanks!

Vagrant version is 1.9.1, using VirtualBox 5.1.20, on Windows 10 host.

**Comment by svpernova09** [comment]
Please show us the contents of `Homestead.yaml`, Also `vagrant ssh` and `sudo ifconfig`

**Comment by ClearMarble** [comment]
Thanks for the super quick response.

**Contents of Homestead.yaml:**
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
mariadb: true

authorize: c:/Users/Jesse/.ssh/id_rsa.pub

keys:
    - c:/Users/Jesse/.ssh/id_rsa

folders:
    - map: c:/localdev/homestead/sites
      to: /home/vagrant/Sites
      type: "nfs"

sites:
    - map: homestead.app
      to: /home/vagrant/Sites/Laravel/public
    - map: uibahome.app
      to: /home/vagrant/Sites/uiba.co/public
    - map: clearmarble.app
      to: /home/vagrant/Sites/clearmarble.net/public
    - map: energycontractbrokers.app
      to: /home/vagrant/Sites/energycontractbrokers.com/public
    - map: keystonetest.app
      to: /home/vagrant/Sites/keystonetest/public
    - map: jssandbox.app
      to: /home/vagrant/Sites/jssandbox/public
    - map: uibajobs.app
      to: /home/vagrant/Sites/uibajobs/public
    - map: bordergab.app
      to: /home/vagrant/Sites/bordergab/public
    - map: uiba-mongo.app
      to: /home/vagrant/Sites/uiba-mongo/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

**Output of vagrant ssh > sudo ifconfig:**
```bash
enp0s3    Link encap:Ethernet  HWaddr 08:00:27:c3:0a:85
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fec3:a85/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:15158 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5061 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:14299679 (14.2 MB)  TX bytes:1483938 (1.4 MB)

enp0s8    Link encap:Ethernet  HWaddr 08:00:27:a1:ef:2f
          inet addr:192.168.10.10  Bcast:192.168.10.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fea1:ef2f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:187283 errors:0 dropped:0 overruns:0 frame:0
          TX packets:215317 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:49352365 (49.3 MB)  TX bytes:105263303 (105.2 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1048 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1048 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:377764 (377.7 KB)  TX bytes:377764 (377.7 KB)
```
