### ISSUE TITLE
Can't do vagrant ssh when user path contains whitespaces

### ISSUE THREAD

**Issue by gerardreches** [laravel/homestead#566]
## Versions
  - Vagrant: 1.9.4
  - Provider: Virtualbox 5.1.22
  - Homestead: Vagrant 1.9.4

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Repositories/phpMyAdmin
      to: /home/vagrant/phpMyAdmin

    - map: ~/Repositories/Laravel
      to: /home/vagrant/Laravel

    - map: ~/Repositories/Vue
      to: /home/vagrant/Vue

    - map: ~/Repositories/Wordpress
      to: /home/vagrant/Wordpress

sites:
    - map: phpmyadmin.dev
      to: /home/vagrant/phpMyAdmin

#    - map: laravel-example.dev
#      to: /home/vagrant/Laravel/example/public
#
#    - map: vue-example.dev
#      to: /home/vagrant/Vue/example/public
#
#    - map: wordpress-example.dev
#      to: /home/vagrant/Wordpress/example
    
    - map: notaria.dev
      to: /home/vagrant/Laravel/notaria/public

    - map: 5thessence.dev
      to: /home/vagrant/Wordpress/5thessence

databases:
    - notaria_db
    - 5thessence_db

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant up output
[Gist](https://gist.github.com/gerardreches/ae5baba5860222a09162c052de71eb8e)

## Expected behavior
After `vagrant up`, I should run `vagrant ssh` to access homestead and it works correctly.

## Actual behavior
The home path is `C:/Users/Carlos Piana`, and when I run `vagrant ssh` I get a warning and can't access to homestead console:
```
$ vagrant ssh
Warning: Identity file C:/Users/Carlos not accessible: No such file or directory.
bash: Piana/Homestead/.vagrant/machines/homestead-7/virtualbox/private_key: No such file or directory
```

## Steps to reproduce
1. Your user home path is like `C:/Users/John Doe`
2. homestead up
3. homestead ssh

**Comment by svpernova09** [comment]
Use full path mappings instead of relative paths, then do `vagrant destroy && vagrant up` to see if the issue remains.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by gerardreches** [comment]
Issue remains with the next `homestead.yaml` configuration and after `vagrant destroy && vagrant up`:
```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
authorize: 'C:/Users/Carlos Piana/.ssh/id_rsa.pub'
keys:
    - 'C:/Users/Carlos Piana/.ssh/id_rsa'
folders:
    - map: 'C:/Users/Carlos Piana/Repositories/phpMyAdmin'
      to: /home/vagrant/phpMyAdmin
    - map: 'C:/Users/Carlos Piana/Repositories/Laravel'
      to: /home/vagrant/Laravel
    - map: 'C:/Users/Carlos Piana/Repositories/Vue'
      to: /home/vagrant/Vue
    - map: 'C:/Users/Carlos Piana/Repositories/Wordpress'
      to: /home/vagrant/Wordpress
sites:
    - map: phpmyadmin.dev
      to: /home/vagrant/phpMyAdmin    
    - map: notaria.dev
      to: /home/vagrant/Laravel/notaria/public
    - map: 5thessence.dev
      to: /home/vagrant/Wordpress/5thessence
databases:
    - notaria_db
    - 5thessence_db

```

**Comment by svpernova09** [comment]
To make sure your paths are being converted properly try removing the single quotes (since you don’t have any characters to escape) and use `\` instead of `/`.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by gerardreches** [comment]
Now `vagrant up` gives me an error ([full log](https://gist.github.com/gerardreches/a1797e2a67a256271715c3fe2c4e3514))

```
==> homestead-7: /tmp/vagrant-shell: line 1: /home/vagrant/.ssh/$2: ambiguous redirect
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
authorize: C:\Users\Carlos Piana\.ssh\id_rsa.pub
keys:
    - C:\Users\Carlos Piana\.ssh\id_rsa
folders:
    - map: C:\Users\Carlos Piana\Repositories\phpMyAdmin
      to: /home/vagrant/phpMyAdmin
    - map: C:\Users\Carlos Piana\Repositories\Laravel
      to: /home/vagrant/Laravel
    - map: C:\Users\Carlos Piana\Repositories\Vue
      to: /home/vagrant/Vue
    - map: C:\Users\Carlos Piana\Repositories\Wordpress
      to: /home/vagrant/Wordpress
sites:
    - map: phpmyadmin.dev
      to: /home/vagrant/phpMyAdmin    
    - map: notaria.dev
      to: /home/vagrant/Laravel/notaria/public
    - map: 5thessence.dev
      to: /home/vagrant/Wordpress/5thessence
databases:
    - notaria_db
    - 5thessence_db
```

**Comment by svpernova09** [comment]
Your username has spaces, you *have* to escape those, change those back:

```
authorize: 'C:/Users/Carlos Piana/.ssh/id_rsa.pub'
keys:
    - 'C:/Users/Carlos Piana/.ssh/id_rsa'
```

**Comment by svpernova09** [comment]
Also make sure you're using 5.2.4 of Homestead. and *not* the master branch.

**Comment by gerardreches** [comment]
After changing those back, the `vagrant up` error disappears, but the `vagrant ssh` issue persists.

And yes, Homestead is using 5.2.4 branch, not master branch.

**Comment by svpernova09** [comment]
Are you still getting 

```
$ vagrant ssh
Warning: Identity file C:/Users/Carlos not accessible: No such file or directory.
bash: Piana/Homestead/.vagrant/machines/homestead-7/virtualbox/private_key: No such file or directory
```

Try 

```
authorize: "C:\Users\Carlos Piana\.ssh\id_rsa.pub"
keys:
    - "C:\Users\Carlos Piana\.ssh\id_rsa"
```

**Comment by gerardreches** [comment]
```
authorize: "C:\Users\Carlos Piana\.ssh\id_rsa.pub"
keys:
    - "C:\Users\Carlos Piana\.ssh\id_rsa"
```
Double quotes gives an error ([Gist](https://gist.github.com/gerardreches/e5479fe40df04531e1d8e5e1a62865c7)).

Same with single quotes gives *ambiguous redirect* error:
```
authorize: 'C:\Users\Carlos Piana\.ssh\id_rsa.pub'
keys:
    - 'C:\Users\Carlos Piana\.ssh\id_rsa'
```
```
$ homestead up --provision
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Running provisioner: file...
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: /tmp/vagrant-shell: line 1: /home/vagrant/.ssh/$2: ambiguous redirect
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by svpernova09** [comment]
Open up `scripts/homestead.rb` and look for this section:

```
        # Copy The SSH Private Keys To The Box
        if settings.include? 'keys'
            settings["keys"].each do |key|
                config.vm.provision "shell" do |s|
                    s.privileged = false
                    s.inline = "echo \"$1\" > /home/vagrant/.ssh/$2 && chmod 600 /home/vagrant/.ssh/$2"
                    s.args = [File.read(File.expand_path(key)), key.split('/').last]
                end
            end
        end
```

Change the `s.inline = ` line to:

```
s.inline = "echo \"$1\" > /home/vagrant/.ssh/\"$2\" && chmod 600 /home/vagrant/.ssh/\"$2\"" 
```

**Comment by gerardreches** [comment]
I still get
```
$ vagrant ssh
Warning: Identity file C:/Users/Carlos not accessible: No such file or directory.
bash: Piana/Homestead/.vagrant/machines/homestead-7/virtualbox/private_key: No such file or directory
```

**Comment by svpernova09** [comment]
Show me the `Homestead.yaml` you're using when you get that error. I'm running out of options / solutions to try. Something in the setup isn't getting the space escaped properly.

**Comment by gerardreches** [comment]
`scripts/homestead.rb` is changed in the way you said, and this is the current `homestead.yaml` using a symlink in a try to avoid the whitespace (`mklink /D "C:\CarlosPiana" "C:\Users\Carlos Piana"`):
```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
authorize: C:/CarlosPiana/.ssh/id_rsa.pub
keys:
    - C:/CarlosPiana/.ssh/id_rsa
folders:
    - map: C:/CarlosPiana/Repositories\phpMyAdmin
      to: /home/vagrant/phpMyAdmin
    - map: C:/CarlosPiana/Repositories\Laravel
      to: /home/vagrant/Laravel
    - map: C:/CarlosPiana/Repositories\Vue
      to: /home/vagrant/Vue
    - map: C:/CarlosPiana/Repositories\Wordpress
      to: /home/vagrant/Wordpress
sites:
    - map: phpmyadmin.dev
      to: /home/vagrant/phpMyAdmin
    - map: notaria.dev
      to: /home/vagrant/Laravel/notaria/public
    - map: 5thessence.dev
      to: /home/vagrant/Wordpress/5thessence
databases:
    - notaria_db
    - 5thessence_db
```

`vagrant up` works fine in this case, but I still get the same message on `vagrant ssh`:
```
Warning: Identity file C:/Users/Carlos not accessible: No such file or directory.
bash: Piana/Homestead/.vagrant/machines/homestead-7/virtualbox/private_key: No such file or directory
```

**Comment by svpernova09** [comment]
AFAIK symlinks aren't going to solve the issue. Since the error is still breaking on the space.

**Comment by gerardreches** [comment]
@svpernova09 Why closed? The issue is still there, I was trying all you have said.

**Comment by svpernova09** [comment]
Sorry, I'm not sure where to go from here. The only solution I can offer would be to move your folders out of your user folder and into a path without spaces.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by IgorGudelj** [comment]
I have the same problem with Vagrant 1.9.4+
On Vagrant 1.9.3 everything works normally.

**Comment by pdbreen** [comment]
I just hit this as well after upgrade from vagrant 1.9.3 to 1.9.5.  I also upgraded homestead from v5.2.1 to v5.4.0 at the same time, but I don't think homestead is involved in this.  Anyway, here's what I did to work around the issue.

1. In Administrator level Command prompt, used "mklink" to create symbolic link to my home directory.  For me, this was done from root directory on C: drive - `mklink home "C:\Users\Patrick Breen"`
2. In Vagrantfile, added this as the first line in the Vagrant.configure section `config.ssh.private_key_path="C:/home/.ssh/id_rsa"`

Kind of hate having to modify the Vagrantfile to fix, but really need to be able to get into the machine!

**Comment by Darkyn** [comment]
Same issue here. Thanks Patrick! Your workaround worked for me but I agree 100% on the need for a more elegant solution.

**Comment by hjchin** [comment]
Thanks Patrick too! It works!

**Comment by IgorGudelj** [comment]
@pdbreen When I do this workaround, 'homestead ssh' works but on 'homestead up' I get the following error:
SSH:
* `private_key_path` file must exist: C:/home/.ssh/id_rsa

Any ideas?

**Comment by pdbreen** [comment]
@IgorGudelj not sure.   Do you mean `vagrant up`?  I'm not familiar with `homestead up` or `homestead ssh`.  Anyway, here's what I see when I `vagrant up`.

```
$ vagrant up
Bringing machine 'homestead-7' up with 'virtualbox' provider...
==> homestead-7: Checking if box 'laravel/homestead' is up to date...
==> homestead-7: Clearing any previously set forwarded ports...
==> homestead-7: Clearing any previously set network interfaces...
==> homestead-7: Preparing network interfaces based on configuration...
    homestead-7: Adapter 1: nat
    homestead-7: Adapter 2: hostonly
==> homestead-7: Forwarding ports...
    homestead-7: 80 (guest) => 8000 (host) (adapter 1)
    homestead-7: 443 (guest) => 44300 (host) (adapter 1)
    homestead-7: 3306 (guest) => 33060 (host) (adapter 1)
    homestead-7: 5432 (guest) => 54320 (host) (adapter 1)
    homestead-7: 8025 (guest) => 8025 (host) (adapter 1)
    homestead-7: 27017 (guest) => 27017 (host) (adapter 1)
    homestead-7: 22 (guest) => 2222 (host) (adapter 1)
==> homestead-7: Running 'pre-boot' VM customizations...
==> homestead-7: Booting VM...
==> homestead-7: Waiting for machine to boot. This may take a few minutes...
    homestead-7: SSH address: 127.0.0.1:2222
    homestead-7: SSH username: vagrant
    homestead-7: SSH auth method: private key
==> homestead-7: Machine booted and ready!
==> homestead-7: Checking for guest additions in VM...
==> homestead-7: Setting hostname...
==> homestead-7: Configuring and enabling network interfaces...
==> homestead-7: Mounting shared folders...
    homestead-7: /vagrant => C:/Users/Patrick Breen/Homestead
    homestead-7: /home/vagrant/src => D:/src
==> homestead-7: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> homestead-7: flag to force provisioning. Provisioners marked to run always will still run.
```

And, here's my diff vs the 5.4.0 branch which is what I have checked out - just the one addition:

```
Patrick Breen@6700k MINGW64 ~/Homestead ((v5.4.0))
$ git diff
diff --git a/Vagrantfile b/Vagrantfile
index 12b8f52..9b424f2 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -17,6 +17,8 @@ require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')
 Vagrant.require_version '>= 1.9.0'

 Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
+    config.ssh.private_key_path="C:/home/.ssh/id_rsa"
+
     if File.exist? aliasesPath then
         config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
         config.vm.provision "shell" do |s|

```

Hope either of those offer some help...

**Comment by Darkyn** [comment]
Quick note...I was running into an issue after executing vagrant destroy but during the process of troubleshooting I upgraded from Vagrant 1.9.5 to 1.9.7. After that, I was able to remove the windows home symlink and the config.ssh.private_key override in Vagrantfile. I'm not only using the original ~/.ssh/id_rsa in Homestead.yaml so I suppose they fixed the issue with spaces in the username. Cheers :)

**Comment by miff2000** [comment]
Anyone else running into this issue, try replacing the parts of the path with spaces in with the output of `dir /X <path>`. For example:

```cmd
C:\Users>dir /x
 Volume in drive C is OS
 Volume Serial Number is 4A7D-5173

 Directory of C:\Users

26/06/2019  03:53    <DIR>                       .
26/06/2019  03:53    <DIR>                       ..
04/09/2019  19:51    <DIR>          USERWI~1     User With Space
26/06/2019  04:52    <DIR>                       Public
26/06/2019  03:58    <DIR>          RDVGRA~1     RDV GRAPHICS SERVICE
12/04/2017  18:49    <DIR>                       TEMP
               0 File(s)              0 bytes
               8 Dir(s)  114,409,021,440 bytes free
```
These are the paths that legacy versions of Windows used to use under the bonnet, as it couldn't handle spaces in paths, but whilst maintaining 'nice' looking names for users.

If I then update the `Homestead.yaml` to use that updated path, it works:

```yaml
---
ip: "192.168.10.10"
provider: virtualbox
name: homestead

authorize: C:\Users\USERWI~1\Documents\userkey.openssh.pub

keys:
    - C:\Users\USERWI~1\Documents\userkey.openssh.key
```
