### ISSUE TITLE
The requested address is not valid in this context

### ISSUE THREAD

**Issue by devcircus** [laravel/homestead#571]
Fresh installs for homestead have been plagued for weeks now with this error. I found a fix online 
for it that involved tweaking line #90 of scripts/homestead.rb.

Replacing the first line:
 ```config.vm.network "forwarded_port", guest: guest, host: host, auto_correct: true```
with this line:
```config.vm.network "forwarded_port", guest: guest, host: host, host_ip: "127.0.0.1", auto_correct: true```

The fix works perfectly. Are there unintended side affects? Things that need to be taken into consideration?

Again, with that fix in place, everything seems to work like is should. It is just a pain to have to change that one line everytime I run composer update.

Any info would be much appreciated.

Vagrant: 1.9.3
Provider: Virtualbox 5.1.18 r114002 (Qt5.6.2)
Homestead: Current Version

## Host operating system
Windows 8,1
## Homestead.yaml
```
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: 'C:\code\*&*&*&*'
        to: /home/vagrant/Code/*&*&*&*
sites:
    -
        map: &*&*&*&.app
        to: /home/vagrant/Code/&*&*&*&/public
databases:
    - &*&*&*&
name: &*&*&*&
hostname: &*&*&*&(Sorry remove my project name)
```

## Vagrant up output
```sh
Checking if box 'laravel/homestead' is up to date...
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/is_port_open.rb:21:in `initialize': The requested address is not valid in its context. - connect(2) for "0.0.0.0" port 8000 (Errno::EADDRNOTAVAIL)
```
