### ISSUE TITLE
PHP install freezing due to Modified configuration file

### ISSUE THREAD

**Issue by dwhoban** [laravel/homestead#575]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues but will do our best to help. Thank you!

## Versions
  - Vagrant: 1.9.4
  - Provider: Virtualbox 5.1.22 r115126 (Qt5.6.2)
  - Homestead: 5.3.1/2.1.0

## Host operating system
macOS 10.12.5 (16F73)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant up output
https://gist.github.com/dwhoban/ee7dfd85d5d434c9ddf894e8b6d9082c

## Expected behavior
Install of clean homestead vm

## Actual behavior
Freezing on PHP 7.1 install

## Steps to reproduce
1. run `homestead up`\`vagrant up`
