### ISSUE TITLE
Blocked at: What do you want to do about modified configuration file php.ini?

### ISSUE THREAD

**Issue by idflood** [laravel/homestead#577]
## Versions
  - Vagrant: 1.9.5
  - Provider: Virtualbox
  - Homestead: 5.3.1 (box 2.1.0)

## Host operating system
macOS Sierra 10.12.4

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Sites
      to: /home/vagrant/Sites
      type: "nfs"

sites:
    - map: test.dev
      to: /home/vagrant/Sites/test/web
      type: apache

databases:
    - homestead
```

## Vagrant up output
https://gist.github.com/idflood/e63898b0cbc16adf4287837730bb6178

## Expected behavior
Vagrant up should finish

## Actual behavior
Blocked at a dialog asking what to do with php.ini file.

## Steps to reproduce
1. Followed the steps here https://laravel.com/docs/5.4/homestead#first-steps
2. Did `git checkout v5.3.1`
3. Modified the Homestead.yaml as shown above
4. vagrant up

The vagrant output is a bit messy I think, the "real last line" should be:
`==> homestead-7: Package configuration┌──────────────────────┤ Modified configuration file ├──────────────────────┐│ A new version (/usr/lib/php/7.1/php.ini-production.cli) of configuration  ││ file /etc/php/7.1/cli/php.ini is available, but the version installed││ currently has been locally modified.││││ What do you want to do about modified configuration file php.ini?││││install the package maintainer's version││keep the local version currently installed         ││show the differences between the versions││show a side-by-side difference between the versions││start a new shell to examine the situation││││││<Ok>│││└───────────────────────────────────────────────────────────────────────────┘`

Eventually I did not modify this file and there seems to be no way of answering this dialog.
