### ISSUE TITLE
Can't Connect to Homestead

### ISSUE THREAD

**Issue by matthewsuan** [laravel/homestead#580]
## Versions
  - Vagrant: 1.9.5
  - Provider: Virtualbox,
  - Homestead: 2.1.8
  - Virtualbox: 5.1.22

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.1`. You *will* show as up-to-date from the `~5.0` branch when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
OSX El Capitan 10.11.6

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public

databases:
    - homestead

variables:
    - key: APP_ENV
      value: local

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant up output
https://gist.github.com/matthewsuan/c8106e6c45c7cac5430ce4ef5ece8352#file-homestead-error

## Hosts File
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
192.168.10.10	homestead.app

## Expected behavior
homestead.app should resolve in the browser.

## Actual behavior
homestead.app is not resolving. I got the site cant be reached error. I already re installed homestead a few times.

## Steps to reproduce
Follow instructions for a fresh install of homestead

## UPDATE
The url resolves fine when doing curl from inside the vm.

### PING RESULTS 
I did a ping on the IP address: 192.168.10.10 and all timed out. It seems the request is not forwarded to the vm.
