### ISSUE TITLE
"share" command not found

### ISSUE THREAD

**Issue by neamtua** [laravel/homestead#588]
Hello,

Trying to share my homestead box for a test and it can't find the share command.
I've updated to the latest version of homestead and provisioned the box again.
Any help would be greatly appreciated. Thank you.

## Versions
  - Vagrant: 1.9.5
  - Provider: Virtualbox 5.1.22 r115126
  - Homestead: I get an error running php bin/homestead. Can't tell you.

## Host operating system
macOS Sierra

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4000
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Sites/homestead
      to: /home/vagrant/Code

databases:
    - homestead

variables:
    - key: APP_ENV
      value: local

blackfire:
    - id: 
      token: 
      client-id: 
      client-token:

ports:
     - send: 9200
       to: 9200
     - send: 27017
       to: 27017
     - send: 28017
       to: 28017
#     - send: 7777
#       to: 777
#       protocol: udp

sites:
    - map: ruvix2.app
      to: /home/vagrant/Code/ruvix2/public
```
