### ISSUE TITLE
Vagrant share using incorrect Local machine address

### ISSUE THREAD

**Issue by Osiruss** [laravel/homestead#589]
Vagrant version:
1.8.4

OS:
OSXSierra

So for some reason vagrant share is now using:
Local machine address: 127.0.0.1

When before it was using:
Local machine address: 192.168.50.10

Which means none of the vagrant shared sites are working.

I know this is my fault but now I do not know how to fix it. 

I was trying to copy files from the vagrant server to my local and then back. Succeeded on the former but I think on the latter I somehow switched what IP address is used. 

Just as a note my vagrant projects are still working and when I create a new project it still pops up on 192.168.50.10 (for example http://www.sandbox.192.168.50.10.nip.io)

I think it could have been when I ran:
sudo scp -r ~/testing.conf vagrant@127.0.0.1:/home/username

As opposed to what have maybe should have been:
sudo scp -r ~/testing.conf vagrant@192.168.50.10:/home/username

Any ideas?

Thank-you

P.s: Sorry if this is the wrong place to ask, just saw similar questions herein

**Comment by svpernova09** [comment]
Please show your `Homestead.yaml`

**Comment by svpernova09** [comment]
Will reopen when you show homestead file.

**Comment by mffap** [comment]
Maybe there is something that I have missed, but unfortunately I experience the same problem with a fresh install of Homestead, that is:

- vm boots up without errors
- timeout on http://homestead.app or http://homestead.app:8000
- `~/Code/Laravel/public/index.html` (test site) is accessible over http://localhost:8000 (but not over http://localhost)
- ping on homestead.app / homestead.app:8000 time out

Steps taken in troubleshooting (still same result)
- `vagrant destroy` followed by `vagrant up --provision` 
- `vagrant reload --provision` and `vagrant provision`
- system reboot
- upgrade system to ensure packages are up-to-date
- tested different browser (firefox, chrome)
- ngix logs are empty on vm
- fresh install of homestead in different folder
- checkout older version (v5.3.2)

The same setup worked before on the same machine.

Please find below the contents of relevant files. 

Thanks for the help

#### Homestead.yaml
_only changed ssh files_

```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.mffap.pub

keys:
    - ~/.ssh/id_rsa.mffap

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

#### /etc/hosts
```
127.0.0.1	localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

#Homestead
192.168.10.10 homestead.app
```
#### /etc/nginx/sites-available/homestead.app
_on vagrant via vagrant ssh_
```
server {
    listen 80;
    listen 443 ssl http2;
    server_name homestead.app;
    root "/home/vagrant/Code/Laravel/public";

    index index.html index.htm index.php;

    charset utf-8;

...

```
