### ISSUE TITLE
vagrant up should fail gracefully when .ssh/id_rsa is missing

### ISSUE THREAD

**Issue by nicolaiskogheim** [laravel/homestead#592]
## Versions
  - Vagrant: Vagrant 1.9.5
  - Provider: Oracle VM VirtualBox Manager 5.1.22
  - Homestead: v5.3.2 (the checked out tag. Don't have the `homestead` command)

## Host operating system
Arch Linux 4.9.30-1-lts #1 SMP Sun May 28 18:47:29 CEST 2017 x86_64 GNU/Linux

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public

databases:
    - homestead
```

## Vagrant up output
https://gist.github.com/nicolaiskogheim/949ffbe3a065917f2611747aec7c3a1c

## Expected behavior
Vagrant should have told me that the keys specified in `homestead.yml` doesn't exist.

## Actual behavior
Stacktrace when ruby wasn't able to read the file.

In [`scripts/homestead.yml:118`](https://github.com/laravel/homestead/blob/master/scripts/homestead.rb#L118) the `keys` from `homestead.yml` is read, but there is no error checking.

```ruby
### scripts/homestead.rb:112
        # Copy The SSH Private Keys To The Box
        if settings.include? 'keys'
            settings["keys"].each do |key|
                config.vm.provision "shell" do |s|
                    s.privileged = false
                    s.inline = "echo \"$1\" > /home/vagrant/.ssh/$2 && chmod 600 /home/vagrant/.ssh/$2"
                    s.args = [File.read(File.expand_path(key)), key.split('/').last]
                end
            end
        end
```

## Steps to reproduce
1. Install homestead
2. Ensure there is no `~/.ssh/id_rsa` file present
3. run `vagrant up`
