### ISSUE TITLE
Error on provisioning

### ISSUE THREAD

**Issue by laurencei** [laravel/homestead#596]
## Versions
  - Vagrant: 1.9.5
  - Provider: VMWare v12 (latest patch)
  - Homestead: 5.4.0 (latest from Git)
  - Box: vmware_desktop v2.1.0 (latest from Atlas)

## Host operating system
Windows 10

## Homestead.yaml
```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: vmware_workstation

authorize: c:/Users/Me/.ssh/my_rsa.pub

keys:
    - c:/Users/Me/.ssh/my_rsa

folders:
    - map: c:/www
      to: /home/vagrant/www
      type: smb

sites:
    - map: example.vm
      to: /home/vagrant/www/example/public
```

## Vagrant up output

![screen](https://user-images.githubusercontent.com/1210658/27015068-7a1e72ce-4efd-11e7-9fc7-01890c9cc6b5.png)

## Steps to reproduce
1. Vagrant up

I cant "interact" with that screen. i.e. I cant click enter, ok or anything - it just hangs there. Pressing `ctrl-c` allows me to exit.

I can then successfully SSH into the box - but the provisioning is incomplete and broken
