### ISSUE TITLE
Apache site: Errors were encountered while processing: php7.1-fpm

### ISSUE THREAD

**Issue by idflood** [laravel/homestead#597]
Hi, I update to homestead `5.4.0` and when I try to run `vagrant reload --provision` I'm hitting another error. It's a bit different than what I encountered here https://github.com/laravel/homestead/issues/577 since the script isn't blocked but in the end apache doesn't work (Internal server error displayed if I try to reach the website).

## Versions
  - Vagrant 1.9.5
  - Provider: Virtualbox Version 5.1.22 r115126 (Qt5.6.2)
  - Homestead: 5.4.0 (box 2.1.0)

## Host operating system
macOS Sierra 10.12.5

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code
      type: "nfs"

sites:
    - map: mysite.dev
      to: /home/vagrant/Code/mysite/wp
      type: apache
```

## Vagrant up output
https://gist.github.com/idflood/45feedc9e0e9d33ea534848a4194b5ff

## Expected behavior
Apache with php should be running. Note that if I remove the `type: apache` the site works correctly but since it rely on custom .htaccess it needs to be served by apache.

## Actual behavior
The box is up but apache/php are not working. If I access the website it returns a "500 Internal Server Error".

## Steps to reproduce
1. Add a site with `type: apache`
2. Run `vagrant reload --provision`

## References
- GH-577
