### ISSUE TITLE
[Request] Multiple PHP Versions?

### ISSUE THREAD

**Issue by divdax** [laravel/homestead#604]
It would be great to provide multiple php version at the same time in a box and specify the php version in the Homestead.yaml like so:

```
sites:
    - map: homestead.app
      to: /home/vagrant/www
      php: 7.0 <====================
    - map: homestead.app
      to: /home/vagrant/www
      php: 5.6 <====================
```

How do you think about this idea? 😄
