### ISSUE TITLE
Homestead.yaml Folder in Vagrant not created

### ISSUE THREAD

**Issue by cschoeni** [laravel/homestead#606]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues but will do our best to help. Thank you!

## Versions
Vagrant 1.9.6
Homestead 5.4

## Host operating system
OS: Ubuntu 17.04

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects/Laravel
      to: /home/vagrant/Code

sites:
    - map: sandbox.app
      to: /home/vagrant/Code/sandbox/public

databases:
    - sandbox

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```
## Vagrant up output
cschoeni@linux:~/Projects/Homestead$ vagrant reload --provision
...
==> homestead-7: Unable to mount one of your folders. Please check your folders in Homestead.yaml
...
## Expected behavior
What should have happened?
- The Folder "Code" in vagrant is not created 
- I testet also with the Original Homestead.yaml. The same error.

## Steps to reproduce
1. vagrant up
2. The error came
3. Set e new config in HOmestead yaml
4. vagrant reload --provision
5. same error

**Comment by svpernova09** [comment]
You should map individual projects, not entire folders with many projects in it.

```
==> homestead-7: Unable to mount one of your folders. Please check your folders in Homestead.yaml
```

This means Homestead couldn't map  `~/Projects/Laravel` for some reason

**Comment by svpernova09** [comment]
Try:

```
folders:
    - map: ~/Projects/Laravel/sandbox
      to: /home/vagrant/Code

sites:
    - map: sandbox.app
      to: /home/vagrant/Code/sandbox/public
```

**Comment by cschoeni** [comment]
Thanks for your answer svpernova09. I try my code bellow 

```yaml
folders:
    - map: ~/Projects/Laravel/sandbox
      to: ~/Code

...

folders:
    - map: home/cschoeni/Projects/Laravel/sandbox
      to: ~/Code

folders:
    - map: ~/Projects/Laravel/sandbox
      to: home/vagrant/Code
```
Its the same error after `vagrant reload --provision`.
The error is in folders by `to:` but a dont now what a can try.


Best
Chris
