### ISSUE TITLE
Homestead Doesn't Support Application Routes Ending in .php

### ISSUE THREAD

**Issue by ericdowell** [laravel/homestead#608]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues but will do our best to help. Thank you!

## Versions
 - Vagrant: Run `vagrant -v` to show the version.
```
Vagrant 1.9.5
```
  - Provider: Virtualbox, VMWare or Parallels and it's version.
```
Virtualbox: Version 5.1.22 r115126 (Qt5.6.2)
```
  - Homestead: Run `homestead --version` to show the version.
```
Per Project Install: "laravel/homestead": "^5.4"
```

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.1`. You *will* show as up-to-date from the `~5.0` branch when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
This is the operating system that you run locally.
```
MacOS Sierra 10.12.5
```

## Homestead.yaml
```yaml
ip: 192.168.10.45
memory: 2048
cpus: 1
provider: virtualbox
name: homestead
hostname: homestead
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    - map: /Users/dowelec/Projects/homestead-example
      to: /home/vagrant/homestead-example
sites:
    - map: homestead-example.app
      to: /home/vagrant/homestead-example/public
      schedule: true
databases:
    - homestead
```

## Vagrant up output
Provide a link to a GitHub Gist containing the complete output.
Do NOT paste the debug output in the issue, just paste the link to the Gist.

https://gist.github.com/ericdowell/ceb59ee20c9a3b874f3dbfba1df49a2e

## Expected behavior
What should have happened?
Nginx (haven't tested Apache) should fallback to the application routes (`index.php`) when a php file isn't found/matched. Thus an application route defined ending with `.php` will handle the request/response.
```php
$app->get( 'path/to/my-fake-file.php', function () use ( $app ) {
    return response()->json( [ 'output' => 'true' ] );
} );
```

## Note
I've created a repo to better show the issue and help with getting setup quickly: https://github.com/ericdowell/homestead-no-php-file-routes.

## Actual behavior
What actually happened?
The rendered page currently reads `No input file specified.`. I would expect the route defined in the application to render the page. I have both Laravel Homestead and Laravel Valet setup and Valet supports routes ending in `.php`.  I don't have time to look into the issue at the moment, but I'm guessing it's a simple Nginx tweak. To make sure it doesn't always default to the application routes I've created http://homestead-example.vm/path/to/my-real-file.php within the example github repo.

## Steps to reproduce
1. Clone example repo: https://github.com/ericdowell/homestead-no-php-file-routes
2. Add `192.168.10.45   homestead-example.vm` to `/etc/hosts` and run `vagrant up`
2. Visit http://homestead-example.vm/path/to/my-fake-file.php
3. See `No input file specified.`

## References
Are there any other GitHub issues (open or closed) that should be linked here?
- None that can be found.
