### ISSUE TITLE
Mysql stops after provisioning

### ISSUE THREAD

**Issue by keithdoyle9** [laravel/homestead#612]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues but will do our best to help. Thank you!

## Versions
  - Vagrant: v1.9.5
  - Provider: VMWare Workstation Pro v12.5.7
  - Homestead: v5.4.0

## Host operating system
Windows 7 Enterprise

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: vmware_workstation
mariadb: true

authorize: C:/Users/kdoyle/.ssh/id_rsa.pub

keys:
    - C:/Users/kdoyle/.ssh/id_rsa

folders:
    - map: C:/Users/kdoyle/code
      to: /home/vagrant/projects

sites:
    - map: advisorbriefcase.seic.dev
      to: /home/vagrant/projects/advisorbriefcase-seic-com
    - map: trackingapp.dev
      to: /home/vagrant/projects/trackingapp/public
      type: laravel
    - map: seic.dev
      to: /home/vagrant/projects/seic-com

databases:
    - homestead
    - trackingapp
    - advbc

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant up output
https://gist.github.com/keithdoyle9/43f847088dabef1bc8f185389b9a779f

## Expected behavior
MySQL service should be running and available

## Actual behavior
Can't connect error

## Steps to reproduce
1. Run vagrant up
2. Note the error at the end of the output about unable to connect
3. ssh into homestead
4. run `mysql` and note same error
