### ISSUE TITLE
'homestead.app' hangs (Took too long to respond)

### ISSUE THREAD

**Issue by fairbraxton** [laravel/homestead#617]
# Edit: This is a known issue with Virtualbox on Linux.
VirtualBox on Linux has a known problem and [has been reported](https://www.virtualbox.org/ticket/16911). To fix this, head over to the [Testbuilds for VirtualBox](https://www.virtualbox.org/wiki/Testbuilds) and update to **5.1.x revision 117130+** and run the .run file it downloads with sudo. 

Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues but will do our best to help. Thank you!

## Versions
  - Vagrant: Run `vagrant -v` to show the version.
Vagrant 1.9.7
  - Provider: Virtualbox, VMWare or Parallels and it's version.
Virtualbox 5.1.24
  - Homestead: Run `homestead --version` to show the version.
Homestead 5.4.0

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.1`. You *will* show as up-to-date from the `~5.0` branch when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Working on Windows, doesn't work on Ubuntu (Dual-boot)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /usb/Dev/Homestead
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Versionr/public

databases:
    - homestead

```

## Vagrant up output
[Output Gist](https://gist.github.com/fairbraxton/70cfbdcf3c7f5a75918f5b2c51c27320)

## Expected behavior
I made a fresh environment (wiped drive) and made Windows-Ubuntu Dual-boot. It all works perfectly fine on the Windows machine, but it doesn't work on Ubuntu.

## Actual behavior
When I go to ```homestead.app``` in Chrome, I get the error: ```homestead.app took too long to respond.```. 

## Steps to reproduce
1. Fresh everything

## References
None.
