### ISSUE TITLE
Homestead not honoring Homestead.yaml.example

### ISSUE THREAD

**Issue by dtirer** [laravel/homestead#620]
I have Hometsead installed on per-project basis.  When I run `vendor/bin/homestead make`, it doesn't honor file paths / site paths from my example file,

Example File
```
folders:
    - map: "/path-to-your-projects/my-company/api"
      to: "/var/www/api"
      type: nfs

sites:
    - map: api.my-company.dev
      to: "/var/www/api/public"
      schedule: true 
```

`vendor/bin/homestead make` output:
```
folders:
    -
        map: /Users/stationhead/Sites/my-company/api
        to: /home/vagrant/Code/api
sites:
    -
        map: api.app
        to: /home/vagrant/Code/api/public
        schedule: true
```

Not that:
* The path is different for the folder mapping
* the `to` field in `folders` is incorrect
* the NFS option was not retained
* The path is different for the sites mapping
* the `to` field in `sites` is incorrect

Homestead Version: 5.4.0
Vagrant 1.9.1
Virtualbox 5.1.14
Host OS: OSX 10.12.5

To re-create:
Simply customize the Homestead.yaml.example in a per project installation and run `vendor/bin/homestead make`
