### ISSUE TITLE
PHP 5.6 error on vagrant provision

### ISSUE THREAD

**Issue by mortscode** [laravel/homestead#625]
## Versions
  - Vagrant: `Vagrant 1.9.7`
  - Provider: Virtualbox `Version 5.1.26 r117224 (Qt5.6.2)`
  - Homestead: `6.0.0`

## Host operating system
Mac OSX 10.12.6

## Homestead.yaml
```
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
mariadb: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /Users/mortscode/Development
      to: /home/vagrant/Development
      type: nfs

sites:
    - map: tmp3.craft.dev
      to: /home/vagrant/Development/Mort/tmp3/public
      php: "7.0"

    - map: test.craft.dev
      to: /home/vagrant/Development/Mort/craft-test/public
      php: "5.6"

databases:
    - tmp3
    - test

variables:
    - key: APP_ENV
      value: local
```

## Vagrant up output
<https://gist.github.com/mortscode/79cecb8fb03f53c05f3fd2096141d58b>

This issue happens when I provision Vagrant. Here's the output for `vagrant provision`
<https://gist.github.com/mortscode/4e69b63df3b492784aab2be5b757cdff>

## Expected behavior
One site running on PHP 7.0 and the other running on PHP 5.6

## Actual behavior
PHP 5.6 threw an error on `provision` and doesn't seem to work

## Steps to reproduce
1. `homestead.yaml` file with 2 sites (one `php: "7.0."` and one `php: "5.6"`
2. run `vagrant provision` or `vagrant reload --provision`
3. notice error:
```
homestead-7: Job for php5.6-fpm.service failed because the control process exited with error code. 
See "systemctl status php5.6-fpm.service" and "journalctl -xe" for details.
```
