### ISSUE TITLE
Composer update fails with composer.json php version set to 7.1.*

### ISSUE THREAD

**Issue by philbates35** [laravel/homestead#638]
## Versions
  - Vagrant: 1.9.1
  - Provider: Virtualbox 5.1.26r117224.
  - Homestead: 6.0.3

## Host operating system
Fedora 26

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: laravel.app
      to: /home/vagrant/Code/laravel/public

databases:
    - homestead
```
## Expected behavior
```
$ composer update php
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
```

## Actual behavior
```
$ composer update php
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php 7.1.* but your PHP version (5.6.4) does not satisfy that requirement.
```

## Steps to reproduce
1. Create a fresh homestead
2. Inside Homestead run `php --version` to verify that PHP7.1 is installed and used from the CLI.
3. Inside homestead run `laravel new {project}` to create a new Laravel project
4. After installation has finished, edit the new project's `"php": ">=5.6.4"` entry to `"php": "7.1.*"`,
5. Run `composer update php` inside the project root.
