### ISSUE TITLE
Problem with sites configuration and/or folders

### ISSUE THREAD

**Issue by mjnciceri** [laravel/homestead#645]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues but will do our best to help. Thank you!

## Versions
  - Vagrant: 1.9.7
  - Provider: Virtualbox 5.1.26
  - Homestead: 6.0.3

## Host operating system
Tested with Ubuntu 16.04 and Windows 10

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
#keys:
#    - ~/.ssh/id_rsa
folders:
    -
        map: 'C:\Users\Marcelo\Proyectos\blog'
        to: /home/vagrant/Code
sites:
    -
        map: homestead.app
        to: /home/vagrant/Code/Laravel/public
databases:
    - homestead
name: blog
hostname: blog
```

## Vagrant up output
https://gist.github.com/mjnciceri/9036dfb72702750aa596bdc0d1604716

## Expected behavior
The sites are not being set according to the current directory in the project.

The root path should be "/home/vagrant/Code/public";

## Actual behavior
What actually happened?

The file generated is currently this one

vagrant@blog:~$ cat /etc/nginx/sites-available/homestead.app
server {
    listen 80;
    listen 443 ssl http2;
    server_name homestead.app;
    root "/home/vagrant/Code/Laravel/public";

It started since commit [c669a03d8b00e346236bdc5c1ddffb7607f82d8f](https://github.com/laravel/homestead/commit/c669a03d8b00e346236bdc5c1ddffb7607f82d8f)

I am not sure if the problem is with the nginx settings or the shared folder configurations. Of course that if I change the homestead.app file or the shared folders in Homestead.yaml, everythins goes fine.

## Steps to reproduce
1. Create a project with composer create-project --prefer-dist laravel/laravel blog
2. Execute vendor\\bin\\homestead make 
3. Execute vagrant up
4. Access on your browser to localhost:8000

## References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:

It started since commit [c669a03d8b00e346236bdc5c1ddffb7607f82d8f](https://github.com/laravel/homestead/commit/c669a03d8b00e346236bdc5c1ddffb7607f82d8f)

**Comment by svpernova09** [comment]
> The root path should be "/home/vagrant/Code/public";

No, the root path should be `/home/vagrant/Code/Laravel/public` because this is what you have your site `to:` path set to, which is what shows in your `cat /etc/nginx/sites-available/homestead.app` as expected.

You should be mapping 1 project to 1 site in Vagrant, not a folder that has multiple projects under it.

**Comment by mjnciceri** [comment]
In that case, the map folder should't be this ?

`folders:
    -
        map: 'C:\Users\Marcelo\Proyectos\blog'
        to: /home/vagrant/Code/Laravel`

Right now is this is generated

`folders:
    -
        map: 'C:\Users\Marcelo\Proyectos\blog'
        to: /home/vagrant/Code`

**Comment by mjnciceri** [comment]
and maybe this line https://github.com/laravel/homestead/blob/b038a817d30f905065e0b345d5970ccbace9e9af/src/Settings/HomesteadSettings.php#L151 should be 'to' => "/home/vagrant/{$projectDirectory}/Laravel",

**Comment by svpernova09** [comment]
The folder `to` path is 100% up to you, but should always be somewhere in `/home/vagrant`. 

Try this:

```
folders:
    -
        map: 'C:\Users\Marcelo\Proyectos\blog'
        to: /home/vagrant/blog
sites:
    -
        map: blog.app
        to: /home/vagrant/blog/public
```
