### ISSUE TITLE
Can't mount shared folders windows subsystem for linux

### ISSUE THREAD

**Issue by dlynch29** [laravel/homestead#653]
## Versions
  - Vagrant: 1.9.7 (WSL)
  - Provider: Virtualbox 5.1.26 (Windows)
  - Homestead: 6.0.1

## Host operating system
Windows 10, but I'm using the Windows Subsystem for Linux.

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/public

databases:
    - homestead

```

## Vagrant up and vagrant --provision
https://gist.github.com/dlynch29/86313ce336ea1fd64c3a6d21d964156e

## Expected behavior
Shared folders are properly mounted and synchronized

## Actual behavior
An error message about shared folders is output by vagrant --provision, and no folders are synchronized

Virtualbox shows this as the only shared folder:
\\?\C:\Users\Daniel Lynch\AppData\Local\lxss\home\daniel\Homestead (named vagrant)

## Steps to reproduce
Vagrant installed via package manager on Bash for windows. 
Virtualbox installed from the virtualbox website for regular (non-linux) windows.
I've tried different changing the shared folder up quite a bit 

I used the documentation from vagrant to use it on WSL. 
https://www.vagrantup.com/docs/other/wsl.html

They say that it just works™ by knowing when it's run in the WSL and uses the windows virtualbox provider.

## References
https://github.com/laravel/homestead/issues/510
