### ISSUE TITLE
"garbage at end of line" on Windows 10

### ISSUE THREAD

**Issue by souhailmerroun** [laravel/homestead#656]
## Versions
  - Vagrant: 1.9.8
  - Provider: Virtualbox

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/www
      to: /home/vagrant/www

sites:
    - map: hello.app
      to: /home/vagrant/www/hello

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant up output
![sans titre](https://user-images.githubusercontent.com/8895242/29770660-5fa0c228-8bf0-11e7-9f58-8fc45ad2505d.png)

## Expected behavior
It's should have allowed me to access to virtual machine

## Actual behavior
It's does not allow me to access to virtual machine

## Steps to reproduce
1. vagrant ssh on command line

## Bug & Solution Idea
I found that the problem was in my user folder on Windows, It's was "Souhail M", the space was the error, after I switched the session to something like this "souhail", it's works well.
