### ISSUE TITLE
Homestead Randomly Closing

### ISSUE THREAD

**Issue by browner12** [laravel/homestead#663]
## Versions
  - Vagrant: 1.9.8
  - Provider: Virtualbox 5.1.26 r117224 (Qt5.6.2)
  - Homestead: Box 3.0.0
  - Homestead Repo: master (I know I shouldn't really do this, but I don't think it's the cause of this issue)

## Host operating system
macOS Sierra 10.12.6

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 8192
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code
```

## Actual behavior

Everything runs completely fine. I can `homestead up` and then log in, and I have no issues. However, the box is randomly shutting itself down. I'll cover back over to my terminal window and I'll see 'Connection to 127.0.0.1 closed by remote host. Connection to 127.0.0.1 closed.'

I have a very powerful Mac, so I shouldn't be running into an resource issues. It's not related to a screensaver or power save.

Do you know any places where I could find logs that might give me some insight into what is going on? I really have no clue where to start debugging this. Once I find some logs, and can post more info.  Thanks,
