### ISSUE TITLE
Fresh homestead unable to load sites

### ISSUE THREAD

**Issue by carc1n0gen** [laravel/homestead#669]
## Versions
  - Vagrant 1.9.1
  - Virtualbox 5.1.22_Ubuntur115126
  - homestead: command not found (both on host and vm)

## Host operating system
Ubuntu 17.04

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa_github.pub

keys:
    - ~/.ssh/id_rsa_github

folders:
    - map: ~/Code/php/Laravel
      to: /home/vagrant/Code/Laravel
    - map: ~/Code/php/weelnk
      to: /home/vagrant/Code/weelnk

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public
    - map: weelnk.app
      to: /home/vagrant/Code/weelnk/public

databases:
    - homestead
    - weelnk

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp


```

## Vagrant up output
https://hastebin.com/dezitaxara.erl

## Expected behavior
The sites should load

## Actual behavior
The sites do not load

## Steps to reproduce
1. Init a fresh laravel app
2. Create host file entries
3. Add mappings to Homestead.yaml
4. vagrant up
5. Try to load site

## Other

I can ping the hostnames I added to the hosts file.  But when I try to load the sites in a browser, the loader just spins forever
