### ISSUE TITLE
Composer update fails with composer.json

### ISSUE THREAD

**Issue by samernajj** [laravel/homestead#671]
## Versions
  - Vagrant: Vagrant 1.9.1.
  - Provider: Virtualbox
  - Homestead: homestead: command not found

## Host operating system
Ubuntu 16.04

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /var/www/html/Homestead
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant up output
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: inline script
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: /tmp/vagrant-shell20170920-25214-ra2l6n.sh
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Certificate: homestead.app
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Site: homestead.app
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Checking for old Schedule
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Restarting Nginx
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating MySQL Database: homestead
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Creating Postgres Database: homestead
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Clear Variables
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Update Composer
==> homestead-7: Updating to version 1.5.2 (stable channel).
==> homestead-7:    
==> homestead-7: Downloading (connecting...)
==> homestead-7: 
==> homestead-7: Downloading (100%)
==> homestead-7:          
==> homestead-7: 
==> homestead-7: Use composer self-update --rollback to return to version 1.4.2
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: /tmp/vagrant-shell20170920-25214-5aoqmq.sh

## Actual behavior
==> homestead-7: Updating to version 1.5.2 (stable channel).
==> homestead-7:    
==> homestead-7: Downloading (connecting...)
==> homestead-7: 
==> homestead-7: Downloading (100%)
==> homestead-7:          
==> homestead-7: 
==> homestead-7: Use composer self-update --rollback to return to version 1.4.2
