### ISSUE TITLE
php7.2-fpm Error after laravel/homestead box update

### ISSUE THREAD

**Issue by bbsnly** [laravel/homestead#694]
## Versions
  - Vagrant: 2.0.0
  - Provider: VirtualBox 5.1.30
  - Homestead: 6.4.0

## Host operating system
MacOS

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code
      type: "nfs"

sites:
    - map: demo.dev
      to: /home/vagrant/Code/demo

databases:
    - demo
```

## Error
When running `vagrant up|reload --provision` it fails to restart Nginx: `php7.2-fpm.service not found`.
Somehow the *php7.2-fpm* is not installed, inside the `/etc/php/7.2/` there is just the `mods-available` folder
