### ISSUE TITLE
sqlsrv driver not available with php 7.1

### ISSUE THREAD

**Issue by abhimanyu003** [laravel/homestead#715]
## Versions
  - Vagrant: 2.0.0.
  - Provider: Virtualbox
  - Homestead: 6.5.0

There is no sqlsrv driver available with php7.1 **but it if we use php7.2 it is working fine.**

## Host operating system
4.11.12-1-rt16-MANJARO

## Homestead.yaml

**No sqlsrv driver**
```yaml
sites:
    - map: homestead.test
      to: /home/vagrant/code/homestad/public
```

**sqlsrv driver available**

```yaml
sites:
    - map: homestead.test
      to: /home/vagrant/code/homestad/public
      php: "7.2"
```
