### ISSUE TITLE
Unable to load dynamic library pdo_sqlsrv.so

### ISSUE THREAD

**Issue by nWidart** [laravel/homestead#719]
## Versions
  - Vagrant: `2.0.1`
  - Provider: Virtualbox, version `5.1.30 r118389`
  - Homestead: `6.5.0`

## Host operating system
Mac Os `10.12.6 (16G29)`

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /Users/nicolaswidart/Sites/Freelance/Themosis/projectname
        to: /home/vagrant/code
sites:
    -
        map: projectname.dev
        to: /home/vagrant/code/htdocs
databases:
    - projectname
name: projectname
hostname: projectname
mariadb: true

```

## Vagrant up output
https://gist.github.com/nWidart/bafba3801a948021388fb7d897a3e090

## Expected behavior
No errors related to the `pdo_sqlsrv.so` extension

## Actual behavior

```
PHP Startup: Unable to load dynamic library &#039;/usr/lib/php/20160303/pdo_sqlsrv.so&#039; - /usr/lib/php/20160303/pdo_sqlsrv.so: cannot open shared object file: No such file or directory in file Unknown on line 0
```

It's doing this mostly on some ajax calls. Yes, not all, and not on page load itself. 
It's also doing this on the initial page load after a fresh vagrant up, but after a refresh or 2, it disappears.

Thanks,
