### ISSUE TITLE
Suggested improvements to installation notes for Windows

### ISSUE THREAD

**Issue by SteveALee** [laravel/homestead#722]
I just installed Homestead on Windows and hit several issues not covered in the [installation notes](https://laravel.com/docs/5.5/homestead#installation-and-setup). Here is a summary for you to consider adding so others do not waste so much time as I did

I did not make it a pull request as given the fact you removed notes on ssh key creation you obviously have opinions about what should be included. I'm happy to issue a PR after discussion.

1. Ensure virtualisation is enabled in the BIOS 
1. Ensure hyper-v is not enabled in (`Turn Windows features on or off`)
1. Ensure Bitdefender `Settings -> Advanced -> scan hosts file `option is off as it comments out new lines
1. Follow [these instructions](http://backendtime.com/setup-laravel-homestead-windows/) to install Homestead and optionally Heidi 
1. Edit `C:\windows\system32\drivers\etc\hosts` as admin and add `192.168.10.10 service-momo.app` at the end. 
1. Run `vagrant plugin install vagrant-winnfsd` to install nfs support and add `type: nfs` to any folder mapping in `Homestead.yaml` . This makes loads faster.
1. Adjust the Folders and Mapping sections in the `Homestead.yaml` file to be per site: 
```yaml 
    - map: ~/projects/site-a 
      to: /home/vagrant/code/site-a 
      type: nfs 
 
    sites: 
    - map: site-a.app 
      to: /home/vagrant/code/site-sa/public 
``` 

I didn't add a step for changing the virtual disk to fixed size as it seems this may not longer make much difference on Windows, and it's fiddly to do.
