### ISSUE TITLE
Only one nginx entry, subsequent entries are not mapped

### ISSUE THREAD

**Issue by Dixon-Jose** [laravel/homestead#739]
## Versions
  - Vagrant: 2.0.1.
  - Provider: Virtualbox 5.2.0.
  - Homestead: 6.5.0

## Host operating system
Linux mint 18.2

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects/code
      to: /home/vagrant/code
sites:
    - map: starting.dev
      to: /home/vagrant/code/starting/public
sites:
    - map: alterBIT.dev
      to: /home/vagrant/code/alterBIT/public

databases:
    - alterbit
    - starting

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```
## Vagrant up output
https://gist.github.com/Dixon-Jose/195da202bcfd1f58566747aa70d419a3
## Expected behavior
starting.dev should load /home/vagrant/code/starting/public but instead loads alterbit.dev
## Actual behavior
In /etc/nginx/sites-available there is no entry for the second site if manually created it works fine.
tried vagrant reload --provision, vagrant destroy and re vagrant up but no entry for the second site

## Steps to reproduce
1. Add mapping to a second site
2.load the second url
3.instead shows the first site

**Comment by svpernova09** [comment]
You don't need multiple `sites` settings. And you should map each project folder individually.

```
folders:
    - map: ~/Projects/code/starting
      to: /home/vagrant/starting
    - map: ~/Projects/code/alterBIT
      to: /home/vagrant/alterBIT
sites:
    - map: starting.dev
      to: /home/vagrant/starting/public
    - map: alterBIT.dev
      to: /home/vagrant/alterBIT/public
```
