### ISSUE TITLE
Timed out after updating homestead

### ISSUE THREAD

**Issue by cloudbluedigital** [laravel/homestead#745]
## Versions
  - Vagrant 2.0.1
  - Provider: Virtualbox - Version 5.1.30 r118389 (Qt5.6.2)
  - Homestead: v5.0.1 

## Host operating system
Windows 10

## Homestead.yaml
```yaml
ip:           192.168.20.20
memory:       2048
cpus:         1
provider:     virtualbox
authorize:    ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map:  'C:\Coding\webuilder'
        to:   /home/vagrant/webuilder
sites:
    -
        map:  webuilder.app
        to:   /home/vagrant/webuilder/public
        php:  "7.2"
databases:
    - webuilder
name:         webuilder
hostname:     webuilder

```

## Vagrant up output
https://gist.github.com/cloudbluedigital/cd78c8dc3b3d09fd8b8aa1dbb6d9ae59

## Expected behavior
Vagrant up to actually start a machine

## Actual behavior
Errored out and given response given in output, it happens randomly and sometimes it does actullay start up but I can't figure out when. Once it does it complains about guest additions being out of date
