### ISSUE TITLE
the path is case-insensitive in the share folders

### ISSUE THREAD

**Issue by cloudsthere** [laravel/homestead#746]
Vagrant 1.9.5
virtualbox

directive like `less TEST` can open file `test` inside the share  folders, which is `/htdocs` in my homestead.
How can i turn it back to the way it should be, which  i mean case-sensitive.
```
memory: 2048
cpus: 1
provider: virtualbox
box: laravel/homestead

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/htdocs
      to: /htdocs
```
