### ISSUE TITLE
HTTPS not working

### ISSUE THREAD

**Issue by kimtree** [laravel/homestead#754]
## Versions
  - Vagrant: Vagrant 2.0.1
  - Provider: VirtualBox 5.2.2 r119230
  - Homestead: Tag v7.0.1

## Host operating system
MacOS 10.13.2(17C88)

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 4096
cpus: 4
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /Users/kimtree/Documents/datable/hashup
      to: /home/vagrant/Code/hashup
      type: "nfs"
    - map: /Users/kimtree/Documents/datable/queduck
      to: /home/vagrant/Code/queduck
      type: "nfs"

sites:
    - map: hashup.dev
      to: /home/vagrant/Code/hashup/public
      php: "7.0"
    - map: queduck.dev
      to: /home/vagrant/Code/queduck/public
      php: "7.0"

databases:
    - homestead
```

## Vagrant destroy & up output
https://gist.github.com/kimtree/50cc80eed0f344417f7a42129f83fcdd

## Expected behavior
It has to be work.

## Actual behavior
Chrome 63.0.3239.84(stable) (64bit) returns "NET::ERR_CERT_AUTHORITY_INVALID" error and It shows info below.

Subject: hashup.dev
Issuer: hashup.dev
Expires on: 2018. 12. 7.
Current date: 2017. 12. 7.

## Steps to reproduce
1. vagrant up
2. Just open a site URL from host machine 

## References
None.
