### ISSUE TITLE
Google Chrome Privacy Issue

### ISSUE THREAD

**Issue by hounslow** [laravel/homestead#758]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 1.9.6
  - Provider: Virtualbox 5.1.30
  - Homestead: 5.0.1

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
macOS High Sierra 10.13.2 

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /Users/matthewhounslow/Homestead/Code
      to: /home/vagrant/Code
      type: "nfs"

sites:
    - map: testapp.test
      to: /home/vagrant/Code/testapp/public
    - map: mobis4.test
      to: /home/vagrant/Code/mobis4/public
    - map: blog.test
      to: /home/vagrant/Code/testapp/blog/public
    - map: example.test
      to: /home/vagrant/Code/testapp/example/public
    - map: projectflyer.test
      to: /home/vagrant/Code/testapp/project-flyer/public
    - map: chartjs-app.test
      to: /home/vagrant/Code/testapp/learning-chartjs/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
[GitHub Gist](https://gist.github.com/hounslow/b970714842523231613084d2244aba60)

## Expected behavior
I should be able to run `vagrant up && vagrant ssh` followed by opening up my website in Chrome and seeing my homepage.

## Actual behavior
Getting the following output from Google Chrome:
Your connection is not private
Attackers might be trying to steal your information from mobis4.test (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID

## Steps to reproduce
1. vagrant up
2. vagrant ssh
3. Go to mobis4.test

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- GH-1234
- ...
