### ISSUE TITLE
Can't Debug Laravel App On Homestead Via PhpStorm

### ISSUE THREAD

**Issue by remyoucef** [laravel/homestead#774]
## Versions
  - Vagrant: 2.0.1.
  - Provider: Virtualbox 5.2.2.
  - Homestead: 5.0.1.

## Host operating system
Windows 10 Pro

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
# gui: true
authorize: c:/Users/RYI/.ssh/id_rsa.pub

keys:
    - c:/Users/RYI/.ssh/id_rsa

folders:
    - map: f:/PhpstormProjects/TheRSM
      to: /home/vagrant/code/thersm

sites:
    - map: thersm.test
      to: /home/vagrant/code/thersm
      php: "7.0"
    - map: phpmyadmin.test
      to: /home/vagrant/code/phpmyadmin

databases:
    - thersm.test

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

#ports:
#     - send: 7777
#       to: 777
#       protocol: udp

```
## Description 
I do the following steps:
- Configure Homestead:
```
   - Install and config xdebug v2.4.1 for php7.0
   - run xon command
   
```
- Configure PhpStorm:
```
       - Add Deployment Server 
              - name: Homestead (TheRSM)
              - type: sftp, host:127.0.0.1
              - port:2222 
              - root path: /home/vagrant/code/thersm
      - Add CLI Interepreter 
              - name: Homestead PHP 7.0 
              - type: Deployment configuration [ Homestead (TheRSM)]
              - PHP executable: /usr/bin/php7.0 
              ** Result:**
                          PHP version: 7.0.26-1+ubuntu16.04.1+deb.sury.org+
                          Debuger: Xdebug v2.4.1] 
    -  Add PHP Server
             - name: thersm.test
             - host: thersm.test
             - port: 80
             - Debuger: Xdebug
             - Check Use path mappings 
                             "F:\PhpstormProjects\TheRSM"=>" /home/vagrant/code/thersm"
     - Start Listening for Php Debug Connections
     - Setup some Breakpoints
```

- Using Google Chrome & Xdebug helper extension or marklets

**Whene i browse "thersm.test"** the website show up without problems and PhpStorm **does'nt** showing any XDebug Incomming Connection.
I try many solutions on the net and none of them work.
