### ISSUE TITLE
mount.nfs: requested NFS version or transport protocol is not supported

### ISSUE THREAD

**Issue by Cysioland** [laravel/homestead#779]
## Versions
  - Vagrant: 2.0.1
  - Provider: Virtualbox 5.2.4 r119758
  - Homestead: 7.0.1

## Host operating system
Antergos

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/PhpstormProjects
      to: /home/vagrant/proj
      type: nfs

sites:
    - map: app.dev
      to: /home/vagrant/proj/app/public

databases:
    - app

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
https://gist.github.com/Cysioland/c1a012c11175aab3c5984c826b540ce7

## Expected behavior
Machine gets brought up with no issues

## Actual behavior
NFS folders can't be mounted, message in title

## Steps to reproduce
1. Use fully updated Antergos or Arch
2. vagrant up your Homestead machine with NFS shared folders
3. Error happens
