### ISSUE TITLE
Specifying site "type" doesn't work

### ISSUE THREAD

**Issue by octoxan** [laravel/homestead#790]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.0.0.
  - Provider: Virtualbox
  - Homestead: 5.0.1

## Host operating system
Ubuntu Budgie 17.04

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Develop/homestead/code
      to: /home/vagrant/code

sites:
    - map: laravel.test
      to: /home/vagrant/code/employ.ahs-se/public
    type: laravel
    - map: magento.test
      to: /home/vagrant/code/supertrapp/public
    type: apache

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
I'm not destroying my box.. but here's the error that's thrown from doing an up, provision, or ssh.

https://gist.github.com/octoxan/341cfd0797ac30638d010f88937278ff

## Expected behavior
I followed the docs exactly, so it should provision a site with type laravel and a site with type apache.

## Actual behavior
Box doesn't work until I remove type lines.

## Steps to reproduce
1. Create a box
2. Add a type to a site

**Comment by svpernova09** [comment]
The value for type must be a string. And you need to ensure your `Homestead.yaml` conforms to proper YAML syntax

```
sites:
    - map: laravel.test
      to: /home/vagrant/code/employ.ahs-se/public
      type: laravel
    - map: magento.test
      to: /home/vagrant/code/supertrapp/public
      type: "apache"
```

Also: You cannot mix type Apache with any other type since Apache purges Nginx. You should either use Homestead per project for your Apache project or the inverse for your Nginx project. Alternatively you could just run 2 global Homestead boxes, 1 for Apache projects, 1 for Nginx.
