### ISSUE TITLE
Dusk ChromeDriver not working until driver exec on a separate connection

### ISSUE THREAD

**Issue by envision** [laravel/homestead#793]
## Versions
  - Vagrant: 2.0.1
  - Provider: Virtualbox 5.2.4
  - Homestead: 7.0.1
  - Homestead box: 5.0.1
  - Laravel: 5.5.28
  - Laravel Dusk: 2.0.8
  - ChromeDriver: 2.33.506092

## Host operating system
macOS 10.13.

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code/app/
      to: /home/vagrant/app

sites:
    - map: thisproject.dev
      to: /home/vagrant/app/thisproject/public

databases:
    - thisproject

```

## Vagrant destroy & up output
https://gist.github.com/envision/b8dbef15d7d3cd2f036e50cf07a8201f

## Custom Dusk Browser Class
https://gist.github.com/envision/6c72a87d03311d282bd4010c9df90b3e

## Expected behavior
Expected Dusk ChromeDriver to work out of the box in Homestead.

## Actual behavior
Getting an error:
```
Facebook\WebDriver\Exception\WebDriverCurlException with message 'Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","chromeOptions":{"binary":"","args":["--disable-gpu","--headless","--no-sandbox","--no-first-run","--window-size=1600,1280"]}}}

Failed to connect to localhost port 9515: Connection refused
```

## Steps to reproduce
1. Save Gist 'Custom Dusk Browser Class' as a file named _Browser.php_ under _app/_
2. `homestead up && homestead ssh && cd app/thisproject`
3. Run: `php artisan tinker`
4. Run: `(new Browser)->browse(function ($b) { $b->visit('https://laracasts.com'); });`
5. Should get an error
6. Open a new terminal window and execute chromedriver: `homestead ssh && cd app/thisproject && vendor/laravel/dusk/bin/chromedriver-linux`
7. Should get output:
```
Starting ChromeDriver 2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4) on port 9515
Only local connections are allowed.
```
8. Run again in the previous tinker terminal: `(new Browser)->browse(function ($b) { $b->visit('https://laracasts.com'); });`
9. Should get `null` now and not an error
