### ISSUE TITLE
Projects running under PHP 5.6

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/homestead#795]
## Versions
  - Vagrant: 2.0.1
  - Provider: Virtualbox
  - Homestead: v7.0.1
  - Laravel: 5.4.36
  - PHP Version: 5.6.32

## Host operating system
Windows 10 Pro

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/pub

keys:
    - ~/.ssh/private.ppk

folders:
    - map: c:/OpenServer/domains
      to: /home/vagrant/code

sites:
    - map: mysite.loc
      to: /home/vagrant/code/mysite.dev/public
      subdomain: promo.mysite.loc
      php: "5.6"

databases:
    - helpers
    - main
```

## Actual behavior
The project works under PHP5.6. After updating the dependencies, an error occurred:
![2018-01-17 09-36-05 whoops there was an error - google chrome](https://user-images.githubusercontent.com/10347617/35030547-5fda6b96-fb70-11e7-8130-1c28f8e4e05b.png)

## Steps to reproduce
The error occurs if I access the `apiResource` method in `routes/api.php`:
```php
app('router')
    ->apiResource('orders', 'Api\OrdersController', [
        'only' => ['show', 'store'],
    ]);
```

If you remove the use of this method, the error disappears.

Next, in the file `composer.lock` found the following dependencies:
```
"name": "doctrine/annotations",
"version": "v1.6.0",
"php": "^7.1"

"name": "doctrine/collections",
"version": "v1.5.0",
"php": "^7.1"

"name": "doctrine/inflector",
"version": "v1.3.0",
"php": "^7.1"

"name": "doctrine/instantiator",
"version": "1.1.0",
"php": "^7.1"

"name": "symfony/css-selector",
"version": "v4.0.3",
"php": "^7.1.3"

"name": "symfony/event-dispatcher",
"version": "v4.0.3",
"php": "^7.1.3"

"name": "symfony/yaml",
"version": "v4.0.3",
"php": "^7.1.3"

"name": "phpdocumentor/reflection-docblock",
"version": "4.2.0",
"php": "^7.0",

"name": "phpunit/php-token-stream",
"version": "2.0.2",
"php": "^7.0"
```

If I use routes:
```php
app('router')
    ->get('orders/{orders}', 'Api\OrdersController@show')
    ->name('orders::show');

app('router')->post('orders', 'Api\OrdersController@store')
    ->name('orders::store');
```
then problem not found.

## Found a solution
The problem occurs because when you execute the `composer update` command, it runs from under php 7.2, which is set by default in Homestead.

```json
    "require": {
        "php": ">=5.6.4",
        "andrey-helldar/spammers": "^1.0",
        "doctrine/dbal": "2.5.*",
        "graham-campbell/exceptions": "^9.0",
        "jenssegers/agent": "^2.6",
        "laracasts/utilities": "^3.0",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "morrislaptop/laravel-queue-clear": "^1.1",
        "pda/pheanstalk": "^3.1",
        "predis/predis": "^1.1"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "~2.4",
        "barryvdh/laravel-ide-helper": "^2.4",
        "filp/whoops": "^2.1",
        "fzaninotto/faker": "~1.4",
        "mnabialek/laravel-sql-logger": "^1.1",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7",
        "reliese/laravel": "^0.0.13"
    },
```

Just found a solution to the problem in Homestead:
```bash
cd ~/code/mysite.loc/
wget https://getcomposer.org/composer.phar
cd /etc
php5.6 ~/code/mysite.loc/composer.phar update -d "/home/vagrant/code/mysite.loc/"
```

When executing the command, the packages successfully downgraded:
```bash
Package operations: 0 installs, 11 updates, 0 removals
  - Updating symfony/css-selector (v4.0.3 => v3.4.3): Loading from cache
  - Updating symfony/event-dispatcher (v4.0.3 => v3.4.3): Loading from cache
  - Updating doctrine/inflector (v1.3.0 => v1.1.0): Loading from cache
  - Updating symfony/yaml (v4.0.3 => v3.4.3): Loading from cache
  - Updating doctrine/instantiator (1.1.0 => 1.0.5): Loading from cache
  - Updating doctrine/annotations (v1.6.0 => v1.4.0): Loading from cache
  - Updating doctrine/cache (v1.7.1 => v1.6.2): Loading from cache
  - Updating doctrine/collections (v1.5.0 => v1.4.0): Loading from cache
  - Updating phpdocumentor/reflection-docblock (4.2.0 => 3.3.2): Loading from cache
  - Updating phpunit/php-token-stream (2.0.2 => 1.4.12): Loading from cache

```

**Comment by andrey-helldar** [comment]
You can also add an alias to `aliases` file in Homestead dir:

```bash
alias composer56=composer56

function composer56() {
    path=$(pwd)
    composerFile=/home/vagrant/composer.phar

    if sudo [ ! -f $composerFile ]; then
        wget https://getcomposer.org/composer.phar -O $composerFile
    fi  
    
    /usr/bin/php5.6 $composerFile -d $path $@
}
```

And run `vagrant reload --provision`

**Comment by andrey-helldar** [comment]
You can also add an alias to `aliases` file in Homestead dir:

```bash
alias composer56=composer56

function composer56() {
    path=$(pwd)
    composerFile=/home/vagrant/composer.phar

    if sudo [ ! -f $composerFile ]; then
        wget https://getcomposer.org/composer.phar -O $composerFile
    fi  
    
    /usr/bin/php5.6 $composerFile $@ -d $path
}
```

And run `vagrant reload --provision`

Then you can use in projects alias `composer56`.
Example:
```bash
composer56 update
composer56 require foo/bar
```

**Comment by svpernova09** [comment]
This isn't a Homestead issue, this is an issue that composer was run against a different version of PHP than you expected. 

We have existing aliases to easily swap PHP versions for the CLI: `php56`, `php70`, `php71`, `php72`. You should use these to change versions as needed.

**Comment by andrey-helldar** [comment]
Why change the PHP version in the system?
And if I use at least two versions of PHP?

Example, I's my home configuration of Homestead:
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa.ppk

folders:
    - map: f:/OpenServer/domains
      to: /home/vagrant/code

sites:
    - map: ai-rus.loc
      to: /home/vagrant/code/ai-rus.loc/public
      schedule: true
      
    - map: laravel-doc.loc
      to: /home/vagrant/code/laravel-doc.loc/public
      
    - map: work.loc
      to: /home/vagrant/code/work.loc/public
      subdomain: promo.work.loc
      php: "5.6"
      
    - map: sales.work.loc
      to: /home/vagrant/code/sales.work.loc/public
      php: "5.6"

databases:
    - ai_rus
    - docs
    - work
```

At the same time, I can simultaneously work with at least two projects.
As you can see, you do not need to change the PHP version via helper in this case.

(translated by Google Translate)
