### ISSUE TITLE
Homestead updating problem

### ISSUE THREAD

**Issue by themeyellow** [laravel/homestead#798]
## Versions
  - Vagrant: 2.0.0
  - Provider: Virtualbox - 5.2.6
  - Homestead: 7

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: E:\Projects
      to: /home/vagrant/Projects

sites:
    - map: phpmyadmin.test
      to: /home/vagrant/Projects/phpMyAdmin

    - map: evaluationplus.test
      to: /home/vagrant/Projects/laravel-evaluationplus/public

    - map: govt-university.test
      to: /home/vagrant/Projects/govt-university/public

    - map: laravel-university.test
      to: /home/vagrant/Projects/laravel-university/public

    - map: pixel.test
      to: /home/vagrant/Projects/pixel/public

    - map: acl.test
      to: /home/vagrant/Projects/acl/public

    - map: voyager.test
      to: /home/vagrant/Projects/voyager/public

    - map: test-project.test
      to: /home/vagrant/Projects/test-project/public

    - map: lazada.test
      to: /home/vagrant/Projects/lazada/public

    - map: joongwon.test
      to: /home/vagrant/Projects/joongwon/public
      
    - map: bookmanager.test
      to: /home/vagrant/Projects/bookmanager/public

    - map: kusom-api.test
      to: /home/vagrant/Projects/kusom-api/public

    - map: theme-yellow.test
      to: /home/vagrant/Projects/yellow-php-user-management-system

    - map: sximo.test
      to: /home/vagrant/Projects/sximo/public

    - map: awesomemail.test
      to: /home/vagrant/Projects/awesomemail

    - map: packages.test
      to: /home/vagrant/Projects/packages/skype/public

    - map: routing.test
      to: /home/vagrant/Projects/routing
      
    - map: routes-test.test
      to: /home/vagrant/Projects/routes-test

    - map: mvc.test
      to: /home/vagrant/Projects/yellow-mvc-framework

    - map: multiuser-site.test
      to: /home/vagrant/Projects/multiuser-site

databases:
    - evaluationx
    - acl
    - govt-university
    - laravel-university
    - pixel
    - test_project
    - voyager
    - lazada
    - joongwon
    - bookmanager
    - kusom_api
    - theme_yellow
    - sximo
    - awesomemail
    - packages
    - yellow_mvc_structure
    - multiuser_site

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
     - send: 50000
       to: 5000
     - send: 7777
       to: 777
       protocol: udp
```

## Vagrant destroy & up output
https://gist.github.com/themeyellow/4a18f0d10ff94daa8cabbe1dbab8db2d

## Expected behavior
I'm updating Homestead following laravel homestead doc (https://laravel.com/docs/5.5/homestead#updating-homestead). After running (vagrant box update) it's updated vagrant box and i was run (1. git pull origin master & 2. composer update) this two command after by after. It's work fine when my pc running those updating time. After restart my pc when i'm running vagrant up then showing me gist error. And homestead version command not working, i'm see homestead 7 in virtualbox.

Thanks,
Arafat
