### ISSUE TITLE
Machine clock loses time synchronisation when computer goes to sleep

### ISSUE THREAD

**Issue by seblavoie** [laravel/homestead#799]
## Versions
  - Vagrant: Vagrant 2.0.1
  - Provider: Virtualbox
  - Homestead: 7.0.1

## Host operating system
macOS 10.13.2

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code
      type: nfs

sites:
    - map: default
      to: /home/vagrant/Code/dovi-website/public
    - map: dovi-website.test
      to: /home/vagrant/Code/dovi-website/public

databases:
    - homestead
    - dovi

ports:
    - send: 8000
      to: 80
```

## Vagrant destroy & up output
Can't really restore the machine now (sorry about that), but the bug has been happening for a couple of versions and my last provisions didn't throw anything weird. If it is really necessary I'll be able to provide it, but I don't think it is absolutely necessary in the case of this issue.

## Expected behavior
Time should stay synced. 

## Actual behavior
Now what happens is when my mac goes to sleep, the virtual machine's clock gets unsynchronized. I get errors when trying to run queues, use pusher or upload to Amazon S3.

## Steps to reproduce
1. Run homestead up
2. Put mac to sleep
3. Wake mac and try to run queues or upload files to S3.

## References
There are issues on Laracasts detailing the same issue. As per the answers, it seems to have to do with the `timesync-set-threshold` in the vagrant file. 
https://laracasts.com/discuss/channels/general-discussion/homesteadvagrant-time-drift-help
https://laracasts.com/discuss/channels/general-discussion/homestead-wrong-time?page=1
