### ISSUE TITLE
XDebug not loaded in PHP

### ISSUE THREAD

**Issue by tyteen4a03** [laravel/homestead#800]
I can't seem to get xdebug to work in the box. `phpinfo()` does not show the xdebug session being loaded.

I have tried running `xon` in `vagrant ssh` with no results.

I'm using box v5.0.1, Homestead v7.0.1, VirtualBox 5.2.6. MacOS 10.13.2.

Homestead.yaml:

```
---
ip: "192.168.10.10"
memory: 4096
cpus: 4
provider: virtualbox
mariadb: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: test.test
      to: /home/vagrant/code/test/public

databases:
    - upmud9

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

`vagrant up` after `vagrant destroy`: https://gist.github.com/tyteen4a03/7f37ddcabb2ae64cd3a0dd2430954ae0
