### ISSUE TITLE
Literally nothing happens when I run `vagrant up`

### ISSUE THREAD

**Issue by Roemerb** [laravel/homestead#801]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.0.1
  - Provider: Virtualbox: 5.2.4r119785
  - Homestead: 7.0.1 (CLI), 5.0.1 (Box)

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
macOS Sierra 10.12.6

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 512
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/ownCloud/dev/Web
      to: /home/vagrant/Code
    - map: ~/ownCloud/dev/PHP
      to: /home/vagrant/PHP

sites:
    - map: personal.test
      to: /home/vagrant/Code/Personal_lara/public
    - map: magento.test
      to: /home/vagrant/Code/magento
    - map: wp.test
      to: /home/vagrant/Code/wp
    - map: makelaar.test
      to: /home/vagrant/Code/makelaarstvcom/public
    - map: payments.test
      to: /home/vagrant/Code/spryngpaymentscom-testing
    - map: presta.test
      to: /home/vagrant/Code/prestashop
    - map: wc.test
      to: /home/vagrant/Code/wc
    - map: focus.test
      to: /home/vagrant/Code/Focus/public
    - map: twin.test
      to: /home/vagrant/Code/Twinspark
databases:
    - homestead

variables:
    - key: 'APP_ENV'
      value: 'local'
    - key: 'APP_DEBUG'
      value: 'true'
```

## Vagrant destroy & up output
Nothing happends, not even on `destroy`

## Expected behavior
The box should boot up

## Actual behavior
While working on a project today, my Homestead box suddenly no longer had an internet connection. After rebooting and messing with some VirtualBox preferences I still could not get it to work. So, I decided to `destroy` the box and re-create it. I found this to be an excellent chance to get the latest version of Homestead, so I updated the CLI and the box (`vagrant box add laravel/homestead --force`). Unfortunately, the fresh box does not boot. When I run `vagrant up` or `vagrant up --provision`, absolutely nothing happens whatsoever. Nothing happens on `vagrant destroy` either...

![Screenshot](https://i.imgur.com/D6o8v4E.png)

Any thoughts on why this could be happening?

## Steps to reproduce
1. `vagrant up`
