### ISSUE TITLE
Running vagrant up fails when mounting SMB shared folders. (Windows 10, Hyper-V)

### ISSUE THREAD

**Issue by KubqoA** [laravel/homestead#802]
## Versions
  - Vagrant: 2.0.1
  - Provider: Hyper-V
  - Homestead: 7.0.1 (CLI), 5.0.1 (Box)

## Host operating system
Windows 10 Pro

## Homestead.yaml
```yaml
---
ip: "172.21.12.10"
memory: 2048
cpus: 1
provider: hyperv
mariadb: true

authorize: c:/Users/arbet/.ssh/id_rsa.pub

keys:
    - c:/Users/arbet/.ssh/id_rsa

folders:
    - map: c:/Users/arbet/Documents/Projects
      to: /home/vagrant/code

sites:
    - map: site.test
      to: /home/vagrant/code/site/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
[GitHub Gist](https://gist.github.com/KubqoA/d8c3296408886753f2b24b39c1dbcaa3)

## Expected behavior
It should boot up and create the whole virtual machine, mounting SMB shared folders and provisioning.

## Actual behavior
It fails after it tries to mount SMB shared folders. I suspect it can be because of bad SMB username, because I am using a Microsoft account and I don't know what should be the proper SMB username. However the output also says `mount error(112): Host is down`

## Steps to reproduce
1. Enable HyperV on Windows 10 Pro
2. Install Vagrant
3. Add homestead Vagrant box
4. Run vagrant up

## References
No.

**Comment by DaWolfey** [comment]
Explicitly set the type to "smb" (under Folder)
You may also need to edit homstead.rb to set the smb version to 2.1 (search for vers= and change it to 2.1).

**Comment by KubqoA** [comment]
Now I am getting mount error(13). Can it be connected to the fact that I am using Microsoft Account? Because I tried several login options and non of them worked.

**Comment by svpernova09** [comment]
It *could* be the Microsoft account, but I honestly don't know. I would try creating a new user and testing it with a non Microsoft account to verify.

**Comment by DaWolfey** [comment]
I use a microsoft account with my profile, and so long as I use the full email address it works correctly.

Revert the edit to homestead.rb, and edit the homestead.yaml:

folders:
    - map: c:/Users/arbet/Documents/Projects
      to: /home/vagrant/code
      type: "smb"
      mount_options: ['vers=2.1', 'mfsymlinks']

which I discovered after my previous post is the correct way.

If it fails to mount, check to see if the shares actually exist on your local machine. If they don't, you'll need to go upstream to vagrant. Post the vagrant up log again, specifically the mount command it tries

**Comment by joachimvs** [comment]
@DaWolfey i have the same issue as @KubqoA . After using your latest settings "vagrant up" seems to run succesfully. But if i use "vagrant ssh" , cd into the folder that i have binded my folder to and i then run "dir" i get the output: "reading directory '.': Input/output error".

**Comment by svpernova09** [comment]
Closing for inactivity / unable to confirm resolved. To anyone experiencing this issue I would review this comment for suggestions: https://github.com/laravel/homestead/issues/802#issuecomment-360251150

**Comment by kulikov-e-s** [comment]
@KubqoA Did you manage to resolve this problem? I'm facing the same

**Comment by danielabbatt** [comment]
I also had this issue, but not with the main folder I was attempting to share, but rather with the /vagrant share that's used for provisioning.
I found that explicitly creating an entry for both the folder I wanted to share, that was using vers=3.02 just fine, and also specifying smb then worked. Otherwise it wasn't pulling in the mount options that are set in the homestead.rb into the end script which is mount_smb_shared_folder.rb as part of Vagrant itself.
```
folders:
    - map: f:/code
      to: /home/vagrant/code
      type: "smb"
    - map: f:/code/Homestead-hyperv
      to: /vagrant
      type: "smb"
```
