### ISSUE TITLE
Homestead could not find driver sqlsrv

### ISSUE THREAD

**Issue by alejoloe007jb** [laravel/homestead#803]
## Versions
  - Vagrant: 2.0.1
  - Provider: Virtualbox
  - Homestead: 7.0.1

## Host operating system
This is the operating system that you run locally.

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
mariadb: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: D:/code
      to: /home/vagrant/code

sites:
    - map: khipu.org
      to: /home/vagrant/code/khipu/public
      php: "7.2"

databases:
    - homestead
```
