### ISSUE TITLE
Zray requires string literal to enable

### ISSUE THREAD

**Issue by Fuxy22** [laravel/homestead#805]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.01
  - Provider: Virtualbox
  - Homestead: 7.1.0

## Host operating system
Linux Mint 17

## Homestead.yaml
```
sites:
    - map: labelprint.io
      to: /home/vagrant/Code/labelprint/public
      schedule: true
      zray: 'true'
```

## Expected behavior
Homestead.yaml would take a boolean to enable or disable zray

## Actual behavior
Z-ray setting requires a string instead.

## Steps to reproduce
1. Set zray setting as boolean
2. Receive below error:
```
Bringing machine 'homestead-7' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* Shell provisioner `args` must be a string or array.
```

Note: This can be a config breaking change so I'm no certain how you want to handle it.
