### ISSUE TITLE
Composer root permision error during "vagrant up"

### ISSUE THREAD

**Issue by dabagab** [laravel/homestead#811]
Composer error: 
You are running composer as "root", while "/home/vagrant/.composer" is owned by "vagrant"
You are already using composer version 1.6.3 (stable channel).

## Versions
  - Vagrant: 2.0.1
  - Provider: Virtualbox 5.2.6
  - Homestead: This command not available, but I just used git clone command to get the latest 30 minutes ago. 

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Fedora 27

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 1024
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects/yyy
      to: /home/vagrant/yyy

sites:
    - map: symfony-app.test
      to: /home/vagrant/yyy/public
      type: symfony4

databases:
    - homestead
```

## Vagrant destroy & up output
 [VagrantUP](https://gist.github.com/dabagab/d198a2dafdd14b8c09a911daeb7a5b98#file-vagrantup-homestead)
Proble is in the line: 135-136

## Expected behavior
composer command could run automatically

## Actual behavior
I have to ssh login to the Homestead and then manually running the composer command.

## Steps to reproduce
1. Git clone "this repository"
2. Running "vagrant up"
3.

## References
I did not find. Maybe this [stackoverflow](https://stackoverflow.com/questions/48576754/vagrant-reload-provision-is-wrong-says-running-composer-as-root-how-can-i-do) entry.
