### ISSUE TITLE
Error when using Z-Ray on provisioning

### ISSUE THREAD

**Issue by marijnhurkens** [laravel/homestead#814]
When using `zray: 'true'` I get an error when using vagrant up (after destroying the environment):

```
failed to create symbolic link '/home/vagrant/code/public/ZendServer'
Protocol error
```

Running Vagrant 2.0.1 on Windows on VirtualBox 5.2.6 r120293 and Homestead 7.1.21.

This seems to be a permission error?

## Homestead.yaml
```yaml
sites:
    -
        map: homestead.test
        to: /home/vagrant/code/public
        php: "7.1"
        zray: 'true'
```

## Expected behavior
The symlink should be created.

**Comment by svpernova09** [comment]
Please post your Homestead.yaml (as the issue template mentions).

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by marijnhurkens** [comment]
Homestead.yaml

```
ip: 192.168.10.10
memory: 8096
cpus: 6
provider: virtualbox
authorize: C:\Users\username\.ssh\rsa.pub
keys:
    - C:\Users\username\.ssh\rsa.ppk
folders:
    -
        map: 'D:\Development\campaign-manager'
        to: /home/vagrant/code
sites:
    -
        map: homestead.test
        to: /home/vagrant/code/public
        php: "7.1"
        zray: 'true'
databases:
    - homestead
name: campaign-manager
hostname: campaign-manager
ssl: true
```

**Comment by svpernova09** [comment]
Z-Ray will only work for PHP 7.2, that is why the symlink is not being created.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by marijnhurkens** [comment]
New config:

```
sites:
    -
        map: homestead.test
        to: /home/vagrant/code/public
        php: "7.2"
        zray: 'true'
````

Output:

```
    campaign-manager: ln: failed to create symbolic link '/home/vagrant/code/public/ZendServer': Protocol error
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
````

Using PHP 7.2 doenst resolve the problem
