### ISSUE TITLE
can not use php5.5, 5.6, 7.0 and 7.2

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/homestead#815]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.0.1
  - Provider: Virtualbox 5.2.4
  - Homestead: bash: homestead: command not found

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: c:/homestead_projects
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead
```

## Vagrant destroy & up output
https://gist.github.com/michaelnguyen547/9a200ced3f6ad7bdeed76c63d558a343

## Expected behavior
Should be able to run PHP 5.6, 7.0, 7.1 and 7.2

## Actual behavior
What actually happened? Please include as much detail as possible.
I can only run PHP 7.1 (which is default). 

php5.5
php5.6
php7.0
php7.2
all give command not found
