### ISSUE TITLE
Homestead memory leak with Z-Ray

### ISSUE THREAD

**Issue by micc83** [laravel/homestead#825]
## Versions
  - Vagrant: 2.0.2
  - Provider: Virtualbox
  - Homestead: 5.1.0

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: ___
        to: ___
sites:
    -
        map: ___
        to: ___
        schedule: true
databases:
    - homestead
name: code
hostname: code

```

## Expected behavior
Z-Ray data collection shouldn't be enabled by default.

## Actual behavior
Z-Ray collect queries even though `zray: 'true'` is not set on `Homestead.yaml`. This cause huge memory leak when running a large number of queries on an artisan command (on the CLI).

## Temporary fix
Add the following in the `__construct` method of your command.
```php
if (function_exists('zray_disable')){
    zray_disable(true);
}
```

## Notes
Even if you'll decide to do nothing about it, I thought it would be useful to leave it here for future reference. I got crazy looking for the cause of the leak.
