### ISSUE TITLE
Sites from Homestead.yaml ignored, no files in /etc/nginx/sites-available.

### ISSUE THREAD

**Issue by sustained** [laravel/homestead#827]
## Versions
  - Vagrant: 2.0.2
  - Provider: Virtualbox (5.2.8)
  - Homestead: 7.2.0

## Host operating system
Fedora

## Homestead.yaml
```yaml
---
networks:
  - type: "public_network"
    ip: "192.168.3.10"

#ip: "127.0.0.1"

memory: 2048
cpus: 1
provider: virtualbox

#authorize: ~/.ssh/id_rsa.pub
#keys:
#    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects/fladdermus-api
      to: /home/vagrant/fladdermus-api

sites:
    - map: fladdermus.api
      to: /home/vagrant/fladdermus-api/public

databases:
    - homestead
```

## Vagrant destroy & up output
https://gist.github.com/sustained/b7ea519d8ccfb60c0aca3cbedb0c33fe

## Expected behavior
There would be some mention of `sites` and them being created in the output of `vagrant up`.

## Actual behavior
There was not.
