### ISSUE TITLE
Type error: Argument 3 passed to MongoDB\Driver\Server::executeQuery() 

### ISSUE THREAD

**Issue by nicholasmaddren** [laravel/homestead#829]
## Versions
  - Vagrant: 2.0.0
  - Provider: Virtualbox
  - Homestead: 7.3.0

## Host operating system
macOS High Sierra

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
mongodb: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code/site
      to: /home/vagrant/site
sites:
    - map: site.local
      to: /home/vagrant/site/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
https://gist.github.com/nicholasmaddren/c4de5780ddd2980611b1ad532c10d65f

## Expected behavior
MongoDB should not return errors when trying to use it.

## Actual behavior
I have tried to use MongoDB in my `web.php` file on my Laravel application like so:
```
use MongoDB\Client as Mongo;
Route::get('mongo', function(Request $request) {
      // connect
    $m = new Mongo();

    // select a database
    $db = $m->homestead;

    // select a collection (analogous to a relational database's table)
    $collection = $db->cars;

    // find everything in the collection
    $cursor = $collection->find();

    return $cursor;
});
```

For some reason I get this error when I visit the route:
```
 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Argument 3 passed to MongoDB\Driver\Server::executeQuery() must be an instance of MongoDB\Driver\ReadPreference or null, array given
```
I have tried adding `mongodb: true` to my Homestead.yaml which appears to install the database fine. I can `vagrant ssh` and then run `mongo` and add data to the database. It seems to fail when I use the PHP Mongo driver to get the data from the database.

## Steps to reproduce
1. Install Laravel project
2. `composer require mongodb/mongodb` in project folder.
3. Add `mongodb: true` to `Homestead.yaml`.
4. Run `vagrant halt`.
5. Run `vagrant up --provision`.
6. Try and use MongoDB from the Laravel application.
