### ISSUE TITLE
Certificate - missing. This site is missing a valid, trusted certificate

### ISSUE THREAD

**Issue by ryancwalsh** [laravel/homestead#834]
## Versions

  - Provider: Virtualbox

```
vboxmanage --version
5.2.6r120293

vagrant -v
Vagrant 2.0.2

git branch
* (HEAD detached at v7.3.0)

vagrant box list
laravel/homestead (virtualbox, 5.2.0)

vagrant box update
==> vboxHomestead: Checking for updates to 'laravel/homestead'
    vboxHomestead: Latest installed version: 5.2.0
    vboxHomestead: Version constraints: >= 5.2.0
    vboxHomestead: Provider: virtualbox
==> vboxHomestead: Box 'laravel/homestead' (v5.2.0) is running the latest version.

homestead.bat --version
Vagrant 2.0.2
```

## Host operating system
Windows 10

## Homestead.yaml
```yaml


---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox
hostname: vboxHomestead
name: vboxHomestead
#gui: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: c:/code
      to: /home/vagrant/Code


      
sites:

    - map: kvb.192.168.1.102.xip.io
      to: /home/vagrant/Code/katievb-laravel/public
      schedule: false
    - map: kvb.test
      to: /home/vagrant/Code/katievb-laravel/public
      schedule: false
    - map: kvbold.rcw    
      to: /home/vagrant/Code/katievb-members-old
      schedule: false
    

databases:
    - homestead
    
networks:
    - type: "public_network"
      ip: "192.168.1.119"
      bridge: "Realtek RTL8811AU Wireless LAN 802.11ac USB 2.0 Network Adapter"

```

## Vagrant destroy & up output
https://gist.github.com/ryancwalsh/268caa5405883f70942333c3f8c54bdd

## Expected behavior
I expect that my Chrome and Firefox accept the Homestead certificate and don't mark my local sites as a security risk. I need to be able to develop SSL features such as with Stripe (https://stackoverflow.com/q/49390912/470749)

## Actual behavior
I'm getting this problem:

[![enter image description here][1]][1]

The error that I'm seeing in Windows 10 Chrome Version 65.0.3325.181 (Official Build) (64-bit) is:

> Your connection is not private 

> Attackers might be trying to steal your
> information from ((mysite)) (for example, passwords,
> messages, or credit cards). Learn more NET::ERR_CERT_AUTHORITY_INVALID
> 
> This page is not secure (broken HTTPS). 

> Certificate - missing 

> This
> site is missing a valid, trusted certificate
> (net::ERR_CERT_AUTHORITY_INVALID).

Firefox Quantum 59.0.2 (64-bit) says:

> Your connection is not secure
> 
> The owner of ((mysite)) has configured their website
> improperly. To protect your information from being stolen, Firefox has
> not connected to this website.
> 
> Connection is Not Secure 

> Could not verify this certificate because the
> issuer is unknown.

## Steps to reproduce
1. vagrant up
2. Browse to my local site in Chrome or Firefox
3. Notice the security warnings (and that Stripe fails to load SSL features)

## References

- https://github.com/laravel/homestead/issues/526
- https://github.com/laravel/homestead/issues/754
- https://github.com/laravel/homestead/pull/701

  [1]: https://i.stack.imgur.com/8VNn7.png

**Comment by svpernova09** [comment]
When you get these errors there should be an option to add an exception to trust the site. You need to do that in order for the cert to work. You may not see a green icon, but SSL will work once this is done.

**Comment by ryancwalsh** [comment]
@svpernova09 Thanks. I've already tried adding the domain as a security exception, and even though that enables me to load the page (using https, even though it says "Not secure" in red), certain browser functions seem blocked. 

For example, this code will not work:

```
const supportedPaymentMethods = [
  {
    supportedMethods: 'basic-card',
  }
];
const paymentDetails = {
  total: {
    label: 'Total',
    amount:{
      currency: 'USD',
      value: 0
    }
  }
};
const options = {};
const request = new PaymentRequest(
  supportedPaymentMethods,
  paymentDetails,
  options
);
request.show();
```

See https://stackoverflow.com/a/49602079/470749

**Apparently Chrome (and probably other browsers) disable certain browser functionality (such as the PaymentRequest API) when the connection isn't fully secure.**

I had assumed that browsers would honor Homestead's certificates as totally legit and "green" and support real https / SSL.

But it sounds like in your experience, you just click through the warnings and add an exception and browse your local site where the address bar says in red "Not secure" (and "https" is crossed out)?

Homestead doesn't aim to show the certificate as green and valid?

Just curious. I'm new to all of this. Thanks.

**Comment by svpernova09** [comment]
Homestead's goal is to be a robust development environment, but within the limitations we're able to easily maintain and support as much as we can. The only way to get around this AFAIK would be to buy an actual certificate from a CA, or possibly use Let's Encrypt.

**Comment by ryancwalsh** [comment]
@svpernova09 Ohhhh... I misunderstood. I could have sworn that I read somewhere that Homestead used Let's Encrypt and completely handled the certificates so that they'd be "green" and valid for local development. Because of my incorrect memory / assumption, I was stubbornly repeatedly uninstalling and reinstalling Homestead trying to get it all to work. 

Ok. I'll look into Let's Encrypt and see if I can get full green https. 

I'll look at:

- https://www.jeffmould.com/2016/05/14/install-lets-encrypt-ssl-certificate-laravel/
- https://letsencrypt.org/docs/certificates-for-localhost/
- https://github.com/laravel/homestead/issues/558#issuecomment-297761443

Thanks.

**Comment by lidoma** [comment]
I fix the missing certificate issue by importing the Homestead Root CA to the Trusted Root Certification Authorities list by followed steps:
- SSH into the Homestead machine and extract a copy of `/etc/nginx/ssl/ca.homestead.homestead.crt` to the local machine
- Import the `ca.homestead.homestead.crt` to the browser.
In Chrome follow: `Setting -> (Advanced) Manage Certificates -> Import`
- Restart the Chrome

**Comment by ryancwalsh** [comment]
@lidoma Thanks. I've already tried that. In your Chrome, is the "https:" in green? Mine has the errors in red shown above (even after I've added the URL as a security exception).

**Comment by lidoma** [comment]
Yes, I have a green `https:`. After I import the certificate file, I expected to have a green lock icon at the next refresh. But i have not. The lock icon gets green as the Chrome was restarted. Beware of the browser and DNS cache.

**Comment by arturcesarmelo** [comment]
i've imported the ca.homestead.homestead.crt into the chrome but i'm still seeing this message

![image](https://user-images.githubusercontent.com/18191910/40282107-67673642-5c40-11e8-8021-3950471739bd.png)


## OS
Ubuntu 16.04 LTS 64bits

## Homestead.yaml
```YAML
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: app.probetsy.test
      to: /home/vagrant/code/probetsy/public
      schedule: true
    - map: api.probetsy.test
      to: /home/vagrant/code/probetsyapi/public
      schedule: true
    - map: app.arturcesarmelo.com
      to: /home/vagrant/code/arturcesarmelo.github.io
    - map: app.blog.com
      to: /home/vagrant/code/blog/public

databases:
    - berlim
    - homestead
    - probetsy
    - probetsyapi

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```
