### ISSUE TITLE
Laravel Homestead does not create a nginx configuration file

### ISSUE THREAD

**Issue by MuhammedKpln** [laravel/homestead#836]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.0.3
  - Provider: Virtualbox 5.2.8
  - Homestead: Windows has not recognized this command, so i guess there is no support.

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Windows

## Homestead.yaml
```
---
ip: "192.168.10.10"
memory: 1024
cpus: 1
provider: virtualbox
mariadb: true
authorize: C:\Users\Muhammed Kaplan\.ssh\id_rsa.pub

keys:
    - C:\Users\Muhammed Kaplan\.ssh\id_rsa

folders:
    - map: C:\Users\Muhammed Kaplan\Documents\src\Laravel
      to: /home/vagrant/projects

sites:
    - map: homestead.app
      to: /home/vagrant/projects/homestead/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
Vagrant destroy: 
```
    homestead-7: Are you sure you want to destroy the 'homestead-7' VM? [y/N] y
==> homestead-7: Forcing shutdown of VM...
==> homestead-7: Destroying VM and associated drives...
```

Vagrant up:
[GitHub Gist](https://gist.github.com/MuhammedKpln/1293a14dcdcfae718ca1e979e72f8516)

## Expected behavior
When VM is created it should also bring the nginx configuration file as well.

## Actual behavior
It didn't create a nginx configuration file there for i created it myself.

## Steps to reproduce
1.Create a vm with vagrant up

**Comment by browner12** [comment]
the `Homestead` command does not exist by default, it is simply an alias to to `vagrant`.  For example, in Mac we map `Homestead` to:

```
cd ~/Homestead && vagrant $1
```

I can see in your Gist that there was an error when running `vagrant up`, so provisioning did not finish successfully on the machine.

Github issues are reserved for bug reports and enhancements. Please close this issue, and move it to a forum like StackOverflow.

Thanks!

**Comment by svpernova09** [comment]
From your `vagrant up` gist:

```
homestead-7: /tmp/vagrant-shell: line 1: /home/vagrant/.ssh/$2: ambiguous redirect
```

This means there is a problem locating your SSH keys, and from your `Homstead.yaml` you have spaces in the path, which does not get translated properly.

Try this:

```
---
ip: "192.168.10.10"
memory: 1024
cpus: 1
provider: virtualbox
mariadb: true
authorize: "C:\Users\Muhammed Kaplan\.ssh\id_rsa.pub"

keys:
    - "C:\Users\Muhammed Kaplan\.ssh\id_rsa"

folders:
    - map: C:\Users\Muhammed Kaplan\Documents\src\Laravel
      to: /home/vagrant/projects

sites:
    - map: homestead.app
      to: /home/vagrant/projects/homestead/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```
