### ISSUE TITLE
Error while processing php7.0-fpm on `vagrant up`

### ISSUE THREAD

**Issue by pascal08** [laravel/homestead#837]
## Versions
  - Vagrant: 2.0.3
  - Provider: Virtualbox 5.2.8
  - Homestead: 7.3.0

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: c:/dev/projects/website
      to: /home/vagrant/website

sites:
    - map: website.localhost
      to: /home/vagrant/website/public

databases:
    - homestead
```

## Vagrant destroy & up output
[Output](https://gist.github.com/pascal08/22c6e1b26502d79139663f17711d580f)

## Expected behavior
Homestead should start without error code (1)

## Actual behavior
Error code (1) returned while processing `php7.0-fpm`

## Steps to reproduce
_On Windows 10_
1. Install VirtualBox 5.2.8
2. Install Vagrant 2.0.3
3. Install Homestead 7.3.0
4. Run `vagrant up` from the Homestead directory

## Workaround
1. Remove `apt-get update -y` from `after.sh`
2. Run `vagrant up` from Homestead directory
3. Run `apt-get update -y` manually inside Homestead VM
4. Choose `keep your currently-installed version` whenever it asks what you want to do with the configuration file

## References
- https://github.com/laravel/homestead/issues/577
