### ISSUE TITLE
Unable to create new Laravel webiste on fresh installation of Homestead

### ISSUE THREAD

**Issue by darki73** [laravel/homestead#842]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.0.3
  - Provider: virtualbox
  - Homestead: 7.3.0

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Windows 10 Pro x64

## Homestead.yaml
```yaml
---
ip: "192.168.20.10"
memory: 2048
cpus: 4
provider: virtualbox

authorize: C:/Users/apple/.ssh/id_rsa.pub

keys:
    - C:/Users/apple/.ssh/id_rsa

folders:
    - map: E:/Homestead
      to: /home/vagrant

sites:
    - map: uapi.test
      to: /home/vagrant/UniverAPI/public

databases:
    - uapi
```

## Vagrant destroy & up output
https://gist.github.com/darki73/215e8f2992e6ba86bd3c98ff1a5e29e5

## Expected behavior
Laravel installation should work out of the box

## Actual behavior
Cant install the npm modules to compile the JS and SCSS.
It is either:
1. cannot create symlink
2. cannot rename file, it is busy

## Steps to reproduce
1. Install Vagrant + Homestead + Virtualbox
2. Change the folders in the Homestead.yaml
3. Vagrant up
4. composer create-project --prefer-dist laravel/laravel Website
5. npm install

## References
No
