### ISSUE TITLE
Homestead won't come up. New install. Lots of port collisions.

### ISSUE THREAD

**Issue by flycast** [laravel/homestead#844]
## Versions
  - Vagrant 2.0.3
  - Provider: Virtualbox 5.2.8
  - Homestead: Run `homestead --version` to show the version.
Can't provide this. When I run 'homestead --version I get:
> homestead --version

> PHP Fatal error:  Cannot redeclare static Symfony\Component\Console\Command\Command::$defaultName as non static Laravel\Homestead\MakeCommand::$defaultName in C:\Users\Eric\AppData\Roaming\Composer\vendor\laravel\homestead\src\MakeCommand.php on line 155
> PHP Stack trace:
> PHP   1. {main}() C:\Users\Eric\AppData\Roaming\Composer\vendor\laravel\homestead\homestead:0
> PHP   2. spl_autoload_call() C:\Users\Eric\AppData\Roaming\Composer\vendor\laravel\homestead\homestead:28
> PHP   3. Composer\Autoload\ClassLoader->loadClass() C:\Users\Eric\AppData\Roaming\Composer\vendor\laravel\homestead\homestead:28
> PHP   4. Composer\Autoload\includeFile() C:\Users\Eric\AppData\Roaming\Composer\vendor\composer\ClassLoader.php:322
> 
> Fatal error: Cannot redeclare static Symfony\Component\Console\Command\Command::$defaultName as non static Laravel\Homestead\MakeCommand::$defaultName in C:\Users\Eric\AppData\Roaming\Composer\vendor\laravel\homestead\src\MakeCommand.php on line 155
> 
> Call Stack:
>     0.0035     364688   1. {main}() C:\Users\Eric\AppData\Roaming\Composer\vendor\laravel\homestead\homestead:0
>     0.4014    1097168   2. spl_autoload_call() C:\Users\Eric\AppData\Roaming\Composer\vendor\laravel\homestead\homestead:28
>     0.4014    1097216   3. Composer\Autoload\ClassLoader->loadClass() C:\Users\Eric\AppData\Roaming\Composer\vendor\laravel\homestead\homestead:28
>     0.4022    1097328   4. Composer\Autoload\includeFile() C:\Users\Eric\AppData\Roaming\Composer\vendor\composer\ClassLoader.php:322

## Host operating system
Windows 10 Pro 64bit

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
https://gist.github.com/flycast/7d4af18e8c7c7e434d589e88fc6b2a49.js

## Expected behavior
I am expecting vagrant homestead to come up. 

## Actual behavior
After I run 'vagrant up' I get the port collision stuff. Checking for port collisions there are none. If I run 'vagrant status' I get:

> > vagrant status
> Current machine states:
> 
> homestead-7               poweroff (virtualbox)
> 
> The VM is powered off. To restart the VM, simply run `vagrant up`

## Steps to reproduce
Following the step by step guide on the homestead site. I did download, install and bring up a machine from the vagrant tutorial on the vagrant site.

- ...
