### ISSUE TITLE
vagrant ssh doesn't work

### ISSUE THREAD

**Issue by AlgirdasM** [laravel/homestead#849]
## Versions
  - Vagrant: Vagrant 2.0.4
  - Vagrant VMware Utility 1.0.1 
  - vagrant-vmware-desktop (1.0.3)
  - Provider: VMWare Fusion Professional Version 8.5.10 (7527438)
  - Homestead: -bash: homestead: command not found, but it is v7.4.0

## Host operating system
macOS High Sierra 10.13.4

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: vmware_fusion

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
https://gist.github.com/AlgirdasM/533f7601dde16cabdb9ae1f630a0390a

## Expected behavior
It should connect to VM.

## Actual behavior
ssh: connect to host 192.168.10.10 port 22: Operation timed out
I can connect to VM with ssh -l vagrant 172.16.191.129, but it should be 192.168.10.10
ifconfig output from VM - https://gist.github.com/AlgirdasM/9998ab214ed181001134ec0002aef34e

## Steps to reproduce
1. macOS High Sierra 10.13.4
2. Install VMWare pro 8.5
3. Install Vagrant 2.0.4
4. Install Vagrant VMware Utility 1.0.1
5. Installed vagrant-vmware-desktop and add licence vagrant-vmware-desktop (1.0.3)
6. Create ~/code
7. git clone https://github.com/laravel/homestead.git ~/Homestead
8. cd ~/Homestead
9. git checkout v7.4.0
10. bash init.sh
11. Edit - Homestead.yaml and change provider: vmware_fusion
12. vagrant up
