### ISSUE TITLE
Missing files/folder

### ISSUE THREAD

**Issue by kunicmarko20** [laravel/homestead#852]
## Versions
  - Vagrant 2.0.4
  - Provider: Virtualbox
  - Homestead: 7.4.1

## Host operating system
Fedora 27

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /Storage/www/laravel/api
        to: /home/vagrant
sites:
    -
        map: laravel-api.test
        to: /home/vagrant/public
databases:
    - homestead
name: api
hostname: api
```

## Vagrant destroy & up output
https://gist.github.com/kunicmarko20/29a414fd78bcdb89a38d7801c8a5406b

## Expected behavior
For it to work

## Actual behavior
Errors out

## Steps to reproduce
1. require homestead
2. vagrant up
3. error

Note:

Commenting out:

```
#authorize: ~/.ssh/id_rsa.pub
#keys:
#    - ~/.ssh/id_rsa
```

In homestead.yaml passes I only get 1 more error:

```
 api: sed: can't read /home/vagrant/.profile: No such file or directory
```

But it doesn't stop `vagrant up` and I can open it in browser.

**Comment by svpernova09** [comment]
You can't map a Host OS folder to `/home/vagrant` since that's the home of the vagrant system user in the VM.

Update your config to:
```
folders:
    -
        map: /Storage/www/laravel/api
        to: /home/vagrant/api
sites:
    -
        map: laravel-api.test
        to: /home/vagrant/api/public
```
