### ISSUE TITLE
Extremly slow homestead startup

### ISSUE THREAD

**Issue by AlMod90** [laravel/homestead#855]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant 2.1.1
  - Virtualbox 5.2.10.
  - Homestead 7.4.1, and also 7.4.2

## Host operating system
Windows 7 SP 1 X64

## Homestead.yaml (using default)
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp 
```

## Vagrant destroy & up output
https://gist.github.com/AlMod90/d0b1e517de7a333ff369c5d42ecba8de#file-destroy-up

## Expected behavior
`vagrant up` should execute within 30-40 seconds

## Actual behavior
`vagrant up` stuck for long on
    homestead-7: Warning: Connection reset. Retrying...
    homestead-7: Warning: Connection aborted. Retrying..
but VM still loads in the end, after 4-5 min

## Steps to reproduce
Yesterday I successfully installed Vagrant, VirtualBox and homestead. Everything was working just fine and boot time was around 30s
Today I started VM with `vagrant up` and boot took like forever (~ 4-5 min)
I'd uninstalled everything, made clean install, default homestead configs but no luck - it's still took 5 min to boot

## Ubuntu debug information included
This commands was executed on system manually, after logging in
[dmesg](https://gist.github.com/AlMod90/d0b1e517de7a333ff369c5d42ecba8de#file-dmesg)
[systemd-analyze](https://gist.github.com/AlMod90/d0b1e517de7a333ff369c5d42ecba8de#file-systemd-analyze)
[systemd-analyze](https://gist.github.com/AlMod90/d0b1e517de7a333ff369c5d42ecba8de#file-systemd-analyze-blame)

**Comment by svpernova09** [comment]
https://gist.github.com/AlMod90/d0b1e517de7a333ff369c5d42ecba8de#file-destroy-up-L63-L84

Looks like it doesn't like your SSH keys.

On WIndows you want to use full drive letter + path in your `Homestead.yaml` so `~/code` becomes:

```
folders:
    - map: "C:\Users\User\code"
      to: /home/vagrant/code
```

Also you'll want to map individual projects, not large code storage directories.

Example:

```
folders:
    - map: "C:\Users\User\code\project1"
      to: /home/vagrant/project1
    - map: "C:\Users\User\code\project2"
      to: /home/vagrant/project2

sites:
    - map: project1.test
      to: /home/vagrant/project1/public
    - map: project2.test
      to: /home/vagrant/project2/public
```
