### ISSUE TITLE
Vagrant up command failed

### ISSUE THREAD

**Issue by jamesbeamingwhite** [laravel/homestead#859]
## Versions
  - Vagrant: 2.1.1
  - Provider: Virtualbox (v5.2.12)
  - Homestead: 7.3.0

## Host operating system
macOS 10.13.4

## Homestead.yaml
```yaml
ip: 192.168.10.11
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /Users/admin/Sites/snap-api
        to: /home/vagrant/code
        type: "nfs"
sites:
    -
        map: api.snapdent.local
        to: /home/vagrant/code/public
databases:
    - homestead
name: snap-api
hostname: snap-api
```

## Vagrant destroy & up output
https://gist.github.com/jamesbeamingwhite/f088805374ec5d6bd1476bffdfd6735f

## Expected behavior
Should not have gotten a non-zero exit status.

## Actual behavior
ran composer install, ran homestead make, edited yaml file to my specifications, ran vagrant up then non-zero exit status occurred.

## References
- #850
