### ISSUE TITLE
Homestead versions with box 6.0.0 fail to be provisioned with "Remote connection disconnect. Retrying..." repeated until hard-failure on Vagrant > 2.0.3

### ISSUE THREAD

**Issue by cbj4074** [laravel/homestead#862]
## Versions
  - Vagrant: 2.0.4
  - Provider: Virtualbox 5.2.12
  - Homestead: 7.4.2

## Host operating system
Windows 7 x64

## Homestead.yaml
```yaml
---
version: 6.0.0
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/homestead.pub

keys:
    - ~/.ssh/homestead

folders:
    - map: C:\Users\me\www
      to: /home/vagrant/Code/www

sites:
    - map: web.site
      to: /home/vagrant/Code/www/public

databases:
    - www

mariadb: true
```

## Vagrant destroy & up output
https://gist.github.com/cbj4074/fcc5cee405b0d176b88aac633cf4069b

## Expected behavior
Homestead should be provisioned successfully.

## Actual behavior
Homestead fails to be provisioned after Vagrant inserts new, secure SSH key, with "Remote connection disconnect. Retrying..." repeated until hard-failure. To be clear, I'm not sure that the key replacement is *causing* the failure; it may simply be the last action that occurs successfully.

I've found two workarounds to this problem:

1. Downgrading the Homestead box version, to `5.2.0`; of course, the fundamental difference between Homestead box versions 5.2.0 and 6.0.0 is that that the former runs Ubuntu 16.04 LTS, while the latter runs 18.04 LTS
2. Downgrading Vagrant to 2.0.3

## Steps to reproduce
1. Attempt to provision a new VM with Vagrant `2.0.4`, Homestead box version `6.0.0`, and Homestead version `7.4.2`
2. Observe failure as described above

## References
It seems that this may be related, because as at least one commenter suggests, downgrading to Vagrant 2.0.3 resolves the issue:

https://github.com/hashicorp/vagrant/issues/9428
