### ISSUE TITLE
ifup and ifdown have been deprecated in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/homestead#867]
## Versions
  - Vagrant: Vagrant 2.0.1
  - Provider: Virtualbox 5.2.8 r1210009
  - Homestead: Laravel Homestead 7.6.0

## Host operating system
Windows 10 64-bit

## Homestead.yaml
```yaml
ip: 192.168.10.11
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: 'C:\Users\lasleh\Development\project'
        to: /home/vagrant/code
sites:
    -
        map: project.development
        to: /home/vagrant/code/public
databases:
    - homestead
name: project
hostname: project

```

## Vagrant destroy & up output
https://gist.github.com/lasselehtinen/c5b03745c98759e5bf582842cea526f4

## Expected behavior
Vagrant should load the virtual machine.

## Actual behavior
I am getting an error about missing ifup/ifdown commands. I can fix the issue by running vagrant ssh , apt-get install ifupdown and then vagrant reload. If you check the release notes for Ubuntu 18.04 LTS, you can see that the ifup and ifdown have been deprecated. Seems like settler was just upgraded to include this in the box version 6.0.

I guess temporary solution would to install ifupdown in settler or in the long run adjust the provisioning so that it uses netplan.io instead.

https://github.com/laravel/settler/releases/tag/v6.0.0

```
λ vagrant box update
==> digijakelija: Checking for updates to 'laravel/homestead'
    digijakelija: Latest installed version: 6.0.0
    digijakelija: Version constraints: >= 5.2.0
    digijakelija: Provider: virtualbox
==> digijakelija: Box 'laravel/homestead' (v6.0.0) is running the latest version.
```

## References
https://github.com/hashicorp/vagrant/issues/9213
https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes#New_since_16.04_LTS
