### ISSUE TITLE
Symfony Flex is not working inside Homestead VM

### ISSUE THREAD

**Issue by Kocal** [laravel/homestead#871]
## Versions
  - Vagrant: 2.1.1
  - Provider: Virtualbox 5.2.12
  - Homestead: 7.6.2

## Host operating system
Debian 9.4 (stretch), with Linux 4.9.0-6-amd64.

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 2
provider: virtualbox
mariadb: true
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /home/kocal/Dev/Mangatheque
        to: /home/vagrant/code
sites:
    -
        map: mangatheque.vm
        to: /home/vagrant/code/public
        type: symfony4
databases:
    - homestead
name: mangatheque
hostname: mangatheque
```

## Vagrant destroy & up output
https://gist.github.com/Kocal/fffa6fd8622f6e28cd30d0c4d930a0ad

## Expected behavior
With the Composer Flex Symfony Flex, I can require dependencies by using Symfony recipes.

This is what happens when I require a Symfony recipe outside Homestead VM: 
![capture d ecran de 2018-06-01 07-50-32](https://user-images.githubusercontent.com/2103975/40823426-7db4e41a-6570-11e8-94c2-503cdec94ff5.png)

## Actual behavior
Symfony Flex do not seems to be "registered" as composer plugin, and so I can't use short notations to require [Symfony recipes](https://symfony.sh/).

![capture d ecran de 2018-06-01 07-49-09](https://user-images.githubusercontent.com/2103975/40823376-4dd3b866-6570-11e8-92af-7ced2fb70b8f.png)

## Steps to reproduce
1. Login to the VM through SSH
2. Run `composer req maker`
3. The package `maker` is not found.

When running `vagrant up`, there is this output at the very end. Is this related?

```log
==> mangatheque: Running provisioner: shell...
    mangatheque: Running: script: Update Composer
    mangatheque: You are running composer as "root", while "/home/vagrant/.composer" is owned by "vagrant"
    mangatheque: You are already using composer version 1.6.5 (stable channel).
```

Thanks!
