### ISSUE TITLE
Zray installed as default

### ISSUE THREAD

**Issue by mstnorris** [laravel/homestead#879]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.1.1
  - Provider: Virtualbox
  - Homestead: 7.7
  - Laravel 5.6.25

## Host operating system
  - macOS Sierra 10.12.6 (16G1212)

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /Users/michael/Code/Laravel/example.com
        to: /home/vagrant/example.com
        type: "nfs"
sites:
    -
        map: example.test
        to: /home/vagrant/example.com/public
        schedule: true
databases:
    - example.com
name: example.com
hostname: example.test
```

## Vagrant destroy & up output
[vagrant destroy && vagrant up](https://gist.github.com/mstnorris/0917940a2164083833629de738a09ae1)

## Expected behaviour
In homestead.rb the sites['zray'] setting defaults to false unless otherwise set to true however

## Actual behavior

![screenshot 2018-06-12 23 09 00](https://user-images.githubusercontent.com/1919816/41319976-a9563672-6e95-11e8-92c4-022fb76f89b1.png)

## Steps to reproduce
1. Create a new laravel project
2. Install Homestead (per project)
3. Run `vagrant up`
4. Visit site in browser

## References
https://github.com/laravel/homestead/issues/808
