### ISSUE TITLE
Vagrant up error

### ISSUE THREAD

**Issue by maxyc** [laravel/homestead#886]
When I run 'vagrant up' the system installation starts. Installed `mongodb`, and with it in the file `vendor/laravel/homestead/scripts/install-mongo.sh a` set `php`. Then 'vagrant' tries to continue installing applications. But why is it trying to install php again and this falls with the question of how to proceed. then not responding to any actions.

## Versions
  - Vagrant 2.1.1
  - Provider: Virtualbox
  - Homestead: 7.8

## Host operating system
Mint 16

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 1024
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
mariadb: true
backup: true
mongodb: true

keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: /var/www/nextrun.gitlab.io
        to: /home/vagrant/code
sites:
    -
        map: nextrun.loc
        to: /home/vagrant/code/public
        schedule: true
        php: '7.2'

databases:
    - homestead

name: nextrun-gitlab-io
hostname: nextrun-gitlab-io
```
