### ISSUE TITLE
Blocked at: What do you want to do about modified configuration file php.ini?

### ISSUE THREAD

**Issue by CamilleBB** [laravel/homestead#893]
Hi there !

## Versions
  - Vagrant: 2.1.1
  - Provider: Virtualbox 5.2.14
  - Homestead: v7.9.0

## Host operating system
Mac OS High Sierra 10.13.5

## Homestead.yaml
```yaml
---
ip: "192.168.10.15"
memory: 4096
cpus: 4
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/www/my-project/website
      to: /home/vagrant/website

sites:
    - map: my-project.com
      to: /home/vagrant/website/public
      php: "7.2"

databases:
    - homestead
    - my-project

mongodb: true
```

## Actual behavior
When I do "vagrant up", the provisioning starts, but during the package **php7.1-cli** installation an interactive question appears.
It asks "What do you want to do about modified configuration file php.ini?"

## Steps to reproduce
1. follow instructions here : https://laravel.com/docs/5.6/homestead#installation-and-setup to set up the Yaml file
2. vagrant up
3. wait until the error...

## References
I saw on https://github.com/laravel/homestead/issues/577 it could come from code in after.sh file but mine is empty.

## Error during the "Vagrant up" :
```
    homestead-7: Setting up php7.1-cli (7.1.19-1+ubuntu18.04.1+deb.sury.org+1) ...
    homestead-7: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    homestead-7: Package configuration┌────────────────────┤ Modified configuration file ├────────────────────┐│ php.ini: A new version (/usr/lib/php/7.1/php.ini-production.cli) of   ││ configuration file /etc/php/7.1/cli/php.ini is available, but the││ version installed currently has been locally modified.││││ What do you want to do about modified configuration file php.ini?││││install the package maintainer's version││keep the local version currently installed          ││show the differences between the versions││show a side-by-side difference between the versions││start a new shell to examine the situation││││││<Ok>│││└───────────────────────────────────────────────────────────────────────┘
```

Thanks for your help !
