### ISSUE TITLE
Slower migrations and phpunit after moving to v7.9.0 and v7.10.0

### ISSUE THREAD

**Issue by scoutman57** [laravel/homestead#896]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Virtualbox: 5.2.14 r123301
  - Vagrant: 2.1.2
  - Provider: Virtualbox
  - Homestead: 7.6.2 | 7.9.0 | 7.10.0

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
This is the operating system that you run locally.

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
mariadb: true
ssl: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.test
      to: /home/vagrant/Code/Laravel/public

databases:
    - testdb
    
# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
I would expect that after upgrading to unbuntu 18.04 (homestead 7.10.0) that the migration and phpunit run times would not be significantly slower in the newer version. If anything one would expect the run times to be faster in the newer versions.

## Actual behavior
The migration and phpunit run times dramatically increased after upgrading to the newer version of homestead. 

## Steps to reproduce
1. create a decent about of migrations (I have about 25)
2. run migrations in homestead v7.6.2 "time php artisan migrate" (note times) repeat for PHPUnit
3. upgrade homestead to v7.10.0
4. run migrations in homestead v7.10.0 "time php artisan migrate" (note times) repeat for PHPUnit

My migration times were 2.647s on homestead v7.6.2 they went up to 17.747s (these times are greatly different with the exact same migrations, the only difference was the homestead version). The times for phpunit test to execute also dramatically increased which I believe is because of the increased times of the migrations. Most of my unit test took 4 seconds to run on 7.6.2 and now take 20-30s on 7.10.0. This issue appears to have introduced after moving to Ubuntu 18.04

I could reproduce this one two different system (MacBook Pro & Hackintosh) Both running High Serria. 

I did not test this in Homestead v7.7.0 or v7.8.0 but noticed this a couple of weeks ago in 7.9.0 but just now was able to get around to testing. Before 7.9.0 I was on 7.6.2.

**Comment by svpernova09** [comment]
Update your `Homestead.yaml` to with these changes and test again to see if you still see the same results:

```
folders:
    - map: ~/Code
      to: /home/vagrant/Code/Laravel

sites:
    - map: homestead.test
      to: /home/vagrant/Laravel/public
```
