### ISSUE TITLE
error launching homestead for first time

### ISSUE THREAD

**Issue by vettloffah** [laravel/homestead#899]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.1.2
  - Provider: virtualbox 5.2.14
  - Homestead: any 'homestead' command gives error: `PHP Fatal error:  Cannot redeclare static Symfony\Component\Console\Command\Command::$defaultName as non static Laravel\Homestead\MakeCommand::$defaultName in C:\Users\Charles Wettlaufer\AppData\Roaming\Composer\vendor\laravel\homestead\src\MakeCommand.php on line 155`

## Host operating system
Windows 10

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
        - map: d:/homestead/
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/public

databases:
    - homestead
```

## Vagrant destroy & up output
https://gist.github.com/vettloffah/509bb87f898acda832ee9889d749178f

## Expected behavior
I have installed virtualbox, vagrant, and homestead and am trying to launch homestead  for the first time, and receiving the above errors. 

## Actual behavior
Errors above in console
