### ISSUE TITLE
Founded a bug in accessing robots.txt and favicon.ico with multi-domains

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/homestead#903]
## Versions
  - Vagrant: 2.1.2
  - Provider: Virtualbox
  - Homestead: 7.12.0

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/pub

keys:
    - ~/.ssh/private.ppk

sites:
    - map: mercedes.loc
      to: /home/vagrant/code/mercedes.loc/public
      subdomain:
        - promo.mercedes.loc
        - sales.mercedes.loc
        - static.mercedes.loc
      schedule: true

databases:
    - mercedes
```

## Expected behavior
For each subdomain, I need to return my robots.txt and favicon.ico files. With the current settings Homestead can not do this, because the path to the files is regulated by the settings of virtual hosts in nginx.

## Actual behavior
The following lines are specified in the virtual hosts settings:
```
location = /favicon.ico { access_log off; log_not_found off; }
location = /robots.txt  { access_log off; log_not_found off; }
```

Because of this, nginx sends the user directly to the file instead of allowing it to be done at the application level.

#### My routes:

```php
// routes/web.php
app('router')
    ->domain(config('app.domains.promo'))
    ->name('promo.')
    ->group(base_path('routes/web/_promo.php'));

app('router')
    ->domain(config('app.domains.sales'))
    ->name('sales.')
    ->group(base_path('routes/web/_sales.php'));

app('router')
    ->domain(config('app.domains.static'))
    ->name('static.')
    ->group(base_path('routes/web/_static.php'));
```

```php
// routes/web/_promo.php
app('router')->get('robots.txt', 'Promo\IndexController@robots')->name('robots');

// routes/web/_sales.php
app('router')->get('robots.txt', 'Sales\IndexController@robots')->name('robots');

// routes/web/_static.php
app('router')->get('robots.txt', 'Statically\IndexController@robots')->name('robots');
```

When opening links `promo.mercedes.loc/robots.txt`, `sales.mercedes.loc/robots.txt` and `static.mercedes.loc/robots.txt` the browser should return different values, but this does not happen.
