### ISSUE TITLE
"no implicit conversion of Integer into String" error when configuring a proxy site type

### ISSUE THREAD

**Issue by stevegriffiths** [laravel/homestead#910]
## Versions
  - Vagrant: 2.1.1
  - Provider: Virtualbox 5.2.16
  - Homestead: 7.8.0

## Host operating system
Windows 10

## Homestead.yaml
---
```yaml
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:\Users\xx\Documents\Websites
      to: /home/vagrant/code

sites:
    - map: homestead.phpmyadmin
      to: /home/vagrant/code/phpmyadmin
    - map: homestead.app1
      to: /home/vagrant/code/app1/public
    - map: homestead.nodejs1
      to: 8080
      type: proxy

databases:
    - homestead

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

#ports:
#    - send: 8081
#      to: 8080
#      protocol: udp
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
Expect vagrant up to run without error, and for one of the sites in the resulting VM to act as a proxy to port 8080 (running a Node.js app) within the machine.

## Actual behavior
Vagrant up fails with the following error:

`homestead.rb:233:in '+': no implicit conversion of Integer into String (TypeError).`

I have narrowed this error down to being the result of this line in the Homestead.yaml file, despite various sources suggesting that this is the correct format for defining a proxy type site in homestead:

`to: 8080`

## Steps to reproduce
1. Create Homestead.yaml file as displayed above.
2. Run vagrant up
