### ISSUE TITLE
VMWare Workstation Pro 14 Fails at SSH auth method: private key

### ISSUE THREAD

**Issue by keithdoyle9** [laravel/homestead#911]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.1.2
  - Provider: VMWare Workstation Pro 14
  - Homestead: v7.12.0
  - Homestead Vagrant Box: 6.1.0

## Host operating system
Windows 7 - 64-bit

## Homestead.yaml
```yaml
---
ip: "192.168.10.11"
memory: 4096
cpus: 4
provider: vmware_desktop

authorize: C:/Users/kdoyle/.ssh/id_rsa.pub

keys:
    - C:/Users/kdoyle/.ssh/id_rsa

folders:
    - map: C:/Users/kdoyle/code
      to: /home/vagrant/code

sites:
    - map: abc.local
      to: /home/vagrant/code/abc-com
      php: "7.2"
      type: apache
    - map: sub.abc.local
      to: /home/vagrant/code/sub-abc-com
      php: "7.2"
      type: apache

databases:
    - homestead
    - dev_example_com

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

## Vagrant destroy & up output
https://gist.github.com/keithdoyle9/202304603bbfd42af276dc6196a13395

## Expected behavior
Machine should've booted up as normal. This worked previously on VMWare Workstation Pro 12.

## Actual behavior
Provisioning sequence timed out at SSH auth method: private key

## Steps to reproduce
1. Install VMWare Workstation Pro 14
2. Install VMWare Vagrant Utility
3. Install Vagrant version 2.1.2
4. Clone Homestead repo and checkout tag v7.12.0
5. Run `init.bat` in Homestead folder
6. Run `vagrant up` in homestead repo
