### ISSUE TITLE
VM name configuration change breaks existing systems

### ISSUE THREAD

**Issue by samlikins** [laravel/homestead#916]
Changes between Homestead 7.12 and 7.13 have broken systems which specify the Vagrant name.  The configuration setting has been "name" for as long as I can recall, but for some reason it has been changed to "names" as of v7.13.

## Versions
  - Vagrant: 2.1.2
  - Provider: 5.2.6
  - Homestead: 7.14.0

## Host operating system
  - macOS High Sierra 10.13.6

## Homestead.yaml
```yaml
ip: 192.168.10.10
cpus: 1
memory: 2048
provider: virtualbox
name: project-name
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    - map: ./
      to: /home/vagrant/code
sites:
    - map: project-name.local
      to: /home/vagrant/code/public
databases:
    - homestead
```

## Vagrant destroy & up output
[GitHub Gist](https://gist.github.com/samlikins/515fa57173b8d83d3b66df642c03750c)

## Expected behavior
A machine with the name "project-name" should have been created.

## Actual behavior
A machine with the name "homestead-7" was created.

## Steps to reproduce
1. Checkout homestead version 7.13 or 7.14
2. Configure the Homestead.yaml file to specify the vm name to something other than "homestead-7"
3. Bring up the Homestead system
4. Run `vagrant global-status`
5. Verify the name of the system created

## References
- N/A
