### ISSUE TITLE
Not able to navigate in the site pages when access the ngrok link

### ISSUE THREAD

**Issue by jn-jairo** [laravel/homestead#920]
## Versions
  - Vagrant: 2.1.2
  - Provider: Virtualbox 5.2.16-123759-Ubuntu-xenial
  - Homestead: 7.14.2

## Host operating system
Ubuntu 16.04.5 LTS

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 512
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/code
      to: /home/vagrant/code

sites:
    - map: blog.test
      to: /home/vagrant/code/blog/public

databases:
    - homestead

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.
```

## Vagrant destroy & up output
https://gist.github.com/jn-jairo/9f6b74105390c3a16ddc5f2da59e6db6

## Expected behavior
Create a Laravel project and share to access the site from ngrok link in another machine and be able to navigate in the site pages.

## Actual behavior
I can access the home page by the ngrok link, but all page links and assets are with the local `blog.test` domain instead of the `00000000.ngrok.io`, so I get a 404 error in the assets and when click in a link.

I tried with `nginx` and `apache`, but the error occurs in both.

I don't know if I am making something wrong, or if I forgot some configuration, but following the documentation I should be able to use the site normally in another machine using the `share` feature.

## Steps to reproduce
1. Create a new laravel project using `composer create-project --prefer-dist laravel/laravel blog`
2. Update the `routes/web.php` to
```php
<?php

Route::get('/', function () { 
    dd(url('/'));
    return view('welcome');
});
```
3. Access in the browser `http://blog.test` and you will see the dump `http://blog.test`
4. Share the site `share blog.test` and access the ngrok link `http://00000000.ngrok.io` and you will see the dump `http://blog.test` instead of `http://00000000.ngrok.io`

I am not sure if this is a homestead bug or if I need to configure something in the Laravel project to use the `share` feature properly.

I even tried [Trusted Proxies](https://laravel.com/docs/5.6/requests#configuring-trusted-proxies) with `protected $proxies = '*';` without success.
