### ISSUE TITLE
php7.3-fpm missing from new vagrant box?

### ISSUE THREAD

**Issue by bironeaj** [laravel/homestead#929]
## Versions
  - Vagrant: 2.1.2
  - Provider: Virtualbox 5.2.10
  - Homestead: v7.15.0

## Host operating system
Pop_OS 18.04 (Ubuntu Based)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/PhpstormProjects/HR
      to: /home/vagrant/code/HR
    - map: ~/PhpstormProjects/Nova
      to: /home/vagrant/code/Nova

sites:
    - map: hr.test
      to: /home/vagrant/code/HR/public
    - map: nova.test
      to: /home/vagrant/code/Nova/public

databases:
    - homestead

```

## Vagrant destroy & up output
I have not tried destroying the box and recreating it. I use non-traditional database drivers that require lots of extra setup on the box (DB2). I will start from scratch and see if the same issue occurs.

## Expected behavior
Running `vagrant reload --provision` should make the appropriate changes to the vagrant box and restart php7.3-fpm.

## Actual behavior
Running `vagrant reload --provision` makes the appropriate changes to the box. However, fails at restarting php7.3-fpm.
```
==> homestead-7: Running provisioner: shell...
    homestead-7: Running: script: Restarting Nginx
    homestead-7: Failed to restart php7.3-fpm.service: Unit php7.3-fpm.service not found.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
I connected to the box itself and it does not seem like PHP 7.3 is installed.

## Steps to reproduce
1. Update to the latest box
2. Update to v7.15.0 homestead
3. Do a reprovision on the box
