### ISSUE TITLE
Homestead.rb : Message: undefined method `has_plugin'

### ISSUE THREAD

**Issue by Cezarion** [laravel/homestead#934]
## Versions
  - Vagrant: 2.0.2
  - Provider: Virtualbox 5.2.18
  - Homestead: 7.15.1

## Host operating system
OSX 10.13 / Ubuntu

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: .
        to: /home/vagrant/code
sites:
    -
        map: www.site.tld
        to: /home/vagrant/code/web
        type: apache
    -
        map: en.site.tld
        to: /home/vagrant/code/web
        type: apache

databases:
    - site

backup: true

name: site
hostname: site.tld
```

## Vagrant destroy & up output
```
Path: /Users/cezarion/Webserver/www-docker/beehive/devops/homestead/scripts/homestead.rb
Line number: 465
Message: undefined method `has_plugin'
```

I think there is a typo here : 
```
if settings.has_key?('backup') && settings['backup'] && (Vagrant::VERSION >= '2.1.0' || Vagrant.has_plugin('vagrant-triggers'))
```

It works fine with 
```
if settings.has_key?('backup') && settings['backup'] && (Vagrant::VERSION >= '2.1.0' || Vagrant.has_plugin?('vagrant-triggers'))
```
