### ISSUE TITLE
Desired PHP version is not specified in SSL vhost in apache sites

### ISSUE THREAD

**Issue by side-by-side** [laravel/homestead#938]
Hi,

I think I found a bug and the roots of it.

## Versions
  - Vagrant: 2.1.4
  - Provider: Virtualbox
  - Homestead: 7.16.1

## Host operating system
Windows 10

## Homestead.yaml
```yaml
sites:
    - map: homestead.test
      to: /var/www/homestead.test/public
      type: "apache"

    - map: homestead5.test
      to: /var/www/homestead5.test/public
      type: "apache"
      php: "5.6"
```

## Expected behavior
http://homestead.test uses default PHP 7.2
https://homestead.test uses default PHP 7.2

http://homestead5.test uses PHP 5.6
https://homestead5.test uses PHP 5.6

## Actual behavior
Everything is fine with homestead.test.

http://homestead5.test uses PHP 5.6
https://homestead5.test uses default PHP 7.2

---

### The issue
When adding `apache` site with different PHP version, the `http` site uses specified PHP version, while the `https` one uses the default one.

The problem is in the [/scripts/serve-apache.sh](https://github.com/laravel/homestead/blob/v7.16.1/scripts/serve-apache.sh) file: Its `http` vhost portion specifies a PHP handler, while the `https` portion doesn't. I tried to copy/paste the following block from the `http` vhost to the `https` one and it solved the problem:

```bash
<IfModule mod_fastcgi.c>
    AddHandler php"$5"-fcgi .php
    Action php"$5"-fcgi /php"$5"-fcgi
    Alias /php"$5"-fcgi /usr/lib/cgi-bin/php"$5"
    FastCgiExternalServer /usr/lib/cgi-bin/php"$5" -socket /var/run/php/php"$5"-fpm.sock -pass-header Authorization
</IfModule>
<IfModule !mod_fastcgi.c>
    <IfModule mod_proxy_fcgi.c>
        <FilesMatch \".+\.ph(ar|p|tml)$\">
            SetHandler \"proxy:unix:/var/run/php/php"$5"-fpm.sock|fcgi://localhost/\"
        </FilesMatch>
    </IfModule>
</IfModule>
```
