### ISSUE TITLE
Failed to restart php7.3-fpm.service: Unit php7.3-fpm.service not found.

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/homestead#943]
## Versions
  - Vagrant: `2.1.5`
  - Provider: `virtualbox 5.2.18`
  - Homestead: `7.17.0`
  - OS: `windows 10 x64 pro`

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa.ppk

folders:
    - map: f:/OpenServer/domains
      to: /home/vagrant/code

sites:
    - map: example.loc
      to: /home/vagrant/code/example.loc/public

databases:
    - example
#   and other 14 databases.
#   I shortened the spelling to reduce the amount of configuration
```

## Actual behavior
I had `6.1.0` version of the box. After that, I wanted to switch to `6.3.0` version, but an error occurs when updating:
```bash
homestead-7: Failed to restart php7.3-fpm.service: Unit php7.3-fpm.service not found.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
Full log: https://pastebin.com/Ah6G1anj
