### ISSUE TITLE
add option to specific port per site

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/homestead#948]
## Versions
  - Vagrant: Vagrant 2.1.1
  - Provider: Virtualbox 5.2.18
  - Homestead: 6.1

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
MacOS Mojave

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 1
provider: virtualbox

authorize: ~/.ssh/michael.pub

keys:
    - ~/.ssh/michael

folders:
    - map: ~/laravel_projects
      to: /home/vagrant/laravel_projects
      
sites:
     - map: homestead52.local
       to: /home/vagrant/laravel_projects/laravel52/public

     - map: homestead53.local
       to: /home/vagrant/laravel_projects/laravel53/public

databases:
    - homestead

```

I am developing a backend API for mobile apps. The app developers can connect to my Homestead through the local network by my-machine-ip:8000. This works out of the box. 

I want to have different port per site such 
* site A / port 80 / forward to port 8000
* site B / port 81 / forward to port 8001

I don't think it is possible right now to do this kind of setup from Homestead.yaml. 

I can ssh into Homestead machine and edit nginx port. However, vagrant reload --provision will clear all changes.
