### ISSUE TITLE
macOS + VirtualBox : Unable to reach apps hosted on Homestead

### ISSUE THREAD

**Issue by wijourdil** [laravel/homestead#954]
## Versions
  - Vagrant: 2.1.5
  - Provider: Virtualbox 5.2.18
  - Homestead: 7.18.0 (previously on 7.3.0, same issue)

## Host operating system
macOS High Sierra v10.13.6

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /WEB-ID/www/
      to: /home/vagrant/code

sites:
#    - map: www.sapiendo-groupama.id
#      to: /home/vagrant/code/sapiendo-groupama
#      type: "apache"
#      php: "7.1"
    - map: www.sapiendo-test.id
      to: /home/vagrant/code/sapiendo-USE-THIS-ONE
      type: "apache"
      php: "7.1"
#    - map: workshop.test
#      to: /home/vagrant/code/_LARACON/workshop/public
#      type: "apache"
#      php: "7.1"
    - map: www.petitdej.id
      to: /home/vagrant/code/breakfast-id/public
      type: "apache"
      php: "7.2"
    - map: admin.hotel-star.id
      to: /home/vagrant/code/hotel-star/public
      type: "apache"
      php: "7.3"
    - map: global.hotel-star.id
      to: /home/vagrant/code/hotel-star-global/public
      type: "apache"
      php: "7.3"
#    - map: wil.fire.shopping-time.fr
#      to: /home/vagrant/code/stn/fire/
#      type: "apache"
#      php: "7.1"

#databases:
#    - sapiendo
#    - les_horaires_prod

ports:
     - send: 33060
       to: 3306
```

## Vagrant destroy & up output
[GitHub Gist](https://gist.github.com/wijourdil/4a9dc47d668e458ef23c64fcc52ff736)

## Expected behavior
I'm simply trying to host some applications on Homestead, and access it via Chrome or any other browser locally.

## Actual behavior
1. I start my VM with the command `vagrant up [--provision]` (with the provision parameter if I updated the .yaml file)
2. If I try to reach a hosted site, for instance www.petitdej.id, I have an error, generally a timeout error or "connection refused".
3. If I access my VM via ssh with `vagrant ssh`, and I try to access the website via `lynx www.petitdej.id` it works

Sometimes, if I reboot my computer it works again, until something happens (I switch between wifi and ethernet connection, I stop / restart the VM for any reason, ...)

I have the feeling that the issue is to "connect" my Mac with the VM, but I can't put the finger on what's going wrong

**Comment by svpernova09** [comment]
On MacOS, the best domain to use would be `.test`. You also don''t need to map ports for 3306 -> 33060 since Homestead will do that manually for you.

Try this `Homestead.yaml`:

```
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
- ~/.ssh/id_rsa

folders:
- map: /WEB-ID/www/
  to: /home/vagrant/code

sites:
#    - map: sapiendo-groupama.test
#      to: /home/vagrant/code/sapiendo-groupama
#      type: "apache"
#      php: "7.1"
- map: sapiendo-test.test
  to: /home/vagrant/code/sapiendo-USE-THIS-ONE
  type: "apache"
  php: "7.1"
#    - map: workshop.test
#      to: /home/vagrant/code/_LARACON/workshop/public
#      type: "apache"
#      php: "7.1"
- map: petitdej.test
  to: /home/vagrant/code/breakfast-id/public
  type: "apache"
  php: "7.2"
- map: admin.hotel-star.test
  to: /home/vagrant/code/hotel-star/public
  type: "apache"
  php: "7.3"
- map: global.hotel-star.test
  to: /home/vagrant/code/hotel-star-global/public
  type: "apache"
  php: "7.3"
#    - map: wil.fire.shopping-time.test
#      to: /home/vagrant/code/stn/fire/
#      type: "apache"
#      php: "7.1"

#databases:
#    - sapiendo
#    - les_horaires_prod

#ports:
#- send: 33060
#  to: 3306
```

And add these lines to `/etc/hosts`

```
192.168.10.10 sapiendo-groupama.test
192.168.10.10 sapiendo-test.test
192.168.10.10 workshop.test
192.168.10.10 petitdej.test
192.168.10.10 admin.hotel-star.test
192.168.10.10 global.hotel-star.test
192.168.10.10 wil.fire.shopping-time.test
```

Then run `vagrant destroy && vagrant up`. You should be able to visit the domains now.
