### ISSUE TITLE
The repository 'https://artifacts.elastic.co/packages/2.x/apt stable Release' does not have a Release file.

### ISSUE THREAD

**Issue by jmcerrejon** [laravel/homestead#960]
## Versions
  - Vagrant: 2.1.5
  - Provider: Virtualbox, 5.2.18
  - Homestead: 7.18

## Host operating system
macOS Mojave 10.14

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
elasticsearch: "2.4.6"

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Documents/sc/www/
      to: /home/vagrant/code/

sites:
    - map: api.movilio.test
      to: /home/vagrant/code/myc-api/public
      php: "5.6"
    - map: movilio.test
      to: /home/vagrant/code/movilio/public
      php: "7.2"

databases:
    - cmobile
    - movilio

ports:
    - send: 62000
      to: 9200
#       protocol: udp
```

## Vagrant destroy & up output

The rest of the output is irrelevant

```
...
    homestead-7: Processing triggers for fontconfig (2.12.6-0ubuntu2) ...
    homestead-7: Warning: apt-key output should not be parsed (stdout is not a terminal)
    homestead-7: OK
    homestead-7: deb https://artifacts.elastic.co/packages/2.x/apt stable main
    homestead-7: Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
    homestead-7: Hit:2 http://ppa.launchpad.net/nginx/development/ubuntu bionic InRelease
    homestead-7: Hit:3 https://deb.nodesource.com/node_8.x bionic InRelease
    homestead-7: Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
    homestead-7: Get:6 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
    homestead-7: Ign:7 https://artifacts.elastic.co/packages/2.x/apt stable InRelease
    homestead-7: Hit:8 https://dist.crystal-lang.org/apt crystal InRelease
    homestead-7: Hit:9 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
    homestead-7: Hit:5 https://cli-assets.heroku.com/apt ./ InRelease
    homestead-7: Err:10 https://artifacts.elastic.co/packages/2.x/apt stable Release
    homestead-7:   404  Not Found [IP: 107.21.127.184 443]
    homestead-7: Hit:11 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease
    homestead-7: Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
    homestead-7: Hit:13 http://packages.blackfire.io/debian any InRelease
    homestead-7: Reading package lists...
    homestead-7: E: The repository 'https://artifacts.elastic.co/packages/2.x/apt stable Release' does not have a Release file.
    homestead-7: Reading package lists...
    homestead-7: Building dependency tree...
    homestead-7: Reading state information...
    homestead-7: E
    homestead-7: : 
    homestead-7: Unable to locate package elasticsearch
    homestead-7: update-rc.d: error: unable to read /etc/init.d/elasticsearch
    homestead-7: sed: can't read /etc/elasticsearch/elasticsearch.yml: No such file or directory
    homestead-7: Failed to enable unit: Unit file elasticsearch.service does not exist.
    homestead-7: Failed to start elasticsearch.service: Unit elasticsearch.service not found.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Steps to reproduce
Just add elasticsearch version <3 (3+ not tested) to Homestead.yaml file
