### ISSUE TITLE
Server unavailable MariaDB 10.3

### ISSUE THREAD

**Issue by iAxel** [laravel/homestead#966]
Server unavailable MariaDB 10.3 on `vagrant up`

## Versions
  - Vagrant: latest
  - Provider: Virtualbox
  - Homestead: latest

## Host operating system
Windows 10 Enterprise x64

## Homestead.yaml
```yaml
---
box: laravel/homestead
ip: "192.168.10.10"
memory: 1024
cpus: 1
provider: virtualbox
mariadb: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: D:\Vagrant\Code
      to: /home/vagrant/code

sites:
    - map: project.test
      to: /home/vagrant/code/project.test/public

databases:
    - homestead

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.
```

## Vagrant destroy & up output
[https://gist.github.com/iAxel/eca8660362603ce9e0061268efdc99cc](url)

## Steps to reproduce
1. Install vagrant & install VirtualBox
2. Run cmd `vagrant box add laravel/homestead`
3. Copy rep laravel/homestead to disk
4. Edit homestead.yaml (add mariadb)
5. Run cmd in folder homestead `vagrant up`
