### ISSUE TITLE
Homestead.rb file not found on per project installation of homestead.

### ISSUE THREAD

**Issue by Fh-abeyer** [laravel/homestead#969]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.1.1
  - Provider: Virtualbox 5.2.20
  - Homestead: 7.18.0

## Host operating system
Windows 10

## Homestead.yaml
```yaml
ip: 192.168.10.10
memory: 2048
cpus: 1
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: 'C:\Users\username\Projects\x'
        to: /home/vagrant/x
sites:
    -
        map: x.test
        to: /home/vagrant/x/public
databases:
    - x
name: x
hostname: x
```
## Expected behavior
When homestead per project installation is installed any user cloning the repo shouldn't need to download PHP and composer before vagrant up to get the project up since homestead is supposed to include this in the vagrant box.

## Actual behavior
I included the homestead per project installation and it works on my computer but when another teammate clones the repo and tries to vagrant up they are confronted with an error that the homestead.rb file doesnt exist. They are then forced to download PHP and composer in order to composer install to get the /laravel/homestead directory.

## Steps to reproduce
1. Create a project with per project homestead installed and functional
2. Save to a repo
3. Have someone without PHP and composer installed locally try to vagrant up
4. Output will produce homestead.rb file not found.
