### ISSUE TITLE
SHA384 is not supported by your openssl extension.

### ISSUE THREAD

**Issue by cwilby** [laravel/homestead#971]
## Versions
  - Vagrant: `2.1.5`
  - Provider: Parallels 14
  - Homestead: `7.18.0`

## Host operating system
Mac OS Mojave

## Homestead.yaml
```yaml
---
name: site-vm
ip: "192.168.10.11"
memory: 8192
cpus: 4
provider: parallels
mongodb: true

authorize: ~/.ssh/id_rsa.pub

keys:
  - ~/.ssh/id_rsa

folders:
  - map: /Users/cwilby/Code/project
    to: /home/vagrant/code

sites:
  - map: site.test
    to: /home/vagrant/code/site-a/public
    
databases:
  - site
```

## Error output

```
==> site-vm: Running provisioner: shell...
    site-vm: Running: script: Update Composer
    site-vm: You are running composer as "root", while "/home/vagrant/.composer" is owned by "vagrant"
    site-vm: Updating to version 1.7.3 (stable channel).
    site-vm:
    site-vm:
    site-vm:   [RuntimeException]
    site-vm:   SHA384 is not supported by your openssl extension, could not verify the phar file integrity
    site-vm:
    site-vm: self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--set-channel-only] [--] [<version>]
```

## References

https://github.com/composer/composer/issues/7669
https://github.com/composer/composer/pull/7649
