### ISSUE TITLE
Resolve host fails due to wrong nameserver

### ISSUE THREAD

**Issue by sulfo** [laravel/homestead#972]
## Versions
* Vagrant: Vagrant 2.2.0
* Provider: Virtualbox Version 5.2.20 r125813 (Qt5.6.3)
* Homestead: v7.19.0

## Host operating system
macOS Sierra

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code
      type: "nfs"

sites:
    - map: foo.test
      to: /home/vagrant/Code/foo/web
      php: "7.1"
    - map: bar.test
      to: /home/vagrant/Code/bar/web
      php: "7.1"
    - map: apple.app
      to: /home/vagrant/Code/apple/web
```

## Vagrant destroy & up output
[GitHub Gist](https://gist.github.com/sulfo/1047dccc1d0f41d5d5d4aa6bf9cfc989) 

## Expected behavior
Expects the box to be able to resolve domains, listed within the `homestead.yaml` file.
`curl --head foo.test` should print the following:
```
vagrant@homestead:~$ curl --head foo.test
HTTP/1.1 500 Internal Server Error
Server: nginx/1.15.0
Date: Sat, 10 Nov 2018 23:58:17 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
```
(It returns 500 due to missing db import after vagrant destroy)

## Actual behavior
The box is not able to resolve the domains within the box.
`curl --head foo.test` return the following:
`curl: (6) Could not resolve host: foo.test`

## Steps to reproduce
1. Update everything to latest release
2. Destroy the box and up it

## My research
So I was working on a project, witch required project A to communicate serverside with project B. That means the server would have to know it’s domain internal,  so it can look it up and serve the result.

I found out, that my `/etc/resolv.conf` is diffrent from my colleagues Homestead boxes, after days of research.

Before changing anything, only my old `.app` domains would resolve correct, witch I found very strange.
 `.test`& `.local`would just fail.

The content of my file:
```
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "systemd-resolve --status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
```

Here’s one of my colleagues `resolv.conf` file:
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.0.2.3
```

I tried to change this to 10.0.2.3, and it fixed all my issues!

However this is overridden after every restart of the box. 

Is this due to a buggy systemd-resolved, or is it just me who has this issue? A other fix for now can be to write all my domains into the servers `etc/hosts` as well, but that’s not a nice fix.
