### ISSUE TITLE
VMware Fusion 11 support

### ISSUE THREAD

**Issue by Gavrisimo** [laravel/homestead#976]
## Versions
  - Vagrant: 2.2.0
  - Provider: vmware_fusion
  - Homestead: v7.19.2

## Host operating system
macOS Mojave 10.14.1

## Homestead.yaml
```yaml
---
box: laravel/homestead
ip: "192.168.10.10"
memory: 512
cpus: 1
provider: vmware_fusion

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/work/code
      to: /home/vagrant/work/code

sites:
    - ...

databases:
    - ...
```

## Vagrant destroy & up output
```
# bmo at bmo-mbp in ~/work/vms/homestead on git:234a43b ● [16:33:11]
→ vagrant destroy && vagrant up
==> homestead-7: VM not created. Moving on...
Bringing machine 'homestead-7' up with 'vmware_fusion' provider...
This provider only works with VMware Fusion 8 or lower. You have
Fusion '11.0.1'. Please install the proper version of VMware
Fusion and try again.
```

## Expected behavior
It should be able to run `vagrant up` command and build the VM.

## Actual behavior
It failed to run because it is saying that the provider only supports VMware Fusion 8 or lower. Just FYI I was successfully running `vmware_fusion` provider with VMware Fusion 10 for quite a while now.

## Steps to reproduce
1. vagrant up
