### ISSUE TITLE
Is there a way to customize the Vagrantfile from the Homestead.yaml file ?

### ISSUE THREAD

**Issue by cheoAlejo** [laravel/homestead#983]
## Versions
  - Vagrant: 2.2.0.
  - Provider: Virtualbox.
  - Homestead: 7.19.2.

## Host operating system
Windows 10 professional.

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: D:\dev\Homestead
      to: /home/vagrant/code

sites:
    - map: auth.homes.io
      to: /home/vagrant/code/auth/public
    - map: miniapp.homes.io
      to: /home/vagrant/code/miniapp/public
    - map: helloworld.homes.io
      to: /home/vagrant/code/helloworld/public
```
## Expected behavior

A way to customize the Vagrantfile without actually modifying it directly.

## Actual behavior

In order to add specific setttings, you have to edit the Vagrantfile directly. For instance, I'm using the vagrant-hostmanager plugin to auto update the host's hosts file when adding new sites, the docs state that you just have to run `vagrant reload --provision`, however, because of an [error in that plugin](https://github.com/devopsgroup-io/vagrant-hostmanager/issues/185), in order to make it work I have to change the following in the Vagrantfile:

```
    elsif Vagrant.has_plugin?('vagrant-hostmanager')
        config.hostmanager.enabled = false
        config.hostmanager.manage_host = true
        config.hostmanager.aliases = settings['sites'].map { |site| site['map'] }
        config.vm.provision :hostmanager
    end
```

Otherwise, I would have to run the following every time I add new sites:

```
vagrant halt
vagrant up --provision
```

## Steps to reproduce

1. Install vagrant-hostmanager plugin.
1. Add a new site to Homestead.yaml while the machine is running.
2. Run `vagrant reload --provision`

## References

- [Issue in the vagrant-hostmanager plugin.](https://github.com/devopsgroup-io/vagrant-hostmanager/issues/185)
- [Configure the plugin as provisioner.](https://github.com/devopsgroup-io/vagrant-hostmanager#provisioner)
