### ISSUE TITLE
Also getting the Unable to mount one of your folders. Please check your folders in Homestead.yaml (Same Issue)

### ISSUE THREAD

**Issue by pandabrand** [laravel/homestead#993]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.1
  - Provider: Virtualbox  5.2.22 r126460
  - Homestead: 7.19.2

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
MacOS 10.13.6 (17G3025)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: /Users/frederickwells/Documents/Work/laravel/code/graph-test
      to: /home/vagrant/code
      type: "nfs"

sites:
    - map: homestead.test
      to: /home/vagrant/code/graph-test/public

databases:
    - homestead

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# zray:
#  If you've already freely registered Z-Ray, you can place the token here.
#     - email: foo@bar.com
#       token: foo
#  Don't forget to ensure that you have 'zray: "true"' for your site.

```

## Vagrant destroy & up output
https://gist.github.com/pandabrand/02f1299c6f374a53f140b190ee8dd2c0

## Expected behavior
What should have happened? Please include as much detail as possible.
homestead vm machine has local folders mounted 
 
## Actual behavior
What actually happened? Please include as much detail as possible.
The same as many other posts on this issue, I get: 
`homestead-7: Unable to mount one of your folders. Please check your folders in Homestead.yaml`
This is a fresh install, no other vms running at the time. As far as I can determine this is all current updated code.

## Steps to reproduce
1. Follow the steps from https://laravel.com/docs/5.7/homestead#installation-and-setup
2. Configure the `folders` property in `Homestead.yaml` to an existing directory on your machine
3. `vagrant up`

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?
For example:
- https://github.com/laravel/homestead/issues/830
- ...
