### ISSUE TITLE
Accessing sites without :8000 doesn't work with vmware

### ISSUE THREAD

**Issue by eminos** [laravel/homestead#994]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.2
  - Provider: VMWare Workstation 14
  - Homestead: v6.4.0 (v7.19.2)

## Host operating system
Windows 10 (10.0.17134 Build 17134)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 4096
cpus: 2
provider: vmware_workstation

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Dev
      to: /home/vagrant/dev

sites:
    - map: li.local
      to: /home/vagrant/dev/li/public
      # type: "apache"
    - map: admin.li.local
      to: /home/vagrant/dev/li/public
      # type: "apache"
    - map: cj.local
      to: /home/vagrant/dev/cj/public
      # type: "apache"

databases:
    - li
    - cj
    - cj_testing

blackfire:
    - id: ...
      token: ...
      client-id: ...
      client-token: ...

ports:
    - send: 6379
      to: 6379

```

## Vagrant destroy & up output
https://pastebin.com/raw/RU9yr1E4

## Expected behavior
Sites should be available at li.local and cj.local **without** providing the forwarded port 8000.
This worked fine for close to a year running with VirtualBox, but today I tried to switch to vmware and this broke.

## Actual behavior
As shown in the vagrant up output linked above I get no errors.
I can access the sites on the host with **li.local:8000**, but as far as I can see this is not the default and expected behaviour (says nothing about it in the docs). And like I mentioned, it **used to work** with virtualbox.

I tried different IP addresses for the VM.
Connecting with ssh works fine.
Pinging the VM IP address from the host times out (why?).
I updated all the different parts today, to no avail. I actually reinstalled homestead (git clone).

Did I forget to enable something? Why can't I just access all the ports on the VM without any port forwarding?

As far as I can see in the docs, this "should just work" (accessing the sites without :8000), and like I said it did with VirtualBox, but now with VMWare it doesn't anymore.

I have purchased the VMWare vagrant provider and set that up as per the instructions (also no errors regarding this).

Actually, I'm not sure if this is expected behaviour, because I found other threads about similar issues, but the other way around. Some people could access sites on port 80, but wanted the port forwarding to 8000.
