### ISSUE TITLE
Attempted to load class "ConstraintValidator" from namespace "Symfony\Component\Validator". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by engharb** [laravel/homestead#997]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.2.
  - Provider: Virtualbox 5.2.22.
  - Homestead: latest version.

## Host operating system
Mac OS

## Homestead.yaml
```yaml
ip: "192.168.33.12"
memory: 2048
cpus: 1
hostname: mywebsite
name: mywebsite
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa

folders:
    - map: "~/svn/app/mywebsite"
      to: "/home/vagrant/mywebsite"
      type: "nfs"

sites:
    - map: mywebsite.de
      to: "/home/vagrant/mywebsite/public"
      type: test
      php: "7.2"

databases:
    - homestead
    - test
    - symfony
```

## Expected behavior
after vagrant ssh I want to install packages using composer install
## Actual behavior
in VM I tried ```composer install``` successfully but one of symfony4 classes is not installed or copied under vendor/symfony/validator 

Class name is ConstraintValidator

Also the composer install result is success with no failure. I'm afraid about such problem if it comes because of nfs or file synchronization or caches.!?

I tried to clear composer cache locally and in VM but that does not work too.
## Steps to reproduce
1. vagrant up
2. vagrant ssh
3. composer install
