### ISSUE TITLE
How to bind a second-level domain to homestead?

### ISSUE THREAD

**Issue by StringKe** [laravel/homestead#999]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: Vagrant 2.2.2
  - Provider: Virtualbox
  - Homestead: Vagrant 2.2.2

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `~5.2`. You *will* show as up-to-date from the `~5.0` version when you `About -> Check for Updates`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
Windows 10  1809 (17763.134)

## Homestead.yaml
```yaml
---
ip: "192.168.10.10"
memory: 1024
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

neo4j: true
    
folders:
    - map: E:/PHPWeb/RunTime/phpMyAdmin
      to: /home/vagrant/runtime/phpmyadmin
      type: nfs
    - map: E:/PHPWeb/Foliker
      to: /home/vagrant/foliker
      type: nfs
    - map: E:/PHPWeb/NewFoliker
      to: /home/vagrant/newFoliker
      type: nfs
    - map: E:/PHPWeb/uRLShort
      to: /home/vagrant/uRLShort
      type: nfs
    - map: E:/PHPWeb/BC-S
      to: /home/vagrant/bc-s
      type: nfs
      
sites:
    - map: mysql.manager
      to: /home/vagrant/runtime/phpmyadmin
    - map: foliker.test
      to: /home/vagrant/foliker/public
    - map: newfoliker.test
      to: /home/vagrant/newFoliker/public
    - map: betaser.vipgz1.idcfengye.com
      to: /home/vagrant/newFoliker/public
    - map: url.test
      to: /home/vagrant/uRLShort/public
    - map: bcs.test
      to: /home/vagrant/bc-s/public
      
databases:
    - foliker
    - newFoliker
    - urlshort
    - bcs

backup: true
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
Do **NOT** paste the debug output in the issue, just paste the link to the Gist.

## Expected behavior
What should have happened? Please include as much detail as possible.

## Problem
```php
<?php

use Illuminate\Routing\Router;

Route::domain('{admin}.bcs.com')->group(function () {

    Admin::registerAuthRoutes();
    Route::group([
        'prefix'        => config('admin.route.prefix'),
        'middleware'    => config('admin.route.middleware'),
    ], function (Router $router) {

        $router->get('/', '\App\Admin\Controllers\HomeController@index');

        $router->resource('shop/categories',\App\Admin\Controllers\Shop\CategoriesController::class);

    });

});
```
Obviously there is a test domain name for `admin.bcs.com`. How do I bind `admin.bcs.com` and `bcs.com` to `homestead`?
